Repository remix-run/remix, pull requests merged in 2021-12, with the labels that each got.

#817 Add `react-router-dom` dependency to gists fixture
  fixtures/gists-app/package.json
Labels: CLA Signed

#818 docs: delete extra period in gitignore path
  contributors.yml
  docs/guides/styling.md
Labels: CLA Signed

#812 docs(cw): add note to template about new account
  packages/create-remix/templates/cloudflare-workers/README.md
Labels: CLA Signed

#828 Prisma fix
  contributors.yml
  docs/tutorials/jokes.md
Labels: CLA Signed

#829 Skip CI tests on docs changes
  .github/workflows/test.yml
  .github/workflows/website.yml
Labels: CLA Signed

#838 Use the correct constructor for the example in documentation
  contributors.yml
  docs/api/conventions.md
Labels: CLA Signed

#794 docs: clarify instruction in blog tutorial
  contributors.yml
  docs/tutorials/blog.md
Labels: CLA Signed

#560 Add step to quickstart
  contributors.yml
  docs/tutorials/blog.md
Labels: CLA Signed

#549 Joke App tutorial: (docs) should not have the prefetch at this point.
  contributors.yml
  docs/tutorials/jokes.md
Labels: CLA Signed

#757 docs: Add a new type for the error object to fix TypeScript errors
  contributors.yml
  docs/tutorials/blog.md
Labels: CLA Signed

#849 fix(dev,serve): remove trailing space in executableBanner in cli
  contributors.yml
  rollup.config.js
Labels: CLA Signed

#439 Support generic in json (aka typed json)
  contributors.yml
  packages/remix-server-runtime/responses.ts
Labels: CLA Signed

#798 fix(docs): fix post page link href in admin page for blog tutorial
  contributors.yml
  docs/tutorials/blog.md
Labels: CLA Signed

#455 refactor: Removed unused `NavLink`
  contributors.yml
Labels: CLA Signed

#473 typo: duplicate 'the'
  contributors.yml
  examples/blog-tutorial/app/routes/demos/actions.tsx
Labels: CLA Signed

#475 docs: Couple of grammar/type-o fixes in getting started tutorial
  contributors.yml
  docs/tutorials/blog.md
Labels: CLA Signed

#476 Fix: Docs - Typos
  contributors.yml
  docs/api/remix.md
Labels: CLA Signed

#477 Update jokes.md
  contributors.yml
Labels: CLA Signed

#855 chore(docs): fix typo
  contributors.yml
  docs/api/remix.md
Labels: CLA Signed

#847 fix: use `null` body instead of empty string
  docs/api/remix.md
  packages/remix-architect/__tests__/server-test.ts
  packages/remix-express/__tests__/server-test.ts
  packages/remix-netlify/__tests__/server-test.ts
  packages/remix-vercel/__tests__/server-test.ts
Labels: CLA Signed

#843 chore(ci): refresh docs every hour
  .github/workflows/website.yml
Labels: CLA Signed

#861 chore: add node version to issue report
  .github/ISSUE_TEMPLATE/bug_report.yml
Labels: CLA Signed

#816 chore: add format GitHub action
  .github/workflows/format.yml
Labels: CLA Signed

#870 Docs: Explain how to handle different request methods with resource routes
  contributors.yml
  docs/guides/resource-routes.md
Labels: CLA Signed

#521 chore(docs): Clarify wordy and confusing sentence in `blog.md`
  contributors.yml
  docs/tutorials/blog.md
Labels: CLA Signed

#534 docs(other-api/serve): update link to adapter
  docs/other-api/serve.md
Labels: CLA Signed

#568 chore(docs): add missing id to textarea
  contributors.yml
  docs/tutorials/blog.md
Labels: CLA Signed

#583 Docs: Fix typo on index.md
  contributors.yml
  docs/index.md
Labels: CLA Signed

#508 docs(jokes): fix RSS date format
  contributors.yml
  docs/tutorials/jokes.md
Labels: CLA Signed

#506 docs(jokes): fix injection flaw in RSS feed
  docs/tutorials/jokes.md
Labels: CLA Signed

#502 docs: fix missing link to mdn for element link
  contributors.yml
  docs/api/conventions.md
Labels: CLA Signed

#610 Docs: Env vars link list update
  contributors.yml
  docs/guides/envvars.md
Labels: CLA Signed

#507 docs: add a postinstall troubleshooting docs-error in tutorials/blog.md
  contributors.yml
  docs/tutorials/blog.md
Labels: CLA Signed

#619 docs(guides/styling) fix link Route Module Links
  contributors.yml
  docs/guides/styling.md
Labels: CLA Signed

#630 Docs updates - rewording and typos
  contributors.yml
  docs/tutorials/blog.md
Labels: CLA Signed

#563 chore(docs): dedupe useActionData generic types
  contributors.yml
  docs/tutorials/jokes.md
  examples/jokes/app/routes/jokes/new.tsx
  examples/jokes/app/routes/login.tsx
Labels: CLA Signed

#814 append to formData/searchParams
  packages/remix-react/components.tsx
Labels: CLA Signed

#569 feat: prefetch link preloads
  fixtures/gists-app/app/components/guitar.jpg
  fixtures/gists-app/app/routes/index.jsx
  fixtures/gists-app/app/routes/links.tsx
  packages/remix-react/links.ts
Labels: CLA Signed

#486 add engines to package.json and set engines-strict=true
  .npmrc
  contributors.yml
  docs/contributing.md
  package.json
Labels: CLA Signed

#666 A couple of minor typos I noticed when going through the jokes tutorial
  contributors.yml
  docs/tutorials/jokes.md
Labels: CLA Signed

#670 docs: fix missing link and backticks in Conventions/link
  contributors.yml
  docs/api/conventions.md
Labels: CLA Signed

#641 docs: Adapt link targets for posts in admin ui
  contributors.yml
  docs/tutorials/blog.md
  examples/blog-tutorial/app/routes/admin.tsx
Labels: CLA Signed

#684 Docs: Fix missing comma in API Routes doc
  contributors.yml
  docs/guides/api-routes.md
Labels: CLA Signed

#710 Update blog.md
  contributors.yml
  docs/tutorials/blog.md
Labels: CLA Signed

#755 fix(docs): fix docs use title
  contributors.yml
  docs/tutorials/jokes.md
Labels: CLA Signed

#720 Fix React JSX Transform Warnings in VS Code
  contributors.yml
  packages/create-remix/templates/_shared_js/jsconfig.json
Labels: CLA Signed

#789 docs: .server filename in constraints
  contributors.yml
  docs/other-api/constraints.md
Labels: CLA Signed

#791 docs: fix component name on informative comment
  contributors.yml
  packages/remix-react/errorBoundaries.tsx
Labels: CLA Signed

#802 Docs: show how to use tailwind @apply
  contributors.yml
  docs/guides/styling.md
Labels: CLA Signed

#512 docs(api/conventions): fix #headers link
  contributors.yml
  docs/api/conventions.md
Labels: CLA Signed

#495 [ImgBot] Optimize images
  examples/jokes/public/social.png
Labels: CLA Signed

#853 Fix code example error in cookie docs.
  contributors.yml
  docs/api/remix.md
Labels: CLA Signed

#540 (docs): add missing param in docs for `useSubmit`
  contributors.yml
  docs/api/remix.md
Labels: CLA Signed

#383 feat: add support for multipart / file uploads
  .gitignore
  docs/api/remix.md
  fixtures/gists-app/.gitignore
  fixtures/gists-app/app/routes/actions.tsx
  fixtures/gists-app/app/routes/methods.tsx
  fixtures/gists-app/app/uploadHandler.server.ts
  fixtures/gists-app/package.json
  fixtures/gists-app/tests/actions-test.ts
  fixtures/gists-app/tests/assets/toupload.txt
  fixtures/gists-app/tests/assets/touploadtoobig.txt
  packages/remix-architect/__tests__/server-test.ts
  packages/remix-architect/package.json
  packages/remix-architect/server.ts
  packages/remix-express/__tests__/server-test.ts
  packages/remix-express/package.json
  packages/remix-express/server.ts
  packages/remix-netlify/__tests__/server-test.ts
  packages/remix-netlify/package.json
  packages/remix-netlify/server.ts
  packages/remix-node/__tests__/form-data-test.ts
  packages/remix-node/__tests__/formData-test.ts
  packages/remix-node/__tests__/parseMultipartFormData-test.ts
  packages/remix-node/fetch.ts
  packages/remix-node/form-data.ts
  packages/remix-node/formData.ts
  packages/remix-node/globals.ts
  packages/remix-node/index.ts
  packages/remix-node/magicExports/platform.ts
  packages/remix-node/package.json
  packages/remix-node/parseMultipartFormData.ts
  packages/remix-node/upload/fileUploadHandler.ts
  packages/remix-node/upload/memoryUploadHandler.ts
  packages/remix-node/upload/meter.ts
  packages/remix-react/__tests__/setupJest.js
  packages/remix-react/data.ts
  packages/remix-vercel/__tests__/server-test.ts
  packages/remix-vercel/package.json
  packages/remix-vercel/server.ts
  yarn.lock
Labels: CLA Signed

#892 Add `async` to action function example
  contributors.yml
  docs/guides/data-writes.md
Labels: CLA Signed

#890 docs: Fix some broken links
  docs/api/conventions.md
Labels: CLA Signed

#891 docs: move 'HtmlMetaDescriptor' to be under 'meta' instead of 'links'
  docs/api/conventions.md
Labels: CLA Signed

#887 Docs - Some fixes in blog tutorial
  contributors.yml
  docs/tutorials/blog.md
Labels: CLA Signed

#908 Fix Grammatical Error In Docs
  contributors.yml
  docs/guides/envvars.md
Labels: CLA Signed

#877 docs: fix for conventions spelling
  contributors.yml
  docs/api/conventions.md
Labels: CLA Signed

#895 fix: jokes tutorial actions should return 400 status for errors
  docs/tutorials/jokes.md
  examples/jokes/app/routes/jokes/new.tsx
  examples/jokes/app/routes/login.tsx
Labels: CLA Signed

#930 fix(fly): use remote-only deploys
  packages/create-remix/templates/fly/package.json
Labels: CLA Signed

#910 Use seconds in KV session storage expiration
  contributors.yml
  packages/remix-cloudflare-workers/sessions/cloudflareKVSessionStorage.ts
Labels: CLA Signed

#482 chore: tsconfig path mappings require baseUrl property
  contributors.yml
  examples/basic/tsconfig.json
  examples/blog-tutorial/tsconfig.json
  examples/jokes/tsconfig.json
  packages/create-remix/templates/_shared_ts/tsconfig.json
Labels: CLA Signed

#860 feat: surface errors from fetch submissions
  packages/remix-react/errorBoundaries.tsx
Labels: CLA Signed

#858 fix: stop routes that won't render from loading
  packages/remix-react/routes.tsx
  packages/remix-react/transition.ts
Labels: CLA Signed

#864 wip: re-work server runtime
  fixtures/gists-app/tests/error-handling-test.ts
  packages/remix-react/browser.tsx
  packages/remix-react/components.tsx
  packages/remix-react/entry.ts
  packages/remix-react/errors.ts
  packages/remix-server-runtime/__tests__/server-test.ts
  packages/remix-server-runtime/__tests__/utils.ts
  packages/remix-server-runtime/data.ts
  packages/remix-server-runtime/entry.ts
  packages/remix-server-runtime/errors.ts
  packages/remix-server-runtime/responses.ts
  packages/remix-server-runtime/routeData.ts
  packages/remix-server-runtime/server.ts
Labels: CLA Signed

#587 feat: use `assetsBuildDirectory` instead of deprecated `browserBuildDirectory` config option
  docs/api/conventions.md
  examples/basic/remix.config.js
  examples/blog-tutorial/remix.config.js
  examples/jokes/remix.config.js
  packages/create-remix/templates/_shared_js/remix.config.js
  packages/create-remix/templates/_shared_ts/remix.config.js
  packages/create-remix/templates/arc/remix.config.js
  packages/create-remix/templates/cloudflare-workers/remix.config.js
  packages/create-remix/templates/express/remix.config.js
  packages/create-remix/templates/fly/remix.config.js
  packages/create-remix/templates/netlify/remix.config.js
  packages/create-remix/templates/remix/remix.config.js
  packages/create-remix/templates/vercel/remix.config.js
Labels: CLA Signed

#955 docs(api): fix variable id → timer
  contributors.yml
  docs/api/remix.md
Labels: CLA Signed

#939 feat: Add <Outlet context> prop
  docs/api/remix.md
  fixtures/gists-app/app/routes/__layout.tsx
  fixtures/gists-app/app/routes/__layout/with-layout.tsx
  fixtures/gists-app/tests/layout-routes-test.ts
  packages/remix-react/components.tsx
  packages/remix-react/index.tsx
  packages/remix-react/magicExports/client.ts
Labels: CLA Signed

#956 chore: run tests on PRs
  .github/workflows/test.yml
  fixtures/gists-app/tests/actions-test.ts
Labels: CLA Signed

#787 fix(remix-react): fix circular dependency
  packages/remix-react/components.tsx
  packages/remix-react/index.tsx
Labels: CLA Signed

#357 feat: Introduce `@remix-run/eslint-config` package
  .eslintrc.js
  fixtures/gists-app/app/routes/methods.tsx
  package.json
  packages/create-remix/templates/_shared_js/app/entry.server.jsx
  packages/create-remix/templates/_shared_js/app/root.jsx
  packages/create-remix/templates/_shared_js/app/routes/demos/about.jsx
  packages/create-remix/templates/_shared_js/app/routes/demos/actions.jsx
  packages/create-remix/templates/_shared_js/app/routes/demos/params/$id.jsx
  packages/create-remix/templates/_shared_js/app/routes/index.jsx
  packages/remix-eslint-config/README.md
  packages/remix-eslint-config/index.js
  packages/remix-eslint-config/jest.js
  packages/remix-eslint-config/package.json
  packages/remix-react/__tests__/transition-test.tsx
  packages/remix-react/components.tsx
  packages/remix-server-runtime/__tests__/server-test.ts
  packages/remix-server-runtime/__tests__/utils.ts
  packages/remix-server-runtime/server.ts
  scripts/version.js
  yarn.lock
Labels: CLA Signed, WIP

#981 revert: experimantal version accidentally merged
  examples/basic/package.json
  examples/blog-tutorial/package.json
  examples/jokes/package.json
  packages/create-remix/package.json
  packages/remix-architect/package.json
  packages/remix-cloudflare-workers/package.json
  packages/remix-dev/package.json
  packages/remix-express/package.json
  packages/remix-netlify/package.json
  packages/remix-node/package.json
  packages/remix-react/package.json
  packages/remix-serve/package.json
  packages/remix-server-runtime/package.json
  packages/remix-vercel/package.json
  packages/remix/package.json
Labels: CLA Signed

#974 chore: move Outlet context to React Router
  fixtures/gists-app/app/routes/__layout.tsx
  fixtures/gists-app/app/routes/__layout/with-layout.tsx
  fixtures/gists-app/package.json
  fixtures/gists-app/tests/layout-routes-test.ts
  package.json
  packages/remix-react/components.tsx
  packages/remix-react/index.tsx
  packages/remix-react/package.json
  packages/remix-server-runtime/package.json
  yarn.lock
Labels: CLA Signed

#982 New example app - Search for a TV show
  contributors.yml
  examples/search-tv-show/.gitignore
  examples/search-tv-show/README.md
  examples/search-tv-show/app/entry.client.tsx
  examples/search-tv-show/app/entry.server.tsx
  examples/search-tv-show/app/root.tsx
  examples/search-tv-show/app/routes/index.tsx
  examples/search-tv-show/app/styles/global.css
  examples/search-tv-show/app/styles/index.css
  examples/search-tv-show/package.json
  examples/search-tv-show/public/favicon.ico
  examples/search-tv-show/remix.config.js
  examples/search-tv-show/remix.env.d.ts
  examples/search-tv-show/sandbox.config.json
  examples/search-tv-show/tsconfig.json
Labels: CLA Signed

#976 feat: allow ESM output of server builds
  packages/remix-dev/__tests__/readConfig-test.ts
  packages/remix-dev/compiler.ts
  packages/remix-dev/config.ts
  packages/remix-react/package.json
  packages/remix-server-runtime/package.json
  packages/remix/package.json
  rollup.config.js
Labels: CLA Signed

#995 Grammar fixes
  docs/api/conventions.md
Labels: CLA Signed

#988 fix(dev): Ignore dotfiles in routes directory
  fixtures/gists-app/app/routes/.blargh
  packages/remix-dev/config/routesConvention.ts
Labels: bug, CLA Signed

#987 chore: Update React Router to v6.1.1
  fixtures/gists-app/package.json
  package.json
  packages/remix-react/package.json
  packages/remix-server-runtime/package.json
  yarn.lock
Labels: CLA Signed

#984 fix: use document over window for browser check
  docs/other-api/constraints.md
  packages/remix-react/scroll-restoration.tsx
Labels: CLA Signed

#997 docs: fix api/remix.md extra semicolon
  contributors.yml
  docs/api/remix.md
Labels: CLA Signed

#1000 Grammar fixes
  docs/api/remix.md
Labels: CLA Signed

#1014 docs: fix highlight line in blog outlet example
  contributors.yml
  docs/tutorials/blog.md
Labels: CLA Signed

#994 Fixed a typo
  contributors.yml
  docs/tutorials/jokes.md
Labels: CLA Signed

#983 feat: define process.env.NODE_ENV for server build
  packages/remix-cloudflare-workers/globals.ts
  packages/remix-dev/compiler.ts
  packages/remix-node/globals.ts
Labels: CLA Signed

#531 chore: Fix small typo in jokes tutorial
  contributors.yml
  docs/tutorials/jokes.md
Labels: CLA Signed

#559 chore: Minor rephrasing in the MDX guide
  docs/guides/mdx.md
Labels: CLA Signed

#585 chore: Fix blog tutorial example filename typo
  contributors.yml
  docs/tutorials/blog.md
Labels: CLA Signed

#558 chore: Fix a few typos in Markdown files
  contributors.yml
  docs/api/remix.md
  docs/guides/constraints.md
  docs/guides/data-writes.md
  docs/guides/envvars.md
  docs/guides/errors.md
  docs/guides/styling.md
  docs/other-api/fetch.md
  docs/other-api/serve.md
  docs/pages/philosophy.md
  docs/tutorials/jokes.md
Labels: CLA Signed

#612 chore: Fix typos in blog.md
  contributors.yml
  docs/tutorials/blog.md
Labels: CLA Signed

#650 chore: Typos in blog.md
  contributors.yml
  docs/tutorials/blog.md
Labels: CLA Signed

#682 chore: fixes typo
  contributors.yml
Labels: CLA Signed

#719 chore: fix typos on api/remix and add isSession documentation
  contributors.yml
  docs/api/remix.md
Labels: CLA Signed

#873 fix "user" typo
  docs/guides/data-writes.md
Labels: CLA Signed

#918 fix(doc): typo in data loading guide
  contributors.yml
  docs/guides/data-loading.md
Labels: CLA Signed

#968 Fix typo
  contributors.yml
  docs/tutorials/blog.md
Labels: CLA Signed

#1009 docs: fix effect typo css in js libs section
  contributors.yml
  docs/guides/styling.md
Labels: CLA Signed

#957 docs: fix typos and links in multiple pages
  contributors.yml
  docs/api/conventions.md
  docs/api/remix.md
  docs/tutorials/jokes.md
Labels: CLA Signed

#621 chore: A possible typo prisma.user.findMany() -> db.user.findMany()
  contributors.yml
Labels: CLA Signed

#964 Missing quote !
  contributors.yml
  docs/other-api/node.md
Labels: CLA Signed

#1039 refactor: use ternaries rather than && in JSX
  docs/api/remix.md
  docs/guides/disabling-javascript.md
Labels: CLA Signed

#1033 fix(doc): remove trailing slash from anchored links
  contributors.yml
  docs/api/conventions.md
Labels: CLA Signed

#1016 chore(docs): add missing highlight on invariant import
  docs/tutorials/blog.md
Labels: CLA Signed

#960 chore(docs): fix sentence fragment
  contributors.yml
  docs/other-api/react-router.md
Labels: CLA Signed

#958 fix(doc): fix code snippets imports and highlighting in new blog tutorial
  contributors.yml
  docs/tutorials/blog.md
Labels: CLA Signed

#1050 fix(create-remix): Pin pre-releases to specific version
  packages/create-remix/cli.ts
Labels: CLA Signed

#1047 chore: remove husky and lint staged, rely on github action
  .github/workflows/format.yml
  .husky/pre-commit
  package.json
  yarn.lock
Labels: CLA Signed

#422 Skip script rendering after hydration
  .gitignore
  contributors.yml
  packages/remix-react/components.tsx
Labels: CLA Signed, WIP, accepted

#989 feat(dev): `ignoredRouteFiles` config option
  examples/basic/remix.config.js
  examples/blog-tutorial/remix.config.js
  examples/jokes/remix.config.js
  fixtures/gists-app/app/routes/.blargh
  fixtures/gists-app/app/routes/blargh.ts
  fixtures/gists-app/remix.config.js
  fixtures/tutorial/remix.config.js
  packages/create-remix/templates/_shared_js/remix.config.js
  packages/create-remix/templates/_shared_ts/remix.config.js
  packages/create-remix/templates/arc/remix.config.js
  packages/create-remix/templates/cloudflare-workers/remix.config.js
  packages/create-remix/templates/express/remix.config.js
  packages/create-remix/templates/fly/remix.config.js
  packages/create-remix/templates/netlify/remix.config.js
  packages/create-remix/templates/remix/remix.config.js
  packages/create-remix/templates/vercel/remix.config.js
  packages/remix-dev/config.ts
  packages/remix-dev/config/routesConvention.ts
  packages/remix-dev/package.json
Labels: CLA Signed

#605 Remove 'full control' sentence
  contributors.yml
  docs/api/conventions.md
Labels: CLA Signed

#1058 chore(test): Test that multiple checkbox selection is correct in post…
  fixtures/gists-app/tests/form-test.ts
Labels: CLA Signed

#1060 feat(create-remix): added CF Pages server choice
  packages/create-remix/cli.ts
Labels: CLA Signed

#1061 chore: update publish scripts to include CF pages
  scripts/publish-private.js
  scripts/publish.js
Labels: CLA Signed

#1067 fix: update pages handler to use middleware pattern for asset handling
  packages/ADDING_A_PACKAGE.md
  packages/create-remix/templates/cloudflare-pages/functions/[[path]].js
  packages/create-remix/templates/cloudflare-pages/package.json
  packages/create-remix/templates/cloudflare-pages/remix.config.js
  packages/create-remix/templates/cloudflare-workers/remix.config.js
  packages/remix-cloudflare-pages/package.json
  packages/remix-cloudflare-pages/worker.ts
  yarn.lock
Labels: CLA Signed

#1075 chore(create-remix): remove Netlify node version step
  packages/create-remix/templates/netlify/README.md
Labels: CLA Signed, accepted

#1076 fix(dev/compiler): update publicPath for server build
  packages/remix-dev/compiler.ts
Labels: CLA Signed

#1066 Update blog.md
  contributors.yml
  docs/tutorials/blog.md
Labels: CLA Signed

#1065 Update CONTRIBUTING.md
  CONTRIBUTING.md
  contributors.yml
Labels: CLA Signed

#1059 docs(remix): fix `useFetcher` examples' filenames
  docs/api/remix.md
Labels: CLA Signed

#1044 docs: add example for <NavLink> taken from react router
  contributors.yml
  docs/api/remix.md
Labels: CLA Signed

#1027 refactor(types): Allow meta to return undefined
  contributors.yml
  packages/remix-react/routeModules.ts
Labels: CLA Signed

#1007 chore(docs): fix accessing client env var example
  contributors.yml
  docs/guides/envvars.md
Labels: CLA Signed

#1002 fix: code highlight
  contributors.yml
  docs/tutorials/jokes.md
Labels: CLA Signed

#1001 Grammar fixes
  docs/pages/philosophy.md
Labels: CLA Signed

#999 docs: guides/styling#tailwind: added `--minify` flag on build command
  contributors.yml
  docs/guides/styling.md
Labels: CLA Signed

#1070 fix: account for string and buffer bodies
  packages/remix-node/parseMultipartFormData.ts
Labels: CLA Signed

#980 fix: data-writes.md
  contributors.yml
  docs/guides/data-writes.md
Labels: CLA Signed

#979 doc: Updated to support tailwind css v3
  contributors.yml
  docs/guides/styling.md
Labels: CLA Signed

#1085 chore: Clean up test output in gists app
  fixtures/gists-app/server.js
Labels: CLA Signed

#1084 feat: added server platform config
  fixtures/gists-app/app/routes/gists.jsx
  packages/remix-dev/__tests__/readConfig-test.ts
  packages/remix-dev/compiler.ts
  packages/remix-dev/config.ts
Labels: CLA Signed

#1040 refactor: use optional chaining
  fixtures/gists-app/app/root.jsx
  packages/remix-dev/cli/commands.ts
  packages/remix-node/formData.ts
  packages/remix-react/links.ts
  packages/remix-server-runtime/server.ts
  packages/remix-server-runtime/sessions.ts
  packages/remix-server-runtime/sessions/cookieStorage.ts
Labels: CLA Signed

#949 chore: add bogas04 to contributors
  contributors.yml
Labels: CLA Signed

#948 docs: document PrefetchPageLinks
  contributors.yml
  docs/api/remix.md
Labels: CLA Signed

#1087 fix(dev/compiler): use inline sourcemaps for server build
  packages/remix-dev/compiler.ts
Labels: CLA Signed

#940 use entries
  contributors.yml
  packages/remix-react/components.tsx
Labels: CLA Signed, accepted

#926 fix: version of react and react-dom are not match
  contributors.yml
  packages/remix-serve/cli.ts
  packages/remix-serve/env.ts
Labels: CLA Signed

#1071 feat: mainfield config based on serverModuleFormat
  packages/remix-dev/compiler.ts
Labels: CLA Signed

#920 Meta function's arguments in Conventions page
  contributors.yml
  docs/api/conventions.md
Labels: CLA Signed

#897 fix(doc): spread syntax missing dot in userFetchers chapter
  .gitignore
  contributors.yml
  docs/api/remix.md
Labels: CLA Signed

#1089 fix: added serverPlatform to CF templates
  packages/create-remix/templates/cloudflare-pages/remix.config.js
  packages/create-remix/templates/cloudflare-workers/remix.config.js
Labels: CLA Signed

#893 Fix: missing quotes around "stylesheet" on guides
  contributors.yml
  docs/guides/styling.md
Labels: CLA Signed

#1088 Fix highlighting error in blog tutorial and typo in contributing page
  contributors.yml
  docs/pages/contributing.md
  docs/tutorials/blog.md
Labels: CLA Signed

#888 change 'you' component to 'your' component
  contributors.yml
  docs/guides/data-loading.md
Labels: CLA Signed

#1090 fix: revert workers types for workers project
  packages/create-remix/templates/cloudflare-workers/package.json
Labels: CLA Signed

#872 adding myself to contributes for PR #490
  contributors.yml
Labels: CLA Signed

#1092 feat: hide CF bug fix in adapter
  packages/create-remix/templates/cloudflare-pages/functions/[[path]].js
  packages/create-remix/templates/cloudflare-pages/package.json
  packages/remix-cloudflare-pages/worker.ts
Labels: CLA Signed

#1094 Cloudflare Pages tweaks
  packages/create-remix/templates/cloudflare-pages/README.md
  packages/create-remix/templates/cloudflare-pages/functions/[[path]].js
  packages/remix-cloudflare-pages/index.ts
  packages/remix-cloudflare-pages/package.json
  packages/remix-cloudflare-pages/worker.ts
  yarn.lock
Labels: CLA Signed

#1097 refactor: use url.href vs url.toString()
  packages/remix-architect/server.ts
  packages/remix-express/server.ts
  packages/remix-netlify/server.ts
  packages/remix-server-runtime/data.ts
  packages/remix-vercel/server.ts
Labels: CLA Signed

#966 chore: remove all `React` default imports
  docs/api/remix.md
  docs/guides/disabling-javascript.md
  fixtures/gists-app/app/pages/one.mdx
  fixtures/gists-app/app/pages/two.mdx
  fixtures/gists-app/app/routes/blog/hello-world.mdx
  fixtures/gists-app/app/routes/blog/second.md
  fixtures/gists-app/app/routes/blog/third.md
  fixtures/gists-app/app/routes/one.mdx
  fixtures/gists-app/app/routes/two.md
  packages/remix-react/browser.tsx
  packages/remix-react/components.tsx
  packages/remix-react/routes.tsx
  packages/remix-react/server.tsx
Labels: CLA Signed, accepted
