Repository remix-run/remix, pull requests merged in 2022-02, with the labels that each got.

#1686 chore: Fix tests
  .gitignore
  NOTES.md
  contributors.yml
  fixtures/gists-app/jest/globalSetup.ts
  fixtures/gists-app/jest/globalTeardown.ts
  fixtures/gists-app/jest/setup.js
  fixtures/gists-app/jest/setup.ts
  fixtures/gists-app/jest/setupAfterEnv.ts
  fixtures/gists-app/package.json
  fixtures/gists-app/tsconfig.json
  jest.config.js
  jest/buildRemix.ts
  jest/setupNodeGlobals.ts
  packages/create-remix/__tests__/cli-test.ts
  packages/create-remix/__tests__/setupAfterEnv.ts
  packages/remix-architect/__tests__/setup.ts
  packages/remix-deno/__tests__/pathMock.ts
  packages/remix-deno/__tests__/server-test.ts
  packages/remix-deno/__tests__/setup.ts
  packages/remix-deno/__tests__/setupJest.js
  packages/remix-express/__tests__/server-test.ts
  packages/remix-express/__tests__/setup.ts
  packages/remix-netlify/__tests__/setup.ts
  packages/remix-node/__tests__/setup.ts
  packages/remix-react/__tests__/setup.ts
  packages/remix-react/__tests__/setupJest.js
  packages/remix-server-runtime/__tests__/setup.ts
  packages/remix-vercel/__tests__/setup.ts
Labels: CLA Signed

#1763 Export AppConfig from remix-run/dev
  examples/basic/remix.config.js
  examples/blog-tutorial/remix.config.js
  examples/catch-boundary/remix.config.js
  examples/chakra-ui/remix.config.js
  examples/client-only-components/remix.config.js
  examples/client-side-validation/remix.config.js
  examples/collected-notes/remix.config.js
  examples/combobox-resource-route/remix.config.js
  examples/form-to-notion-db/remix.config.js
  examples/framer-motion/remix.config.js
  examples/image-resize/remix.config.js
  examples/jokes/remix.config.js
  examples/mantine/remix.config.js
  examples/multiple-forms/remix.config.js
  examples/multiple-params/remix.config.js
  examples/newsletter-signup/remix.config.js
  examples/nprogress/remix.config.js
  examples/on-demand-hydration/remix.config.js
  examples/outlet-form-rerender/remix.config.js
  examples/pathless-routes/remix.config.js
  examples/pm-app/remix.config.js
  examples/quirrel/remix.config.js
  examples/redis-upstash-session/remix.config.js
  examples/remix-auth-form/remix.config.js
  examples/remix-auth-github/remix.config.js
  examples/remix-auth-supabase/remix.config.js
  examples/sanity/remix.config.js
  examples/sass/remix.config.js
  examples/search-input/remix.config.js
  examples/sharing-loader-data/remix.config.js
  examples/socket.io/remix.config.js
  examples/strapi/remix.config.js
  examples/styled-components/remix.config.js
  examples/tailwindcss/remix.config.js
  examples/template/remix.config.js
  examples/turborepo-vercel/apps/remix-app/remix.config.js
  fixtures/gists-app/remix.config.js
  packages/create-remix/templates/_shared_js/remix.config.js
  packages/create-remix/templates/_shared_ts/remix.config.js
  packages/create-remix/templates/arc/remix.config.js
  packages/create-remix/templates/cloudflare-pages/remix.config.js
  packages/create-remix/templates/cloudflare-workers/remix.config.js
  packages/create-remix/templates/deno/remix.config.js
  packages/create-remix/templates/express/remix.config.js
  packages/create-remix/templates/fly/remix.config.js
  packages/create-remix/templates/netlify/remix.config.js
  packages/create-remix/templates/remix/remix.config.js
  packages/create-remix/templates/vercel/remix.config.js
  packages/remix-dev/index.ts
Labels: CLA Signed

#1749 chore: template updates
  packages/create-remix/templates/arc/preferences.arc
  packages/create-remix/templates/deno_ts/tsconfig.json
Labels: CLA Signed

#1765 chore(tests): add integration fixture tests
  .gitignore
  integration/action-test.tsx
  integration/compiler-test.tsx
  integration/global-setup.ts
  integration/headers-test.tsx
  integration/helpers/create-fixture.tsx
  integration/loader-test.tsx
  jest.config.js
  packages/create-remix/index.ts
  packages/remix-dev/cli/commands.ts
  packages/remix-dev/log.ts
Labels: CLA Signed

#1767 chore: have eslint ignore deno type defs
  .eslintignore
Labels: CLA Signed

#1735 docs(examples): indicate in jokes tutorial that fly.io has now a free tier for hosting databases
  contributors.yml
  docs/tutorials/jokes.md
Labels: CLA Signed

#1746 docs(jokes): fix divergent login.tsx import example
  contributors.yml
  docs/tutorials/jokes.md
Labels: CLA Signed

#1147 docs: fix a typo in the example of the resource routes docs
  contributors.yml
  docs/guides/resource-routes.md
Labels: CLA Signed

#1152 docs: fix misleading example usage of useFetcher load()
  docs/api/remix.md
Labels: CLA Signed

#1750 ci: wait for publish to finish before running deployment tests
  .github/workflows/arc-prerelease-deployment.test.yml
  .github/workflows/cf-pages-prerelease-deployment.test.yml
  .github/workflows/cf-workers-prerelease-deployment.test.yml
  .github/workflows/fly-prerelease-deployment-test.yml
  .github/workflows/netlify-prerelease-deployment-test.yml
  .github/workflows/release.yml
  .github/workflows/vercel-prerelease-deployment-test.yml
  .nvmrc
  scripts/deployment-test/_shared.mjs
  scripts/deployment-test/arc.mjs
  scripts/deployment-test/cf-pages.mjs
  scripts/deployment-test/cf-workers.mjs
  scripts/deployment-test/fly.mjs
  scripts/deployment-test/netlify.mjs
  scripts/deployment-test/vercel.mjs
Labels: CLA Signed

#1226 docs: fix inconsistency in cookie options expires and maxAge
  docs/api/remix.md
Labels: CLA Signed

#1653 feat: add Remix Fly Stack
  packages/create-remix/cli.ts
  packages/create-remix/index.ts
  packages/create-remix/templates/fly-stack/Dockerfile
  packages/create-remix/templates/fly-stack/README.md
  packages/create-remix/templates/fly-stack/app/db.server.ts
  packages/create-remix/templates/fly-stack/app/entry.client.tsx
  packages/create-remix/templates/fly-stack/app/entry.server.tsx
  packages/create-remix/templates/fly-stack/app/models/note.server.ts
  packages/create-remix/templates/fly-stack/app/models/user.server.ts
  packages/create-remix/templates/fly-stack/app/root.tsx
  packages/create-remix/templates/fly-stack/app/routes/index.tsx
  packages/create-remix/templates/fly-stack/app/routes/join.tsx
  packages/create-remix/templates/fly-stack/app/routes/login.tsx
  packages/create-remix/templates/fly-stack/app/routes/logout.tsx
  packages/create-remix/templates/fly-stack/app/session.server.ts
  packages/create-remix/templates/fly-stack/app/styles/app.css
  packages/create-remix/templates/fly-stack/docker-compose.yml
  packages/create-remix/templates/fly-stack/dockerignore
  packages/create-remix/templates/fly-stack/env.example
  packages/create-remix/templates/fly-stack/fly.production.toml
  packages/create-remix/templates/fly-stack/fly.staging.toml
  packages/create-remix/templates/fly-stack/github/workflows/deploy.production.yml
  packages/create-remix/templates/fly-stack/github/workflows/deploy.staging.yml
  packages/create-remix/templates/fly-stack/gitignore
  packages/create-remix/templates/fly-stack/package-lock.json
  packages/create-remix/templates/fly-stack/package.json
  packages/create-remix/templates/fly-stack/prisma/migrations/20220125172404_init/migration.sql
  packages/create-remix/templates/fly-stack/prisma/migrations/migration_lock.toml
  packages/create-remix/templates/fly-stack/prisma/schema.prisma
  packages/create-remix/templates/fly-stack/prisma/seed.ts
  packages/create-remix/templates/fly-stack/public/favicon.ico
  packages/create-remix/templates/fly-stack/remix.config.js
  packages/create-remix/templates/fly-stack/remix.env.d.ts
  packages/create-remix/templates/fly-stack/scripts/init.mjs
  packages/create-remix/templates/fly-stack/tsconfig.json
Labels: CLA Signed

#1769 chore(tests): migrate catch boundary tests to new integration tests
  fixtures/gists-app/tests/catch-handling-test.ts
  fixtures/tutorial/.gitignore
  fixtures/tutorial/README.md
  fixtures/tutorial/app/catchall.tsx
  fixtures/tutorial/app/entry.client.tsx
  fixtures/tutorial/app/entry.server.tsx
  fixtures/tutorial/app/root.tsx
  fixtures/tutorial/app/routes/gists.new.tsx
  fixtures/tutorial/app/routes/gists.tsx
  fixtures/tutorial/app/routes/index.tsx
  fixtures/tutorial/app/routes/team.tsx
  fixtures/tutorial/app/routes/team/$member.tsx
  fixtures/tutorial/app/routes/team/index.tsx
  fixtures/tutorial/app/styles/gists.new.css
  fixtures/tutorial/app/styles/global.css
  fixtures/tutorial/app/styles/index.css
  fixtures/tutorial/app/tsconfig.json
  fixtures/tutorial/package.json
  fixtures/tutorial/public/favicon.ico
  fixtures/tutorial/remix.config.js
  fixtures/tutorial/scripts/install_remix.js
  integration/catch-boundary-test.ts
  integration/global-setup.ts
  integration/helpers/create-fixture.tsx
Labels: CLA Signed

#1538 feat(remix-architect): add DynamoDB tables session storage
  contributors.yml
  docs/api/remix.md
  packages/remix-architect/index.ts
  packages/remix-architect/package.json
  packages/remix-architect/sessions/arcTableSessionStorage.ts
Labels: CLA Signed

#1775 chore: add magic export for createArcTableSessionStorage
  packages/remix-architect/magicExports/platform.ts
Labels: CLA Signed

#1768 ci: update fly deployment test to use —-remote-only
  scripts/deployment-test/fly.mjs
Labels: CLA Signed

#1764 feat: update esbuild
  integration/compiler-test.ts
  integration/helpers/create-fixture.tsx
  packages/remix-dev/compiler.ts
  packages/remix-dev/package.json
  yarn.lock
Labels: CLA Signed

#1781 fix: support submit buttons outside of the form
  fixtures/gists-app/app/routes/methods.tsx
  fixtures/gists-app/tests/form-test.ts
  packages/remix-react/components.tsx
Labels: CLA Signed

#1783 fix(Link,NavLink) ensure prefetch works with explicit event handlers
  contributors.yml
  packages/remix-react/__tests__/components-test.tsx
  packages/remix-react/components.tsx
Labels: CLA Signed

#1473 docs(examples): Add routes-gen example
  contributors.yml
  examples/routes-gen/.gitignore
  examples/routes-gen/README.md
  examples/routes-gen/app/entry.client.tsx
  examples/routes-gen/app/entry.server.tsx
  examples/routes-gen/app/root.tsx
  examples/routes-gen/app/routes.d.ts
  examples/routes-gen/app/routes/index.tsx
  examples/routes-gen/app/routes/products/$productId.tsx
  examples/routes-gen/app/routes/products/index.tsx
  examples/routes-gen/package.json
  examples/routes-gen/public/favicon.ico
  examples/routes-gen/remix.config.js
  examples/routes-gen/remix.env.d.ts
  examples/routes-gen/tsconfig.json
Labels: CLA Signed

#1474 docs(example): Use routes with modals example
  examples/route-modal/.gitignore
  examples/route-modal/README.md
  examples/route-modal/app/entry.client.tsx
  examples/route-modal/app/entry.server.tsx
  examples/route-modal/app/root.tsx
  examples/route-modal/app/routes/invoices.tsx
  examples/route-modal/app/routes/invoices/$id/edit.tsx
  examples/route-modal/app/routes/invoices/add.tsx
  examples/route-modal/package-lock.json
  examples/route-modal/package.json
  examples/route-modal/public/favicon.ico
  examples/route-modal/remix.config.js
  examples/route-modal/remix.env.d.ts
  examples/route-modal/tsconfig.json
Labels: CLA Signed

#1766 fix: do not clone request for actions
  integration/file-uploads-test.ts
  integration/helpers/create-fixture.tsx
  packages/remix-server-runtime/data.ts
Labels: CLA Signed

#1833 Fix some small typos
  contributors.yml
  docs/guides/data-loading.md
  docs/guides/styling.md
  docs/pages/contributing.md
Labels: CLA Signed

#1771 docs: fix typo in Jokes App tutorial (peak -> peek)
  contributors.yml
  docs/tutorials/jokes.md
Labels: CLA Signed

#1805 docs: fix typo -- remove erroneous apostrophe
  contributors.yml
  docs/tutorials/jokes.md
Labels: CLA Signed

#1505 chore(docs): typo in internal link
  contributors.yml
  docs/guides/data-loading.md
Labels: CLA Signed

#1476 Fixes typo
  contributors.yml
  docs/pages/technical-explanation.md
Labels: CLA Signed

#1471 Fix typo
  contributors.yml
  examples/blog-tutorial/app/utils.server.tsx
Labels: CLA Signed

#1284 fix(docs): typo in conventions.md
  contributors.yml
  docs/api/conventions.md
Labels: CLA Signed

#1241 fix typo
  contributors.yml
  docs/api/remix.md
Labels: CLA Signed

#1231 docs: fix typo in Mutations section
  contributors.yml
  docs/tutorials/jokes.md
Labels: CLA Signed

#1218 fix(docs): typo in jokes tutorial
  contributors.yml
  docs/tutorials/jokes.md
Labels: CLA Signed

#1205 doc: fix typo in "use cookies" section
  contributors.yml
  docs/api/remix.md
Labels: CLA Signed

#1169 docs: fix typo in docs/guides/styling.md
  contributors.yml
  docs/guides/styling.md
Labels: CLA Signed

#1821 docs(examples): link labels with their fields in examples, to enhance accessibility
  examples/blog-tutorial/app/routes/admin/new.tsx
  examples/client-side-validation/app/root.tsx
  examples/client-side-validation/package-lock.json
  examples/route-modal/app/routes/invoices/$id/edit.tsx
  examples/route-modal/app/routes/invoices/add.tsx
Labels: CLA Signed

#1813 [Docs] – Add `useLoaderData` import to "Using Sessions" example
  contributors.yml
  docs/api/remix.md
Labels: CLA Signed

#1784 docs: fix CLA link in contributing.md
  contributors.yml
  docs/pages/contributing.md
Labels: CLA Signed

#1742 Correct code example in Remix Package docs for transition.type
  contributors.yml
  docs/api/remix.md
Labels: CLA Signed

#1565 docs: fix variable name in CatchBoundary example
  contributors.yml
  docs/api/conventions.md
Labels: CLA Signed

#1734 docs(examples): rename `with-rust` to `rust`
  examples/rust/.gitignore
  examples/rust/README.md
  examples/rust/app/entry.client.tsx
  examples/rust/app/entry.server.tsx
  examples/rust/app/root.tsx
  examples/rust/app/routes/index.tsx
  examples/rust/app/rust.server.ts
  examples/rust/app/styles/global.css
  examples/rust/app/styles/index.css
  examples/rust/package.json
  examples/rust/public/favicon.ico
  examples/rust/remix.config.js
  examples/rust/remix.env.d.ts
  examples/rust/rust-functions/.gitignore
  examples/rust/rust-functions/Cargo.toml
  examples/rust/rust-functions/src/lib.rs
  examples/rust/tsconfig.json
  examples/with-rust/package-lock.json
Labels: CLA Signed

#1546 docs(jsdoc): Add missing JSDocs, including @see pointers to the docs
  contributors.yml
  packages/remix-cloudflare-pages/sessions/cloudflareKVSessionStorage.ts
  packages/remix-node/parseMultipartFormData.ts
  packages/remix-node/sessions/fileStorage.ts
  packages/remix-react/components.tsx
  packages/remix-react/errorBoundaries.tsx
  packages/remix-react/routeModules.ts
  packages/remix-react/scroll-restoration.tsx
  packages/remix-server-runtime/cookies.ts
  packages/remix-server-runtime/responses.ts
  packages/remix-server-runtime/sessions.ts
  packages/remix-server-runtime/sessions/cookieStorage.ts
  packages/remix-server-runtime/sessions/memoryStorage.ts
Labels: CLA Signed

#1835 Add Netlify-specific context to Remix server actions
  contributors.yml
  packages/create-remix/templates/netlify/server.js
Labels: CLA Signed

#1440 chore(docs): updates response const -> let
  contributors.yml
  docs/other-api/adapter.md
Labels: CLA Signed

#1436 docs(blog): Add prerequisites to Developer Blog page
  contributors.yml
  docs/tutorials/blog.md
Labels: CLA Signed

#1431 docs: update code highlights
  contributors.yml
  docs/api/remix.md
  docs/guides/data-writes.md
  docs/guides/envvars.md
  docs/guides/optimistic-ui.md
  docs/other-api/adapter.md
  docs/other-api/serve.md
Labels: CLA Signed

#1535 docs(examples): Add DataLoader example
  examples/dataloader/.gitignore
  examples/dataloader/README.md
  examples/dataloader/app/data.server.ts
  examples/dataloader/app/entry.client.tsx
  examples/dataloader/app/entry.server.tsx
  examples/dataloader/app/loaders/userLoader.ts
  examples/dataloader/app/root.tsx
  examples/dataloader/app/routes/index.tsx
  examples/dataloader/app/routes/users.tsx
  examples/dataloader/app/routes/users/index.tsx
  examples/dataloader/package-lock.json
  examples/dataloader/package.json
  examples/dataloader/public/favicon.ico
  examples/dataloader/remix.config.js
  examples/dataloader/remix.env.d.ts
  examples/dataloader/server/index.ts
  examples/dataloader/tsconfig.json
Labels: CLA Signed

#1844 chore: update docs links (`main` branch)
  README.md
  examples/catch-boundary/README.md
  examples/client-side-validation/README.md
  examples/combobox-resource-route/app/routes/index.tsx
  examples/multiple-forms/README.md
  examples/nprogress/README.md
  examples/pathless-routes/README.md
  examples/redis-upstash-session/app/sessions/upstash.server.ts
  examples/remix-auth-supabase/app/supabase.ts
  examples/sharing-loader-data/README.md
  examples/socket.io/README.md
  examples/strapi/README.md
  examples/tailwindcss/README.md
  packages/remix-server-runtime/sessions.ts
Labels: CLA Signed

#1843 chore: update docs links (`dev` branch)
  README.md
  examples/catch-boundary/README.md
  examples/client-side-validation/README.md
  examples/combobox-resource-route/app/routes/index.tsx
  examples/multiple-forms/README.md
  examples/nprogress/README.md
  examples/pathless-routes/README.md
  examples/redis-upstash-session/app/sessions/upstash.server.ts
  examples/remix-auth-supabase/app/supabase.ts
  examples/sharing-loader-data/README.md
  examples/socket.io/README.md
  examples/strapi/README.md
  examples/tailwindcss/README.md
  packages/remix-cloudflare-pages/sessions/cloudflareKVSessionStorage.ts
  packages/remix-node/parseMultipartFormData.ts
  packages/remix-node/sessions/fileStorage.ts
  packages/remix-react/components.tsx
  packages/remix-react/errorBoundaries.tsx
  packages/remix-react/routeModules.ts
  packages/remix-react/scroll-restoration.tsx
  packages/remix-server-runtime/cookies.ts
  packages/remix-server-runtime/responses.ts
  packages/remix-server-runtime/sessions.ts
  packages/remix-server-runtime/sessions/cookieStorage.ts
  packages/remix-server-runtime/sessions/memoryStorage.ts
Labels: CLA Signed

#1339 fix(docs): minor fix in api/conventions#IgnoringSearchParams
  docs/api/conventions.md
Labels: CLA Signed

#1296 fix(docs): minor corrections in styling#tailwind
  contributors.yml
  docs/guides/styling.md
Labels: CLA Signed

#1266 docs: fix type error `POST` to `post`
  contributors.yml
  docs/api/remix.md
Labels: CLA Signed

#1634 docs: Adds example of Prisma generated type
  contributors.yml
  docs/guides/data-loading.md
Labels: CLA Signed

#1669 docs(example): add an example of using useMatches to access loader data across your application
  contributors.yml
  examples/usematches-loader-data/.gitignore
  examples/usematches-loader-data/README.md
  examples/usematches-loader-data/app/db.server.ts
  examples/usematches-loader-data/app/entry.client.tsx
  examples/usematches-loader-data/app/entry.server.tsx
  examples/usematches-loader-data/app/root.tsx
  examples/usematches-loader-data/app/routes/index.tsx
  examples/usematches-loader-data/app/useMatchesData.ts
  examples/usematches-loader-data/app/useUser.ts
  examples/usematches-loader-data/package-lock.json
  examples/usematches-loader-data/package.json
  examples/usematches-loader-data/public/favicon.ico
  examples/usematches-loader-data/remix.config.js
  examples/usematches-loader-data/remix.env.d.ts
  examples/usematches-loader-data/tsconfig.json
Labels: CLA Signed

#1855 updated the correct example for `createMemorySessionStorage()`
  contributors.yml
  docs/api/remix.md
Labels: CLA Signed

#1850 chore: run ESLint on MD codeblocks
  .eslintrc.js
  NOTES.md
  docs/api/conventions.md
  docs/api/remix.md
  docs/guides/api-routes.md
  docs/guides/constraints.md
  docs/guides/data-loading.md
  docs/guides/disabling-javascript.md
  docs/guides/optimistic-ui.md
  docs/guides/resource-routes.md
  docs/guides/styling.md
  docs/pages/philosophy.md
  docs/pages/technical-explanation.md
  docs/tutorials/blog.md
  docs/tutorials/jokes.md
  examples/sanity/app/components/Preview.jsx
  package.json
  yarn.lock
Labels: CLA Signed

#1860 docs: Add context for deployment from blog tutorial
  docs/tutorials/blog.md
Labels: CLA Signed

#1801 chore: Create `release` script
  DEVELOPMENT.md
  package.json
  scripts/release.js
  scripts/tsconfig.json
  scripts/utils.js
  scripts/version.js
  yarn.lock
Labels: CLA Signed

#1780 fix(remix-architect,remix-netlify): support binary data responses
  packages/remix-architect/__tests__/554828.jpeg
  packages/remix-architect/__tests__/server-test.ts
  packages/remix-architect/binary-types.ts
  packages/remix-architect/server.ts
  packages/remix-netlify/__tests__/554828.jpeg
  packages/remix-netlify/__tests__/server-test.ts
  packages/remix-netlify/binary-types.ts
  packages/remix-netlify/server.ts
Labels: CLA Signed

#1225 docs: fix invalid ternary statement
  docs/api/remix.md
Labels: CLA Signed

#1213 docs: CSS Preprocessors
  contributors.yml
  docs/guides/styling.md
Labels: CLA Signed

#1154 (fix:docs) Added information about the `end` prop for NavLink
  contributors.yml
  docs/api/remix.md
Labels: CLA Signed

#936 fix: Numerical URL targets cause site hang
  contributors.yml
  packages/remix-react/scroll-restoration.tsx
Labels: CLA Signed, accepted

#739 PNPM fix: Add missing `history` phantom dep to `@remix-run/react` package
  contributors.yml
  packages/remix-react/browser.tsx
  packages/remix-react/components.tsx
  packages/remix-react/errorBoundaries.tsx
  packages/remix-react/links.ts
  packages/remix-react/routeMatching.ts
  packages/remix-react/routeModules.ts
  packages/remix-react/server.tsx
  packages/remix-react/transition.ts
Labels: CLA Signed

#1863 Fix DynamoDB key for arcTableSessionStorage deleteData
  packages/remix-architect/sessions/arcTableSessionStorage.ts
Labels: CLA Signed

#1861 fix(create-remix/express): update caching to be dynamic based on path
  packages/create-remix/templates/express/server.js
Labels: CLA Signed

#1859 chore: use `async` `action`/`loader` functions
  docs/pages/faq.md
  examples/dataloader/app/routes/index.tsx
  examples/remix-auth-auth0/app/routes/auth0.tsx
  examples/remix-auth-auth0/app/routes/callback.tsx
  examples/route-modal/app/routes/invoices/$id/edit.tsx
  examples/routes-gen/app/routes/products/index.tsx
Labels: CLA Signed

#1858 chore: fix formatting
  docs/pages/faq.md
Labels: CLA Signed

#1847 fix(remix-server-runtime): fix headers function access to loaderHeaders when parent has no loader
  contributors.yml
  integration/headers-test.ts
  packages/remix-server-runtime/headers.ts
  packages/remix-server-runtime/server.ts
Labels: CLA Signed

#1846 chore: run workflows on main repo only (`dev` branch)
  .github/workflows/format.yml
Labels: CLA Signed

#1845 chore: run workflows on main repo only (`main` branch)
  .github/workflows/arc-prerelease-deployment.test.yml
  .github/workflows/cf-pages-prerelease-deployment.test.yml
  .github/workflows/cf-workers-prerelease-deployment.test.yml
  .github/workflows/fly-prerelease-deployment-test.yml
  .github/workflows/format.yml
  .github/workflows/netlify-prerelease-deployment-test.yml
  .github/workflows/vercel-prerelease-deployment-test.yml
Labels: CLA Signed

#1864 chore: fix formatting
  docs/guides/styling.md
  docs/tutorials/jokes.md
Labels: CLA Signed

#1872 docs: fix wrong new code line marking in blog tutorial
  contributors.yml
  docs/tutorials/blog.md
Labels: CLA Signed

#1873 chore: enable MD codeblock linting again
  .eslintrc.js
Labels: CLA Signed

#1477 docs(examples): Add ioredis example
  contributors.yml
  examples/ioredis/.env.example
  examples/ioredis/.gitignore
  examples/ioredis/README.md
  examples/ioredis/app/entry.client.tsx
  examples/ioredis/app/entry.server.tsx
  examples/ioredis/app/root.tsx
  examples/ioredis/app/routes/index.tsx
  examples/ioredis/app/utils/redis.server.ts
  examples/ioredis/package-lock.json
  examples/ioredis/package.json
  examples/ioredis/public/favicon.ico
  examples/ioredis/remix.config.js
  examples/ioredis/remix.env.d.ts
  examples/ioredis/tsconfig.json
Labels: CLA Signed

#1240 fix: button data is missing if clicking on the svg element within the button
  contributors.yml
  fixtures/gists-app/app/routes/methods.tsx
  integration/form-test.ts
  packages/remix-react/components.tsx
Labels: CLA Signed

#1877 docs(tutorial): link label with its field in blog tutorial, to enhance accessibility
  docs/tutorials/blog.md
Labels: CLA Signed

#1789 feat: implement debug flag to attach debugger (#337, #795)
  contributors.yml
  packages/remix-dev/__tests__/cli-test.ts
  packages/remix-dev/cli.ts
Labels: CLA Signed

#1882 Change ?? to || in ScrollRestoration inlined code
  packages/remix-react/scroll-restoration.tsx
Labels: CLA Signed

#1881 cherry pick 1685 commits
  contributors.yml
  packages/remix-react/__tests__/components-test.tsx
  packages/remix-react/components.tsx
Labels: CLA Signed

#1638 fix: adds support for creating new projects with nested paths
  contributors.yml
  packages/create-remix/index.ts
Labels: CLA Signed

#1573 fixed code line highlights in Expected Errors section of jokes tutorial.
  docs/tutorials/jokes.md
Labels: CLA Signed

#1563 fix(ci): use built in cache strategy
  .github/workflows/test.yml
  contributors.yml
Labels: CLA Signed

#1429 Remove unneeded while loop
  examples/redis-upstash-session/app/sessions/upstash.server.ts
Labels: CLA Signed

#1416 Update fetcher load/submit error message
  packages/remix-react/components.tsx
  packages/remix-react/transition.ts
Labels: CLA Signed

#1350 Fix filename in Tutorial
  contributors.yml
  docs/tutorials/blog.md
Labels: CLA Signed

#1306 Add return to redirect
  contributors.yml
  docs/guides/data-writes.md
Labels: CLA Signed

#1883 feat(create-remix): run init script during project scaffolding
  packages/create-remix/index.ts
  packages/create-remix/package.json
  packages/create-remix/templates/arc-stack/README.md
  packages/create-remix/templates/arc-stack/github/workflows/deploy.yml
  packages/create-remix/templates/arc-stack/gitignore
  packages/create-remix/templates/arc-stack/scripts/init.js
  packages/create-remix/templates/fly-stack/README.md
  packages/create-remix/templates/fly-stack/package.json
  packages/create-remix/templates/fly-stack/scripts/init.js
  packages/create-remix/templates/fly-stack/scripts/init.mjs
  yarn.lock
Labels: CLA Signed

#1245 fix Route Module Constraints link
  contributors.yml
  docs/api/remix.md
Labels: CLA Signed

#1237 Add native _redirects support for Cloudflare Pages
  packages/remix-cloudflare-pages/worker.ts
Labels: CLA Signed

#1235 fix: remove misleading PrefetchBehavior document
  contributors.yml
  packages/remix-react/components.tsx
Labels: CLA Signed

#1234 fix: add status text to express & vercel packages
  packages/remix-express/server.ts
  packages/remix-vercel/server.ts
Labels: CLA Signed

#1199 Link to contributing page directly
  README.md
  contributors.yml
Labels: CLA Signed

#1203 build: add .ico loader
  fixtures/gists-app/app/root.jsx
  packages/remix-dev/compiler/loaders.ts
Labels: CLA Signed

#1181 [Feature]: Make the default path of cookies to be /
  packages/remix-server-runtime/__tests__/cookies-test.ts
  packages/remix-server-runtime/__tests__/sessions-test.ts
  packages/remix-server-runtime/cookies.ts
Labels: CLA Signed

#1157 Use replace instead of replaceAll in jokes tutorial
  contributors.yml
  docs/tutorials/jokes.md
Labels: CLA Signed

#1175 feat(#310): display version number in create-remix cli
  packages/create-remix/cli.ts
Labels: CLA Signed

#1146 Change recommended test command for projects
  contributors.yml
  docs/pages/contributing.md
Labels: CLA Signed

#1130 Rename `Whoa` function name to Whoa instead of `AboutIndex`
  contributors.yml
  examples/basic/app/routes/demos/about/whoa.tsx
  examples/blog-tutorial/app/routes/demos/about/whoa.tsx
Labels: CLA Signed

#1103 tweak wording for root default components
  packages/remix-react/errorBoundaries.tsx
Labels: CLA Signed

#1100 refactor: getStylesheetPrefetchLinks (one more time)
  packages/remix-react/links.ts
Labels: CLA Signed

#1893 chore: fix 'No Response' workflow
  .github/workflows/no-response.yml
Labels: CLA Signed

#1897 docs: typos in /api/remix
  docs/api/remix.md
Labels: CLA Signed

#1895 ci: update format PAT
  .github/workflows/format.yml
Labels: CLA Signed

#1894 chore: run 'No Response' workflow on main repo only
  .github/workflows/no-response.yml
Labels: CLA Signed

#1899 docs: fix typo in /api/remix
  docs/api/remix.md
Labels: CLA Signed

#1888 chore(useMatches): memoize matches
  contributors.yml
  packages/remix-react/components.tsx
Labels: CLA Signed, needs-response

#1180 fix(remix-eslint-config): fix dependencies
  packages/remix-eslint-config/package.json
  yarn.lock
Labels: CLA Signed

#1123 chore(react): update links rel and as unions to LiteralUnion for better IntelliSense
  packages/remix-react/links.ts
Labels: CLA Signed

#832 Prevent pushing miniflare files to github
  contributors.yml
  packages/create-remix/templates/cloudflare-workers/gitignore
Labels: CLA Signed

#679 docs(jokes): fix passwordHash included in body on /jokes/* response in
  contributors.yml
  docs/tutorials/jokes.md
  examples/jokes/app/routes/jokes.tsx
  examples/jokes/app/utils/session.server.ts
Labels: CLA Signed

#1903 chore: added warning about the unavailability of build
  contributors.yml
  examples/socket.io/server/index.js
Labels: CLA Signed

#1913 feat: expose upload handler types
  packages/remix-node/index.ts
  packages/remix-node/magicExports/platform.ts
Labels: CLA Signed

#1836 Add cache-control header to cloudflare pages template
  contributors.yml
  packages/create-remix/templates/cloudflare-pages/public/_headers
Labels: CLA Signed

#1927 docs(example): Bullmq Task Queue Example
  contributors.yml
  examples/bullmq-task-queue/.env.example
  examples/bullmq-task-queue/.gitignore
  examples/bullmq-task-queue/README.md
  examples/bullmq-task-queue/app/entry.client.tsx
  examples/bullmq-task-queue/app/entry.server.tsx
  examples/bullmq-task-queue/app/queues/notifier.server.ts
  examples/bullmq-task-queue/app/root.tsx
  examples/bullmq-task-queue/app/routes/index.tsx
  examples/bullmq-task-queue/app/utils/redis.server.ts
  examples/bullmq-task-queue/package-lock.json
  examples/bullmq-task-queue/package.json
  examples/bullmq-task-queue/public/favicon.ico
  examples/bullmq-task-queue/remix.config.js
  examples/bullmq-task-queue/remix.env.d.ts
  examples/bullmq-task-queue/tsconfig.json
Labels: CLA Signed

#1948 refactor: use ternaries rather than && in JSX
  docs/api/remix.md
  docs/guides/styling.md
  docs/pages/technical-explanation.md
  examples/image-resize/app/components/image.tsx
  examples/remix-auth-auth0/app/routes/index.tsx
  examples/remix-auth-form/app/routes/login.tsx
  examples/remix-auth-github/app/routes/index.tsx
  examples/route-modal/app/routes/invoices/add.tsx
  examples/search-input/app/routes/index.tsx
Labels: CLA Signed

#1839 feat: add serverDependenciesToBundle to remix config
  integration/compiler-test.ts
  packages/remix-dev/__tests__/readConfig-test.ts
  packages/remix-dev/compiler/plugins/serverBareModulesPlugin.ts
  packages/remix-dev/config.ts
Labels: CLA Signed

#1958 fix(remix-architect,remix-netlify): update binary data responses
  packages/remix-architect/__tests__/server-test.ts
  packages/remix-architect/server.ts
  packages/remix-netlify/__tests__/server-test.ts
  packages/remix-netlify/server.ts
Labels: CLA Signed

#1331 chore(remix-react): make inline scripts more robust
  contributors.yml
  packages/remix-react/__tests__/components-test.tsx
  packages/remix-react/components.tsx
  packages/remix-react/scroll-restoration.tsx
Labels: CLA Signed

#1961 docs: fix missing property serialization
  contributors.yml
  docs/pages/philosophy.md
Labels: CLA Signed

#1937 fix: restore scroll position for hashed routes
  contributors.yml
  packages/remix-react/scroll-restoration.tsx
Labels: CLA Signed

#1925 [Doc][Tutorial][Developer Blog] Delete obsolete line
  contributors.yml
  docs/tutorials/blog.md
Labels: CLA Signed

#1905 chore: have VS Code use project typescript version
  .gitignore
  .vscode/settings.json
Labels: CLA Signed

#1971 fix(create-remix): escape [ and ] in .gitignore
  contributors.yml
  packages/create-remix/templates/cloudflare-pages/gitignore
Labels: CLA Signed

#1976 chore: add experimental label for deno
  packages/create-remix/cli.ts
Labels: CLA Signed

#1975 chore: revert esbuild version
  packages/remix-dev/package.json
  yarn.lock
Labels: CLA Signed

#1969 fix(create-remix/stacks): dont return user password from functions
  packages/create-remix/index.ts
  packages/create-remix/package.json
  packages/create-remix/templates/arc-stack/README.md
  packages/create-remix/templates/arc-stack/app.arc
  packages/create-remix/templates/arc-stack/app/models/user.ts
  packages/create-remix/templates/arc-stack/app/root.tsx
  packages/create-remix/templates/arc-stack/app/routes/index.tsx
  packages/create-remix/templates/arc-stack/app/routes/join.tsx
  packages/create-remix/templates/arc-stack/app/routes/login.tsx
  packages/create-remix/templates/arc-stack/app/session.server.ts
  packages/create-remix/templates/arc-stack/app/styles/global.css
  packages/create-remix/templates/arc-stack/package-lock.json
  packages/create-remix/templates/arc-stack/package.json
  packages/create-remix/templates/fly-stack/app/models/note.server.ts
  packages/create-remix/templates/fly-stack/app/models/user.server.ts
  packages/create-remix/templates/fly-stack/app/root.tsx
  packages/create-remix/templates/fly-stack/app/routes/index.tsx
  packages/create-remix/templates/fly-stack/app/routes/join.tsx
  packages/create-remix/templates/fly-stack/app/routes/login.tsx
  packages/create-remix/templates/fly-stack/app/session.server.ts
  packages/create-remix/templates/fly-stack/app/styles/app.css
  packages/create-remix/templates/fly-stack/package-lock.json
  packages/create-remix/templates/fly-stack/package.json
  packages/create-remix/templates/fly-stack/prisma/migrations/20220216171839_init/migration.sql
  packages/create-remix/templates/fly-stack/prisma/schema.prisma
  yarn.lock
Labels: CLA Signed

#1260 docs(blog): fix diff highlights in tutorial for getPost function
  contributors.yml
  docs/tutorials/blog.md
Labels: CLA Signed, needs-response

#1418 docs(jokes): minor fixes and improvements
  contributors.yml
  docs/tutorials/jokes.md
  examples/jokes/app/routes/jokes/$jokeId.tsx
  examples/jokes/app/routes/jokes/new.tsx
  examples/jokes/app/routes/login.tsx
Labels: CLA Signed

#1808 docs(examples): added file upload example
  contributors.yml
  examples/file-and-cloudinary-upload/.env.sample
  examples/file-and-cloudinary-upload/.gitignore
  examples/file-and-cloudinary-upload/README.md
  examples/file-and-cloudinary-upload/app/entry.client.tsx
  examples/file-and-cloudinary-upload/app/entry.server.tsx
  examples/file-and-cloudinary-upload/app/root.tsx
  examples/file-and-cloudinary-upload/app/routes/cloudinary-upload.tsx
  examples/file-and-cloudinary-upload/app/routes/local-upload.tsx
  examples/file-and-cloudinary-upload/app/utils/utils.server.ts
  examples/file-and-cloudinary-upload/package-lock.json
  examples/file-and-cloudinary-upload/package.json
  examples/file-and-cloudinary-upload/public/favicon.ico
  examples/file-and-cloudinary-upload/remix.config.js
  examples/file-and-cloudinary-upload/remix.env.d.ts
  examples/file-and-cloudinary-upload/tsconfig.json
Labels: CLA Signed

#1922 docs: update highlighting in data loading
  contributors.yml
  docs/guides/data-loading.md
Labels: CLA Signed

#1947 docs: fix typo in tutorials/blog
  contributors.yml
  docs/tutorials/blog.md
Labels: CLA Signed

#1954 docs: update cloudinary stream upload
  docs/api/remix.md
Labels: CLA Signed

#1994 Simpler asset caching strategy in Express template
  packages/create-remix/templates/express/server.js
Labels: CLA Signed

#1992 fix(remix-dev): update `serverModuleFormat` deprecation notice
  packages/remix-dev/config.ts
Labels: CLA Signed

#2013 fix(node): add source-map-support to base node pkg
  packages/remix-architect/server.ts
  packages/remix-express/server.ts
  packages/remix-netlify/server.ts
  packages/remix-node/__tests__/errors-test.ts
  packages/remix-node/errors.ts
  packages/remix-node/index.ts
  packages/remix-node/package.json
  packages/remix-server-runtime/platform.ts
  packages/remix-vercel/server.ts
  yarn.lock
Labels: CLA Signed

#1417 docs(examples): add react-spring example
  examples/react-spring/.gitignore
  examples/react-spring/README.md
  examples/react-spring/app/entry.client.tsx
  examples/react-spring/app/entry.server.tsx
  examples/react-spring/app/no-script.css
  examples/react-spring/app/root.tsx
  examples/react-spring/app/routes/index.tsx
  examples/react-spring/app/styles.css
  examples/react-spring/package-lock.json
  examples/react-spring/package.json
  examples/react-spring/public/favicon.ico
  examples/react-spring/remix.config.js
  examples/react-spring/remix.env.d.ts
  examples/react-spring/tsconfig.json
Labels: CLA Signed

#2019 fix: strip ".client" files from server bundle
  integration/compiler-test.ts
  packages/remix-dev/compiler.ts
Labels: CLA Signed

#2025 fix(components): use typeof document
  docs/pages/gotchas.md
  examples/pm-app/app/utils/index.ts
  packages/remix-react/components.tsx
Labels: CLA Signed

#1500 chore(examples): add postcss as tailwindcss dependency (#1497)
  contributors.yml
  examples/tailwindcss/package.json
Labels: CLA Signed

#1997 fix: use browser polyfills for deno node builtins
  packages/remix-dev/compiler.ts
  packages/remix-dev/compiler/plugins/serverBareModulesPlugin.ts
Labels: CLA Signed

#1854 fix: `onSubmit`: Get submission values from form attributes instead of props
  integration/form-test.ts
  integration/helpers/create-fixture.tsx
  packages/remix-react/components.tsx
Labels: CLA Signed

#2061 fix(remix-dev): Remove x-powered-by header from Express dev server
  contributors.yml
  packages/remix-dev/cli/commands.ts
Labels: CLA Signed

#2059 fix: Allow `process.env.NODE_ENV === "test"` in build
  packages/remix-dev/build.ts
Labels: CLA Signed

#1986 ci: add retry logic to fly and cf pages deployments
  .github/workflows/deployment-test.yml
  scripts/deployment-test/_shared.mjs
  scripts/deployment-test/arc.mjs
  scripts/deployment-test/cf-pages.mjs
  scripts/deployment-test/cf-workers.mjs
  scripts/deployment-test/fly.mjs
  scripts/deployment-test/netlify.mjs
  scripts/deployment-test/vercel.mjs
Labels: CLA Signed

#2081 chore: ESLint integration
  packages/remix-eslint-config/index.js
  packages/remix-eslint-config/package.json
  packages/remix-eslint-config/rules/jsx-a11y.js
  packages/remix-eslint-config/rules/react.js
  packages/remix-eslint-config/settings/import.js
  packages/remix-eslint-config/settings/react.js
  packages/remix-react/components.tsx
Labels: CLA Signed

#1232 fix(dev/compiler): mark imports using node protocol as external
  packages/remix-dev/compiler/plugins/serverBareModulesPlugin.ts
Labels: CLA Signed

#2090 docs: Update small typos in data-writes.md
  contributors.yml
  docs/guides/data-writes.md
Labels: CLA Signed

#2037 Small typo fix Update README.md
  contributors.yml
  examples/chakra-ui/README.md
Labels: CLA Signed

#1259 docs: fixed small mistake
  contributors.yml
Labels: CLA Signed

#2011 docs: Update README.md
  contributors.yml
  examples/file-and-cloudinary-upload/README.md
Labels: CLA Signed
