Repository remix-run/remix, pull requests merged in 2022-06, with the labels that each got.

#3315 chore: run `sort-package-json` on packages
  package.json
  packages/create-remix/package.json
  packages/remix-architect/package.json
  packages/remix-cloudflare-pages/package.json
  packages/remix-cloudflare-workers/package.json
  packages/remix-cloudflare/package.json
  packages/remix-deno/package.json
  packages/remix-dev/package.json
  packages/remix-eslint-config/package.json
  packages/remix-express/package.json
  packages/remix-netlify/package.json
  packages/remix-node/package.json
  packages/remix-react/package.json
  packages/remix-serve/package.json
  packages/remix-server-runtime/package.json
  packages/remix-vercel/package.json
  packages/remix/package.json
Labels: CLA Signed

#3353 fix(examples/firebase-auth-firestore): Fix imports and throw meaningful errors when missing .env
  contributors.yml
  examples/firebase-auth-firestore/app/server/firebase.server.ts
Labels: CLA Signed, examples

#3370 ci: do not automatically add `name` field in `package.json` for apps
  .github/workflows/format.yml
  scripts/patchup-example-names.mjs
Labels: CLA Signed

#2057 feat(templates/vercel): add `$schema` in vercel config file
  templates/vercel/vercel.json
Labels: CLA Signed, template:vercel

#3381 chore(templates): update `vercel` template
  templates/vercel/package.json
  templates/vercel/vercel.json
Labels: CLA Signed, template:vercel

#3375 ci: update needs-response workflow to use official stale action
  .github/workflows/no-response.yml
Labels: CLA Signed

#3391 fix(remix-dev): Allow debugging for the remix shorthand
  packages/remix-dev/cli/run.ts
Labels: CLA Signed, package:dev

#3358 fix(examples): use `post` action in `firebase-auth-firestore` example
  examples/firebase-auth-firestore/app/routes/index.tsx
Labels: CLA Signed, examples

#3368 docs(guides/envvars): clarify docs for local/production env variables
  contributors.yml
  docs/guides/envvars.md
Labels: CLA Signed, documentation

#3362 feat(examples/firebase-auth-firestore): use rest api for server auth
  examples/firebase-auth-firestore/.env.example
  examples/firebase-auth-firestore/README.md
  examples/firebase-auth-firestore/app/server/auth.server.ts
  examples/firebase-auth-firestore/app/server/firebase-rest.server.ts
  examples/firebase-auth-firestore/app/server/firebase.server.ts
  examples/firebase-auth-firestore/package.json
Labels: CLA Signed, examples

#3413 fix(remix-dev): add `@babel/preset-env` in `dependencies`
  packages/remix-dev/package.json
  yarn.lock
Labels: CLA Signed, package:dev

#3418 docs(guide): fix typo in Migrating React Router App
  contributors.yml
  docs/guides/migrating-react-router-app.md
Labels: CLA Signed, documentation

#3417 feat(examples/firebase-auth-firestore): avoid auth rate limiting
  examples/firebase-auth-firestore/app/firebase-rest.ts
  examples/firebase-auth-firestore/app/routes/login.tsx
  examples/firebase-auth-firestore/app/server/auth.server.ts
  examples/firebase-auth-firestore/app/server/firebase.server.ts
Labels: CLA Signed, examples

#3426 chore: update GitHub Actions
  .github/workflows/stacks.yml
  .github/workflows/website.yml
Labels: CLA Signed

#3432 tests: update Tailwind config in tests
  packages/remix-dev/__tests__/fixtures/replace-remix-imports/package.json
  packages/remix-dev/__tests__/fixtures/replace-remix-imports/tailwind.config.js
  scripts/playground/template/package.json
  scripts/playground/template/tailwind.config.js
Labels: CLA Signed

#3440 chore(examples): import `installGlobals` from package root in `blog-tutorial` example
  examples/blog-tutorial/cypress/support/create-user.ts
  examples/blog-tutorial/cypress/support/delete-user.ts
  examples/blog-tutorial/test/setup-test-env.ts
Labels: CLA Signed, examples

#3436 fix(remix-server-runtime): use correct error/catch boundary on SSR action errors
  integration/catch-boundary-test.ts
  integration/error-boundary-test.ts
  packages/remix-server-runtime/__tests__/server-test.ts
  packages/remix-server-runtime/server.ts
Labels: CLA Signed, package:server-runtime

#3445 enhancement(cli): Ask about TypeScript before `npm install`
  packages/remix-dev/__tests__/cli-test.ts
  packages/remix-dev/cli/create.ts
  packages/remix-dev/cli/run.ts
Labels: CLA Signed, package:dev

#3447 enhancement(dev/cli): Add `--port` flag to `remix dev`
  packages/remix-dev/__tests__/cli-test.ts
  packages/remix-dev/cli/commands.ts
  packages/remix-dev/cli/run.ts
Labels: CLA Signed, package:dev

#3384 docs(tutorial/jokes): Add missing createUserSession import
  contributors.yml
  docs/tutorials/jokes.md
Labels: CLA Signed, documentation

#3459 docs(tutorials/jokes): update code highlighting
  docs/tutorials/jokes.md
Labels: CLA Signed, documentation

#3472 ci: dont cut a nightly if the latest dev commit was the last nightly
  .github/workflows/nightly.yml
Labels: CLA Signed

#3470 ci: migrate workflows to use `workflow_call` instead of `repository_dispatch`
  .github/workflows/deployments.yml
  .github/workflows/nightly.yml
  .github/workflows/release-comments.yml
  .github/workflows/release.yml
  .github/workflows/stacks.yml
Labels: CLA Signed

#3476 fix(templates/deno): fix `resolve_nom_imports`
  templates/deno/.vscode/resolve_npm_imports.json
Labels: CLA Signed, template:deno

#3477 chore: format Deno files
  .github/workflows/format.yml
  package.json
  packages/remix-deno/.empty.js
  packages/remix-deno/README.md
  templates/deno/.vscode/extensions.json
  templates/deno/README.md
Labels: CLA Signed

#3483 chore: lint & format Deno files
  .github/workflows/format.yml
  .github/workflows/test.yml
  package.json
  packages/remix-deno/.empty.js
  packages/remix-deno/README.md
  packages/remix-deno/globals.ts
  templates/deno/.vscode/extensions.json
  templates/deno/README.md
Labels: CLA Signed

#3486 fix: add ignored files to Deno lint & format scripts
  package.json
Labels: CLA Signed

#3485 docs(tutorials/jokes): fix typo
  contributors.yml
  docs/tutorials/jokes.md
Labels: CLA Signed, documentation

#3488 fix: fix ignored files in Deno lint & format scripts
  package.json
Labels: CLA Signed

#3489 fix: fix ignored files in Deno lint & format scripts
  package.json
Labels: CLA Signed

#3484 docs(pages/contributing): add requirement to install `playwright`
  docs/pages/contributing.md
Labels: CLA Signed, documentation

#3463 chore(remix-dev): set default `devServerPort` to 8002
  packages/remix-dev/config.ts
Labels: CLA Signed, package:dev

#3490 docs(tutorials/jokes): fix code highlighting
  docs/tutorials/jokes.md
Labels: CLA Signed, documentation

#3491 docs: update incorrect fetcher.type "load" to "normalLoad"
  contributors.yml
  docs/api/remix.md
Labels: CLA Signed, documentation

#3496 Revert "chore(templates): update `vercel` template (#3381)"
  templates/vercel/package.json
Labels: CLA Signed, template:vercel

#3497 chore(scripts): remove obsoleted `dev` script
  package.json
Labels: CLA Signed

#3498 ci(nightly): fix NEXT_VERSION
  .github/workflows/nightly.yml
Labels: CLA Signed

#3501 ci(deployments): define required secrets
  .github/workflows/deployments.yml
  .github/workflows/nightly.yml
  .github/workflows/release.yml
Labels: CLA Signed

#3517 docs(conventions): Fix a typo
  contributors.yml
  docs/api/conventions.md
Labels: CLA Signed, documentation

#3520 ci: update how secrets are passed to reusable workflows
  .github/workflows/nightly.yml
  .github/workflows/release.yml
Labels: CLA Signed

#3443 ci: add script to convert links in docs to references
  .github/workflows/format.yml
  docs/api/conventions.md
  docs/api/remix.md
  docs/guides/accessibility.md
  docs/guides/cache-control.md
  docs/guides/constraints.md
  docs/guides/data-writes.md
  docs/guides/envvars.md
  docs/guides/errors.md
  docs/guides/mdx.md
  docs/guides/migrating-react-router-app.md
  docs/guides/not-found.md
  docs/guides/performance.md
  docs/guides/styling.md
  docs/guides/typescript.md
  docs/index.md
  docs/other-api/adapter.md
  docs/other-api/dev.md
  docs/other-api/fetch.md
  docs/other-api/react-router.md
  docs/other-api/serve.md
  docs/pages/contributing.md
  docs/pages/faq.md
  docs/pages/gotchas.md
  docs/pages/philosophy.md
  docs/pages/stacks.md
  docs/tutorials/blog.md
  docs/tutorials/jokes.md
  package.json
  scripts/markdown-references.mjs
  yarn.lock
Labels: CLA Signed

#3150 feat(remix-dev/cli/migrate): add `convert-to-javascript` migration
  .eslintignore
  packages/remix-dev/__tests__/migrations/convert-to-javascript-test.ts
  packages/remix-dev/__tests__/migrations/fixtures/indie-stack/app/entry.client.tsx
  packages/remix-dev/__tests__/migrations/fixtures/indie-stack/app/entry.server.tsx
  packages/remix-dev/__tests__/migrations/fixtures/indie-stack/app/root.tsx
  packages/remix-dev/__tests__/migrations/fixtures/indie-stack/app/routes/index.tsx
  packages/remix-dev/__tests__/migrations/fixtures/indie-stack/cypress/e2e/smoke.cy.ts
  packages/remix-dev/__tests__/migrations/fixtures/indie-stack/cypress/support/commands.ts
  packages/remix-dev/__tests__/migrations/fixtures/indie-stack/cypress/support/create-user.ts
  packages/remix-dev/__tests__/migrations/fixtures/indie-stack/cypress/support/delete-user.ts
  packages/remix-dev/__tests__/migrations/fixtures/indie-stack/cypress/support/e2e.ts
  packages/remix-dev/__tests__/migrations/fixtures/indie-stack/mocks/index.js
  packages/remix-dev/__tests__/migrations/fixtures/indie-stack/package.json
  packages/remix-dev/__tests__/migrations/fixtures/indie-stack/prisma/seed.ts
  packages/remix-dev/__tests__/migrations/fixtures/indie-stack/public/favicon.ico
  packages/remix-dev/__tests__/migrations/fixtures/indie-stack/remix.config.js
  packages/remix-dev/__tests__/migrations/fixtures/indie-stack/remix.env.d.ts
  packages/remix-dev/__tests__/migrations/fixtures/indie-stack/test/setup-test-env.ts
  packages/remix-dev/__tests__/migrations/fixtures/indie-stack/tsconfig.json
  packages/remix-dev/__tests__/migrations/fixtures/indie-stack/vitest.config.ts
  packages/remix-dev/cli/migrate/migrations/convert-to-javascript/cleanupPackageJson.ts
  packages/remix-dev/cli/migrate/migrations/convert-to-javascript/convertTSConfigs.ts
  packages/remix-dev/cli/migrate/migrations/convert-to-javascript/convertTSFilesToJS/convertTSFileToJS.ts
  packages/remix-dev/cli/migrate/migrations/convert-to-javascript/convertTSFilesToJS/index.ts
  packages/remix-dev/cli/migrate/migrations/convert-to-javascript/index.ts
  packages/remix-dev/cli/migrate/migrations/convert-to-javascript/transform/checkNoDifferentImportTypesCombined.ts
  packages/remix-dev/cli/migrate/migrations/convert-to-javascript/transform/createExpressionStatement.ts
  packages/remix-dev/cli/migrate/migrations/convert-to-javascript/transform/createVariableDeclarationIdentifier.ts
  packages/remix-dev/cli/migrate/migrations/convert-to-javascript/transform/createVariableDeclarationObjectPattern.ts
  packages/remix-dev/cli/migrate/migrations/convert-to-javascript/transform/index.ts
  packages/remix-dev/cli/migrate/migrations/index.ts
  packages/remix-dev/cli/migrate/migrations/transforms.ts
  packages/remix-dev/package.json
Labels: CLA Signed, package:dev

#3503 chore(docs): Build out CLI docs
  docs/other-api/dev.md
Labels: CLA Signed, documentation

#3511 docs(guides/data-writes): fix `form`/`Form` explanation
  contributors.yml
  docs/guides/data-writes.md
Labels: CLA Signed, documentation

#3473 docs(tutorials/blog): add 'create migration' step
  docs/tutorials/blog.md
Labels: CLA Signed, documentation

#3467 docs(examples): add firestore rules to `firebase-auth-firestore` example
  examples/firebase-auth-firestore/firebase-fixtures/auth/config.json
  examples/firebase-auth-firestore/firebase-fixtures/firestore.rules
  examples/firebase-auth-firestore/firebase.json
Labels: CLA Signed, examples

#3458 docs(api/remix): add note to sessions usage section
  contributors.yml
  docs/api/remix.md
Labels: CLA Signed, documentation

#3142 ci: use tags instead of releases
  .github/workflows/nightly.yml
  .github/workflows/release-comments.yml
  scripts/release/comment.mjs
  scripts/release/comment.ts
  scripts/release/constants.ts
  scripts/release/github.ts
  scripts/release/octokit.mjs
  scripts/release/octokit.ts
  scripts/release/package-lock.json
  scripts/release/package.json
  scripts/release/tsconfig.json
  scripts/release/utils.ts
Labels: CLA Signed

#3531 Brophdawg11/deferred cancellation
  packages/remix-node/globals.ts
  packages/remix-react/__tests__/setup.ts
  packages/remix-react/__tests__/transition-test.tsx
  packages/remix-react/transition.ts
Labels: CLA Signed

#3460 fix: Handle revalidations across multi-redirects
  integration/redirects-test.ts
  packages/remix-react/__tests__/transition-test.tsx
  packages/remix-react/transition.ts
Labels: CLA Signed

#3085 fix(remix-dev): update `serverBareModulesPlugin` to use `require.resolve` instead of using `package.json` to determine if deps are installed
  packages/remix-dev/compiler.ts
  packages/remix-dev/compiler/plugins/serverBareModulesPlugin.ts
Labels: CLA Signed

#3543 chore(refactor): Create `magicExports` in Rollup build
  package.json
  packages/remix-architect/magicExports/remix.ts
  packages/remix-cloudflare-pages/magicExports/remix.ts
  packages/remix-cloudflare-workers/magicExports/remix.ts
  packages/remix-cloudflare/magicExports/remix.ts
  packages/remix-node/magicExports/remix.ts
  packages/remix-react/magicExports/remix.ts
  packages/remix-server-runtime/magicExports/remix.ts
  rollup.config.js
  yarn.lock
Labels: CLA Signed

#2804 fix(remix-dev): fix private stack validation
  contributors.yml
  packages/remix-dev/__tests__/create-test.ts
  packages/remix-dev/__tests__/github-mocks.ts
  packages/remix-dev/cli/create.ts
  packages/remix-dev/cli/run.ts
Labels: CLA Signed, package:dev, feat:stacks

#3555 ci: move reusable actions to root workflow dir
  .github/workflows/deployments.yml
  .github/workflows/nightly.yml
  .github/workflows/release-comments.yml
  .github/workflows/release-test.yml
  .github/workflows/release.yml
  .github/workflows/reusable-test.yml
  .github/workflows/stacks.yml
  .github/workflows/test.yml
Labels: CLA Signed

#3540 chore: Add script for copying build output to package `dist` directories
  integration/cf-compiler-test.ts
  integration/compiler-test.ts
  integration/helpers/create-fixture.ts
  integration/helpers/node-template/package.json
  package.json
  packages/create-remix/package.json
  packages/create-remix/tsconfig.json
  packages/remix-architect/package.json
  packages/remix-architect/tsconfig.json
  packages/remix-cloudflare-pages/package.json
  packages/remix-cloudflare-pages/tsconfig.json
  packages/remix-cloudflare-workers/package.json
  packages/remix-cloudflare-workers/tsconfig.json
  packages/remix-cloudflare-workers/worker.ts
  packages/remix-cloudflare/package.json
  packages/remix-cloudflare/tsconfig.json
  packages/remix-dev/cli/setup.ts
  packages/remix-dev/package.json
  packages/remix-dev/tsconfig.json
  packages/remix-express/package.json
  packages/remix-express/tsconfig.json
  packages/remix-netlify/package.json
  packages/remix-netlify/tsconfig.json
  packages/remix-node/package.json
  packages/remix-node/tsconfig.json
  packages/remix-react/package.json
  packages/remix-react/tsconfig.json
  packages/remix-serve/package.json
  packages/remix-serve/tsconfig.json
  packages/remix-server-runtime/package.json
  packages/remix-server-runtime/tsconfig.json
  packages/remix-vercel/package.json
  packages/remix-vercel/tsconfig.json
  packages/remix/package.json
  packages/remix/tsconfig.json
  rollup.config.js
  scripts/clean-build.mjs
  scripts/copy-build-to-dist.mjs
  scripts/run-migration-on-examples.js
  scripts/tsconfig.json
  tsconfig.json
Labels: CLA Signed

#3080 chore(remix-dev): replace process.env.GITHUB_TOKEN with cli flag
  docs/other-api/dev.md
  docs/pages/stacks.md
  packages/remix-dev/__tests__/cli-test.ts
  packages/remix-dev/__tests__/create-test.ts
  packages/remix-dev/cli/create.ts
  packages/remix-dev/cli/run.ts
Labels: CLA Signed, documentation, package:dev

#3558 docs(blog-tutorial): fix prisma migrate command
  contributors.yml
  docs/tutorials/blog.md
Labels: CLA Signed, documentation

#3557 docs(api/conventions): add note about how to access server-side data in `meta` function
  contributors.yml
  docs/api/conventions.md
Labels: CLA Signed, documentation

#3567 chore(integration): improve build failure output in tests
  integration/helpers/create-fixture.ts
Labels: CLA Signed

#3571 fix(remix-dev/cli/init): always remove `remix.init` folder
  packages/remix-dev/__tests__/create-test.ts
  packages/remix-dev/cli/commands.ts
  packages/remix-dev/cli/run.ts
Labels: CLA Signed, package:dev

#3591 ci(release-test): remove pull_request trigger
  .github/workflows/release-test.yml
Labels: CLA Signed

#3579 fix(remix-dev): fix Yarn PnP resolve issue
  contributors.yml
  packages/remix-dev/compiler.ts
Labels: CLA Signed, package:dev

#3593 fix: remove bahmutov/npm-install to fix windows builds
  .github/workflows/deployments.yml
  .github/workflows/format.yml
  .github/workflows/nightly.yml
  .github/workflows/release-comments.yml
  .github/workflows/release-private.yml
  .github/workflows/release.yml
  .github/workflows/reusable-test.yml
  .github/workflows/stacks.yml
Labels: CLA Signed

#3607 fix: fix deep imports
  packages/remix-dev/.gitignore
  packages/remix-dev/package.json
  packages/remix-node/.gitignore
  packages/remix-node/package.json
  rollup.config.js
  scripts/copy-build-to-dist.mjs
Labels: CLA Signed

#3602 fix(remix-dev,remix-serve): fix network `family` detection
  contributors.yml
  packages/remix-dev/cli/commands.ts
  packages/remix-serve/cli.ts
Labels: CLA Signed, package:serve, package:dev

#3188 feat(remix-dev): add `watchPaths` config option
  contributors.yml
  docs/api/conventions.md
  packages/remix-dev/__tests__/readConfig-test.ts
  packages/remix-dev/compiler.ts
  packages/remix-dev/config.ts
Labels: CLA Signed, documentation, package:dev
