Repository remix-run/remix, pull requests merged in 2022-12, with the labels that each got.

#3970 fix(remix-dev): allow defining multiple routes for the same route module file
  .changeset/big-spoons-grab.md
  contributors.yml
  packages/remix-dev/__tests__/defineRoutes-test.ts
  packages/remix-dev/compiler/assets.ts
  packages/remix-dev/config/routes.ts
Labels: CLA Signed, package:dev

#2879 feat: Allow pass-through script props in `ScrollRestoration`
  .changeset/late-files-trade.md
  packages/remix-react/__tests__/scroll-restoration-test.tsx
  packages/remix-react/components.tsx
  packages/remix-react/scroll-restoration.tsx
Labels: CLA Signed, feat:scroll

#4738 ci(nightly): add deno for typechecking deno files
  .github/workflows/nightly.yml
Labels: CLA Signed

#4745 docs(tutorials/blog): Don't mention removed errors typecheck
  contributors.yml
  docs/tutorials/blog.md
Labels: CLA Signed, docs

#4717 ci: fix race condition writing `globals.d.ts` shim
  scripts/build.mjs
  scripts/copy-build-to-dist.mjs
Labels: CLA Signed

#4749 chore: bump @playwright/test to latest
  package.json
  yarn.lock
Labels: CLA Signed

#4753 chore: bump @playwright/test to latest
  package.json
  yarn.lock
Labels: CLA Signed

#4734 Fix 4199: TypedResponse allows incompatible types
  .changeset/light-sheep-give.md
  contributors.yml
  packages/remix-server-runtime/__tests__/responses-test.ts
  packages/remix-server-runtime/responses.ts
Labels: CLA Signed

#4739 test: add transition integration tests
  integration/transition-state-test.ts
Labels: CLA Signed

#4751 ci: only apply `awaiting release` label to prs related to `./packages`
  .github/workflows/merged-pr.yml
Labels: CLA Signed

#4539 feat: testing helpers
  .changeset/poor-shrimps-boil.md
  package.json
  packages/remix-react/index.tsx
  packages/remix-server-runtime/index.ts
  packages/remix-testing/create-remix-stub.tsx
  packages/remix-testing/index.ts
  packages/remix-testing/install-globals.ts
  packages/remix-testing/package.json
  packages/remix-testing/rollup.config.js
  packages/remix-testing/tsconfig.json
  scripts/publish.js
  scripts/utils.js
  tsconfig.json
  yarn.lock
Labels: CLA Signed

#4756 chore(remix-testing): update dependencies
  packages/remix-testing/package.json
Labels: CLA Signed, dependencies, package:testing

#4757 fix(remix-testing): fix deps
  packages/remix-server-runtime/index.ts
  packages/remix-testing/create-remix-stub.tsx
  packages/remix-testing/package.json
Labels: CLA Signed, package:testing

#4763 ci(nightly): add deno for typechecking deno files
  .github/workflows/nightly.yml
Labels: CLA Signed

#4770 docs(other-api/react-router): fix `react-router` links
  docs/other-api/react-router.md
Labels: CLA Signed, docs

#4771 fix(types): Add missing type def for `future` value in `@remix-run/dev/server-build`
  .changeset/blue-tigers-look.md
  packages/remix-dev/compiler/plugins/serverEntryModulePlugin.ts
  packages/remix-dev/server-build.ts
Labels: CLA Signed, package:dev

#4732 Remove ENABLE_REMIX_ROUTER flags
  .github/workflows/reusable-test.yml
  .github/workflows/test.yml
  package.json
  packages/remix-server-runtime/rollup.config.js
  yarn.lock
Labels: CLA Signed

#4783 templates: add `typecheck` script
  templates/arc/package.json
  templates/cloudflare-pages/package.json
  templates/cloudflare-workers/package.json
  templates/deno/.vscode/resolve_npm_imports.json
  templates/deno/package.json
  templates/express/package.json
  templates/fly/package.json
  templates/netlify/package.json
  templates/remix/package.json
  templates/vercel/package.json
Labels: CLA Signed, template:express, template:architect, template:vercel, template:cloudflare-pages, template:cloudflare-workers, template:fly, template:netlify, template:remix, template:deno

#4782 Remove instanceof Response checks in favor of isResponse
  .changeset/rare-bikes-report.md
  integration/loader-test.ts
  packages/remix-server-runtime/package.json
  packages/remix-server-runtime/server.ts
  yarn.lock
Labels: CLA Signed

#4731 refactor(remix-react): upgrade Remix to `react-router-dom@6.4` (non-data-router) and drop `history`
  .changeset/early-camels-guess.md
  packages/remix-react/__tests__/transition-test.tsx
  packages/remix-react/browser.tsx
  packages/remix-react/components.tsx
  packages/remix-react/errorBoundaries.tsx
  packages/remix-react/links.ts
  packages/remix-react/package.json
  packages/remix-react/routeMatching.ts
  packages/remix-react/routeModules.ts
  packages/remix-react/server.tsx
  packages/remix-react/transition.ts
  packages/remix-server-runtime/package.json
  packages/remix-server-runtime/routeMatching.ts
  packages/remix-server-runtime/routeModules.ts
  yarn.lock
Labels: CLA Signed, package:server-runtime, renderer:react

#4797 ci(nightly): move git operations after build
  .github/workflows/nightly.yml
Labels: CLA Signed

#4538 perf(remix-dev): Optimize `parentRouteId` lookup in `defineConventionalRoutes`
  contributors.yml
  packages/remix-dev/__tests__/routesConvention-test.ts
  packages/remix-dev/config/routesConvention.ts
Labels: CLA Signed, package:dev

#4800 chore(dev): add changeset for PR #4538
  .changeset/metal-impalas-brake.md
Labels: CLA Signed

#3325 refactor(remix-react): use `react-router-dom` import instead of `react-router`
  packages/remix-react/__tests__/transition-test.tsx
  packages/remix-react/routes.tsx
Labels: CLA Signed, renderer:react

#4696 chore: unify error usage
  docs/guides/optimistic-ui.md
  integration/form-data-test.ts
  integration/server-source-maps-test.ts
  packages/remix-cloudflare-pages/worker.ts
  packages/remix-cloudflare-workers/worker.ts
  packages/remix-deno/server.ts
  packages/remix-dev/__tests__/create-test.ts
  packages/remix-dev/__tests__/utils/withApp.ts
  packages/remix-dev/cli/commands.ts
  packages/remix-dev/cli/create.ts
  packages/remix-dev/cli/migrate/jscodeshift.ts
  packages/remix-dev/cli/run.ts
  packages/remix-dev/codemod/utils/task.ts
  packages/remix-dev/compiler/plugins/serverBareModulesPlugin.ts
  packages/remix-dev/compiler/remixCompiler.ts
  packages/remix-dev/compiler/routeExports.ts
  packages/remix-dev/compiler/watch.ts
  packages/remix-dev/config.ts
  packages/remix-dev/devServer/serve.ts
  packages/remix-dev/env.ts
  packages/remix-express/server.ts
  packages/remix-react/routeModules.ts
  packages/remix-react/scroll-restoration.tsx
  packages/remix-react/transition.ts
  packages/remix-server-runtime/cookies.ts
  packages/remix-server-runtime/server.ts
  rollup.config.js
  rollup.utils.js
  scripts/copy-build-to-dist.mjs
  scripts/release.js
  scripts/utils.js
Labels: CLA Signed, adapter:express, adapter:cloudflare-pages, adapter:cloudflare-workers, docs, package:dev, package:server-runtime, renderer:react, runtime:deno

#4803 Add fetcher state/type tests
  integration/fetcher-state-test.ts
  integration/transition-state-test.ts
  packages/remix-react/package.json
  yarn.lock
Labels: CLA Signed

#4754 chore(deps): bump esbuild to latest
  .changeset/fresh-shrimps-join.md
  packages/remix-dev/compiler/compileBrowser.ts
  packages/remix-dev/package.json
  scripts/release/package-lock.json
  scripts/release/package.json
  yarn.lock
Labels: CLA Signed, dependencies

#4814 ci(nightly): move git operations after build
  .github/workflows/nightly.yml
Labels: CLA Signed

#4785 test(integration): close server synchronously
  integration/abort-signal-test.ts
  integration/action-test.ts
  integration/bug-report-test.ts
  integration/catch-boundary-data-test.ts
  integration/catch-boundary-test.ts
  integration/compiler-test.ts
  integration/error-boundary-test.ts
  integration/error-data-request-test.ts
  integration/fetcher-layout-test.ts
  integration/fetcher-test.ts
  integration/file-uploads-test.ts
  integration/form-test.ts
  integration/helpers/create-fixture.ts
  integration/hook-useSubmit-test.ts
  integration/js-routes-test.ts
  integration/layout-route-test.ts
  integration/link-test.ts
  integration/loader-test.ts
  integration/mdx-test.ts
  integration/meta-test.ts
  integration/multiple-cookies-test.ts
  integration/prefetch-test.ts
  integration/redirects-test.ts
  integration/rendering-test.ts
  integration/resource-routes-test.ts
  integration/server-code-in-browser-message-test.ts
  integration/set-cookie-revalidation-test.ts
  integration/transition-state-test.ts
  integration/transition-test.ts
  integration/upload-test.ts
Labels: CLA Signed

#4815 chore: edit the optional segments changeset
  .changeset/moody-pants-own.md
Labels: CLA Signed

#4825 fix: wrong parentheses in the optional segments changeset
  .changeset/moody-pants-own.md
  contributors.yml
Labels: CLA Signed

#4827 docs(api/remix): fix link to `PrefetchPageLinks` page
  docs/api/remix.md
Labels: CLA Signed, docs

#4830 ci(nightly): remove need for xargs, only get diff names
  .github/workflows/nightly.yml
Labels: CLA Signed

#4833 docs(file-conventions/remix-config): update `watchPaths`' description
  contributors.yml
  docs/file-conventions/remix-config.md
Labels: CLA Signed, docs

#4832 docs(api/remix): fix link to `unstable_createFileUploadHandler` page
  docs/api/remix.md
Labels: CLA Signed, docs

#4736 chore(scripts): Use relaxed peer dependencies to avoid triggering major version bumps
  .changeset/config.json
  package.json
  packages/remix-dev/package.json
  scripts/bump-peer-dep-ranges.mjs
  scripts/tsconfig.json
Labels: CLA Signed

#4829 Add integration tests for request structures
  .changeset/mighty-grapes-laugh.md
  .changeset/sharp-paws-nail.md
  integration/catch-boundary-test.ts
  integration/request-test.ts
  packages/remix-react/package.json
  packages/remix-server-runtime/package.json
  yarn.lock
Labels: CLA Signed, feat:routing, feat:loader, package:server-runtime

#4855 fix(remix-dev): resolve asset entry full path to support mono-repo import of styles
  .changeset/mighty-rules-drum.md
  packages/remix-dev/compiler/compileBrowser.ts
  packages/remix-dev/compiler/compilerServer.ts
  packages/remix-dev/compiler/plugins/cssFilePlugin.ts
Labels: CLA Signed

#4861 docs(tutorials/jokes): fix code highlighting
  contributors.yml
  docs/tutorials/jokes.md
Labels: CLA Signed, docs

#4703 RRR Step 3 - Hydration
  integration/request-test.ts
  integration/transition-state-test.ts
  packages/remix-eslint-config/rules/core.js
  packages/remix-react/browser.tsx
  packages/remix-react/components.tsx
  packages/remix-react/data.ts
  packages/remix-react/errors.ts
  packages/remix-react/index.tsx
  packages/remix-react/routeModules.ts
  packages/remix-react/routes.tsx
  packages/remix-react/server.tsx
  packages/remix-server-runtime/errors.ts
  packages/remix-server-runtime/routes.ts
  packages/remix-server-runtime/server.ts
  packages/remix-server-runtime/serverHandoff.ts
Labels: CLA Signed

#4868 Bump RR deps
  .changeset/late-peas-hang.md
  packages/remix-react/package.json
  packages/remix-server-runtime/package.json
  yarn.lock
Labels: CLA Signed

#4761 perf(remix-architect,remix-netlify): improve performance of `isBinaryType`
  .changeset/late-bottles-shop.md
  contributors.yml
  packages/remix-architect/__tests__/binaryTypes-test.ts
  packages/remix-architect/binaryTypes.ts
  packages/remix-netlify/__tests__/binaryTypes.test.ts
  packages/remix-netlify/binaryTypes.ts
Labels: CLA Signed, adapter:architect, adapter:netlify

#4879 docs(route/handle): fix typo
  contributors.yml
  docs/route/handle.md
Labels: CLA Signed, docs

#4883 chore: fix docs links
  README.md
  packages/remix-deno/README.md
  packages/remix-node/sessions/fileStorage.ts
  packages/remix-react/components.tsx
  packages/remix-react/errorBoundaries.tsx
  packages/remix-react/routeModules.ts
  packages/remix-react/scroll-restoration.tsx
  packages/remix-server-runtime/__tests__/sessions-test.ts
  packages/remix-server-runtime/cookies.ts
  packages/remix-server-runtime/formData.ts
  packages/remix-server-runtime/responses.ts
  packages/remix-server-runtime/sessions.ts
  packages/remix-server-runtime/sessions/cookieStorage.ts
  packages/remix-server-runtime/sessions/memoryStorage.ts
Labels: CLA Signed

#3537 fix(templates/cloudflare-pages): fix start script
  contributors.yml
  templates/cloudflare-pages/package.json
Labels: CLA Signed, template:cloudflare-pages

#4755 chore(remix-testing): remove internal installGlobals
  .changeset/quick-cats-fix.md
  packages/remix-testing/README.md
  packages/remix-testing/index.ts
  packages/remix-testing/install-globals.ts
  packages/remix-testing/package.json
  yarn.lock
Labels: CLA Signed, package:testing

#4891 fix(dev): build modules for ts->js conversion
  .changeset/many-zebras-arrive.md
  packages/remix-dev/cli/migrate/migrations/transforms.ts
  packages/remix-dev/rollup.config.js
Labels: CLA Signed, package:dev

#4881 ci(release): make commenting work for changeset releases
  .github/workflows/postrelease.yml
  .github/workflows/release.yml
  scripts/release/find-release-from-changeset.js
Labels: CLA Signed

#4856 Revert "ci: add typechecking for deno (#4715)"
  .changeset/clean-clocks-float.md
  .github/workflows/nightly.yml
  .github/workflows/reusable-test.yml
  packages/remix-deno/server.ts
  scripts/build.mjs
Labels: CLA Signed

#4885 RRR Rendering Follow Ups
  integration/error-boundary-test.ts
  integration/form-test.ts
  packages/remix-dev/codemod/replace-remix-magic-imports/utils/export.ts
  packages/remix-eslint-config/rules/core.js
  packages/remix-eslint-config/rules/packageExports.js
  packages/remix-react/__tests__/components-test.tsx
  packages/remix-react/__tests__/scroll-restoration-test.tsx
  packages/remix-react/__tests__/transition-test.tsx
  packages/remix-react/components.tsx
  packages/remix-react/data.ts
  packages/remix-react/errorBoundaries.tsx
  packages/remix-react/index.tsx
  packages/remix-react/links.ts
  packages/remix-react/package.json
  packages/remix-react/routeModules.ts
  packages/remix-react/routes.tsx
  packages/remix-react/server.tsx
  packages/remix-server-runtime/__tests__/server-test.ts
  packages/remix-server-runtime/package.json
  packages/remix-server-runtime/routeModules.ts
  packages/remix-server-runtime/server.ts
  packages/remix-server-runtime/serverHandoff.ts
  packages/remix-testing/create-remix-stub.tsx
  rollup.utils.js
  yarn.lock
Labels: CLA Signed

#4901 chore: Add script to remove pre-release notes from changelogs
  package.json
  scripts/remove-prerelease-changelogs.mjs
  scripts/unist.d.ts
  yarn.lock
Labels: CLA Signed

#4910 docs(route/headers): Fix incorrect link on headers
  contributors.yml
  docs/route/headers.md
Labels: CLA Signed, docs

#4912 Fix flakey firefox tests
  integration/error-boundary-test.ts
  integration/fetcher-layout-test.ts
  integration/file-uploads-test.ts
  integration/upload-test.ts
Labels: CLA Signed

#4914 refactor: use type imports instead of type modifiers
  packages/remix-dev/codemod/index.ts
  packages/remix-dev/codemod/replace-remix-magic-imports/transform.ts
  packages/remix-dev/codemod/replace-remix-magic-imports/utils/detect.ts
  packages/remix-dev/codemod/replace-remix-magic-imports/utils/export.ts
  packages/remix-dev/codemod/replace-remix-magic-imports/utils/postinstall.ts
  packages/remix-dev/compiler/build.ts
  packages/remix-dev/compiler/compileBrowser.ts
  packages/remix-dev/compiler/compilerServer.ts
  packages/remix-dev/compiler/plugins/cssFilePlugin.ts
  packages/remix-dev/compiler/remixCompiler.ts
  packages/remix-dev/compiler/watch.ts
Labels: CLA Signed, package:dev

#4922 Include shouldRevalidate in client bundles
  integration/revalidate-test.ts
  packages/remix-dev/compiler/plugins/browserRouteModulesPlugin.ts
Labels: CLA Signed, feat:routing, package:dev

#4933 Add a few missed re-exports and back-compat
  integration/fetcher-state-test.ts
  packages/remix-react/components.tsx
  packages/remix-react/index.tsx
  packages/remix-react/transition.ts
Labels: CLA Signed

#4936 chore: fix ESLint warning
  integration/revalidate-test.ts
Labels: CLA Signed

#4831 docs(file-conventions/routes-files): fix folder structure in examples
  docs/file-conventions/routes-files.md
Labels: CLA Signed, docs

#4923 docs: fix React Router docs links
  docs/components/outlet.md
  docs/file-conventions/routes-files.md
  docs/guides/migrating-react-router-app.md
Labels: CLA Signed, docs

#4937 docs(pages/gotchas): fix link to `uploadHandler`
  docs/pages/gotchas.md
Labels: CLA Signed, docs

#4935 Update to RR 6.6.0 deps
  .changeset/shaggy-garlics-confess.md
  packages/remix-react/package.json
  packages/remix-server-runtime/package.json
  yarn.lock
Labels: CLA Signed, package:server-runtime, renderer:react

#4915 chore(remix-testing): utilize react-router 6.5+
  .changeset/silver-ducks-protect.md
  packages/remix-react/index.tsx
  packages/remix-testing/create-remix-stub.tsx
  packages/remix-testing/package.json
  yarn.lock
Labels: CLA Signed, renderer:react, package:testing

#4944 Bump to react router 6.6.1 pre versions
  .changeset/gentle-yaks-lick.md
  packages/remix-react/package.json
  packages/remix-server-runtime/package.json
  packages/remix-testing/package.json
  yarn.lock
Labels: CLA Signed

#4943 fix: re-export `V2_HtmlMetaDescriptor` and `V2_MetaFunction` from runtime packages
  .changeset/lucky-chairs-remember.md
  packages/remix-cloudflare/index.ts
  packages/remix-deno/index.ts
  packages/remix-node/index.ts
  packages/remix-server-runtime/index.ts
  packages/remix-server-runtime/reexport.ts
Labels: CLA Signed

#4947 fix: `V2_MetaFunction` should return `V2_HtmlMetaDescriptor[]`
  .changeset/rotten-bulldogs-reply.md
  packages/remix-server-runtime/routeModules.ts
Labels: CLA Signed

#4952 Bump router versions to stable
  .changeset/metal-birds-tease.md
  packages/remix-react/package.json
  packages/remix-server-runtime/package.json
  packages/remix-testing/package.json
  yarn.lock
Labels: CLA Signed

#4954 fix: pass through request abort signal
  .changeset/big-geese-cry.md
  packages/remix-react/data.ts
Labels: CLA Signed

#4956 docs(route/index): fix broken link
  docs/route/index.md
Labels: CLA Signed, docs

#4939 templates: update to React v18
  contributors.yml
  templates/cloudflare-pages/app/entry.client.tsx
  templates/cloudflare-pages/package.json
  templates/cloudflare-workers/app/entry.client.tsx
  templates/cloudflare-workers/package.json
  templates/deno/app/entry.client.tsx
  templates/deno/package.json
Labels: CLA Signed, template:cloudflare-pages, template:cloudflare-workers, template:deno
