Repository remix-run/remix, pull requests merged in 2022-05, with the labels that each got.

#2224 docs(guides/constraints): link to Reach UI's `useIsomorphicLayoutEffect`
  docs/guides/constraints.md
Labels: CLA Signed, needs-response, documentation

#3045 docs(guides/constraints): fix typo
  contributors.yml
  docs/guides/constraints.md
Labels: CLA Signed, documentation

#3042 docs(examples): add `graphql` to `dependencies` of `graphql-api` example
  contributors.yml
  examples/graphql-api/README.md
  examples/graphql-api/package.json
Labels: CLA Signed, examples

#3064 fix: provide clear error messages for create-remix errors
  packages/remix-dev/__tests__/create-test.ts
  packages/remix-dev/__tests__/github-mocks.ts
  packages/remix-dev/__tests__/msw.ts
  packages/remix-dev/cli/create.ts
Labels: package:create-remix, package:dev

#3068 docs(pages/stacks): fix typo
  contributors.yml
  docs/pages/stacks.md
Labels: CLA Signed, documentation

#3070 chore(examples): bring `blog-tutorial` example in line with `indie-stack`
  examples/blog-tutorial/.github/workflows/deploy.yml
  examples/blog-tutorial/.gitpod.Dockerfile
  examples/blog-tutorial/.gitpod.yml
  examples/blog-tutorial/Dockerfile
  examples/blog-tutorial/README.md
  examples/blog-tutorial/app/routes/healthcheck.tsx
  examples/blog-tutorial/app/routes/join.tsx
  examples/blog-tutorial/app/routes/login.tsx
  examples/blog-tutorial/app/routes/notes/new.tsx
  examples/blog-tutorial/app/session.server.ts
  examples/blog-tutorial/app/utils.ts
  examples/blog-tutorial/mocks/start.ts
  examples/blog-tutorial/package.json
  examples/blog-tutorial/remix.config.js
Labels: CLA Signed, examples

#3059 fix(remix-dev): support JSX in `.js` route files
  docs/api/conventions.md
  docs/guides/typescript.md
  integration/js-routes-test.ts
  packages/remix-dev/compiler/routes.ts
  rollup.config.js
Labels: CLA Signed, package:dev

#3073 test(replace-remix-imports): use cross-platform `grep` to avoid conditional `expect`
  package.json
  packages/remix-dev/__tests__/replace-remix-imports-test.ts
  packages/remix-dev/package.json
  yarn.lock
Labels: CLA Signed

#3077 docs(api/conventions): fix typos
  contributors.yml
  docs/api/conventions.md
Labels: CLA Signed, documentation

#3039 ci: tweak "found x prs since..." message to include versions
  scripts/release/comment.mjs
  scripts/release/constants.mjs
  scripts/release/octokit.mjs
Labels: CLA Signed

#3033 docs(api/conventions): fix typo
  contributors.yml
  docs/api/conventions.md
Labels: CLA Signed, documentation

#2441 docs(templates/express): fix `README`
  contributors.yml
  templates/express/README.md
Labels: CLA Signed, template:express

#3071 chore: bring `playground` in line with `blues-stack`
  scripts/playground/template/app/routes/join.tsx
  scripts/playground/template/app/routes/login.tsx
  scripts/playground/template/app/session.server.ts
  scripts/playground/template/app/utils.ts
  scripts/playground/template/package.json
  scripts/playground/template/remix.config.js
Labels: CLA Signed

#3043 docs(example): add an example of using flash session
  contributors.yml
  examples/session-flash/.eslintrc.js
  examples/session-flash/.gitignore
  examples/session-flash/README.md
  examples/session-flash/app/entry.client.tsx
  examples/session-flash/app/entry.server.tsx
  examples/session-flash/app/root.tsx
  examples/session-flash/app/routes/index.tsx
  examples/session-flash/app/utils/session.server.ts
  examples/session-flash/package.json
  examples/session-flash/public/favicon.ico
  examples/session-flash/remix.config.js
  examples/session-flash/remix.env.d.ts
  examples/session-flash/sandbox.config.json
  examples/session-flash/tsconfig.json
Labels: CLA Signed, needs-response, examples

#3084 chore(remix-eslint-config): comment out replaceRemixImportsOptions as it's not currently used
  packages/remix-eslint-config/rules/core.js
Labels: CLA Signed, package:eslint-config

#3094 feat(remix-react): clean up which button clicked submit implementation
  packages/remix-react/components.tsx
Labels: CLA Signed, package:react

#3087 chore(remix-dev): only check if dir is empty, not if it exists
  packages/remix-dev/__tests__/create-test.ts
  packages/remix-dev/cli/create.ts
Labels: CLA Signed

#3097 chore: fix unfixable eslint errors
  examples/session-flash/app/root.tsx
  examples/session-flash/app/routes/index.tsx
Labels: CLA Signed

#2992 ci(comments): parse pr description for closing keywords as github will only link PRs and issues to the repo's default branch
  .github/workflows/nightly.yml
  scripts/release/comment.mjs
  scripts/release/octokit.mjs
Labels: CLA Signed

#3019 docs(examples): ignore `routes.d.ts` and generate it automatically in `routes-gen` example
  contributors.yml
  examples/routes-gen/.gitignore
  examples/routes-gen/README.md
  examples/routes-gen/package.json
Labels: CLA Signed, examples

#3111 chore(examples): use helper functions as much as possible in `jokes` example
  contributors.yml
  examples/jokes/app/utils/session.server.ts
Labels: CLA Signed, examples

#3061 fix: clear build directory before new builds
  packages/remix-dev/cli/commands.ts
Labels: CLA Signed

#3115 ci: bump cli test process timeout
  packages/remix-dev/__tests__/cli-test.ts
Labels: CLA Signed

#3114 fix(remix-dev/cli/migrate): directly use `jscodeshift` instead of via CLI
  packages/remix-dev/cli/migrate/jscodeshift.ts
  packages/remix-dev/cli/migrate/migrations/replace-remix-imports/index.ts
  packages/remix-dev/cli/migrate/migrations/replace-remix-imports/transform/options.ts
  packages/remix-dev/package.json
  yarn.lock
Labels: CLA Signed, package:dev

#3075 fix: fix rollup playground livereload
  rollup.config.js
Labels: CLA Signed

#3121 docs: Fix typos
  docs/guides/api-routes.md
  docs/guides/data-loading.md
  docs/guides/data-writes.md
  docs/pages/contributing.md
  docs/pages/faq.md
  docs/tutorials/blog.md
Labels: CLA Signed, documentation

#2309 test: add test where `form` is descendant of element with stop propagation on click
  contributors.yml
  integration/form-test.ts
Labels: CLA Signed

#3110 chore(templates): ignore lockfiles
  templates/.gitignore
Labels: CLA Signed

#3038 docs(remix-server-runtime): fix `remix-deno` link
  packages/remix-server-runtime/README.md
Labels: CLA Signed, package:server-runtime

#3144 docs(guides/data-loading): fix type inference example
  contributors.yml
  docs/guides/data-loading.md
Labels: CLA Signed, documentation

#3109 fix(remix-dev): fix package manager detection
  packages/remix-dev/__tests__/create-test.ts
  packages/remix-dev/cli/run.ts
Labels: CLA Signed, package:dev

#3135 tests: bring fixture templates in line with actual templates
  integration/helpers/cf-template/app/entry.client.tsx
  integration/helpers/cf-template/app/entry.server.tsx
  integration/helpers/cf-template/app/root.tsx
  integration/helpers/cf-template/package.json
  integration/helpers/cf-template/remix.env.d.ts
  integration/helpers/cf-template/tsconfig.json
  integration/helpers/node-template/app/entry.client.tsx
  integration/helpers/node-template/app/entry.server.tsx
  integration/helpers/node-template/app/root.tsx
  integration/helpers/node-template/package.json
  integration/helpers/node-template/remix.env.d.ts
  integration/helpers/node-template/tsconfig.json
Labels: CLA Signed

#3146 fix(remix-dev/cli/init): only run `npm install` when `package.json` is available
  packages/remix-dev/cli/commands.ts
Labels: CLA Signed

#3076 feat(remix-dev): pass `packageManager` to `remix.init` script
  packages/remix-dev/cli/commands.ts
Labels: CLA Signed, package:dev

#2982 chore(tests): run against Node v18
  .github/workflows/test.yml
Labels: CLA Signed

#3083 chore: add missing `peerDependencies`
  package.json
  yarn.lock
Labels: CLA Signed

#3107 feat(remix-netlify): broaden `peerDependencies`
  packages/remix-netlify/package.json
  templates/netlify/package.json
  yarn.lock
Labels: CLA Signed, adapter:netlify, template:netlify

#3148 ci: fix regex when parsing pr body for mentioned issues
  scripts/release/octokit.mjs
Labels: CLA Signed

#3026 ci: create and run each stack upon release
  .github/workflows/nightly.yml
  .github/workflows/release.yml
  .github/workflows/stacks.yml
Labels: CLA Signed

#3081 chore(remix-dev): add support for importing `*.webmanifest` files
  packages/remix-dev/compiler/loaders.ts
  packages/remix-dev/modules.ts
Labels: CLA Signed

#3119 docs(example): add twind example
  contributors.yml
  examples/twind/.eslintrc.js
  examples/twind/.gitignore
  examples/twind/README.md
  examples/twind/app/entry.client.tsx
  examples/twind/app/entry.server.tsx
  examples/twind/app/root.tsx
  examples/twind/app/routes/anything.tsx
  examples/twind/app/routes/index.tsx
  examples/twind/package.json
  examples/twind/public/favicon.ico
  examples/twind/remix.config.js
  examples/twind/remix.env.d.ts
  examples/twind/sandbox.config.json
  examples/twind/tsconfig.json
  examples/twind/twind.config.ts
Labels: CLA Signed, examples

#2865 docs(pages/FAQ): ad another nested object solution for form, using Ramda
  contributors.yml
  docs/pages/faq.md
Labels: CLA Signed, needs-response, documentation

#3152 ci: skip tests if PR only touches docs
  .github/workflows/test.yml
Labels: CLA Signed

#3151 chore(remix-dev): add `@types/npmcli__package-json` to `devDependencies`
  packages/remix-dev/cli/migrate/migrations/replace-remix-imports/index.ts
  packages/remix-dev/cli/migrate/migrations/replace-remix-imports/resolveTransformOptions.ts
  packages/remix-dev/package.json
  yarn.lock
Labels: CLA Signed, package:dev

#3154 docs(guides/styling): fix typo
  contributors.yml
  docs/guides/styling.md
Labels: CLA Signed, documentation

#3018 docs: React Router migration docs
  docs/guides/migrating-react-router-app.md
Labels: CLA Signed, documentation

#3162 docs(contributing): clarify that template changes go to main
  docs/pages/contributing.md
Labels: CLA Signed, documentation

#3168 docs(guides/migrating-react-router-app): small updates
  docs/guides/migrating-react-router-app.md
Labels: CLA Signed, documentation

#3167 docs(api/conventions): mention `actionHeaders` in `headers`' arguments
  contributors.yml
  docs/api/conventions.md
Labels: CLA Signed, documentation

#3169 docs(guides/migrating-react-router-app): fix highlight
  docs/guides/migrating-react-router-app.md
Labels: CLA Signed, documentation

#3141 docs(guides/styling): clarify Tailwind example
  contributors.yml
  docs/guides/styling.md
Labels: CLA Signed, needs-response, documentation

#3182 docs(examples): update `tsconfig`
  examples/basic/tsconfig.json
  examples/bullmq-task-queue/tsconfig.json
  examples/catch-boundary/tsconfig.json
  examples/chakra-ui/tsconfig.json
  examples/client-only-components/tsconfig.json
  examples/client-side-validation/tsconfig.json
  examples/collected-notes/tsconfig.json
  examples/combobox-resource-route/tsconfig.json
  examples/dark-mode/tsconfig.json
  examples/emotion/tsconfig.json
  examples/file-and-cloudinary-upload/tsconfig.json
  examples/firebase-auth-firestore/tsconfig.json
  examples/form-to-notion-db/tsconfig.json
  examples/framer-motion/tsconfig.json
  examples/framer-route-animation/tsconfig.json
  examples/gdpr-cookie-consent/tsconfig.json
  examples/google-analytics/tsconfig.json
  examples/graphql-api/tsconfig.json
  examples/image-resize/tsconfig.json
  examples/infinite-scrolling/tsconfig.json
  examples/io-ts-formdata-decoding/tsconfig.json
  examples/ioredis/tsconfig.json
  examples/jokes/tsconfig.json
  examples/mantine/tsconfig.json
  examples/msw/tsconfig.json
  examples/multiple-forms/tsconfig.json
  examples/multiple-params/tsconfig.json
  examples/newsletter-signup/tsconfig.json
  examples/nprogress/tsconfig.json
  examples/on-demand-hydration/tsconfig.json
  examples/outlet-form-rerender/tsconfig.json
  examples/pathless-routes/tsconfig.json
  examples/pm-app/tsconfig.json
  examples/quirrel/tsconfig.json
  examples/react-spring/tsconfig.json
  examples/redis-upstash-session/tsconfig.json
  examples/remix-auth-auth0/tsconfig.json
  examples/remix-auth-form/tsconfig.json
  examples/remix-auth-github/tsconfig.json
  examples/remix-auth-supabase-github/tsconfig.json
  examples/remix-auth-supabase/tsconfig.json
  examples/route-modal/tsconfig.json
  examples/routes-gen/tsconfig.json
  examples/rust/tsconfig.json
  examples/sass/tsconfig.json
  examples/search-input/tsconfig.json
  examples/sharing-loader-data/tsconfig.json
  examples/socket.io/tsconfig.json
  examples/stitches/tsconfig.json
  examples/strapi/tsconfig.json
  examples/stripe-integration/tsconfig.json
  examples/styled-components/tsconfig.json
  examples/styletron/tsconfig.json
  examples/supabase-subscription/tsconfig.json
  examples/tailwindcss/tsconfig.json
  examples/template/tsconfig.json
  examples/tiptap-collab-editing/tsconfig.json
  examples/toast-message/tsconfig.json
  examples/turborepo-vercel/apps/remix-app/tsconfig.json
  examples/usematches-loader-data/tsconfig.json
Labels: CLA Signed, examples

#3183 docs: update `tsconfig`
  docs/guides/typescript.md
Labels: CLA Signed, documentation

#3184 tests: update `tsconfig`
  integration/helpers/cf-template/jsconfig.json
  integration/helpers/node-template/jsconfig.json
  packages/remix-dev/__tests__/fixtures/stack/tsconfig.json
Labels: CLA Signed

#3187 chore(templates): update dependencies
  templates/arc/package.json
  templates/cloudflare-pages/package.json
  templates/cloudflare-workers/package.json
  templates/express/package.json
  templates/fly/package.json
  templates/netlify/package.json
  templates/remix/package.json
  templates/vercel/package.json
Labels: CLA Signed, template:express, template:architect, template:vercel, template:cloudflare-pages, template:cloudflare-workers, template:fly, template:netlify, template:remix

#2736 feat: replace node-fetch with @remix-run/web-fetch
  .github/workflows/test.yml
  .gitignore
  docs/api/conventions.md
  docs/api/remix.md
  docs/decisions/0002-do-not-clone-request.md
  docs/decisions/template.md
  docs/pages/gotchas.md
  examples/file-and-cloudinary-upload/app/routes/cloudinary-upload.tsx
  examples/file-and-cloudinary-upload/app/routes/local-upload.tsx
  examples/file-and-cloudinary-upload/app/utils/utils.server.ts
  integration/action-test.ts
  integration/assets/toupload.txt
  integration/file-uploads-test.ts
  integration/upload-test.ts
  packages/remix-architect/__tests__/server-test.ts
  packages/remix-architect/server.ts
  packages/remix-cloudflare/index.ts
  packages/remix-eslint-config/rules/packageExports.js
  packages/remix-express/__tests__/server-test.ts
  packages/remix-express/server.ts
  packages/remix-netlify/__tests__/server-test.ts
  packages/remix-netlify/server.ts
  packages/remix-node/__tests__/assets/test.txt
  packages/remix-node/__tests__/fetch-test.ts
  packages/remix-node/__tests__/fileUploadHandler-test.ts
  packages/remix-node/__tests__/formData-test.ts
  packages/remix-node/__tests__/parseMultipartFormData-test.ts
  packages/remix-node/fetch.ts
  packages/remix-node/formData.ts
  packages/remix-node/globals.ts
  packages/remix-node/index.ts
  packages/remix-node/magicExports/remix.ts
  packages/remix-node/package.json
  packages/remix-node/parseMultipartFormData.ts
  packages/remix-node/stream.ts
  packages/remix-node/upload/fileUploadHandler.ts
  packages/remix-node/upload/memoryUploadHandler.ts
  packages/remix-node/upload/meter.ts
  packages/remix-react/routes.tsx
  packages/remix-server-runtime/__tests__/formData-test.ts
  packages/remix-server-runtime/data.ts
  packages/remix-server-runtime/formData.ts
  packages/remix-server-runtime/index.ts
  packages/remix-server-runtime/package.json
  packages/remix-server-runtime/reexport.ts
  packages/remix-server-runtime/server.ts
  packages/remix-server-runtime/upload/errors.ts
  packages/remix-server-runtime/upload/memoryUploadHandler.ts
  packages/remix-vercel/__tests__/server-test.ts
  packages/remix-vercel/server.ts
  tsconfig.json
  yarn.lock
Labels: CLA Signed, examples, adapter:architect, adapter:vercel, adapter:express, adapter:netlify, documentation, package:eslint-config, package:server-runtime, runtime:node, runtime:cloudflare

#3189 fix(remix-dev/cli/migrate): fix `packageExports` map
  packages/remix-cloudflare/index.ts
  packages/remix-dev/cli/migrate/migrations/replace-remix-imports/transform/mapNormalizedImports/packageExports.ts
  packages/remix-eslint-config/rules/packageExports.js
  packages/remix-node/index.ts
Labels: CLA Signed, package:dev, package:eslint-config, runtime:node, runtime:cloudflare

#3191 chore(templates/cloudflare-pages): ignore `/functions/[[path]].js.map`
  templates/cloudflare-pages/.gitignore
Labels: CLA Signed, template:cloudflare-pages

#3198 docs(api/remix): remove dot
  contributors.yml
  docs/api/remix.md
Labels: CLA Signed, documentation

#2938 fix(remix-react): avoid duplicate `loader` calls when using `prefetch-intent`
  docs/api/remix.md
  integration/prefetch-test.ts
  packages/remix-react/components.tsx
Labels: CLA Signed, package:react

#3078 chore(remix-dev): default to "just the basics"
  packages/remix-dev/cli/run.ts
Labels: CLA Signed, package:dev, feat:dx

#2779 fix(remix-server-runtime): update error message when route doesn't have exports
  packages/remix-server-runtime/data.ts
Labels: CLA Signed, package:server-runtime

#3074 refactor(remix-dev): clean up custom `tsconfig` loader
  packages/remix-dev/compiler/utils/tsconfig/configLoader.ts
  packages/remix-dev/compiler/utils/tsconfig/index.ts
  packages/remix-dev/compiler/utils/tsconfig/tsConfigLoader.ts
  packages/remix-dev/package.json
  yarn.lock
Labels: CLA Signed, package:dev

#3207 feat(remix-server-runtime): strip `body` from `request` before calling `loader`s
  docs/decisions/0002-do-not-clone-request.md
  packages/remix-server-runtime/responses.ts
  packages/remix-server-runtime/server.ts
Labels: CLA Signed, package:server-runtime

#3216 fix(templates/vercel): add `index.js.map` to `.gitignore`
  contributors.yml
  templates/vercel/.gitignore
Labels: CLA Signed, template:vercel

#3218 fix: change how request is "cloned" for loaders
  packages/remix-server-runtime/__tests__/handler-test.ts
  packages/remix-server-runtime/server.ts
Labels: CLA Signed

#3215 feat(remix-deno): export new `@remix-run/server-runtime` upload functions & types
  packages/remix-deno/index.ts
Labels: CLA Signed, runtime:deno

#2864 feat(remix-dev/cli): let `replace-remix-imports` migration re-install to update lockfile
  packages/remix-dev/__tests__/replace-remix-imports-test.ts
  packages/remix-dev/cli/commands.ts
  packages/remix-dev/cli/create.ts
  packages/remix-dev/cli/getPreferredPackageManager.ts
  packages/remix-dev/cli/migrate/migrations/replace-remix-imports/index.ts
  packages/remix-dev/cli/migrate/run.ts
  packages/remix-dev/cli/migrate/types.ts
  packages/remix-dev/cli/run.ts
Labels: CLA Signed, package:dev

#3181 chore(remix-dev): remove suggested `paths` from default tsconfig
  integration/tsconfig-test.ts
  packages/remix-dev/compiler/utils/tsconfig/write-config-defaults.ts
Labels: CLA Signed, package:dev

#3223 fix(scripts): Prevent publishing without a tag
  scripts/publish-private.js
  scripts/publish.js
Labels: CLA Signed

#3091 chore(remix-server-runtime): warn against using `expires` in `createCookieSessionStorage` and `createSessionStorage`
  packages/remix-server-runtime/__tests__/cookies-test.ts
  packages/remix-server-runtime/__tests__/sessions-test.ts
  packages/remix-server-runtime/cookies.ts
Labels: CLA Signed, package:server-runtime

#3226 docs: add index.md and front matter to decisions
  docs/decisions/0001-use-npm-to-manage-npm-dependencies-for-deno-projects.md
  docs/decisions/0002-do-not-clone-request.md
  docs/decisions/index.md
  docs/decisions/template.md
Labels: CLA Signed

#3228 docs(server-runtime): update link for deno server runtime package
  packages/remix-server-runtime/README.md
Labels: CLA Signed

#3221 chore(templates): bring `deno` template in line with other templates
  .vscode/deno_resolve_npm_imports.json
  templates/deno/.gitignore
  templates/deno/.vscode/resolve_npm_imports.json
  templates/deno/.vscode/settings.json
  templates/deno/README.md
  templates/deno/app/entry.client.tsx
  templates/deno/app/entry.server.tsx
  templates/deno/app/root.tsx
  templates/deno/app/routes/index.tsx
  templates/deno/package.json
  templates/deno/remix.config.js
Labels: CLA Signed, template:deno

#3231 docs: fix links to decision docs
  packages/remix-deno/README.md
  templates/deno/README.md
Labels: CLA Signed

#3233 chore(create-remix): add deno to template choices
  packages/remix-dev/cli/run.ts
Labels: CLA Signed

#3242 fix(examples, docs): fix typos
  contributors.yml
  docs/guides/migrating-react-router-app.md
  examples/google-analytics/app/utils/gtags.client.ts
  examples/image-resize/app/routes/assets/resize/$.ts
  examples/infinite-scrolling/app/routes/offset/advanced.tsx
  examples/infinite-scrolling/app/routes/page/advanced.tsx
  examples/io-ts-formdata-decoding/app/routes/index.tsx
  examples/pm-app/app/routes/dashboard/projects/$projectId.tsx
  examples/pm-app/app/styles/global.css
  examples/route-modal/app/routes/invoices/$id/edit.tsx
  examples/route-modal/app/routes/invoices/add.tsx
Labels: CLA Signed, examples, documentation

#3243 fix(templates/cloudflare-pages): fix runtime globals reference
  templates/cloudflare-pages/remix.env.d.ts
Labels: CLA Signed, template:cloudflare-pages

#3250 fix(examples): fix `README` of `stitches` example
  examples/stitches/README.md
Labels: CLA Signed, examples

#3236 chore(templates): remove `.eslintignore` from `deno` template
  templates/deno/.eslintignore
Labels: CLA Signed, template:deno

#3229 tests: bring `deno` fixture template in line with actual template
  .eslintignore
  integration/helpers/deno-template/.gitignore
  integration/helpers/deno-template/app/entry.client.tsx
  integration/helpers/deno-template/app/entry.server.tsx
  integration/helpers/deno-template/app/root.tsx
  integration/helpers/deno-template/package.json
  integration/helpers/deno-template/remix.config.js
Labels: CLA Signed

#3245 fix(templates/cloudflare-workers): fix runtime globals reference
  templates/cloudflare-workers/remix.env.d.ts
Labels: CLA Signed, template:cloudflare-workers

#3239 fix(templates/deno): use `Deno.env` instead of `process.env`
  templates/deno/server.ts
Labels: CLA Signed, template:deno

#3254 Revert "chore: update Deno import maps on release"
  .vscode/deno_resolve_npm_imports.json
  contributors.yml
  packages/remix-deno/README.md
  packages/remix-server-runtime/README.md
  scripts/utils.js
  templates/deno/.gitignore
  templates/deno/.vscode/resolve_npm_imports.json
  templates/deno/.vscode/settings.json
  templates/deno/README.md
  templates/deno/app/entry.client.tsx
  templates/deno/app/entry.server.tsx
  templates/deno/app/root.tsx
  templates/deno/app/routes/index.tsx
  templates/deno/package.json
  templates/deno/remix.config.js
  templates/vercel/.gitignore
Labels: CLA Signed

#3249 fix(remix-dev): improve `appTemplate` message
  contributors.yml
  docs/tutorials/jokes.md
  packages/remix-dev/cli/run.ts
Labels: CLA Signed, package:create-remix, package:dev

#3259 docs(decisions): remove frontmatter and index file
  decisions/0001-use-npm-to-manage-npm-dependencies-for-deno-projects.md
  decisions/0002-do-not-clone-request.md
  decisions/index.md
  decisions/template.md
Labels: CLA Signed

#3266 docs(conventions): Fix a typo
  contributors.yml
  docs/api/conventions.md
Labels: CLA Signed, documentation

#3253 docs(other-api/react-router): update links to `react-router` docs
  contributors.yml
  docs/other-api/react-router.md
Labels: CLA Signed, documentation

#2944 fix: Better support for `imageSrcSet` + `imageSizes` in route `links` (#184)
  integration/link-test.ts
  packages/remix-react/components.tsx
  packages/remix-react/links.ts
  packages/remix-server-runtime/links.ts
Labels: CLA Signed, package:server-runtime, package:react

#2218 docs(remix-eslint-config): update `README`
  packages/remix-eslint-config/README.md
Labels: CLA Signed, documentation, package:eslint-config

#3269 docs(jokes): Clarify restart of dev server when resetting prisma db
  docs/tutorials/jokes.md
Labels: CLA Signed, documentation

#3274 docs(tutorials/blog): use generics instead of type casting
  contributors.yml
  docs/tutorials/blog.md
Labels: CLA Signed, documentation

#3278 fix(templates/deno): get types for `@remix-run/deno` directly from `node_modules/`
  templates/deno/.vscode/resolve_npm_imports.json
Labels: CLA Signed, template:deno

#2332 docs(templates/arc): remove redundant `arc` call from README
  contributors.yml
  templates/arc/README.md
Labels: CLA Signed, needs-response, documentation, template:architect

#3279 chore(templates/arc): move arc to devDependencies
  templates/arc/README.md
  templates/arc/package.json
Labels: CLA Signed

#2824 feat(templates/deno): deploying to Deno Deploy
  .github/workflows/deployments.yml
  scripts/deployment-test/deno-deploy.mjs
  templates/deno/.vscode/extensions.json
  templates/deno/README.md
  templates/deno/package.json
Labels: CLA Signed, template:deno

#3283 docs(decisions/0001): fix typo
  decisions/0001-use-npm-to-manage-npm-dependencies-for-deno-projects.md
Labels: CLA Signed

#3268 docs(examples): add link to `EdgeDB` variant of `jokes` example
  contributors.yml
  examples/jokes/README.md
Labels: CLA Signed, examples, documentation

#3291 docs: update uploadHandler docs
  docs/api/remix.md
Labels: CLA Signed

#3287 chore(templates): remove `description`, `license` & `name` keys from `package.json`
  templates/arc/package.json
  templates/cloudflare-pages/package.json
  templates/cloudflare-workers/package.json
  templates/deno/package.json
  templates/express/package.json
  templates/fly/package.json
  templates/netlify/package.json
  templates/remix/package.json
  templates/vercel/package.json
Labels: CLA Signed, template:express, template:architect, template:vercel, template:cloudflare-pages, template:cloudflare-workers, template:fly, template:netlify, template:remix, template:deno

#3290 docs: remove `description` & `license` keys from `package.json`
  docs/guides/typescript.md
Labels: CLA Signed, documentation

#3285 feat(remix-eslint-config): enable deprecated imports warnings
  packages/remix-eslint-config/rules/core.js
Labels: CLA Signed, package:eslint-config

#3289 tests: remove `description` & `license` keys from `package.json`
  integration/helpers/cf-template/package.json
  integration/helpers/node-template/package.json
  packages/remix-dev/__tests__/fixtures/replace-remix-imports/package.json
  packages/remix-dev/__tests__/fixtures/stack/package.json
  scripts/playground/template/package.json
Labels: CLA Signed

#3208 chore: remove unused dependencies from root `package.json`
  package.json
  yarn.lock
Labels: CLA Signed

#2876 enhancement: Export additional types from `@remix-run/react`
  packages/remix-react/components.tsx
  packages/remix-react/index.tsx
Labels: CLA Signed

#3319 fix(templates/deno): ignore `build` dirs from tooling
  templates/deno/package.json
Labels: CLA Signed, template:deno

#3329 docs(examples): update `.env.example` of `firebase-auth-firestore` example
  contributors.yml
  examples/firebase-auth-firestore/.env.example
Labels: CLA Signed, examples
