Repository remix-run/remix, pull requests merged in 2022-09, with the labels that each got.

#2445 refactor(remix-server-runtime): simplify `isIndexRequestUrl`
  packages/remix-server-runtime/server.ts
Labels: CLA Signed, package:server-runtime

#4066 docs(other-api/serve): add preserve cache in development example
  contributors.yml
  docs/other-api/serve.md
Labels: CLA Signed, documentation

#4125 docs(gotcha): Fix fs-extra re-export sample
  docs/pages/gotchas.md
Labels: CLA Signed, documentation

#4129 chore(remix-architect,remix-netlify): fix ESLint warnings
  packages/remix-architect/__tests__/server-test.ts
  packages/remix-netlify/__tests__/server-test.ts
Labels: CLA Signed, adapter:architect, adapter:netlify

#4147 docs(api/useFetchers): typo fix
  contributors.yml
  docs/api/remix.md
Labels: CLA Signed, documentation

#4158 fix link to remix app server page
  contributors.yml
  docs/other-api/dev.md
Labels: CLA Signed

#2455 fix(remix-server-runtime): don't automatically cast `error` without check
  .changeset/lazy-lions-invent.md
  packages/remix-server-runtime/server.ts
Labels: CLA Signed, package:server-runtime

#4157 docs(styling.md): fix filename path in code block
  docs/guides/styling.md
Labels: CLA Signed, documentation

#4133 docs: fixed broken links
  contributors.yml
  docs/guides/migrating-react-router-app.md
Labels: CLA Signed, documentation

#4113 chore(examples): update turborepo example readme
  examples/turborepo-vercel/README.md
Labels: CLA Signed, examples

#4170 docs(examples/usematches): Fix incorrect link in README
  contributors.yml
  examples/usematches-loader-data/README.md
Labels: CLA Signed, examples

#4169 ci: Fix netlify/architect node 14 tests with AbortController polyfill
  packages/remix-architect/__tests__/server-test.ts
  packages/remix-architect/server.ts
  packages/remix-express/server.ts
  packages/remix-netlify/__tests__/server-test.ts
  packages/remix-netlify/server.ts
  packages/remix-vercel/server.ts
Labels: CLA Signed, adapter:architect, adapter:vercel, adapter:express, adapter:netlify

#4181 docs(api/remix): fix heading level (#3789)
  contributors.yml
  docs/api/remix.md
Labels: CLA Signed, documentation

#4173 docs(examples): add `vanilla-extract` example
  contributors.yml
  examples/vanilla-extract/.eslintrc
  examples/vanilla-extract/.gitignore
  examples/vanilla-extract/.styles/global.css.ts
  examples/vanilla-extract/.styles/index.ts
  examples/vanilla-extract/.styles/sprinkles.css.ts
  examples/vanilla-extract/README.md
  examples/vanilla-extract/app/components/Box/Box.ts
  examples/vanilla-extract/app/components/Text/Text.css.ts
  examples/vanilla-extract/app/components/Text/Text.tsx
  examples/vanilla-extract/app/components/index.ts
  examples/vanilla-extract/app/entry.client.tsx
  examples/vanilla-extract/app/entry.server.tsx
  examples/vanilla-extract/app/root.tsx
  examples/vanilla-extract/app/routes/index.tsx
  examples/vanilla-extract/package.json
  examples/vanilla-extract/public/favicon.ico
  examples/vanilla-extract/remix.config.js
  examples/vanilla-extract/remix.env.d.ts
  examples/vanilla-extract/tsconfig.json
  examples/vanilla-extract/tsup.config.js
Labels: CLA Signed, examples

#3012 chore(remix-dev): when using jsconfig, include js in jsconfig files instead of ts
  integration/helpers/create-fixture.ts
  integration/tsconfig-test.ts
  packages/remix-dev/__tests__/fixtures/stack.tar.gz
  packages/remix-dev/__tests__/fixtures/stack/tsconfig.json
  packages/remix-dev/compiler/plugins/serverBareModulesPlugin.ts
  packages/remix-dev/compiler/utils/tsconfig/index.ts
  packages/remix-dev/compiler/utils/tsconfig/write-config-defaults.ts
  packages/remix-dev/config.ts
Labels: CLA Signed, package:dev

#4171 ci: use `Promise.allSettled` when commenting to prevent errors when commenting on issues that were converted to discussions
  scripts/release/comment.ts
Labels: CLA Signed

#4137 docs(examples): add `leaflet` example
  examples/leaflet/.eslintrc.js
  examples/leaflet/.gitignore
  examples/leaflet/README.md
  examples/leaflet/app/components/client-only.tsx
  examples/leaflet/app/components/map.client.tsx
  examples/leaflet/app/entry.client.tsx
  examples/leaflet/app/entry.server.tsx
  examples/leaflet/app/root.tsx
  examples/leaflet/app/routes/index.tsx
  examples/leaflet/package.json
  examples/leaflet/public/favicon.ico
  examples/leaflet/remix.config.js
  examples/leaflet/remix.env.d.ts
  examples/leaflet/sandbox.config.json
  examples/leaflet/tsconfig.json
Labels: CLA Signed, examples

#4203 chore: lock RR version
  .changeset/cyan-cats-sip.md
  examples/session-flash/package.json
  packages/remix-react/package.json
  packages/remix-server-runtime/package.json
  yarn.lock
Labels: CLA Signed

#4207 docs(examples): Update references to the examples repository
  docs/api/conventions.md
  docs/api/remix.md
  docs/guides/migrating-react-router-app.md
  docs/guides/styling.md
  docs/index.md
  docs/pages/community.md
  docs/pages/contributing.md
  docs/tutorials/jokes.md
Labels: CLA Signed

#4217 docs: fix `react-router` docs links
  docs/api/conventions.md
  docs/guides/migrating-react-router-app.md
Labels: CLA Signed, documentation

#4225 docs(api/conventions): fix broken link
  docs/api/conventions.md
Labels: CLA Signed, documentation

#4224 docs(tutorials/jokes): fix typo + code highlighting
  contributors.yml
  docs/tutorials/jokes.md
Labels: CLA Signed, documentation

#4209 docs(api/remix): fix outdated `transition.type` names
  docs/api/remix.md
Labels: CLA Signed, documentation

#4235 chore: flush node streams
  .changeset/seven-bears-listen.md
  packages/remix-node/stream.ts
Labels: CLA Signed

#4241 docs(tutorials/jokes): fix code highlighting
  contributors.yml
  docs/tutorials/jokes.md
Labels: CLA Signed, documentation

#4238 fix: preserve ?index for fetcher get submissions
  .changeset/sour-roses-heal.md
  integration/fetcher-test.ts
  packages/remix-react/components.tsx
Labels: CLA Signed

#4034 chore(remix-dev): allow setting `tsconfig`'s `moduleResolution` to `node`, `node16` or `nodenext`
  .changeset/five-apricots-happen.md
  integration/tsconfig-test.ts
  packages/remix-dev/compiler/utils/tsconfig/write-config-defaults.ts
Labels: CLA Signed, package:dev

#4246 fix(@remix-run/react): remove unused `type-fest` dependency
  .changeset/hot-pugs-tie.md
  packages/remix-react/package.json
  yarn.lock
Labels: CLA Signed, package:server-runtime

#4251 fix(@remix-run/server-runtime): inline `Merge` type utility from `type-fest`
  packages/remix-server-runtime/serialize.ts
Labels: CLA Signed

#4255 refactor(remix-server-runtime): replace `type-fest`'s `Merge` with intersection
  packages/remix-react/__tests__/hook-types-test.tsx
  packages/remix-server-runtime/serialize.ts
Labels: CLA Signed, package:server-runtime

#4268 docs(api/remix): fix typo
  contributors.yml
  docs/api/remix.md
Labels: CLA Signed, documentation

#4208 fix(remix-dev): Update create-remix to use the new examples repository
  .changeset/curvy-zoos-cough.md
  packages/remix-dev/__tests__/create-test.ts
  packages/remix-dev/__tests__/fixtures/examples-main.tar.gz
  packages/remix-dev/__tests__/github-mocks.ts
  packages/remix-dev/cli/create.ts
  packages/remix-eslint-config/internal.js
Labels: CLA Signed, package:dev, package:eslint-config

#4269 chore: update tsconfigs to use composite
  .gitignore
  integration/tsconfig.json
  packages/create-remix/tsconfig.json
  packages/remix-architect/tsconfig.json
  packages/remix-cloudflare-pages/tsconfig.json
  packages/remix-cloudflare-workers/tsconfig.json
  packages/remix-cloudflare/tsconfig.json
  packages/remix-dev/tsconfig.json
  packages/remix-express/tsconfig.json
  packages/remix-netlify/tsconfig.json
  packages/remix-node/tsconfig.json
  packages/remix-react/tsconfig.json
  packages/remix-serve/tsconfig.json
  packages/remix-server-runtime/tsconfig.json
  packages/remix-vercel/tsconfig.json
  packages/remix/tsconfig.json
  tsconfig.json
Labels: CLA Signed, adapter:architect, adapter:vercel, adapter:express, adapter:netlify, adapter:cloudflare-pages, adapter:cloudflare-workers, package:serve, package:create-remix, package:dev, package:remix, package:server-runtime, runtime:node, runtime:cloudflare, package:react

#4276 chore: fix a borked test caused by shallow clone
  integration/tsconfig-test.ts
Labels: CLA Signed

#4277 chore: update web-fetch dependency
  .changeset/proud-geese-sin.md
  .yarnrc
  packages/remix-node/package.json
  yarn.lock
Labels: CLA Signed

#3841 fix(remix-dev): write other server build output files to `assetsBuildDirectory`
  .changeset/flat-rivers-wait.md
  integration/assets/image.png
  integration/helpers/create-fixture.ts
  integration/resource-routes-test.ts
  packages/remix-dev/compiler.ts
Labels: CLA Signed, package:dev

#4272 docs: update all `create-remix` calls to use latest version
  DEVELOPMENT.md
  docs/guides/deployment.md
  docs/tutorials/blog.md
Labels: CLA Signed, documentation

#4290 chore: add changeset for #4041
  .changeset/poor-sloths-whisper.md
Labels: CLA Signed

#4285 ci: use GitHub Actions account to commit format changes
  .github/workflows/format.yml
Labels: CLA Signed

#4072 ci: comment and close issues when stable, just comment on nightly
  .github/workflows/merged-pr.yml
  .github/workflows/nightly.yml
  .github/workflows/postrelease.yml
  .github/workflows/release-comments.yml
  .github/workflows/release.yml
  scripts/release/comment.ts
  scripts/release/constants.ts
  scripts/release/github.ts
  scripts/release/package-lock.json
  scripts/release/utils.ts
Labels: CLA Signed

#4245 feat(remix-server-runtime): RRR 1.1 - handleResourceRequest
  .changeset/light-chairs-tickle.md
  .github/workflows/reusable-test.yml
  .github/workflows/test.yml
  integration/helpers/create-fixture.ts
  integration/resource-routes-test.ts
  integration/tsconfig.json
  package.json
  packages/create-remix/tsconfig.json
  packages/remix-server-runtime/__tests__/data-test.ts
  packages/remix-server-runtime/__tests__/handler-test.ts
  packages/remix-server-runtime/__tests__/server-test.ts
  packages/remix-server-runtime/data.ts
  packages/remix-server-runtime/rollup.config.js
  packages/remix-server-runtime/router/history.ts
  packages/remix-server-runtime/router/index.ts
  packages/remix-server-runtime/router/router.ts
  packages/remix-server-runtime/router/utils.ts
  packages/remix-server-runtime/routes.ts
  packages/remix-server-runtime/server.ts
  yarn.lock
Labels: CLA Signed, package:server-runtime
