Repository remix-run/remix, pull requests merged in 2022-07, with the labels that each got.

#3619 fix(remix-dev/create): check for undefined `--token`
  packages/remix-dev/cli/create.ts
Labels: CLA Signed, package:dev

#3631 docs(api/conventions): Fix broken routing guide link
  contributors.yml
  docs/api/conventions.md
Labels: CLA Signed, documentation

#3598 docs(api/conventions): fix a typo
  contributors.yml
  docs/api/conventions.md
Labels: CLA Signed, documentation

#3610 chore: remove last usage of bahmutov/npm-install
  .github/workflows/stacks.yml
Labels: CLA Signed

#3595 fix(docs,examples,templates): make `npm-run-all` calls work when using Yarn
  contributors.yml
  docs/guides/styling.md
  examples/blog-tutorial/package.json
  examples/pm-app/package.json
  examples/quirrel/package.json
  examples/sass/package.json
  examples/strapi/package.json
  examples/tailwindcss/package.json
  packages/remix-dev/__tests__/fixtures/replace-remix-imports/package.json
  scripts/playground/template/package.json
  templates/arc/package.json
  templates/cloudflare-pages/package.json
  templates/cloudflare-workers/package.json
  templates/deno/package.json
  templates/express/package.json
Labels: CLA Signed, examples, documentation, template:express, template:architect, template:cloudflare-pages, template:cloudflare-workers, template:deno

#3573 feat(remix-dev/cli/init): add `--no-delete` flag
  packages/remix-dev/__tests__/cli-test.ts
  packages/remix-dev/__tests__/create-test.ts
  packages/remix-dev/cli/commands.ts
  packages/remix-dev/cli/run.ts
Labels: CLA Signed, package:dev

#3644 fix: fix `playground` creation
  contributors.yml
  scripts/playground/new.js
  scripts/playground/template/package.json
Labels: CLA Signed

#3521 chore(integration): fix type errors and start enforcing type checks
  integration/esm-only-warning-test.ts
  integration/helpers/playwright-fixture.ts
  integration/prefetch-test.ts
  integration/tsconfig-test.ts
  integration/tsconfig.json
  packages/remix-express/tsconfig.json
  packages/remix-react/tsconfig.json
  packages/remix-server-runtime/tsconfig.json
  tsconfig.json
Labels: CLA Signed, feat:typescript

#3642 fix: Update the installation step for the jokes app
  contributors.yml
  docs/api/remix.md
  docs/tutorials/jokes.md
Labels: CLA Signed, documentation

#3547 docs: jokes app tutorial in fetching jokes part
  contributors.yml
  docs/tutorials/jokes.md
Labels: CLA Signed, documentation

#3637 chore: adds theme-ui example project
  contributors.yml
  examples/theme-ui/.eslintrc.js
  examples/theme-ui/.gitignore
  examples/theme-ui/README.md
  examples/theme-ui/app/entry.client.tsx
  examples/theme-ui/app/entry.server.tsx
  examples/theme-ui/app/root.tsx
  examples/theme-ui/app/routes/index.tsx
  examples/theme-ui/app/routes/jokes-error.tsx
  examples/theme-ui/app/routes/jokes.tsx
  examples/theme-ui/app/styles/context.tsx
  examples/theme-ui/app/styles/createEmotionCache.tsx
  examples/theme-ui/package.json
  examples/theme-ui/public/favicon.ico
  examples/theme-ui/remix.config.js
  examples/theme-ui/remix.env.d.ts
  examples/theme-ui/sandbox.config.json
  examples/theme-ui/tsconfig.json
Labels: CLA Signed, examples

#2313 feat(remix-netlify): add support for `@netlify/functions` v0.11
  packages/remix-netlify/package.json
Labels: CLA Signed, adapter:netlify

#3553 ci: debug failing deployment tests
  .github/workflows/deployments.yml
  scripts/deployment-test/_shared.mjs
  scripts/deployment-test/arc.mjs
  scripts/deployment-test/cf-pages.mjs
  scripts/deployment-test/cf-workers.mjs
  scripts/deployment-test/deno-deploy.mjs
  scripts/deployment-test/fly.mjs
  scripts/deployment-test/netlify.mjs
  scripts/deployment-test/package.json
  scripts/deployment-test/vercel.mjs
  templates/cloudflare-workers/package.json
  templates/cloudflare-workers/wrangler.toml
Labels: CLA Signed

#3664 chore(examples): fix ESLint warnings in `theme-ui` example
  examples/theme-ui/app/entry.client.tsx
  examples/theme-ui/app/entry.server.tsx
  examples/theme-ui/app/root.tsx
  examples/theme-ui/app/routes/index.tsx
  examples/theme-ui/app/routes/jokes.tsx
  examples/theme-ui/app/styles/context.tsx
  examples/theme-ui/app/styles/createEmotionCache.tsx
Labels: CLA Signed, examples

#3662 ci(deploy/vercel): pass token via `--token`
  scripts/deployment-test/vercel.mjs
Labels: CLA Signed

#3633 fix(remix-dev/compiler): fix Yarn PnP resolution for empty modules
  packages/remix-dev/compiler.ts
  packages/remix-dev/package.json
  yarn.lock
Labels: CLA Signed, package:dev

#3658 fix(docs/tutorials): update pre-requisite Node version
  docs/tutorials/blog.md
  docs/tutorials/jokes.md
Labels: CLA Signed, documentation

#3678 fix: Revert changes to loader/action types
  packages/remix-cloudflare/index.ts
  packages/remix-deno/index.ts
  packages/remix-node/index.ts
  packages/remix-react/__tests__/hook-types-test.tsx
  packages/remix-react/components.tsx
  packages/remix-react/errors.ts
  packages/remix-server-runtime/__tests__/responses-test.ts
  packages/remix-server-runtime/__tests__/utils.ts
  packages/remix-server-runtime/errors.ts
  packages/remix-server-runtime/index.ts
  packages/remix-server-runtime/interface.ts
  packages/remix-server-runtime/reexport.ts
  packages/remix-server-runtime/responses.ts
  packages/remix-server-runtime/routeModules.ts
  rollup.config.js
Labels: CLA Signed

#3677 fix(remix-server-runtime): support interfaces in `JsonFunction`
  packages/remix-server-runtime/responses.ts
Labels: CLA Signed, package:server-runtime

#3569 chore: Introduce Changesets
  .changeset/README.md
  .changeset/config.json
  .github/workflows/release-private.yml
  .github/workflows/release.yml
  package.json
  yarn.lock
Labels: CLA Signed

#3676 feat(remix-react): add magic comment to allow `webpack` bundling
  packages/remix-react/routeModules.ts
Labels: CLA Signed, package:react

#3376 Move rollup configs to individual packages
  .eslintrc.js
  package.json
  packages/create-remix/.eslintrc.js
  packages/create-remix/rollup.config.js
  packages/remix-architect/rollup.config.js
  packages/remix-cloudflare-pages/rollup.config.js
  packages/remix-cloudflare-workers/rollup.config.js
  packages/remix-cloudflare/rollup.config.js
  packages/remix-deno/rollup.config.js
  packages/remix-dev/rollup.config.js
  packages/remix-express/rollup.config.js
  packages/remix-netlify/rollup.config.js
  packages/remix-node/rollup.config.js
  packages/remix-react/rollup.config.js
  packages/remix-serve/rollup.config.js
  packages/remix-server-runtime/rollup.config.js
  packages/remix-vercel/rollup.config.js
  packages/remix/rollup.config.js
  rollup.config.js
  rollup.utils.js
  scripts/copy-build-to-dist.mjs
  yarn.lock
Labels: CLA Signed

#3681 doc: mention deno server runtime
  contributors.yml
  docs/api/remix.md
Labels: CLA Signed, documentation

#3689 fix(templates/deno): grab `@remix-run/deno` types directly from `node_modules/`
  templates/deno/.vscode/resolve_npm_imports.json
Labels: CLA Signed, template:deno

#3694 fix(remix-dev): declare `--port` & `-p` flags
  packages/remix-dev/cli/run.ts
Labels: CLA Signed, package:dev

#3688 refactor(rollup): cleanup `magicExports` remains
  packages/remix-architect/rollup.config.js
  rollup.utils.js
Labels: CLA Signed

#3698 docs(guides/typescript): fix code highlighting
  contributors.yml
  docs/guides/typescript.md
Labels: CLA Signed, documentation

#859 feat(remix-react): add WebSocket reconnect to `LiveReload`
  .changeset/fast-yaks-whisper.md
  contributors.yml
  packages/remix-react/components.tsx
Labels: CLA Signed, feat:dx, package:react

#3349 feat(remix-dev,remix-serve): include publicPath in server build manifest
  packages/remix-dev/__tests__/readConfig-test.ts
  packages/remix-dev/cli/commands.ts
  packages/remix-dev/compiler/plugins/serverEntryModulePlugin.ts
  packages/remix-dev/config.ts
  packages/remix-serve/cli.ts
  packages/remix-serve/index.ts
  packages/remix-server-runtime/build.ts
Labels: CLA Signed, package:serve, package:dev

#3702 docs(decisions): remove unused index and frontmatter
  decisions/0001-use-npm-to-manage-npm-dependencies-for-deno-projects.md
  decisions/0002-do-not-clone-request.md
  decisions/index.md
Labels: CLA Signed

#3703 docs(decisions): remove unused frontmatter from template
  decisions/template.md
Labels: CLA Signed

#3656 fix(serverBareModulesPlugin): update require.resolve to use full import, update warning
  .changeset/yellow-flowers-trade.md
  integration/compiler-test.ts
  integration/helpers/create-fixture.ts
  packages/remix-dev/compiler/plugins/serverBareModulesPlugin.ts
Labels: CLA Signed

#3705 docs(templates/deno): nest deno deploy setup under "deployment" section
  templates/deno/README.md
Labels: CLA Signed

#2079 fix(templates/cloudflare-workers): prevent building twice with `wrangler publish`
  templates/cloudflare-workers/package.json
Labels: CLA Signed, needs-response, template:cloudflare-workers

#3420 feat(remix-vercel): add support for `@vercel/node` v2
  .changeset/slimy-avocados-tickle.md
  packages/remix-vercel/__tests__/server-test.ts
  packages/remix-vercel/package.json
  yarn.lock
Labels: CLA Signed, adapter:vercel

#3709 templates(vercel): update `@vercel/node` dependency
  templates/vercel/package.json
Labels: CLA Signed, template:vercel

#3716 fix(remix-eslint-config): use `require.resolve` when importing `@babel/preset-react`
  .changeset/blue-starfishes-study.md
  contributors.yml
  packages/remix-eslint-config/index.js
Labels: CLA Signed, package:eslint-config

#3721 fix(remix-react): fix `shouldReload` bug for deferred cancellations on fetcher submissions
  packages/remix-react/__tests__/transition-test.tsx
  packages/remix-react/transition.ts
Labels: CLA Signed, package:react

#3736 chore(ci): Add workflow for experimental releases
  .github/workflows/release-experimental.yml
Labels: CLA Signed

#3743 fix(remix-dev): update type for ServerBuild virtual module
  .changeset/weak-icons-matter.md
  packages/remix-dev/server-build.ts
Labels: CLA Signed

#3704 docs(decisions-0003): infer types for `useLoaderData` from `loader` type using generic
  decisions/0003-infer-types-for-useloaderdata-and-useactiondata-from-loader-and-action-via-generics.md
Labels: CLA Signed, documentation

#3764 feat(remix-react): export `UseDataFunctionReturn` type
  .changeset/loud-emus-cross.md
  packages/remix-react/index.tsx
  rollup.utils.js
Labels: CLA Signed, feat:typescript, package:react

#3763 feat(remix-dev): add support for `handle`, `links` & `loader` to mdx
  .changeset/tender-impalas-invite.md
  contributors.yml
  docs/guides/mdx.md
  integration/mdx-test.ts
  packages/remix-dev/compiler/plugins/mdx.ts
Labels: CLA Signed, documentation, package:dev, feat:mdx

#3754 templates(netlify): improve DX for Netlify serverless template
  contributors.yml
  templates/netlify/README.md
  templates/netlify/package.json
  templates/netlify/remix.config.js
Labels: CLA Signed, template:netlify

#3767 docs(guides/data-writes): remove extra period
  contributors.yml
  docs/guides/data-writes.md
Labels: CLA Signed, documentation

#3770 docs(tutorial/blog): Instruct to restart the dev server after marked install
  contributors.yml
  docs/tutorials/blog.md
Labels: CLA Signed, documentation

#3776 docs(uploads): Update unstable_createFileUploadHandler callbacks signature
  docs/api/remix.md
Labels: CLA Signed, documentation

#3787 docs(tutorials): update Node requirement
  docs/tutorials/blog.md
  docs/tutorials/jokes.md
Labels: CLA Signed, documentation

#3782 docs(tutorials/blog): add message about TS2305 warning
  docs/tutorials/blog.md
Labels: CLA Signed, documentation

#3790 docs: add `@remix-run/deno` reference in import comments
  docs/api/conventions.md
  docs/api/remix.md
  docs/guides/bff.md
  docs/guides/constraints.md
  docs/guides/data-loading.md
  docs/guides/data-writes.md
  docs/guides/mdx.md
  docs/guides/optimistic-ui.md
  docs/guides/resource-routes.md
  docs/guides/styling.md
  docs/other-api/node.md
  docs/other-api/serve.md
  docs/pages/faq.md
  docs/pages/gotchas.md
  docs/pages/philosophy.md
Labels: CLA Signed, documentation

#3793 chore(ci): Trigger experimental release from tag instead of GitHub
  .github/workflows/release-experimental.yml
Labels: CLA Signed

#3796 chore: Add script for faster builds
  .github/workflows/nightly.yml
  .github/workflows/reusable-test.yml
  package.json
  scripts/build.mjs
Labels: CLA Signed

#3799 docs(guide): Fix a typo in migrating-react-router-app.md
  contributors.yml
  docs/guides/migrating-react-router-app.md
Labels: CLA Signed

#3801 feat(mdx): support exporting links function
  .changeset/neat-nymphs.md
  contributors.yml
  docs/guides/mdx.md
  integration/mdx-test.ts
  packages/remix-dev/compiler/plugins/mdx.ts
Labels: CLA Signed

#3797 Fix `json()` when inferring the return type
  .changeset/long-taxis-drop.md
  contributors.yml
  packages/remix-node/index.ts
Labels: CLA Signed, feat:typescript

#3798 docs(guide): Clarify how to handle 404s
  contributors.yml
  docs/guides/not-found.md
Labels: CLA Signed, documentation

#3744 ci: move comments, deploy and stacks test to different action
  .github/workflows/postrelease.yml
  .github/workflows/release-comments.yml
  .github/workflows/release.yml
  .github/workflows/reusable-test.yml
  scripts/release/comment.ts
  scripts/release/constants.ts
  scripts/release/github.ts
  scripts/release/utils.ts
Labels: CLA Signed

#3803 ci: move comments, deploy and stacks test to different action (#3744, #3803)
  .github/workflows/postrelease.yml
  .github/workflows/release-comments.yml
  .github/workflows/release.yml
  .github/workflows/reusable-test.yml
  scripts/release/comment.ts
  scripts/release/constants.ts
  scripts/release/github.ts
  scripts/release/utils.ts
Labels: CLA Signed

#3802 docs(examples): convert `sanity` example to TypeScript
  examples/sanity/app/components/Preview.jsx
  examples/sanity/app/components/Preview.tsx
  examples/sanity/app/components/index.ts
  examples/sanity/app/entry.client.jsx
  examples/sanity/app/entry.client.tsx
  examples/sanity/app/entry.server.tsx
  examples/sanity/app/lib/sanity/config.ts
  examples/sanity/app/lib/sanity/filterDataToSingleItem.ts
  examples/sanity/app/lib/sanity/getClient.ts
  examples/sanity/app/lib/sanity/helpers.js
  examples/sanity/app/lib/sanity/helpers.tsx
  examples/sanity/app/lib/sanity/index.ts
  examples/sanity/app/lib/sanity/usePreviewSubscription.ts
  examples/sanity/app/root.jsx
  examples/sanity/app/root.tsx
  examples/sanity/app/routes/$slug.tsx
  examples/sanity/app/routes/index.jsx
  examples/sanity/app/routes/index.tsx
  examples/sanity/jsconfig.json
  examples/sanity/package.json
  examples/sanity/remix.env.d.ts
  examples/sanity/studio/package.json
  examples/sanity/studio/static/.gitkeep
  examples/sanity/tsconfig.json
Labels: CLA Signed, examples

#3815 chore(revert): Remove `UseDataFunctionReturn` type export
  .changeset/loud-emus-cross.md
  packages/remix-react/index.tsx
  rollup.utils.js
Labels: CLA Signed

#3816 chore(templates): update dependencies
  templates/arc/package.json
  templates/cloudflare-pages/package.json
  templates/cloudflare-workers/package.json
  templates/express/package.json
  templates/fly/package.json
  templates/netlify/package.json
  templates/remix/package.json
  templates/vercel/package.json
Labels: CLA Signed, template:express, template:architect, template:vercel, template:cloudflare-pages, template:cloudflare-workers, template:fly, template:netlify, template:remix

#3529 refactor(remix-dev/cli): use `convert-to-javascript` migration internally
  packages/remix-dev/__tests__/cli-test.ts
  packages/remix-dev/__tests__/create-test.ts
  packages/remix-dev/__tests__/migrations/convert-to-javascript-test.ts
  packages/remix-dev/cli/convert-to-javascript.ts
  packages/remix-dev/cli/create.ts
  packages/remix-dev/cli/migrate/flags.ts
  packages/remix-dev/cli/migrate/migrations/convert-to-javascript/convertTSFilesToJS/index.ts
  packages/remix-dev/cli/migrate/migrations/convert-to-javascript/index.ts
  packages/remix-dev/cli/migrate/migrations/replace-remix-imports/index.ts
  packages/remix-dev/cli/migrate/run.ts
  packages/remix-dev/cli/migrate/types.ts
  packages/remix-dev/cli/run.ts
Labels: CLA Signed, package:dev

#3433 docs(examples): add file upload to S3 example
  contributors.yml
  examples/file-and-s3-upload/.env.sample
  examples/file-and-s3-upload/.eslintrc.js
  examples/file-and-s3-upload/.gitignore
  examples/file-and-s3-upload/README.md
  examples/file-and-s3-upload/app/entry.client.tsx
  examples/file-and-s3-upload/app/entry.server.tsx
  examples/file-and-s3-upload/app/root.tsx
  examples/file-and-s3-upload/app/routes/s3-upload.tsx
  examples/file-and-s3-upload/app/utils/s3.server.ts
  examples/file-and-s3-upload/package.json
  examples/file-and-s3-upload/public/favicon.ico
  examples/file-and-s3-upload/remix.config.js
  examples/file-and-s3-upload/remix.env.d.ts
  examples/file-and-s3-upload/sandbox.config.json
  examples/file-and-s3-upload/tsconfig.json
Labels: CLA Signed, examples

#2803 feat(remix-dev): support a TypeScript file for the `remix.init` index script
  contributors.yml
  packages/remix-dev/__tests__/create-test.ts
  packages/remix-dev/__tests__/fixtures/stack-init-ts.tar.gz
  packages/remix-dev/cli/commands.ts
  packages/remix-dev/cli/create.ts
Labels: CLA Signed, feat:typescript, package:dev

#3823 docs(guides/disabling-javascript): fix typo
  contributors.yml
  docs/guides/disabling-javascript.md
Labels: CLA Signed, documentation

#3817 fix: write other server build output files
  .changeset/famous-schools-shop.md
  integration/assets/image.png
  integration/helpers/create-fixture.ts
  integration/resource-routes-test.ts
  packages/remix-dev/compiler.ts
Labels: CLA Signed

#3160 feat(templates): update Cloudflare templates to use `wrangler` v2
  templates/cloudflare-pages/package.json
  templates/cloudflare-workers/README.md
  templates/cloudflare-workers/package.json
  templates/cloudflare-workers/wrangler.toml
Labels: CLA Signed, template:cloudflare-pages, template:cloudflare-workers

#3834 chore(bug-report-template): Remove unnecessary async
  contributors.yml
  integration/bug-report-test.ts
Labels: CLA Signed

#3766 fix(remix-react): support undefined unions as optional keys in `UseDataFunctionReturn` type
  .changeset/olive-pumpkins-kick.md
  contributors.yml
  packages/remix-react/__tests__/hook-types-test.tsx
  packages/remix-react/components.tsx
  packages/remix-react/package.json
  yarn.lock
Labels: CLA Signed, package:react

#3836 docs: add basic doc entry for how nightly releases work and how they run
  docs/pages/contributing.md
Labels: CLA Signed, documentation

#3868 fix: add main field to remix-run/deno
  .changeset/five-kiwis-type.md
  packages/remix-deno/package.json
Labels: CLA Signed

#3872 Calm esm warnings
  .changeset/silent-trains-build.md
  integration/esm-only-warning-test.ts
  packages/remix-dev/compiler/plugins/serverBareModulesPlugin.ts
Labels: CLA Signed

#3879 fix(@remix-run/react): preserve `null` properties for `useLoaderData` and `useActionData` inference
  .changeset/nervous-walls-sing.md
  packages/remix-react/components.tsx
Labels: CLA Signed

#3880 fix(remix-dev): Remove logical nullish assignment
  .changeset/chilled-ants-care.md
  packages/remix-dev/cli/run.ts
Labels: CLA Signed
