Repository remix-run/remix, pull requests merged in 2022-11, with the labels that each got.

#4465 docs(pages/community): add KCD's frontendmasters courses
  contributors.yml
  docs/pages/community.md
Labels: CLA Signed, documentation

#4017 feat(templates/express): support `.env` durning local development
  contributors.yml
  templates/express/package.json
Labels: CLA Signed, template:express

#4490 docs(technical-explanation): fix typos
  contributors.yml
  docs/pages/technical-explanation.md
Labels: CLA Signed, documentation

#4507 ci: update stale workflow
  .github/workflows/no-response.yml
Labels: CLA Signed

#4514 ci(nightly): update output command
  .github/workflows/nightly.yml
Labels: CLA Signed

#4418 chore(tests): use `intent` instead of `action`
  integration/form-test.ts
  integration/transition-test.ts
Labels: CLA Signed

#4417 docs: use `intent` instead of `action` or hidden input
  docs/pages/faq.md
Labels: CLA Signed, documentation

#4550 Revert "ci: use GitHub Actions account to commit format changes"
  .github/workflows/format.yml
Labels: CLA Signed

#4554 chore: remove assert flow
  integration/error-boundary-test.ts
  integration/error-data-request-test.ts
  integration/transition-test.ts
  packages/remix-server-runtime/__tests__/server-test.ts
  packages/remix-server-runtime/server.ts
Labels: CLA Signed

#4561 fix(remix-react): Remove nullish coalescing operator
  .changeset/curvy-countries-boil.md
  packages/remix-react/components.tsx
Labels: CLA Signed, package:react

#4565 docs(pages/contributing): Fix typos
  docs/pages/contributing.md
Labels: CLA Signed, docs

#3299 feat(remix-dev): add `.wasm` as a supported file type
  contributors.yml
  packages/remix-dev/compiler/loaders.ts
  packages/remix-dev/modules.ts
Labels: CLA Signed, package:dev

#4583 ci(deployment-test/cf-workers): update worker url
  scripts/deployment-test/cf-workers.mjs
Labels: CLA Signed

#4591 docs(decisions): fix typos
  contributors.yml
  decisions/0001-use-npm-to-manage-npm-dependencies-for-deno-projects.md
Labels: CLA Signed, docs

#4593 chore(templates): update dependencies to latest minor
  templates/arc/package.json
  templates/cloudflare-pages/package.json
  templates/cloudflare-workers/package.json
  templates/express/package.json
  templates/fly/package.json
  templates/netlify/package.json
  templates/remix/package.json
  templates/vercel/package.json
Labels: CLA Signed, template:express, template:architect, template:vercel, template:cloudflare-pages, template:cloudflare-workers, template:fly, template:netlify, template:remix

#4477 chore(remix): fix typo
  contributors.yml
  packages/remix/index.ts
Labels: CLA Signed, package:remix

#4566 feat(compiler): Add support for remix config feature flags
  .changeset/calm-eels-invite.md
  packages/remix-dev/__tests__/readConfig-test.ts
  packages/remix-dev/compiler/plugins/serverEntryModulePlugin.ts
  packages/remix-dev/config.ts
  packages/remix-dev/index.ts
  packages/remix-react/components.tsx
  packages/remix-react/entry.ts
  packages/remix-server-runtime/build.ts
  packages/remix-server-runtime/entry.ts
  packages/remix-server-runtime/server.ts
Labels: CLA Signed, package:dev, package:server-runtime, renderer:react

#4385 feat(remix-server-runtime): RRR 1.3 / 1.4 - handleDocumentRequest
  .changeset/light-avocados-drop.md
  integration/catch-boundary-test.ts
  integration/compiler-test.ts
  integration/error-boundary-test.ts
  integration/error-data-request-test.ts
  integration/fetcher-test.ts
  integration/mdx-test.ts
  integration/transition-test.ts
  packages/remix-react/routes.tsx
  packages/remix-server-runtime/__tests__/server-test.ts
  packages/remix-server-runtime/data.ts
  packages/remix-server-runtime/headers.ts
  packages/remix-server-runtime/router/history.ts
  packages/remix-server-runtime/router/index.ts
  packages/remix-server-runtime/router/router.ts
  packages/remix-server-runtime/router/utils.ts
  packages/remix-server-runtime/routes.ts
  packages/remix-server-runtime/server.ts
Labels: CLA Signed

#4611 add missing changeset
  .changeset/purple-baboons-beg.md
Labels: CLA Signed

#4283 docs(pages/community): add tutorial
  contributors.yml
  docs/pages/community.md
Labels: CLA Signed, docs

#4619 test(remix-dev): bring `replace-remix-magic-imports` fixture in line with template
  packages/remix-dev/__tests__/fixtures/replace-remix-magic-imports/tsconfig.json
Labels: CLA Signed

#4612 feat(remix-server-runtime): RRR 2 - Deploy `@remix-run/server-runtime` changes
  .changeset/beige-planes-type.md
  packages/remix-server-runtime/__tests__/data-test.ts
  packages/remix-server-runtime/data.ts
  packages/remix-server-runtime/headers.ts
  packages/remix-server-runtime/responses.ts
  packages/remix-server-runtime/server.ts
Labels: CLA Signed

#4624 chore(tests): Only retry on failed tests in CI
  integration/playwright.config.ts
Labels: CLA Signed

#4625 docs(guides/data-writes): Fix a couple typos
  contributors.yml
  docs/guides/data-writes.md
Labels: CLA Signed, docs

#4528 refactor(dev): dev server
  packages/remix-dev/channel.ts
  packages/remix-dev/cli/commands.ts
  packages/remix-dev/compiler/compileBrowser.ts
  packages/remix-dev/compiler/compilerServer.ts
  packages/remix-dev/compiler/index.ts
  packages/remix-dev/compiler/remixCompiler.ts
  packages/remix-dev/compiler/watch.ts
  packages/remix-dev/devServer/index.ts
  packages/remix-dev/devServer/liveReload.ts
  packages/remix-dev/devServer/serve.ts
Labels: CLA Signed, package:dev

#3284 feat: deprecate all functions & types exported from `magicExports`
  .changeset/khaki-meals-prove.md
  rollup.utils.js
Labels: CLA Signed, adapter:architect, adapter:cloudflare-pages, adapter:cloudflare-workers, package:server-runtime, runtime:node, runtime:cloudflare, renderer:react

#4644 fix(remix-node): update `@remix-run/web-fetch` to 4.3.2
  .changeset/moody-cats-relax.md
  packages/remix-architect/__tests__/server-test.ts
  packages/remix-express/__tests__/server-test.ts
  packages/remix-netlify/__tests__/server-test.ts
  packages/remix-node/package.json
  packages/remix-vercel/__tests__/server-test.ts
  yarn.lock
Labels: CLA Signed, runtime:node

#4301 chore(remix-dev): bump esbuild to 0.15.12
  .changeset/neat-months-run.md
  packages/remix-dev/compiler/assets.ts
  packages/remix-dev/compiler/compileBrowser.ts
  packages/remix-dev/compiler/compilerServer.ts
  packages/remix-dev/package.json
  scripts/release/package-lock.json
  scripts/release/package.json
  yarn.lock
Labels: CLA Signed, package:dev

#4646 fix: update references to codemod
  .changeset/happy-flies-own.md
  packages/remix-eslint-config/rules/core.js
  rollup.utils.js
  scripts/run-migration-on-examples.js
Labels: CLA Signed

#4610 feat(`react`,`server-runtime`): Support for v2 array syntax for route `meta`
  .changeset/tricky-bobcats-nail.md
  integration/meta-test.ts
  packages/remix-react/components.tsx
  packages/remix-react/routeModules.ts
  packages/remix-react/routes.tsx
  packages/remix-server-runtime/routeModules.ts
  packages/remix-server-runtime/routes.ts
Labels: CLA Signed, package:server-runtime, renderer:react

#4596 chore: fix `postrelease` workflow
  .github/workflows/postrelease.yml
Labels: CLA Signed

#4660 fix: add missing return to Fix remix dev command
  .changeset/itchy-paws-remain.md
  packages/remix-dev/cli/commands.ts
Labels: CLA Signed

#4661 Fix magic export deprecation messaging
  .changeset/khaki-meals-prove.md
  .changeset/sharp-ears-begin.md
  packages/remix-dev/compiler/compileBrowser.ts
  packages/remix-dev/compiler/compilerServer.ts
  packages/remix-dev/compiler/plugins/deprecatedRemixPackagePlugin.ts
  rollup.utils.js
Labels: CLA Signed, package:dev

#4668 Bump remix to react-router-dom@6.4.3
  .changeset/early-camels-guess.md
  packages/remix-react/components.tsx
  packages/remix-react/package.json
  packages/remix-server-runtime/package.json
  packages/remix-server-runtime/routeMatching.ts
  packages/remix-server-runtime/routeModules.ts
  yarn.lock
Labels: CLA Signed

#4627 fix: Integration test for external redirects
  contributors.yml
  integration/redirects-test.ts
Labels: CLA Signed, package:server-runtime

#4699 Remove duped router in favor of @remix-run/router dependency
  .changeset/shy-zebras-march.md
  integration/fetcher-test.ts
  packages/remix-server-runtime/headers.ts
  packages/remix-server-runtime/package.json
  packages/remix-server-runtime/router/history.ts
  packages/remix-server-runtime/router/index.ts
  packages/remix-server-runtime/router/router.ts
  packages/remix-server-runtime/router/utils.ts
  packages/remix-server-runtime/routes.ts
  packages/remix-server-runtime/server.ts
  yarn.lock
Labels: CLA Signed

#4673 chore: add JSDoc deprecation to CJS exports
  .changeset/sharp-weeks-rush.md
  rollup.utils.js
Labels: CLA Signed

#4702 Bump remix to RR 6.4.4 and drop history dependency
  packages/remix-react/__tests__/transition-test.tsx
  packages/remix-react/browser.tsx
  packages/remix-react/components.tsx
  packages/remix-react/errorBoundaries.tsx
  packages/remix-react/links.ts
  packages/remix-react/package.json
  packages/remix-react/routeMatching.ts
  packages/remix-react/routeModules.ts
  packages/remix-react/server.tsx
  packages/remix-react/transition.ts
  packages/remix-server-runtime/routeModules.ts
  yarn.lock
Labels: CLA Signed

#4669 RRR Step 2 - Server Rendering
  packages/remix-dev/cli/commands.ts
  packages/remix-react/components.tsx
  packages/remix-react/data.ts
  packages/remix-react/entry.ts
  packages/remix-react/errorBoundaries.tsx
  packages/remix-react/index.tsx
  packages/remix-react/links.ts
  packages/remix-react/routeMatching.ts
  packages/remix-react/routes.tsx
  packages/remix-react/server.tsx
  packages/remix-react/transition.ts
  packages/remix-server-runtime/entry.ts
  packages/remix-server-runtime/headers.ts
  packages/remix-server-runtime/package.json
  packages/remix-server-runtime/routeMatching.ts
  packages/remix-server-runtime/routeModules.ts
  packages/remix-server-runtime/router/history.ts
  packages/remix-server-runtime/router/index.ts
  packages/remix-server-runtime/router/router.ts
  packages/remix-server-runtime/router/utils.ts
  packages/remix-server-runtime/routes.ts
  packages/remix-server-runtime/server.ts
Labels: CLA Signed

#4709 fix(remix-dev): convert `config.appDirectory` to relative unix path
  packages/remix-dev/__tests__/migrations/convert-to-javascript-test.ts
  packages/remix-dev/cli/migrate/migrations/convert-to-javascript/index.ts
Labels: CLA Signed, package:dev

#4718 chore: add changeset for #4709
  .changeset/weak-beds-thank.md
Labels: CLA Signed

#4715 ci: add typechecking for deno
  .changeset/clean-clocks-float.md
  .github/workflows/reusable-test.yml
  .vscode/deno_resolve_npm_imports.json
  packages/remix-deno/server.ts
  scripts/build.mjs
Labels: CLA Signed, feat:typescript, feat:deno, runtime:deno

#4720 Update to @remix-run/router stable 1.0.4 release
  .changeset/wicked-falcons-approve.md
  packages/remix-server-runtime/package.json
  yarn.lock
Labels: CLA Signed

#4684 docs: fix `useActionData`/`useLoaderData` usage
  docs/api/conventions.md
  docs/api/remix.md
  docs/guides/api-routes.md
  docs/guides/bff.md
  docs/guides/constraints.md
  docs/guides/data-loading.md
  docs/guides/data-writes.md
  docs/guides/envvars.md
  docs/guides/mdx.md
  docs/guides/not-found.md
  docs/guides/optimistic-ui.md
  docs/guides/resource-routes.md
  docs/guides/routing.md
  docs/guides/styling.md
  docs/other-api/serve.md
  docs/pages/faq.md
  docs/pages/philosophy.md
  docs/pages/technical-explanation.md
  docs/tutorials/blog.md
  docs/tutorials/jokes.md
Labels: CLA Signed, docs

#4723 docs: fix code highlighting
  docs/guides/data-writes.md
  docs/guides/optimistic-ui.md
Labels: CLA Signed, docs

#4725 fix: Firefox LiveReload
  .changeset/thin-oranges-boil.md
  packages/remix-react/components.tsx
Labels: CLA Signed
