Repository remix-run/remix, pull requests merged in 2022-03, with the labels that each got.

#1428 docs(examples): GDPR Cookie Consent
  examples/gdpr-cookie-consent/.gitignore
  examples/gdpr-cookie-consent/README.md
  examples/gdpr-cookie-consent/app/cookies.ts
  examples/gdpr-cookie-consent/app/entry.client.tsx
  examples/gdpr-cookie-consent/app/entry.server.tsx
  examples/gdpr-cookie-consent/app/root.tsx
  examples/gdpr-cookie-consent/app/routes/enable-analytics.tsx
  examples/gdpr-cookie-consent/app/routes/index.tsx
  examples/gdpr-cookie-consent/package-lock.json
  examples/gdpr-cookie-consent/package.json
  examples/gdpr-cookie-consent/public/dummy-analytics-script.js
  examples/gdpr-cookie-consent/public/favicon.ico
  examples/gdpr-cookie-consent/remix.config.js
  examples/gdpr-cookie-consent/remix.env.d.ts
  examples/gdpr-cookie-consent/tsconfig.json
Labels: CLA Signed

#1970 fix: include createArcTableSessionStorage in remix exports
  rollup.config.js
Labels: CLA Signed

#2182 fix(remix): export a type so that remix/index.d.ts is not empty
  packages/remix/index.ts
Labels: CLA Signed

#2181 fix(create-remix): express template docs and move npm-run-all to devDependencies
  packages/create-remix/templates/express/README.md
  packages/create-remix/templates/express/package.json
Labels: CLA Signed

#2103 chore: remove `dotenv` references
  docs/tutorials/jokes.md
  examples/bullmq-task-queue/package-lock.json
  examples/bullmq-task-queue/package.json
  examples/file-and-cloudinary-upload/package-lock.json
  examples/file-and-cloudinary-upload/package.json
  examples/form-to-notion-db/README.md
  examples/form-to-notion-db/package-lock.json
  examples/form-to-notion-db/package.json
  examples/ioredis/package-lock.json
  examples/ioredis/package.json
  examples/redis-upstash-session/package-lock.json
  examples/redis-upstash-session/package.json
  examples/remix-auth-auth0/package-lock.json
  examples/remix-auth-auth0/package.json
  examples/remix-auth-supabase/package-lock.json
  examples/remix-auth-supabase/package.json
  examples/sanity/app/entry.server.jsx
  examples/sanity/package.json
  examples/sanity/yarn.lock
  packages/create-remix/templates/fly-stack/package.json
Labels: CLA Signed

#2193 docs(jokes): add example code to test error boundaries
  contributors.yml
  docs/tutorials/jokes.md
Labels: CLA Signed

#2185 chore(CI): update workflow action versions
  .github/workflows/deployment-test.yml
  .github/workflows/format.yml
  .github/workflows/release-private.yml
  .github/workflows/release.yml
  .github/workflows/test.yml
  .github/workflows/website.yml
  packages/create-remix/templates/arc-stack/github/workflows/deploy.yml
  packages/create-remix/templates/fly-stack/github/workflows/deploy.production.yml
  packages/create-remix/templates/fly-stack/github/workflows/deploy.staging.yml
Labels: CLA Signed

#2196 docs(examples): remove `devServerPort` from `remix.config.js`
  docs/api/conventions.md
  examples/gdpr-cookie-consent/remix.config.js
  examples/graphql-api/remix.config.js
  examples/jokes/remix.config.js
  examples/remix-auth-supabase-github/remix.config.js
  examples/stitches/remix.config.js
  fixtures/gists-app/remix.config.js
Labels: CLA Signed

#2197 docs(create-remix): remove `devServerPort` from `remix.config.js` in templates
  packages/create-remix/templates/arc-stack/remix.config.js
  packages/create-remix/templates/arc/remix.config.js
  packages/create-remix/templates/cloudflare-pages/remix.config.js
  packages/create-remix/templates/cloudflare-workers/remix.config.js
  packages/create-remix/templates/deno/remix.config.js
  packages/create-remix/templates/express/remix.config.js
  packages/create-remix/templates/fly-stack/remix.config.js
  packages/create-remix/templates/fly/remix.config.js
  packages/create-remix/templates/netlify/remix.config.js
  packages/create-remix/templates/remix/remix.config.js
  packages/create-remix/templates/vercel/remix.config.js
Labels: CLA Signed

#2144 docs(examples): update Tailwind CSS example
  examples/tailwindcss/.eslintrc.js
  examples/tailwindcss/.gitignore
  examples/tailwindcss/app/entry.server.tsx
  examples/tailwindcss/app/root.tsx
  examples/tailwindcss/package.json
  examples/tailwindcss/remix.config.js
  examples/tailwindcss/sandbox.config.json
  examples/tailwindcss/tsconfig.json
Labels: CLA Signed

#2143 docs(styling): update Tailwind CSS docs
  docs/guides/styling.md
Labels: CLA Signed

#2212 docs(examples): simplify ESLint config for sanity example
  examples/multiple-params/.eslintrc.js
Labels: CLA Signed

#2194 chore: add local debugging logs for transition manager
  DEVELOPMENT.md
  babel.config.js
  package.json
  packages/remix-react/transition.ts
  yarn.lock
Labels: CLA Signed

#2225 docs(jokes): add missing form error message
  contributors.yml
  docs/tutorials/jokes.md
  examples/jokes/app/routes/jokes/new.tsx
Labels: CLA Signed

#2188 fix: keep fetcher in loading state during action submission redirect
  DEVELOPMENT.md
  docs/api/remix.md
  packages/remix-react/__tests__/transition-test.tsx
  packages/remix-react/transition.ts
Labels: CLA Signed

#2249 docs(tutorials/jokes): fix highlighted lines
  docs/tutorials/jokes.md
Labels: CLA Signed

#2250 chore(docs): Explicitly return `Response` in loader/action examples
  docs/api/conventions.md
  docs/api/remix.md
  docs/guides/api-routes.md
  docs/guides/constraints.md
  docs/guides/data-loading.md
  docs/guides/data-writes.md
  docs/guides/envvars.md
  docs/guides/mdx.md
  docs/guides/not-found.md
  docs/guides/optimistic-ui.md
  docs/guides/resource-routes.md
  docs/guides/styling.md
  docs/pages/faq.md
  docs/pages/gotchas.md
  docs/pages/philosophy.md
  docs/pages/technical-explanation.md
  docs/tutorials/blog.md
  docs/tutorials/jokes.md
  examples/jokes/app/routes/jokes.tsx
  examples/jokes/app/routes/jokes/$jokeId.tsx
  examples/jokes/app/routes/jokes/index.tsx
  examples/jokes/app/routes/jokes/new.tsx
Labels: CLA Signed

#2141 docs(example): Refactor bullmq task queue example
  examples/bullmq-task-queue/app/queues/notifier.server.ts
  examples/bullmq-task-queue/app/routes/index.tsx
  examples/bullmq-task-queue/app/utils/queue.server.ts
Labels: CLA Signed

#2269 test: added fixture test from Logan for fetcher resource routes
  integration/fetcher-test.ts
  integration/helpers/create-fixture.tsx
Labels: CLA Signed

#2286 docs: add remix stacks docs
  docs/pages/philosophy.md
  docs/pages/stacks.md
  docs/pages/technical-explanation.md
Labels: CLA Signed

#2291 fix(netlify): use Netlify internal functions dir
  packages/create-remix/templates/netlify/gitignore
  packages/create-remix/templates/netlify/netlify.toml
  packages/create-remix/templates/netlify/remix.config.js
  packages/remix-dev/config.ts
Labels: CLA Signed

#2035 docs(examples): add stripe payment integration example
  examples/stripe-integration/.env.sample
  examples/stripe-integration/.gitignore
  examples/stripe-integration/README.md
  examples/stripe-integration/app/entry.client.tsx
  examples/stripe-integration/app/entry.server.tsx
  examples/stripe-integration/app/root.tsx
  examples/stripe-integration/app/routes/api/stripe-web-hook.tsx
  examples/stripe-integration/app/routes/buy.tsx
  examples/stripe-integration/app/routes/payment/cancelled.tsx
  examples/stripe-integration/app/routes/payment/success.tsx
  examples/stripe-integration/app/utils/stripe.server.tsx
  examples/stripe-integration/package-lock.json
  examples/stripe-integration/package.json
  examples/stripe-integration/public/favicon.ico
  examples/stripe-integration/remix.config.js
  examples/stripe-integration/remix.env.d.ts
  examples/stripe-integration/tsconfig.json
Labels: CLA Signed, needs-response

#2260 docs(examples): explicitly return `Response` in `action`/`loader`
  examples/basic/app/routes/demos/params/$id.tsx
  examples/blog-tutorial/app/routes/admin.tsx
  examples/blog-tutorial/app/routes/demos/params/$id.tsx
  examples/blog-tutorial/app/routes/posts/$slug.tsx
  examples/blog-tutorial/app/routes/posts/index.tsx
  examples/client-side-validation/app/root.tsx
  examples/dataloader/app/routes/users.tsx
  examples/dataloader/app/routes/users/index.tsx
  examples/gdpr-cookie-consent/app/root.tsx
  examples/graphql-api/app/routes/api/character.tsx
  examples/graphql-api/app/routes/api/characters.tsx
  examples/graphql-api/app/routes/character/$id.tsx
  examples/graphql-api/app/routes/character/error.tsx
  examples/newsletter-signup/app/routes/newsletter.tsx
  examples/nprogress/app/routes/slow-page.tsx
  examples/pm-app/app/root.tsx
  examples/pm-app/app/routes/dashboard.tsx
  examples/pm-app/app/routes/dashboard/index.tsx
  examples/pm-app/app/routes/dashboard/projects/new.tsx
  examples/pm-app/app/routes/dashboard/todo-lists/index.tsx
  examples/pm-app/app/routes/dashboard/todo-lists/new.tsx
  examples/pm-app/app/routes/dashboard/todos/index.tsx
  examples/pm-app/app/routes/register.tsx
  examples/pm-app/app/routes/sign-in.tsx
  examples/quirrel/app/routes/index.tsx
  examples/remix-auth-supabase-github/app/root.tsx
  examples/routes-gen/app/routes/products/index.tsx
  examples/rust/app/routes/index.tsx
  examples/sanity/app/routes/$slug.jsx
  examples/sanity/app/routes/index.jsx
  examples/sharing-loader-data/app/routes/workshops/$workshopId.tsx
  examples/strapi/app/routes/index.tsx
  examples/usematches-loader-data/app/root.tsx
Labels: CLA Signed

#2301 chore: update remix-dev and remix-serve start message
  packages/remix-dev/cli/commands.ts
  packages/remix-serve/cli.ts
Labels: CLA Signed

#2314 fix(templates): bring in line with each other
  templates/arc-ts/.gitignore
  templates/arc/.gitignore
  templates/arc/remix.config.js
  templates/cloudflare-pages-ts/.gitignore
  templates/cloudflare-pages-ts/package.json
  templates/cloudflare-pages/.gitignore
  templates/cloudflare-pages/package.json
  templates/cloudflare-pages/remix.config.js
  templates/cloudflare-workers-ts/.gitignore
  templates/cloudflare-workers-ts/package.json
  templates/cloudflare-workers/.gitignore
  templates/cloudflare-workers/package.json
  templates/cloudflare-workers/remix.config.js
  templates/deno-ts/.gitignore
  templates/deno-ts/package.json
  templates/deno-ts/tsconfig.json
  templates/deno/package.json
  templates/deno/remix.config.js
  templates/express-ts/.gitignore
  templates/express-ts/package.json
  templates/express/.gitignore
  templates/express/package.json
  templates/express/remix.config.js
  templates/fly-ts/.gitignore
  templates/fly/.gitignore
  templates/fly/remix.config.js
  templates/netlify-ts/.gitignore
  templates/netlify-ts/package.json
  templates/netlify/.gitignore
  templates/netlify/package.json
  templates/netlify/remix.config.js
  templates/remix-ts/remix.config.js
  templates/remix/remix.config.js
  templates/vercel-ts/package.json
  templates/vercel/package.json
  templates/vercel/remix.config.js
Labels: CLA Signed

#2271 fix: disambiguate layout vs index route fetcher submissions
  integration/fetcher-layout-test.ts
  packages/remix-react/transition.ts
Labels: CLA Signed

#2316 Pedro/mime
  yarn.lock
Labels: CLA Signed

#2318 Autofix formatting in templates
  .eslintignore
  packages/remix-dev/compiler.ts
  templates/arc-ts/package.json
  templates/arc/package.json
  templates/cloudflare-pages-ts/package.json
  templates/cloudflare-pages/package.json
  templates/cloudflare-workers-ts/package.json
  templates/cloudflare-workers/package.json
  templates/express-ts/package.json
  templates/express-ts/server.js
  templates/express/package.json
  templates/express/server.js
  templates/fly-ts/package.json
  templates/fly/package.json
  templates/netlify-ts/package.json
  templates/netlify/package.json
  templates/remix-ts/package.json
  templates/remix/package.json
  templates/vercel-ts/package.json
  templates/vercel/package.json
Labels: CLA Signed

#2325 feat(remix-react): add support for `charset` in `meta` function
  packages/remix-react/components.tsx
  templates/arc-ts/app/root.tsx
  templates/arc/app/root.jsx
  templates/cloudflare-pages-ts/app/root.tsx
  templates/cloudflare-pages/app/root.jsx
  templates/cloudflare-workers-ts/app/root.tsx
  templates/cloudflare-workers/app/root.jsx
  templates/deno-ts/app/root.tsx
  templates/express-ts/app/root.tsx
  templates/express/app/root.jsx
  templates/fly-ts/app/root.tsx
  templates/fly/app/root.jsx
  templates/netlify-ts/app/root.tsx
  templates/netlify/app/root.jsx
  templates/remix-ts/app/root.tsx
  templates/remix/app/root.jsx
  templates/vercel-ts/app/root.tsx
  templates/vercel/app/root.jsx
Labels: CLA Signed

#2326 docs(templates/deno): mark deno template as experimental
  templates/deno-ts/README.md
Labels: CLA Signed

#2330 fix(create-remix): prevent npx querying to install remix dev
  packages/create-remix/cli.ts
Labels: CLA Signed

#2339 ci(deployment-test): switch to @remix-run/dev for deployment tests
  packages/remix-dev/__tests__/cli-test.ts
  scripts/deployment-test/arc.mjs
  scripts/deployment-test/cf-pages.mjs
  scripts/deployment-test/cf-workers.mjs
  scripts/deployment-test/fly.mjs
  scripts/deployment-test/netlify.mjs
  scripts/deployment-test/package-lock.json
  scripts/deployment-test/package.json
  scripts/deployment-test/vercel.mjs
  scripts/utils.js
Labels: CLA Signed

#2346 fix(remix-dev/create): move getRepoInfo check after example/template check
  packages/remix-dev/create.ts
Labels: CLA Signed

#2347 test(remix-dev/create): enable cli tests
  packages/remix-dev/__tests__/cli-test.ts
  packages/remix-dev/cli/commands.ts
Labels: CLA Signed

#2343 docs(examples): move `charset` & `viewport` to `meta` function
  examples/basic/app/root.tsx
  examples/blog-tutorial/app/root.tsx
  examples/bullmq-task-queue/app/root.tsx
  examples/catch-boundary/app/root.tsx
  examples/chakra-ui/app/root.tsx
  examples/client-only-components/app/root.tsx
  examples/client-side-validation/app/root.tsx
  examples/collected-notes/app/root.tsx
  examples/combobox-resource-route/app/root.tsx
  examples/dataloader/app/root.tsx
  examples/emotion/app/root.tsx
  examples/file-and-cloudinary-upload/app/root.tsx
  examples/form-to-notion-db/app/root.tsx
  examples/framer-motion/app/root.tsx
  examples/framer-route-animation/app/root.tsx
  examples/gdpr-cookie-consent/app/root.tsx
  examples/graphql-api/app/root.tsx
  examples/image-resize/app/root.tsx
  examples/io-ts-formdata-decoding/app/root.tsx
  examples/ioredis/app/root.tsx
  examples/jokes/app/root.tsx
  examples/mantine/app/root.tsx
  examples/msw/app/root.tsx
  examples/multiple-forms/app/root.tsx
  examples/multiple-params/app/root.tsx
  examples/newsletter-signup/app/root.tsx
  examples/nprogress/app/root.tsx
  examples/on-demand-hydration/app/root.tsx
  examples/outlet-form-rerender/app/root.tsx
  examples/pathless-routes/app/root.tsx
  examples/pm-app/app/root.tsx
  examples/quirrel/app/root.tsx
  examples/react-spring/app/root.tsx
  examples/redis-upstash-session/app/root.tsx
  examples/remix-auth-auth0/app/root.tsx
  examples/remix-auth-form/app/root.tsx
  examples/remix-auth-github/app/root.tsx
  examples/remix-auth-supabase-github/app/root.tsx
  examples/remix-auth-supabase/app/root.tsx
  examples/route-modal/app/root.tsx
  examples/routes-gen/app/root.tsx
  examples/rust/app/root.tsx
  examples/sanity/app/root.jsx
  examples/sanity/public/favicon.ico
  examples/sanity/public/favicon.png
  examples/sass/app/root.tsx
  examples/search-input/app/root.tsx
  examples/sharing-loader-data/app/root.tsx
  examples/socket.io/app/root.tsx
  examples/stitches/app/root.tsx
  examples/strapi/app/root.tsx
  examples/stripe-integration/app/root.tsx
  examples/styled-components/app/root.tsx
  examples/tailwindcss/app/root.tsx
  examples/template/app/root.tsx
  examples/toast-message/app/root.tsx
  examples/turborepo-vercel/apps/remix-app/app/root.tsx
  examples/usematches-loader-data/app/root.tsx
Labels: CLA Signed

#2351 fix(templates): remove `cross-env` references
  templates/arc-ts/package.json
  templates/arc/package.json
  templates/cloudflare-pages-ts/package.json
  templates/cloudflare-pages/package.json
  templates/cloudflare-workers-ts/package.json
  templates/cloudflare-workers/package.json
  templates/deno-ts/package.json
  templates/express-ts/package.json
  templates/express/package.json
  templates/fly-ts/package.json
  templates/fly/package.json
  templates/remix-ts/package.json
  templates/remix/package.json
  templates/vercel-ts/package.json
  templates/vercel/package.json
Labels: CLA Signed

#2345 docs: remove `charSet` `meta` tags
  docs/guides/disabling-javascript.md
  docs/guides/styling.md
  docs/tutorials/jokes.md
Labels: CLA Signed

#2312 chore: fix ESLint errors
  .eslintignore
  templates/deno-ts/.eslintrc.js
Labels: CLA Signed

#2328 docs(examples): fix `build` script of Tailwind example
  docs/guides/styling.md
  examples/tailwindcss/package.json
Labels: CLA Signed

#2297 docs(examples): bring `stripe-integration` example in line with templates
  examples/stripe-integration/.env.example
  examples/stripe-integration/.eslintrc.js
  examples/stripe-integration/.gitignore
  examples/stripe-integration/app/routes/api/stripe-web-hook.tsx
  examples/stripe-integration/app/routes/buy.tsx
  examples/stripe-integration/package.json
  examples/stripe-integration/remix.config.js
  examples/stripe-integration/tsconfig.json
Labels: CLA Signed

#2280 docs(examples): bring `msw` example in line with templates
  examples/msw/.eslintrc.js
  examples/msw/.gitignore
  examples/msw/package.json
  examples/msw/sandbox.config.json
  examples/msw/tsconfig.json
Labels: CLA Signed

#2251 docs(api/remix): fix highlighted lines
  docs/api/remix.md
Labels: CLA Signed

#2205 chore: remove `$` from command lines
  packages/create-remix/README.md
  packages/remix-architect/README.md
  packages/remix-cloudflare-pages/README.md
  packages/remix-cloudflare-workers/README.md
  packages/remix-dev/README.md
  packages/remix-express/README.md
  packages/remix-netlify/README.md
  packages/remix-node/README.md
  packages/remix-react/README.md
  packages/remix-serve/README.md
  packages/remix-server-runtime/README.md
  packages/remix-vercel/README.md
  packages/remix/README.md
Labels: CLA Signed

#2204 docs(examples/templates): remove `$` from command lines
  docs/other-api/dev.md
  examples/bullmq-task-queue/README.md
  examples/graphql-api/README.md
  examples/ioredis/README.md
  examples/redis-upstash-session/README.md
  templates/arc-ts/README.md
  templates/arc/README.md
  templates/cloudflare-pages-ts/README.md
  templates/cloudflare-pages/README.md
  templates/cloudflare-workers-ts/README.md
  templates/cloudflare-workers/README.md
  templates/netlify-ts/README.md
  templates/netlify/README.md
Labels: CLA Signed

#2164 chore: use `action` field instead of `_action`
  examples/multiple-forms/README.md
  examples/multiple-forms/app/routes/invitations.tsx
  integration/transition-test.ts
Labels: CLA Signed

#2145 chore(eslint-config): fix `repository` field in `package.json`
  packages/remix-eslint-config/package.json
Labels: CLA Signed

#2352 fix(templates): fix version of remix packages
  templates/arc-ts/package.json
  templates/arc/package.json
  templates/cloudflare-pages-ts/package.json
  templates/cloudflare-pages/package.json
  templates/cloudflare-workers-ts/package.json
  templates/cloudflare-workers/package.json
  templates/deno-ts/package.json
  templates/express-ts/package.json
  templates/express/package.json
  templates/fly-ts/package.json
  templates/fly/package.json
  templates/netlify-ts/package.json
  templates/netlify/package.json
  templates/remix-ts/package.json
  templates/remix/package.json
  templates/vercel-ts/package.json
  templates/vercel/package.json
Labels: CLA Signed

#2350 fix(remix-dev): improve message about init script
  packages/remix-dev/cli/commands.ts
Labels: CLA Signed

#2322 [@remix-run/remix-eslint-config] Include jest-testing-library.js
  contributors.yml
  packages/remix-eslint-config/package.json
Labels: CLA Signed

#2333 chore: update example and template package.json names to resolve 'jest-haste-map' warning
  .github/workflows/format.yml
  examples/graphql-api/package.json
  examples/msw/package.json
  examples/remix-auth-auth0/package.json
  examples/route-modal/package.json
  examples/routes-gen/package.json
  examples/rust/package.json
  examples/stitches/package.json
  examples/stripe-integration/package.json
  examples/tailwindcss/package.json
  examples/usematches-loader-data/package.json
  jest.config.js
  packages/remix-dev/__tests__/cli-test.ts
  scripts/patchup-example-names.mjs
  templates/arc-ts/package.json
  templates/arc/package.json
  templates/cloudflare-pages-ts/package.json
  templates/cloudflare-pages/package.json
  templates/cloudflare-workers-ts/package.json
  templates/cloudflare-workers/package.json
  templates/deno-ts/package.json
  templates/express-ts/package.json
  templates/express/package.json
  templates/fly-ts/package.json
  templates/fly/package.json
  templates/netlify-ts/package.json
  templates/netlify/package.json
  templates/remix-ts/package.json
  templates/remix/package.json
  templates/vercel-ts/package.json
  templates/vercel/package.json
Labels: CLA Signed

#2357 Fix amusing typo (carrot -> caret) 🥕
  contributors.yml
  docs/pages/stacks.md
Labels: CLA Signed

#2362 feat(scripts): sort updated files in `patchup-example-names` script
  examples/emotion/package.json
  examples/msw/package.json
  examples/multiple-params/package.json
  examples/stripe-integration/package.json
  package.json
  scripts/patchup-example-names.mjs
Labels: CLA Signed

#2290 fix: check for private registry config
  packages/remix-dev/create.ts
Labels: CLA Signed

#2363 fix: update remix app server caching
  packages/remix-serve/index.ts
  templates/express-ts/server.js
  templates/express/server.js
Labels: CLA Signed

#2273 fix: typo in the word “tool”
  docs/guides/styling.md
Labels: CLA Signed, documentation

#2267 Fix typo in performance guide docs (it's -> its)
  contributors.yml
  docs/guides/performance.md
Labels: CLA Signed, documentation

#2310 Missing "json" import in Blog tutorial
  contributors.yml
  docs/tutorials/blog.md
Labels: CLA Signed, documentation

#2137 docs(examples): remove not allowed and unneeded div in blog example
  examples/blog-tutorial/app/routes/demos/actions.tsx
Labels: CLA Signed, documentation

#2329 docs(tutorials/jokes) - Fix delete files instructions
  contributors.yml
  docs/tutorials/jokes.md
Labels: CLA Signed, documentation

#2264 docs(jokes): Fix text description of validation
  contributors.yml
  docs/tutorials/jokes.md
Labels: CLA Signed, documentation

#623 `remix dev` - Custom port note
  contributors.yml
  docs/other-api/dev.md
Labels: CLA Signed, documentation

#2138 docs(tailwind): Add .gitignore to relevant files
  examples/tailwindcss/README.md
Labels: CLA Signed, examples: usage, documentation

#2369 docs(tutorials): mention stacks to avoid confusing new comers
  contributors.yml
  docs/tutorials/blog.md
  docs/tutorials/jokes.md
Labels: CLA Signed, documentation

#2355 docs(styling): remove `cross-env` references from Tailwind example
  docs/guides/styling.md
Labels: CLA Signed

#2375 chore: Cli cleanup
  packages/create-remix/cli.ts
  packages/create-remix/package.json
  packages/create-remix/tsconfig.json
  packages/remix-dev/cli.ts
  packages/remix-dev/cli/colors.ts
  packages/remix-dev/cli/commands.ts
  packages/remix-dev/cli/create.ts
  packages/remix-dev/cli/index.ts
  packages/remix-dev/cli/logging.ts
  packages/remix-dev/cli/run.ts
  packages/remix-dev/cli/setup.ts
  packages/remix-dev/compiler.ts
  packages/remix-dev/compiler/warnings.ts
  packages/remix-dev/index.ts
  rollup.config.js
  yarn.lock
Labels: CLA Signed

#2377 docs(useFormAction): delete is not a valid form method
  contributors.yml
  docs/api/remix.md
Labels: CLA Signed, documentation

#2296 docs: Clarify default mode used by remix build
  docs/guides/envvars.md
Labels: CLA Signed, documentation

#1534 docs(tutorial): Added import in Jokes tutorial
  contributors.yml
  docs/tutorials/jokes.md
Labels: CLA Signed, documentation

#2379 chore: use get-port in gists app
  fixtures/gists-app/package.json
  fixtures/gists-app/server.js
Labels: CLA Signed

#2282 Fixed Blog Tutorial Highlight
  contributors.yml
  docs/tutorials/blog.md
Labels: CLA Signed, documentation

#2380 docs(other-api/adapter): update adapters list
  docs/other-api/adapter.md
Labels: CLA Signed, documentation

#2381 docs(routing): remove TODO item from guide navigation
  contributors.yml
  docs/guides/routing.md
Labels: CLA Signed, documentation

#2220 docs(examples): add supabase realtime subscription example
  examples/supabase-subscription/.env.sample
  examples/supabase-subscription/.gitignore
  examples/supabase-subscription/README.md
  examples/supabase-subscription/app/entry.client.tsx
  examples/supabase-subscription/app/entry.server.tsx
  examples/supabase-subscription/app/root.tsx
  examples/supabase-subscription/app/routes/realtime.tsx
  examples/supabase-subscription/app/utils/supabaseClient.server.tsx
  examples/supabase-subscription/package-lock.json
  examples/supabase-subscription/package.json
  examples/supabase-subscription/public/favicon.ico
  examples/supabase-subscription/remix.config.js
  examples/supabase-subscription/remix.env.d.ts
  examples/supabase-subscription/tsconfig.json
Labels: CLA Signed, examples: usage

#2376 test: use shared puppeteer instance for tests
  fixtures/gists-app/jest/globalSetup.ts
  fixtures/gists-app/jest/globalTeardown.ts
  fixtures/gists-app/jest/setup.ts
  fixtures/gists-app/jest/setupAfterEnv.ts
  fixtures/gists-app/tests/utils.ts
  integration/helpers/global-setup.ts
  integration/helpers/setupAfterEnv.ts
  jest.config.js
  package.json
  packages/remix-dev/__tests__/cli-test.ts
  scripts/patchup-example-names.mjs
  yarn.lock
Labels: CLA Signed

#2353 docs(examples): update `.eslintrc`
  examples/basic/.eslintrc.js
  examples/blog-tutorial/.eslintrc.js
  examples/bullmq-task-queue/.eslintrc.js
  examples/catch-boundary/.eslintrc.js
  examples/chakra-ui/.eslintrc.js
  examples/client-only-components/.eslintrc.js
  examples/client-side-validation/.eslintrc.js
  examples/collected-notes/.eslintrc.js
  examples/combobox-resource-route/.eslintrc.js
  examples/dataloader/.eslintrc.js
  examples/emotion/.eslintrc.js
  examples/file-and-cloudinary-upload/.eslintrc.js
  examples/form-to-notion-db/.eslintrc.js
  examples/framer-motion/.eslintrc.js
  examples/framer-route-animation/.eslintrc.js
  examples/gdpr-cookie-consent/.eslintrc.js
  examples/graphql-api/.eslintrc.js
  examples/image-resize/.eslintrc.js
  examples/io-ts-formdata-decoding/.eslintrc.js
  examples/ioredis/.eslintrc.js
  examples/jokes/.eslintrc.js
  examples/mantine/.eslintrc.js
  examples/msw/.eslintrc.js
  examples/multiple-forms/.eslintrc.js
  examples/multiple-params/.eslintrc.js
  examples/newsletter-signup/.eslintrc.js
  examples/nprogress/.eslintrc.js
  examples/on-demand-hydration/.eslintrc.js
  examples/outlet-form-rerender/.eslintrc.js
  examples/pathless-routes/.eslintrc.js
  examples/pm-app/.eslintrc.js
  examples/quirrel/.eslintrc.js
  examples/react-spring/.eslintrc.js
  examples/redis-upstash-session/.eslintrc.js
  examples/remix-auth-auth0/.eslintrc.js
  examples/remix-auth-form/.eslintrc.js
  examples/remix-auth-github/.eslintrc.js
  examples/remix-auth-supabase-github/.eslintrc.js
  examples/remix-auth-supabase/.eslintrc.js
  examples/route-modal/.eslintrc.js
  examples/routes-gen/.eslintrc.js
  examples/rust/.eslintrc.js
  examples/sanity/.eslintrc.js
  examples/sass/.eslintrc.js
  examples/search-input/.eslintrc.js
  examples/sharing-loader-data/.eslintrc.js
  examples/socket.io/.eslintrc.js
  examples/stitches/.eslintrc.js
  examples/strapi/.eslintrc.js
  examples/stripe-integration/.eslintrc.js
  examples/styled-components/.eslintrc.js
  examples/tailwindcss/.eslintrc.js
  examples/template/.eslintrc.js
  examples/toast-message/.eslintrc.js
  examples/turborepo-vercel/apps/remix-app/.eslintrc.js
  examples/usematches-loader-data/.eslintrc.js
Labels: CLA Signed

#1982 chore: update config.yml; add more community remix official resource links
  .github/ISSUE_TEMPLATE/config.yml
  contributors.yml
Labels: CLA Signed, documentation

#2392 docs(examples): bring `supabase-subscription` in line with template
  examples/supabase-subscription/.env.example
  examples/supabase-subscription/.eslintrc.js
  examples/supabase-subscription/.gitignore
  examples/supabase-subscription/README.md
  examples/supabase-subscription/app/root.tsx
  examples/supabase-subscription/app/routes/realtime.tsx
  examples/supabase-subscription/app/utils/supabaseClient.server.tsx
  examples/supabase-subscription/package-lock.json
  examples/supabase-subscription/package.json
  examples/supabase-subscription/remix.config.js
  examples/supabase-subscription/sandbox.config.json
  examples/supabase-subscription/tsconfig.json
Labels: CLA Signed

#2393 docs(examples): use typed `meta` function in TS files
  examples/basic/app/routes/demos/actions.tsx
  examples/basic/app/routes/demos/params.tsx
  examples/blog-tutorial/app/routes/demos/actions.tsx
  examples/blog-tutorial/app/routes/demos/params.tsx
Labels: CLA Signed, documentation

#2396 docs(examples/framer-motion): Fix wrong codesandbox link on README.md
  contributors.yml
  examples/framer-motion/README.md
Labels: CLA Signed, examples: usage

#2406 docs(styling): fix broken link in CSS preprocessor section
  contributors.yml
  docs/guides/styling.md
Labels: CLA Signed, documentation

#2398 docs: typo in data-writes
  contributors.yml
  docs/guides/data-writes.md
Labels: CLA Signed, documentation

#1761 docs(jokes): Adding missing line numbers from auth source update
  docs/tutorials/jokes.md
Labels: CLA Signed, documentation

#2395 docs(jokes): Add missing highlight of updated lines
  contributors.yml
  docs/tutorials/jokes.md
Labels: CLA Signed, documentation

#2342 feat: send 405 not 500 for missing action and surface in CatchBoundary
  integration/catch-boundary-data-test.ts
  integration/catch-boundary-test.ts
  packages/remix-react/routes.tsx
  packages/remix-react/transition.ts
  packages/remix-server-runtime/__tests__/server-test.ts
  packages/remix-server-runtime/data.ts
Labels: CLA Signed

#2370 feat: revalidate on redirect if cookies were set
  integration/set-cookie-revalidation-test.ts
  packages/remix-react/routes.tsx
  packages/remix-react/transition.ts
  packages/remix-server-runtime/server.ts
Labels: CLA Signed, feat:cookies

#2420 docs(example): Fix broken CodeSandbox url in `collected-notes` example
  contributors.yml
  examples/collected-notes/README.md
Labels: CLA Signed, documentation

#2411 fix: Keep empty meta from rendering a tag
  fixtures/gists-app/app/routes/meta.tsx
  fixtures/gists-app/tests/meta-test.ts
  packages/remix-react/components.tsx
  packages/remix-react/routeModules.ts
  packages/remix-server-runtime/routeModules.ts
Labels: CLA Signed

#2436 docs: fix typo
  DEVELOPMENT.md
  contributors.yml
Labels: CLA Signed, documentation

#2431 fix(create-remix): don't require "create" command
  packages/create-remix/cli.ts
Labels: CLA Signed

#1661 docs(examples): add dark mode example
  examples/dark-mode/.gitignore
  examples/dark-mode/README.md
  examples/dark-mode/app/entry.client.tsx
  examples/dark-mode/app/entry.server.tsx
  examples/dark-mode/app/root.tsx
  examples/dark-mode/app/routes/action/set-theme.tsx
  examples/dark-mode/app/routes/index.tsx
  examples/dark-mode/app/styles/styles.css
  examples/dark-mode/app/utils/theme-provider.tsx
  examples/dark-mode/app/utils/theme.server.ts
  examples/dark-mode/package-lock.json
  examples/dark-mode/package.json
  examples/dark-mode/public/favicon.ico
  examples/dark-mode/remix.config.js
  examples/dark-mode/remix.env.d.ts
  examples/dark-mode/tsconfig.json
Labels: CLA Signed, needs-response

#2438 chore(tests): Assert that apps without an ErrorBoundary renders internal boundary
  integration/errory-boundary-test.ts
Labels: CLA Signed

#2374 feat: add getDependenciesToBundle to @remix-run/dev
  packages/remix-dev/compiler.ts
  packages/remix-dev/compiler/dependencies.ts
  packages/remix-dev/index.ts
  packages/remix-dev/package.json
  yarn.lock
Labels: CLA Signed

#2443 docs(examples): bring dark mode example in line with templates
  examples/dark-mode/.eslintrc.js
  examples/dark-mode/.gitignore
  examples/dark-mode/app/root.tsx
  examples/dark-mode/app/routes/index.tsx
  examples/dark-mode/package-lock.json
  examples/dark-mode/remix.config.js
  examples/dark-mode/sandbox.config.json
  examples/dark-mode/tsconfig.json
Labels: CLA Signed, examples: usage

#2447 ci: re-use arc app
  scripts/deployment-test/arc.mjs
  scripts/deployment-test/package.json
Labels: CLA Signed

#2451 test(integration): convert `meta` tests
  fixtures/gists-app/app/routes/meta.tsx
  fixtures/gists-app/tests/meta-test.ts
  integration/meta-test.ts
  packages/remix-dev/__tests__/readConfig-test.ts
Labels: CLA Signed

#2285 docs(examples): make Stitches example render properly the SSR pass
  contributors.yml
  examples/stitches/app/entry.server.tsx
  examples/stitches/app/root.tsx
  examples/stitches/app/routes/index.tsx
  examples/stitches/app/styles/server.context.ts
Labels: CLA Signed, examples

#2331 feat(remix-react): add support for `http-equiv` in `meta` function
  docs/api/conventions.md
  docs/api/remix.md
  integration/meta-test.ts
  packages/remix-react/components.tsx
  packages/remix-react/routeModules.ts
  packages/remix-server-runtime/routeModules.ts
Labels: CLA Signed, package:react

#2449 docs(examples): add Google Analytics example
  examples/google-analytics/.gitignore
  examples/google-analytics/README.md
  examples/google-analytics/app/entry.client.tsx
  examples/google-analytics/app/entry.server.tsx
  examples/google-analytics/app/root.tsx
  examples/google-analytics/app/routes/contact.tsx
  examples/google-analytics/app/routes/dashboard.tsx
  examples/google-analytics/app/routes/index.tsx
  examples/google-analytics/app/routes/profile.tsx
  examples/google-analytics/app/utils/gtags.client.ts
  examples/google-analytics/package.json
  examples/google-analytics/public/favicon.ico
  examples/google-analytics/remix.config.js
  examples/google-analytics/remix.env.d.ts
  examples/google-analytics/tsconfig.json
Labels: CLA Signed, examples

#2482 docs(examples): bring `google-analytics` example in line with templates
  examples/google-analytics/.eslintrc.js
  examples/google-analytics/app/root.tsx
  examples/google-analytics/app/routes/contact.tsx
  examples/google-analytics/app/routes/dashboard.tsx
  examples/google-analytics/app/routes/index.tsx
  examples/google-analytics/app/routes/profile.tsx
  examples/google-analytics/package.json
  examples/google-analytics/remix.config.js
Labels: CLA Signed, needs-response, examples

#2484 docs(tutorials): improve blog tutorial TS support
  contributors.yml
  docs/tutorials/blog.md
Labels: CLA Signed, documentation

#2107 docs(examples): add infinite scrolling example
  contributors.yml
  examples/infinite-scrolling/.gitignore
  examples/infinite-scrolling/README.md
  examples/infinite-scrolling/app/entry.client.tsx
  examples/infinite-scrolling/app/entry.server.tsx
  examples/infinite-scrolling/app/root.tsx
  examples/infinite-scrolling/app/routes/index.tsx
  examples/infinite-scrolling/app/routes/offset/advanced.tsx
  examples/infinite-scrolling/app/routes/offset/simple.tsx
  examples/infinite-scrolling/app/routes/page/advanced.tsx
  examples/infinite-scrolling/app/routes/page/alternative.tsx
  examples/infinite-scrolling/app/routes/page/simple.tsx
  examples/infinite-scrolling/app/styles/index.css
  examples/infinite-scrolling/app/utils/backend.server.ts
  examples/infinite-scrolling/package-lock.json
  examples/infinite-scrolling/package.json
  examples/infinite-scrolling/public/favicon.ico
  examples/infinite-scrolling/remix.config.js
  examples/infinite-scrolling/remix.env.d.ts
  examples/infinite-scrolling/tsconfig.json
Labels: CLA Signed, needs-response, examples

#2486 docs(examples): bring `infinite-scrolling` example in line with templates
  examples/infinite-scrolling/.eslintrc.js
  examples/infinite-scrolling/.gitignore
  examples/infinite-scrolling/app/root.tsx
  examples/infinite-scrolling/app/routes/offset/advanced.tsx
  examples/infinite-scrolling/app/routes/offset/simple.tsx
  examples/infinite-scrolling/app/routes/page/advanced.tsx
  examples/infinite-scrolling/app/routes/page/alternative.tsx
  examples/infinite-scrolling/app/routes/page/simple.tsx
  examples/infinite-scrolling/package-lock.json
  examples/infinite-scrolling/package.json
  examples/infinite-scrolling/remix.config.js
  examples/infinite-scrolling/tsconfig.json
Labels: CLA Signed, examples

#2496 chore: Use `remix setup cloudflare` for CF templates
  templates/cloudflare-pages-ts/package.json
  templates/cloudflare-pages/package.json
  templates/cloudflare-workers-ts/package.json
  templates/cloudflare-workers/package.json
Labels: CLA Signed

#2493 fix(remix-dev): add missing deps that got removed during a rebase
  .github/workflows/test.yml
  packages/remix-architect/magicExports/remix.ts
  packages/remix-cloudflare-pages/package.json
  packages/remix-cloudflare/magicExports/remix.ts
  packages/remix-dev/cli/commands.ts
  packages/remix-dev/compiler/shims/react.ts
  packages/remix-dev/package.json
  packages/remix-eslint-config/index.js
  packages/remix-eslint-config/internal.js
  packages/remix-node/magicExports/remix.ts
  packages/remix-react/magicExports/remix.ts
  packages/remix-server-runtime/magicExports/remix.ts
  yarn.lock
Labels: CLA Signed, package:dev

#2415 feat(remix-dev,remix-serve): Allow specifying HOST environment variable
  contributors.yml
  packages/remix-dev/cli/commands.ts
  packages/remix-serve/cli.ts
Labels: CLA Signed

#2499 docs(examples/jokes): add validation to prevent open redirect on login
  contributors.yml
  docs/tutorials/jokes.md
  examples/jokes/app/routes/login.tsx
Labels: CLA Signed, examples

#2454 test(integration): represent real app in `app/root.jsx`
  integration/catch-boundary-data-test.ts
  integration/catch-boundary-test.ts
  integration/error-boundary-test.ts
  integration/headers-test.ts
  integration/loader-test.ts
  integration/prefetch-test.ts
  integration/rendering-test.ts
  integration/set-cookie-revalidation-test.ts
  integration/splat-routes-test.ts
  integration/transition-test.ts
Labels: CLA Signed

#2510 fix(docs/tutorials): fix highlighted code lines in Jokes tutorial
  contributors.yml
  docs/tutorials/jokes.md
Labels: CLA Signed, documentation

#2514 fix: deno template adjustments
  templates/deno-ts/README.md
  templates/deno-ts/remix-deno/crypto.ts
  templates/deno-ts/remix-deno/implementations.ts
  templates/deno-ts/remix-deno/index.ts
  templates/deno-ts/remix-deno/server.ts
  templates/deno-ts/remix-deno/sessions/fileStorage.ts
  templates/deno-ts/server.ts
Labels: CLA Signed

#2515 fix(docs/tutorials): fix typo in blog tutorial
  contributors.yml
  docs/tutorials/blog.md
Labels: CLA Signed, documentation

#2516 chore(examples): fix ESLint errors & warnings
  docs/tutorials/blog.md
  examples/blog-tutorial/.eslintrc.js
  examples/blog-tutorial/README.md
  examples/infinite-scrolling/app/routes/page/advanced.tsx
  examples/stitches/app/entry.server.tsx
Labels: CLA Signed, examples

#2507 fix(remix-dev): avoid setting blank Authorization header in `isRemixTemplate` functions
  contributors.yml
  packages/remix-dev/cli/create.ts
Labels: CLA Signed, package:dev

#2155 feat(remix-server-runtime): throw error when cookie limit is reached
  contributors.yml
  packages/remix-server-runtime/__tests__/sessions-test.ts
  packages/remix-server-runtime/sessions/cookieStorage.ts
Labels: CLA Signed, feat:cookies, feat:dx, package:server-runtime

#2525 fix(cli): stop CLI from logging full stack trace on known errors
  packages/create-remix/cli.ts
Labels: CLA Signed

#2531 fix(remix-react): use `.flat().map()` instead of `flatMap` in `Meta` component
  packages/remix-react/components.tsx
Labels: CLA Signed, package:react

#2541 docs(conventions): update `entry.client.tsx` example to be in line with templates
  docs/api/conventions.md
Labels: CLA Signed, documentation

#2545 chore(examples): add `sandbox.config.json` again to `blog` example
  examples/blog-tutorial/sandbox.config.json
Labels: CLA Signed, examples

#2527 feat: nightly releases
  .github/workflows/release-comments.yml
  .github/workflows/release.yml
  package.json
  scripts/release/comment.mjs
  scripts/release/constants.mjs
  scripts/release/octokit.mjs
  yarn.lock
Labels: CLA Signed

#2500 fix(remix-dev/cli): Remove excess fetching and improve error handling
  packages/remix-dev/__tests__/cli-test.ts
  packages/remix-dev/cli/commands.ts
  packages/remix-dev/cli/create.ts
  packages/remix-dev/cli/run.ts
  packages/remix-dev/package.json
Labels: CLA Signed, package:dev

#1811 docs(examples): add Firebase Auth + Firestore example
  contributors.yml
  examples/firebase-auth-firestore/.env.example
  examples/firebase-auth-firestore/.gitignore
  examples/firebase-auth-firestore/README.md
  examples/firebase-auth-firestore/app/entry.client.tsx
  examples/firebase-auth-firestore/app/entry.server.tsx
  examples/firebase-auth-firestore/app/root.tsx
  examples/firebase-auth-firestore/app/routes/index.tsx
  examples/firebase-auth-firestore/app/routes/join.tsx
  examples/firebase-auth-firestore/app/routes/login.tsx
  examples/firebase-auth-firestore/app/routes/logout.tsx
  examples/firebase-auth-firestore/app/server/auth.server.ts
  examples/firebase-auth-firestore/app/server/db.server.ts
  examples/firebase-auth-firestore/app/server/firebase.server.ts
  examples/firebase-auth-firestore/app/sessions.ts
  examples/firebase-auth-firestore/package-lock.json
  examples/firebase-auth-firestore/package.json
  examples/firebase-auth-firestore/public/favicon.ico
  examples/firebase-auth-firestore/remix.config.js
  examples/firebase-auth-firestore/remix.env.d.ts
  examples/firebase-auth-firestore/screen_recording.gif
  examples/firebase-auth-firestore/tsconfig.json
Labels: CLA Signed

#2568 docs(loader): remove section about returning plain objects
  docs/api/conventions.md
Labels: CLA Signed, documentation

#2403 fix(remix-react): add proper error-message if server-side code spills to client
  integration/server-code-in-browser-message-test.ts
  packages/remix-react/components.tsx
Labels: CLA Signed, feat:dx, package:react

#2065 fix(remix-dev): fix linked sourcemap to enabled breakpoints for debugging
  contributors.yml
  integration/helpers/create-fixture.tsx
  integration/server-source-maps-test.ts
  packages/remix-dev/compiler.ts
Labels: CLA Signed, package:dev, feat:dx

#2257 fix(remix-server-runtime): fix invalid character error in cookie serialize
  contributors.yml
  packages/remix-server-runtime/__tests__/cookies-test.ts
  packages/remix-server-runtime/cookies.ts
Labels: CLA Signed, feat:cookies, package:server-runtime

#2558 feat(remix-dev): added ESM only package warning to bundle
  integration/esm-only-warning-test.ts
  integration/helpers/create-fixture.tsx
  packages/remix-dev/cli/logging.ts
  packages/remix-dev/compiler.ts
  packages/remix-dev/compiler/plugins/serverBareModulesPlugin.ts
Labels: CLA Signed, package:dev

#1977 feat(remix-dev): support worker package exports for Cloudflare runtime
  integration/cf-compiler-test.ts
  integration/helpers/create-fixture.tsx
  packages/remix-dev/compiler.ts
Labels: CLA Signed, package:dev

#2569 chore: use external server for express template
  templates/express/.gitignore
  templates/express/package.json
  templates/express/remix.config.js
  templates/express/server.js
Labels: CLA Signed

#2573 chore: remove old `cloudflare` templates
  templates/cloudflare-pages-ts/package.json
  templates/cloudflare-workers-ts/package.json
Labels: CLA Signed, template:cloudflare-pages, template:cloudflare-workers

#2430 feat(remix-dev): add `codemod` command
  packages/remix-dev/__tests__/cli-test.ts
  packages/remix-dev/cli/check-git-status.ts
  packages/remix-dev/cli/codemod/index.ts
  packages/remix-dev/cli/codemod/questions.ts
  packages/remix-dev/cli/codemod/run/index.ts
  packages/remix-dev/cli/codemod/run/transforms/index.ts
  packages/remix-dev/cli/codemod/run/transforms/jscodeshift-transform.ts
  packages/remix-dev/cli/codemod/run/transforms/types.ts
  packages/remix-dev/cli/codemod/run/transforms/update-remix-imports/cleanup-package-json.ts
  packages/remix-dev/cli/codemod/run/transforms/update-remix-imports/get-jscodeshift-extra-options.ts
  packages/remix-dev/cli/codemod/run/transforms/update-remix-imports/index.ts
  packages/remix-dev/cli/codemod/run/transforms/update-remix-imports/jscodeshift-transform/get-new-import-declarations.ts
  packages/remix-dev/cli/codemod/run/transforms/update-remix-imports/jscodeshift-transform/get-remix-imports.ts
  packages/remix-dev/cli/codemod/run/transforms/update-remix-imports/jscodeshift-transform/index.ts
  packages/remix-dev/cli/codemod/run/transforms/update-remix-imports/jscodeshift-transform/map-normalized-imports/index.ts
  packages/remix-dev/cli/codemod/run/transforms/update-remix-imports/jscodeshift-transform/map-normalized-imports/package-exports.ts
  packages/remix-dev/cli/codemod/run/transforms/update-remix-imports/jscodeshift-transform/normalize-imports.ts
  packages/remix-dev/cli/codemod/run/validate-answers.ts
  packages/remix-dev/cli/codemod/transform-options.ts
  packages/remix-dev/cli/commands.ts
  packages/remix-dev/cli/run.ts
  packages/remix-dev/package.json
  rollup.config.js
  yarn.lock
Labels: CLA Signed, package:dev

#2574 chore(examples): update `entry.server.tsx` to be in line with templates
  docs/api/conventions.md
  docs/guides/styling.md
  examples/jokes/app/entry.server.tsx
  examples/pm-app/app/entry.server.tsx
  examples/sanity/app/entry.server.jsx
  examples/styled-components/app/entry.server.tsx
  fixtures/gists-app/app/entry.server.jsx
  templates/deno/app/entry.server.tsx
Labels: CLA Signed, examples, documentation
