Repository remix-run/remix, pull requests merged in 2022-04, with the labels that each got.

#2576 fix(remix-dev): add runtime to `package.json` in `update-remix-imports` codemod
  packages/remix-dev/cli/codemod/run/transforms/update-remix-imports/cleanup-package-json.ts
  packages/remix-dev/cli/codemod/run/transforms/update-remix-imports/get-jscodeshift-extra-options.ts
  packages/remix-dev/cli/codemod/run/transforms/update-remix-imports/index.ts
Labels: CLA Signed, package:dev

#2530 feat(cloudflare+cloudflare-pages+cloudflare-workers+templates): add support for `@cloudflare/workers-types` v3
  packages/remix-cloudflare-pages/package.json
  packages/remix-cloudflare-pages/tsconfig.json
  packages/remix-cloudflare-workers/package.json
  packages/remix-cloudflare-workers/tsconfig.json
  packages/remix-cloudflare/package.json
  packages/remix-cloudflare/tsconfig.json
  templates/cloudflare-pages/package.json
  templates/cloudflare-workers/package.json
  yarn.lock
Labels: CLA Signed, needs-response, adapter:cloudflare-pages, adapter:cloudflare-workers, template:cloudflare-pages, template:cloudflare-workers, runtime:cloudflare

#2579 docs(blog): remove any type to correlate to docs where it says "TypeScript is mad"
  contributors.yml
  docs/tutorials/blog.md
Labels: CLA Signed, documentation

#2583 docs(examples): bring `firebase-auth-firestore` example in line with templates
  examples/firebase-auth-firestore/.env.example
  examples/firebase-auth-firestore/.eslintrc.js
  examples/firebase-auth-firestore/.gitignore
  examples/firebase-auth-firestore/app/root.tsx
  examples/firebase-auth-firestore/package-lock.json
  examples/firebase-auth-firestore/package.json
  examples/firebase-auth-firestore/remix.config.js
  examples/firebase-auth-firestore/sandbox.config.json
  examples/firebase-auth-firestore/tsconfig.json
Labels: CLA Signed, examples

#2587 refactor(remix-dev): `migrate` command instead of `codemod`
  packages/remix-dev/__tests__/cli-test.ts
  packages/remix-dev/cli/codemod/run/transforms/index.ts
  packages/remix-dev/cli/codemod/transform-options.ts
  packages/remix-dev/cli/commands.ts
  packages/remix-dev/cli/migrate/index.ts
  packages/remix-dev/cli/migrate/migration-options.ts
  packages/remix-dev/cli/migrate/questions.ts
  packages/remix-dev/cli/migrate/run/index.ts
  packages/remix-dev/cli/migrate/run/transforms/index.ts
  packages/remix-dev/cli/migrate/run/transforms/jscodeshift-transform.ts
  packages/remix-dev/cli/migrate/run/transforms/replace-remix-imports/cleanup-package-json.ts
  packages/remix-dev/cli/migrate/run/transforms/replace-remix-imports/get-jscodeshift-extra-options.ts
  packages/remix-dev/cli/migrate/run/transforms/replace-remix-imports/index.ts
  packages/remix-dev/cli/migrate/run/transforms/replace-remix-imports/jscodeshift-transform/get-new-import-declarations.ts
  packages/remix-dev/cli/migrate/run/transforms/replace-remix-imports/jscodeshift-transform/get-remix-imports.ts
  packages/remix-dev/cli/migrate/run/transforms/replace-remix-imports/jscodeshift-transform/index.ts
  packages/remix-dev/cli/migrate/run/transforms/replace-remix-imports/jscodeshift-transform/map-normalized-imports/index.ts
  packages/remix-dev/cli/migrate/run/transforms/replace-remix-imports/jscodeshift-transform/map-normalized-imports/package-exports.ts
  packages/remix-dev/cli/migrate/run/transforms/replace-remix-imports/jscodeshift-transform/normalize-imports.ts
  packages/remix-dev/cli/migrate/run/transforms/types.ts
  packages/remix-dev/cli/migrate/run/validate-answers.ts
  packages/remix-dev/cli/run.ts
  rollup.config.js
Labels: CLA Signed, package:dev

#2586 docs(routing): fix small typo
  docs/guides/routing.md
Labels: CLA Signed, documentation

#2575 chore(templates): run `replace-remix-imports` migration
  templates/arc/app/entry.client.tsx
  templates/arc/app/entry.server.tsx
  templates/arc/app/root.tsx
  templates/arc/package.json
  templates/cloudflare-pages/app/entry.client.tsx
  templates/cloudflare-pages/app/entry.server.tsx
  templates/cloudflare-pages/app/root.tsx
  templates/cloudflare-pages/package.json
  templates/cloudflare-workers/app/entry.client.tsx
  templates/cloudflare-workers/app/entry.server.tsx
  templates/cloudflare-workers/app/root.tsx
  templates/cloudflare-workers/package.json
  templates/express/app/entry.client.tsx
  templates/express/app/entry.server.tsx
  templates/express/app/root.tsx
  templates/express/package.json
  templates/fly/app/entry.client.tsx
  templates/fly/app/entry.server.tsx
  templates/fly/app/root.tsx
  templates/fly/package.json
  templates/netlify/app/entry.client.tsx
  templates/netlify/app/entry.server.tsx
  templates/netlify/app/root.tsx
  templates/netlify/package.json
  templates/remix/app/entry.client.tsx
  templates/remix/app/entry.server.tsx
  templates/remix/app/root.tsx
  templates/remix/package.json
  templates/vercel/app/entry.client.tsx
  templates/vercel/app/entry.server.tsx
  templates/vercel/app/root.tsx
  templates/vercel/package.json
Labels: CLA Signed, template:express, template:architect, template:vercel, template:cloudflare-pages, template:cloudflare-workers, template:fly, template:netlify, template:remix

#2561 docs(examples): fix typo in `framer-route-animation`
  contributors.yml
  examples/framer-route-animation/README.md
Labels: CLA Signed, needs-response, documentation

#2581 fix(remix-react): add missing hash when redirecting client side
  integration/transition-test.ts
  packages/remix-react/routes.tsx
Labels: CLA Signed, package:react

#2456 fix(remix-react): make `LiveReload` work for ports other than 8002
  packages/remix-react/components.tsx
Labels: CLA Signed, package:react

#1537 fix(remix-architect): set request URL scheme to `http` when running arc sandbox
  packages/remix-architect/server.ts
Labels: CLA Signed, adapter:architect

#2595 fix: validate content-type for request.formData()
  integration/form-data-test.ts
  packages/remix-node/fetch.ts
  packages/remix-node/parseMultipartFormData.ts
Labels: CLA Signed

#2495 fix(remix-architect,remix-node): don't parse multipart `formData` to string
  contributors.yml
  packages/remix-architect/server.ts
  packages/remix-node/parseMultipartFormData.ts
Labels: CLA Signed, adapter:architect, runtime:node

#2600 chore(test): Move `action` tests to `integration`
  integration/action-test.ts
  integration/assets/toupload.txt
  integration/assets/touploadtoobig.txt
  integration/gists-app/tests/actions-test.ts
Labels: CLA Signed

#2601 docs(examples): run `replace-remix-imports` migration on `turborepo-vercel` example
  examples/turborepo-vercel/apps/remix-app/package.json
Labels: CLA Signed, examples

#2617 docs(tutorial): improve a sentence in `blog-tutorial` README
  contributors.yml
  examples/blog-tutorial/README.md
Labels: CLA Signed, documentation

#2596 Docs: replace `remix` imports
  docs/api/conventions.md
  docs/guides/constraints.md
  docs/guides/data-loading.md
  docs/guides/data-writes.md
  docs/guides/disabling-javascript.md
  docs/guides/mdx.md
  docs/guides/not-found.md
  docs/guides/optimistic-ui.md
  docs/guides/resource-routes.md
  docs/guides/styling.md
  docs/other-api/dev.md
  docs/other-api/serve.md
  docs/pages/faq.md
  docs/pages/gotchas.md
  docs/pages/philosophy.md
  docs/tutorials/blog.md
  docs/tutorials/jokes.md
Labels: CLA Signed, documentation

#2630 Revert "docs: note about remix setup"
  docs/tutorials/blog.md
Labels: CLA Signed, documentation

#2631 fix(templates/vercel): fix dependencies
  templates/vercel/package.json
Labels: CLA Signed, template:vercel

#2613 refactor(remix-dev/cli): cleanup `migrate` command
  packages/remix-dev/cli/checkGitStatus.ts
  packages/remix-dev/cli/migrate/flags.ts
  packages/remix-dev/cli/migrate/index.ts
  packages/remix-dev/cli/migrate/jscodeshift.ts
  packages/remix-dev/cli/migrate/migration-options.ts
  packages/remix-dev/cli/migrate/migrations/index.ts
  packages/remix-dev/cli/migrate/migrations/replace-remix-imports/cleanupPackageJson.ts
  packages/remix-dev/cli/migrate/migrations/replace-remix-imports/getTransformOptions.ts
  packages/remix-dev/cli/migrate/migrations/replace-remix-imports/index.ts
  packages/remix-dev/cli/migrate/migrations/replace-remix-imports/transform/get-new-import-declarations.ts
  packages/remix-dev/cli/migrate/migrations/replace-remix-imports/transform/get-remix-imports.ts
  packages/remix-dev/cli/migrate/migrations/replace-remix-imports/transform/index.ts
  packages/remix-dev/cli/migrate/migrations/replace-remix-imports/transform/map-normalized-imports/index.ts
  packages/remix-dev/cli/migrate/migrations/replace-remix-imports/transform/map-normalized-imports/package-exports.ts
  packages/remix-dev/cli/migrate/migrations/replace-remix-imports/transform/normalize-imports.ts
  packages/remix-dev/cli/migrate/migrations/transforms.ts
  packages/remix-dev/cli/migrate/questions.ts
  packages/remix-dev/cli/migrate/resolveInput.ts
  packages/remix-dev/cli/migrate/run.ts
  packages/remix-dev/cli/migrate/run/index.ts
  packages/remix-dev/cli/migrate/run/transforms/index.ts
  packages/remix-dev/cli/migrate/run/transforms/replace-remix-imports/index.ts
  packages/remix-dev/cli/migrate/run/transforms/types.ts
  packages/remix-dev/cli/migrate/run/validate-answers.ts
  packages/remix-dev/cli/migrate/types.ts
  packages/remix-dev/cli/run.ts
  packages/remix-dev/package.json
  rollup.config.js
  yarn.lock
Labels: CLA Signed, package:dev

#2638 docs: run `replace-remix-imports` migration
  docs/guides/routing.md
Labels: CLA Signed, documentation

#2513 feat(remix-cloudflare-pages): add `GetLoadContextFunction` & `RequestHandler` types + remove `@remix-run/server-runtime` dependency
  packages/remix-cloudflare-pages/index.ts
  packages/remix-cloudflare-pages/package.json
  packages/remix-cloudflare-pages/worker.ts
  packages/remix-dev/cli/migrate/migrations/replace-remix-imports/transform/map-normalized-imports/package-exports.ts
Labels: CLA Signed, adapter:cloudflare-pages

#2637 refactor(remix-dev/cli): adhere to codestyle conventions
  packages/remix-dev/cli/migrate/migrations/replace-remix-imports/transform/getNewImportDeclarations.ts
  packages/remix-dev/cli/migrate/migrations/replace-remix-imports/transform/getRemixImports.ts
  packages/remix-dev/cli/migrate/migrations/replace-remix-imports/transform/index.ts
  packages/remix-dev/cli/migrate/migrations/replace-remix-imports/transform/mapNormalizedImports/index.ts
  packages/remix-dev/cli/migrate/migrations/replace-remix-imports/transform/mapNormalizedImports/packageExports.ts
  packages/remix-dev/cli/migrate/migrations/replace-remix-imports/transform/normalizeImports.ts
Labels: CLA Signed, package:dev

#2639 chore(examples): remove `remix` types from `pm-app` example
  examples/pm-app/typings/remix.d.ts
Labels: CLA Signed, examples

#2647 Update blog.md
  contributors.yml
  docs/tutorials/blog.md
Labels: CLA Signed

#2651 chore(test): Migrate `link` tests to integration
  integration/gists-app/tests/link-test.ts
  integration/helpers/create-fixture.tsx
  integration/link-test.ts
  temp.jsx
Labels: CLA Signed

#2635 feat(remix,remix-dev): warn if `remix setup` is called or if importing from `remix`
  packages/remix-dev/cli/checkGitStatus.ts
  packages/remix-dev/cli/commands.ts
  packages/remix-dev/cli/logging.ts
  packages/remix-dev/cli/migrate/run.ts
  packages/remix-dev/cli/run.ts
  packages/remix-dev/cli/setup.ts
  packages/remix-dev/colors.ts
  packages/remix-dev/compiler.ts
  packages/remix-dev/compiler/warnings.ts
  packages/remix-dev/logging.ts
  packages/remix/index.ts
Labels: CLA Signed, package:dev, package:remix

#2640 chore(examples): remove `postinstall` call from `Dockerfile` of `blog-tutorial` example
  examples/blog-tutorial/Dockerfile
Labels: CLA Signed, examples

#2641 docs(guides/styling): remove `postinstall` references
  docs/guides/styling.md
Labels: CLA Signed, documentation

#2642 docs(guides/typescript): bring `package.json` & `tsconfig.json` in line with latest templates
  docs/guides/typescript.md
Labels: CLA Signed, documentation

#2643 docs(api/remix): replace `remix` imports
  docs/api/conventions.md
  docs/api/remix.md
  docs/guides/constraints.md
  docs/guides/data-loading.md
  docs/guides/data-writes.md
  docs/guides/mdx.md
  docs/guides/optimistic-ui.md
  docs/guides/resource-routes.md
  docs/guides/styling.md
  docs/other-api/node.md
  docs/other-api/serve.md
  docs/pages/faq.md
  docs/pages/gotchas.md
  docs/pages/philosophy.md
Labels: CLA Signed, documentation

#2653 fix(remix-dev/cli/migrate): bug fixes & improved DX
  packages/remix-dev/cli/migrate/jscodeshift.ts
  packages/remix-dev/cli/migrate/migrations/index.ts
  packages/remix-dev/cli/migrate/migrations/replace-remix-imports/getTransformOptions.ts
  packages/remix-dev/cli/migrate/migrations/replace-remix-imports/index.ts
  packages/remix-dev/cli/migrate/migrations/replace-remix-imports/transform/index.ts
  packages/remix-dev/cli/migrate/resolveInput.ts
Labels: CLA Signed, package:dev

#2150 docs: use ASCII characters
  contributors.yml
  docs/api/conventions.md
  docs/api/remix.md
Labels: CLA Signed, documentation

#2652 fix(remix-dev): resource route module making it to the browser
  integration/fetcher-test.ts
  packages/remix-dev/compiler/plugins/browserRouteModulesPlugin.ts
Labels: CLA Signed, package:dev

#2529 fix(examples): use Node instead of npm for CMD process in `Dockerfile` of `jokes` example
  contributors.yml
  examples/jokes/Dockerfile
Labels: CLA Signed, examples

#2657 fix(remix-netlify): don't parse multipart `formData` to string
  packages/remix-netlify/server.ts
Labels: CLA Signed, adapter:netlify

#2659 chore: add @typescript-eslint/consistent-type-imports rule
  packages/remix-eslint-config/rules/typescript.js
Labels: CLA Signed

#2661 docs: replace `[NBSP]` with normal space
  docs/api/conventions.md
  docs/guides/errors.md
  docs/guides/routing.md
  docs/tutorials/jokes.md
  examples/sanity/studio/README.md
Labels: CLA Signed, documentation

#2665 ci: update deploy requirement
  .github/workflows/release.yml
Labels: CLA Signed

#2662 fix(remix-react): pass `port` to inline script of `LiveReload`
  packages/remix-react/components.tsx
Labels: CLA Signed, package:react

#2461 ci: normalize Node.js version across actions
  .github/workflows/deployment-test.yml
  .github/workflows/format.yml
  .github/workflows/release-comments.yml
  .github/workflows/release-private.yml
  .github/workflows/release.yml
  .gitignore
  contributors.yml
  scripts/deployment-test/package-lock.json
Labels: CLA Signed

#2667 chore: improve workflows a bit
  .github/workflows/deployment-test.yml
  .github/workflows/format.yml
  .github/workflows/no-response.yml
  .github/workflows/release-comments.yml
  .github/workflows/release-private.yml
  .github/workflows/release.yml
  .github/workflows/test.yml
  .github/workflows/website.yml
  contributors.yml
  package.json
  scripts/deployment-test/package-lock.json
Labels: CLA Signed

#2669 chore: remove `package-lock.json` from `deployment-test`
  .gitignore
  scripts/deployment-test/package-lock.json
Labels: CLA Signed

#2663 chore(playground): add playground
  .eslintignore
  .gitignore
  docs/pages/contributing.md
  package.json
  playground/README.md
  rollup.config.js
  scripts/playground/new.js
  scripts/playground/template/.env
  scripts/playground/template/.gitignore
  scripts/playground/template/.prettierignore
  scripts/playground/template/README.md
  scripts/playground/template/app/db.server.ts
  scripts/playground/template/app/entry.client.tsx
  scripts/playground/template/app/entry.server.tsx
  scripts/playground/template/app/models/note.server.ts
  scripts/playground/template/app/models/user.server.ts
  scripts/playground/template/app/root.tsx
  scripts/playground/template/app/routes/index.tsx
  scripts/playground/template/app/routes/join.tsx
  scripts/playground/template/app/routes/login.tsx
  scripts/playground/template/app/routes/logout.tsx
  scripts/playground/template/app/routes/notes.tsx
  scripts/playground/template/app/routes/notes/$noteId.tsx
  scripts/playground/template/app/routes/notes/index.tsx
  scripts/playground/template/app/routes/notes/new.tsx
  scripts/playground/template/app/session.server.ts
  scripts/playground/template/app/utils.ts
  scripts/playground/template/package.json
  scripts/playground/template/prisma/migrations/20220307190657_init/migration.sql
  scripts/playground/template/prisma/migrations/migration_lock.toml
  scripts/playground/template/prisma/schema.prisma
  scripts/playground/template/prisma/seed.ts
  scripts/playground/template/public/favicon.ico
  scripts/playground/template/remix.config.js
  scripts/playground/template/remix.env.d.ts
  scripts/playground/template/remix.init/index.js
  scripts/playground/template/server.js
  scripts/playground/template/tailwind.config.js
  scripts/playground/template/tsconfig.json
Labels: CLA Signed

#2676 chore(remix-dev/tests): run `replace-remix-imports` migration over stack fixture
  packages/remix-dev/__tests__/fixtures/stack/app/entry.client.tsx
  packages/remix-dev/__tests__/fixtures/stack/app/entry.server.tsx
  packages/remix-dev/__tests__/fixtures/stack/app/root.tsx
  packages/remix-dev/__tests__/fixtures/stack/package.json
Labels: CLA Signed, package:dev

#2556 chore(remix-dev): always ask if they want ts or js during create
  packages/remix-dev/__tests__/cli-test.ts
  packages/remix-dev/__tests__/create-test.ts
  packages/remix-dev/cli/commands.ts
  packages/remix-dev/cli/convert-to-javascript.ts
  packages/remix-dev/cli/create.ts
  packages/remix-dev/cli/run.ts
  packages/remix-dev/compiler/plugins/serverRouteModulesPlugin.ts
  packages/remix-dev/env.ts
Labels: CLA Signed

#2593 fix(remix-dev/compiler): make `getDependenciesToBundle` more resilient to misconfigured `packages.json`s
  integration/compiler-test.ts
  packages/remix-dev/compiler/dependencies.ts
  packages/remix-dev/config.ts
Labels: CLA Signed, package:dev

#2460 refactor(remix-server-runtime): simplify `responseInit` assign in `json` helper
  packages/remix-server-runtime/responses.ts
Labels: CLA Signed, package:server-runtime

#2459 refactor(remix-server-runtime): use `Object.entries` instead of `Object.keys` in `createRoutes`
  packages/remix-server-runtime/routes.ts
Labels: CLA Signed, package:server-runtime

#2450 chore(remix-server-runtime): standardize on uppercase method
  packages/remix-server-runtime/server.ts
Labels: CLA Signed, package:server-runtime

#2695 chore(remix-dev/cli): simplify `validateNewProjectPath` in `create` command
  contributors.yml
  packages/remix-dev/cli/create.ts
Labels: CLA Signed, package:dev

#2694 fix(remix-dev): manually resolve package.json for deps
  integration/compiler-test.ts
  packages/remix-dev/compiler/plugins/serverBareModulesPlugin.ts
Labels: CLA Signed

#2717 docs(pages/technical-explanation): update code highlighting
  contributors.yml
  docs/pages/technical-explanation.md
Labels: CLA Signed, documentation

#2721 docs(tutorials/jokes): add missing installation setup line
  contributors.yml
  docs/tutorials/jokes.md
Labels: CLA Signed, documentation

#2704 docs: Fix upload handler examples + add context
  docs/api/remix.md
  docs/pages/gotchas.md
Labels: CLA Signed, documentation

#2705 docs(guides/constraints): handle root path in `removeTrailingSlash` helper
  contributors.yml
  docs/guides/constraints.md
Labels: CLA Signed, documentation

#2731 feat(remix-eslint-config): add ESLint warning when using deprecated `remix` imports
  packages/remix-eslint-config/rules/core.js
  packages/remix-eslint-config/rules/packageExports.js
Labels: CLA Signed, package:eslint-config

#2710 docs(blog): add imports
  contributors.yml
  docs/tutorials/blog.md
Labels: CLA Signed, documentation

#2634 test: use playwright for integration tests
  .github/workflows/test.yml
  .gitignore
  docs/pages/contributing.md
  integration/action-test.ts
  integration/bug-report-test.ts
  integration/catch-boundary-data-test.ts
  integration/catch-boundary-test.ts
  integration/cf-compiler-test.ts
  integration/compiler-test.ts
  integration/error-boundary-test.ts
  integration/esm-only-warning-test.ts
  integration/fetcher-layout-test.ts
  integration/fetcher-test.ts
  integration/file-uploads-test.ts
  integration/form-data-test.ts
  integration/form-test.ts
  integration/headers-test.ts
  integration/helpers/create-fixture.ts
  integration/helpers/create-fixture.tsx
  integration/helpers/global-setup.ts
  integration/helpers/global-teardown.ts
  integration/helpers/playwright-fixture.ts
  integration/helpers/setupAfterEnv.ts
  integration/helpers/utils.ts
  integration/jest.config.js
  integration/layout-route-test.ts
  integration/link-test.ts
  integration/loader-test.ts
  integration/meta-test.ts
  integration/multiple-cookies-test.ts
  integration/path-mapping-test.ts
  integration/playwright.config.ts
  integration/prefetch-test.ts
  integration/rendering-test.ts
  integration/resource-routes-test.ts
  integration/server-code-in-browser-message-test.ts
  integration/server-entry-test.ts
  integration/server-source-maps-test.ts
  integration/set-cookie-revalidation-test.ts
  integration/splat-routes-test.ts
  integration/transition-test.ts
  package.json
  packages/remix-eslint-config/internal.js
  yarn.lock
Labels: CLA Signed

#2727 docs(api/remix): add missing `id` on match object from `useMatches`
  contributors.yml
  docs/api/remix.md
Labels: CLA Signed, documentation

#1822 feat(cli): exit with code 1 when remix build fails
  contributors.yml
  packages/remix-dev/cli/commands.ts
  packages/remix-dev/compiler.ts
Labels: CLA Signed, feat:dx

#2738 chore: remove `pptr-testing-library` dependency
  package.json
  yarn.lock
Labels: CLA Signed

#2757 docs(faq): Explain the difference between CatchBoundary and ErrorBoundary
  docs/pages/faq.md
Labels: CLA Signed, documentation

#2670 feat(remix-dev/cli): add DX improvements for `migrate` command & `replace-remix-imports` migration
  .eslintignore
  packages/remix-dev/__tests__/cli-test.ts
  packages/remix-dev/__tests__/fixtures/replace-remix-imports/app/db.server.ts
  packages/remix-dev/__tests__/fixtures/replace-remix-imports/app/entry.client.tsx
  packages/remix-dev/__tests__/fixtures/replace-remix-imports/app/entry.server.tsx
  packages/remix-dev/__tests__/fixtures/replace-remix-imports/app/models/note.server.ts
  packages/remix-dev/__tests__/fixtures/replace-remix-imports/app/models/post.server.ts
  packages/remix-dev/__tests__/fixtures/replace-remix-imports/app/models/user.server.ts
  packages/remix-dev/__tests__/fixtures/replace-remix-imports/app/root.tsx
  packages/remix-dev/__tests__/fixtures/replace-remix-imports/app/routes/healthcheck.tsx
  packages/remix-dev/__tests__/fixtures/replace-remix-imports/app/routes/index.tsx
  packages/remix-dev/__tests__/fixtures/replace-remix-imports/app/routes/join.tsx
  packages/remix-dev/__tests__/fixtures/replace-remix-imports/app/routes/login.tsx
  packages/remix-dev/__tests__/fixtures/replace-remix-imports/app/routes/logout.tsx
  packages/remix-dev/__tests__/fixtures/replace-remix-imports/app/routes/notes.tsx
  packages/remix-dev/__tests__/fixtures/replace-remix-imports/app/routes/notes/$noteId.tsx
  packages/remix-dev/__tests__/fixtures/replace-remix-imports/app/routes/notes/index.tsx
  packages/remix-dev/__tests__/fixtures/replace-remix-imports/app/routes/notes/new.tsx
  packages/remix-dev/__tests__/fixtures/replace-remix-imports/app/routes/posts/$slug.tsx
  packages/remix-dev/__tests__/fixtures/replace-remix-imports/app/routes/posts/admin.tsx
  packages/remix-dev/__tests__/fixtures/replace-remix-imports/app/routes/posts/admin/index.tsx
  packages/remix-dev/__tests__/fixtures/replace-remix-imports/app/routes/posts/admin/new.tsx
  packages/remix-dev/__tests__/fixtures/replace-remix-imports/app/routes/posts/index.tsx
  packages/remix-dev/__tests__/fixtures/replace-remix-imports/app/session.server.ts
  packages/remix-dev/__tests__/fixtures/replace-remix-imports/app/utils.test.ts
  packages/remix-dev/__tests__/fixtures/replace-remix-imports/app/utils.ts
  packages/remix-dev/__tests__/fixtures/replace-remix-imports/package.json
  packages/remix-dev/__tests__/fixtures/replace-remix-imports/public/favicon.ico
  packages/remix-dev/__tests__/fixtures/replace-remix-imports/remix.config.js
  packages/remix-dev/__tests__/fixtures/replace-remix-imports/remix.env.d.ts
  packages/remix-dev/__tests__/fixtures/replace-remix-imports/tailwind.config.js
  packages/remix-dev/__tests__/fixtures/replace-remix-imports/tsconfig.json
  packages/remix-dev/__tests__/replace-remix-imports-test.ts
  packages/remix-dev/cli/migrate/flags.ts
  packages/remix-dev/cli/migrate/jscodeshift.ts
  packages/remix-dev/cli/migrate/migrations/replace-remix-imports/cleanupPackageJson.ts
  packages/remix-dev/cli/migrate/migrations/replace-remix-imports/dependency.ts
  packages/remix-dev/cli/migrate/migrations/replace-remix-imports/getTransformOptions.ts
  packages/remix-dev/cli/migrate/migrations/replace-remix-imports/index.ts
  packages/remix-dev/cli/migrate/migrations/replace-remix-imports/messages.ts
  packages/remix-dev/cli/migrate/migrations/replace-remix-imports/remixSetup.ts
  packages/remix-dev/cli/migrate/migrations/replace-remix-imports/resolveTransformOptions.ts
  packages/remix-dev/cli/migrate/migrations/replace-remix-imports/transform/adapter.ts
  packages/remix-dev/cli/migrate/migrations/replace-remix-imports/transform/getRemixImports.ts
  packages/remix-dev/cli/migrate/migrations/replace-remix-imports/transform/index.ts
  packages/remix-dev/cli/migrate/migrations/replace-remix-imports/transform/mapNormalizedImports/index.ts
  packages/remix-dev/cli/migrate/migrations/replace-remix-imports/transform/mapNormalizedImports/packageExports.ts
  packages/remix-dev/cli/migrate/migrations/replace-remix-imports/transform/normalizeImports.ts
  packages/remix-dev/cli/migrate/migrations/replace-remix-imports/transform/options.ts
  packages/remix-dev/cli/migrate/migrations/replace-remix-imports/transform/runtime.ts
  packages/remix-dev/cli/migrate/resolveInput.ts
  packages/remix-dev/cli/migrate/run.ts
  packages/remix-dev/cli/run.ts
  packages/remix-dev/colors.ts
  packages/remix-dev/logging.ts
  packages/remix-dev/package.json
  packages/remix-dev/tsconfig.json
  rollup.config.js
  yarn.lock
Labels: CLA Signed, package:dev, feat:dx

#2401 chore(issues-template): Clarify instructions when the user have a fix
  integration/bug-report-test.ts
Labels: CLA Signed

#2759 chore(remix-dev): choose a better port if 3000 isn't available
  packages/remix-dev/cli/commands.ts
Labels: CLA Signed, package:dev

#2764 chore(eslint): disable deprecated imports rule
  packages/remix-eslint-config/rules/core.js
Labels: CLA Signed

#2562 feat(remix-dev): use auto-detected package manager
  contributors.yml
  packages/remix-dev/__tests__/create-test.ts
  packages/remix-dev/cli/commands.ts
  packages/remix-dev/cli/create.ts
  packages/remix-dev/cli/run.ts
Labels: CLA Signed, package:dev, feat:dx

#2767 chore(remix-dev): use fullImportPath to resolve package
  integration/compiler-test.ts
  packages/remix-dev/compiler/plugins/serverBareModulesPlugin.ts
Labels: CLA Signed

#2733 fix(remix-dev): Prioritize remix templates in CLI create
  packages/remix-dev/__tests__/create-test.ts
  packages/remix-dev/cli/create.ts
Labels: CLA Signed

#2765 test: add tests for magic exports until they are removed
  integration/cf-compiler-test.ts
  integration/compiler-test.ts
  integration/helpers/create-fixture.ts
  package.json
  yarn.lock
Labels: CLA Signed

#2671 ci: only comment on issues and PRs when `packages` change
  .github/workflows/deployment-test.yml
  .github/workflows/deployments.yml
  .github/workflows/nightly.yml
  .github/workflows/release-comments.yml
  .github/workflows/release.yml
  scripts/release/comment.mjs
  scripts/release/constants.mjs
  scripts/release/octokit.mjs
Labels: CLA Signed

#2547 chore(remix-dev): remove unused `chalk-animation` dependency
  packages/remix-dev/package.json
  yarn.lock
Labels: CLA Signed, package:dev

#2783 fix: LiveReload only executes on client
  packages/remix-react/components.tsx
Labels: CLA Signed

#2784 fix(cli/migrate): remove `@remix-run/` prefix when checking for remix adapter
  packages/remix-dev/cli/migrate/migrations/replace-remix-imports/resolveTransformOptions.ts
Labels: CLA Signed

#2785 fix(cli/migrate): remove `@remix-run/` prefix when checking for remix adapters
  packages/remix-dev/cli/migrate/migrations/replace-remix-imports/resolveTransformOptions.ts
Labels: CLA Signed

#2787 fix(cli/migrate): `gray` should be gray, not blue
  packages/remix-dev/colors.ts
Labels: CLA Signed

#2780 ci: more nightly updates
  .github/workflows/nightly.yml
  scripts/version.js
Labels: CLA Signed

#2790 fix(cli/migrate): use best version spec as remix version
  packages/remix-dev/cli/migrate/migrations/replace-remix-imports/index.ts
Labels: CLA Signed, package:dev

#2791 fix(cli/migrate): use best version spec as remix version
  packages/remix-dev/cli/migrate/migrations/replace-remix-imports/index.ts
Labels: CLA Signed, package:dev

#2806 fix(remix-dev): add try/catch to `warnOnceIfEsmOnlyPackage` for when a package's dependency isn't installed
  packages/remix-dev/compiler/plugins/serverBareModulesPlugin.ts
Labels: CLA Signed, package:dev

#2789 ci: opt out of caching deployment test dependencies
  .github/workflows/deployments.yml
Labels: CLA Signed

#2805 fix(templates/deno): `build` and `start` run without errors
  templates/deno/app/deps/@remix-run/react.ts
  templates/deno/app/deps/@remix-run/server-runtime.ts
  templates/deno/app/deps/react-dom-server.ts
  templates/deno/app/deps/react-dom.ts
  templates/deno/app/deps/react.ts
  templates/deno/app/entry.server.tsx
  templates/deno/app/root.tsx
  templates/deno/deno.json
  templates/deno/package.json
  templates/deno/remix-deno/deps/@remix-run/server-runtime.ts
Labels: CLA Signed

#2802 ci: restore some changes lost in a merge conflict
  .github/workflows/release.yml
Labels: CLA Signed

#2763 fix(cli): don't use system path separator on remote repo URLs
  contributors.yml
  packages/remix-dev/cli/create.ts
Labels: CLA Signed

#2809 ci(test): cache playwright binaries
  .github/workflows/test.yml
Labels: CLA Signed

#2722 docs(pages/gotchas): make more clear what's good/bad in `unstable_createFileUploadHandler` example
  docs/pages/gotchas.md
Labels: CLA Signed, documentation

#2818 fix(templates/deno): remix's `createRequestHandler` no longer has a `platform` arg
  templates/deno/remix-deno/server.ts
Labels: CLA Signed

#2819 refactor(templates/deno): do not reference removed `deno.json` file
  templates/deno/.vscode/settings.json
Labels: CLA Signed

#2807 ci: more nightly updates (dev)
  .github/workflows/deployments.yml
  .github/workflows/nightly.yml
  scripts/version.js
Labels: CLA Signed

#2771 ci(test): cache playwright binaries
  .github/workflows/test.yml
Labels: CLA Signed

#2711 docs: add Gitpod quickstart to blog tutorial
  docs/tutorials/blog.md
Labels: CLA Signed, documentation

#2794 docs(examples): add real time collaborative text editing using `tiptap` & `webrtc`
  examples/tiptap-collab-editing/.eslintrc.js
  examples/tiptap-collab-editing/.gitignore
  examples/tiptap-collab-editing/README.md
  examples/tiptap-collab-editing/app/entry.client.tsx
  examples/tiptap-collab-editing/app/entry.server.tsx
  examples/tiptap-collab-editing/app/root.tsx
  examples/tiptap-collab-editing/app/routes/editor.tsx
  examples/tiptap-collab-editing/app/utils/webrtc.client.tsx
  examples/tiptap-collab-editing/package.json
  examples/tiptap-collab-editing/public/favicon.ico
  examples/tiptap-collab-editing/remix.config.js
  examples/tiptap-collab-editing/remix.env.d.ts
  examples/tiptap-collab-editing/sandbox.config.json
  examples/tiptap-collab-editing/tsconfig.json
Labels: CLA Signed, examples

#2829 ci(nightly): set up git
  .github/workflows/nightly.yml
Labels: CLA Signed

#2741 chore: remove `remix-eslint-config` dependencies from root `package.json`
  package.json
Labels: CLA Signed

#2808 docs: add docs on ?index query param
  docs/api/conventions.md
  docs/api/remix.md
  docs/guides/routing.md
Labels: CLA Signed, documentation

#2742 chore(remix-eslint-config): cleanup `peerDependencies`
  packages/remix-eslint-config/package.json
Labels: CLA Signed, package:eslint-config

#2837 docs(example): Fix link in google analytics example
  examples/google-analytics/README.md
Labels: CLA Signed, examples

#2838 fix: Ensure parent loaders are called on fetchActionRedirect
  integration/transition-test.ts
  package.json
  packages/remix-react/__tests__/transition-test.tsx
  packages/remix-react/transition.ts
Labels: CLA Signed

#2814 chore(test): Add OS matrix to test workflow for Windows, macOS
  .github/workflows/test.yml
  integration/compiler-test.ts
  package.json
  packages/remix-dev/__tests__/cli-test.ts
  packages/remix-dev/__tests__/create-test.ts
  packages/remix-dev/__tests__/replace-remix-imports-test.ts
  packages/remix-dev/cli/create.ts
  packages/remix-dev/cli/run.ts
  packages/remix-dev/compiler.ts
  yarn.lock
Labels: CLA Signed

#2840 fix(remix-dev): either use provided env port, or randomize from 3000 to 3100
  packages/remix-dev/cli/commands.ts
Labels: CLA Signed, package:dev

#2839 ci(publish.js): a few more nightly adjustments
  .github/workflows/nightly.yml
  scripts/publish.js
Labels: CLA Signed

#2843 ci: add note to nightly workflow
  .github/workflows/nightly.yml
Labels: CLA Signed

#2841 ci: update playwright caching to work across matrix
  .github/workflows/test.yml
Labels: CLA Signed

#2863 docs(examples): replace `window` check with `document` check in `dark-mode` example
  examples/dark-mode/app/utils/theme-provider.tsx
Labels: CLA Signed, examples

#2739 chore: Ignore dotfiles in route subdirs too
  contributors.yml
  templates/arc/remix.config.js
  templates/cloudflare-pages/remix.config.js
  templates/cloudflare-workers/remix.config.js
  templates/express/remix.config.js
  templates/fly/remix.config.js
  templates/netlify/remix.config.js
  templates/remix/remix.config.js
  templates/vercel/remix.config.js
Labels: CLA Signed, feat:dx

#2867 fix(remix-dev/create): use path.split and path.join to always make path posix style
  packages/remix-dev/cli/create.ts
Labels: CLA Signed

#2869 chore(templates): ignore dotfiles in route subdirectories too
  contributors.yml
  templates/arc/remix.config.js
  templates/cloudflare-pages/remix.config.js
  templates/cloudflare-workers/remix.config.js
  templates/express/remix.config.js
  templates/fly/remix.config.js
  templates/netlify/remix.config.js
  templates/remix/remix.config.js
  templates/vercel/remix.config.js
Labels: CLA Signed, template:express, template:architect, template:vercel, template:cloudflare-pages, template:cloudflare-workers, template:fly, template:netlify, template:remix

#2872 chore(tests): ignore dotfiles in route subdirectories too
  integration/helpers/cf-template/remix.config.js
  integration/helpers/node-template/remix.config.js
  packages/remix-dev/__tests__/fixtures/stack/remix.config.js
Labels: CLA Signed

#2871 docs(conventions): ignore dotfiles in route subdirectories too
  docs/api/conventions.md
Labels: CLA Signed, documentation

#2870 chore(examples): ignore dotfiles in route subdirectories too
  examples/basic/remix.config.js
  examples/catch-boundary/remix.config.js
  examples/chakra-ui/remix.config.js
  examples/client-only-components/remix.config.js
  examples/client-side-validation/remix.config.js
  examples/collected-notes/remix.config.js
  examples/combobox-resource-route/remix.config.js
  examples/dark-mode/remix.config.js
  examples/dataloader/remix.config.js
  examples/emotion/remix.config.js
  examples/file-and-cloudinary-upload/remix.config.js
  examples/firebase-auth-firestore/remix.config.js
  examples/form-to-notion-db/remix.config.js
  examples/framer-motion/remix.config.js
  examples/framer-route-animation/remix.config.js
  examples/gdpr-cookie-consent/remix.config.js
  examples/google-analytics/remix.config.js
  examples/graphql-api/remix.config.js
  examples/image-resize/remix.config.js
  examples/infinite-scrolling/remix.config.js
  examples/io-ts-formdata-decoding/remix.config.js
  examples/ioredis/remix.config.js
  examples/jokes/remix.config.js
  examples/mantine/remix.config.js
  examples/msw/remix.config.js
  examples/multiple-forms/remix.config.js
  examples/multiple-params/remix.config.js
  examples/newsletter-signup/remix.config.js
  examples/nprogress/remix.config.js
  examples/on-demand-hydration/remix.config.js
  examples/outlet-form-rerender/remix.config.js
  examples/pathless-routes/remix.config.js
  examples/pm-app/remix.config.js
  examples/quirrel/remix.config.js
  examples/react-spring/remix.config.js
  examples/redis-upstash-session/remix.config.js
  examples/remix-auth-auth0/remix.config.js
  examples/remix-auth-form/remix.config.js
  examples/remix-auth-github/remix.config.js
  examples/remix-auth-supabase-github/remix.config.js
  examples/remix-auth-supabase/remix.config.js
  examples/route-modal/remix.config.js
  examples/routes-gen/remix.config.js
  examples/rust/remix.config.js
  examples/sanity/remix.config.js
  examples/sass/remix.config.js
  examples/search-input/remix.config.js
  examples/sharing-loader-data/remix.config.js
  examples/socket.io/remix.config.js
  examples/stitches/remix.config.js
  examples/strapi/remix.config.js
  examples/stripe-integration/remix.config.js
  examples/styled-components/remix.config.js
  examples/supabase-subscription/remix.config.js
  examples/tailwindcss/remix.config.js
  examples/template/remix.config.js
  examples/tiptap-collab-editing/remix.config.js
  examples/toast-message/remix.config.js
  examples/turborepo-vercel/apps/remix-app/remix.config.js
  examples/usematches-loader-data/remix.config.js
Labels: CLA Signed, examples

#2873 test: run against node 14 and node 16
  .github/workflows/test.yml
  packages/remix-dev/__tests__/create-test.ts
Labels: CLA Signed

#2931 fix: bundle netlify-edge
  .vscode/settings.json
  deno-import-map.json
  packages/remix-dev/compiler.ts
  packages/remix-dev/compiler/plugins/serverBareModulesPlugin.ts
  packages/remix-netlify-edge/index.d.ts
  packages/remix-netlify-edge/index.js
  packages/remix-netlify-edge/index.ts
  packages/remix-netlify-edge/mod.ts
  packages/remix-netlify-edge/package.json
  packages/remix-netlify-edge/remix-deno/crypto.ts
  packages/remix-netlify-edge/remix-deno/implementations.ts
  packages/remix-netlify-edge/remix-deno/mod.ts
  packages/remix-netlify-edge/server.ts
  rollup.config.js
  scripts/publish.js
  templates/netlify/package.json
  templates/netlify/remix.init/vscode.json
  tsconfig.json
  yarn.lock
Labels: CLA Signed

#2855 docs(examples): add styletron example
  contributors.yml
  examples/styletron/.eslintrc.js
  examples/styletron/.gitignore
  examples/styletron/README.md
  examples/styletron/app/entry.client.tsx
  examples/styletron/app/entry.server.tsx
  examples/styletron/app/root.tsx
  examples/styletron/app/routes/index.tsx
  examples/styletron/app/styletron.ts
  examples/styletron/package.json
  examples/styletron/public/favicon.ico
  examples/styletron/remix.config.js
  examples/styletron/remix.env.d.ts
  examples/styletron/sandbox.config.json
  examples/styletron/tsconfig.json
Labels: CLA Signed, examples

#2862 docs(examples): update `socket.io` example
  contributors.yml
  examples/socket.io/README.md
  examples/socket.io/package.json
Labels: CLA Signed, examples

#2939 docs(tutorials/jokes): update line highlights
  contributors.yml
  docs/tutorials/jokes.md
Labels: CLA Signed, documentation

#2874 fix: re-inline live reload script
  packages/remix-dev/config.ts
  packages/remix-react/__tests__/components-test.tsx
  packages/remix-react/components.tsx
Labels: CLA Signed

#2942 fix: updated conditions for deno and netlify edge
  packages/remix-dev/compiler.ts
Labels: CLA Signed

#2945 ci: add content-type to curl, rename `GITHUB_REF` to `VERSION`
  .github/workflows/nightly.yml
  .github/workflows/release-comments.yml
  .github/workflows/release.yml
  scripts/release/constants.mjs
Labels: CLA Signed

#2875 feat: clean directories before initial builds
  packages/remix-dev/cli/commands.ts
Labels: CLA Signed

#2786 fix(remix-dev): apply suggested and mandatory tsconfig when values are missing
  packages/remix-dev/colors.ts
  packages/remix-dev/compiler/utils/tsconfig/index.ts
  packages/remix-dev/compiler/utils/tsconfig/write-config-defaults.ts
Labels: CLA Signed, package:dev

#2957 docs(examples): Fix typo in msw README
  contributors.yml
  examples/msw/README.md
Labels: CLA Signed, examples

#2964 ci(nightly,release): use repository-dispatch action
  .github/workflows/nightly.yml
  .github/workflows/release.yml
Labels: CLA Signed

#2977 ci(deployments): disable lockfile usage for bahmutov/npm-install action
  .github/workflows/deployments.yml
Labels: CLA Signed

#2990 chore: Remove npm tags from experimental releases
  scripts/publish.js
Labels: CLA Signed

#2999 docs(tutorials/blog): update line highlighting
  contributors.yml
  docs/tutorials/blog.md
Labels: CLA Signed, documentation

#3001 test: increase timeout of test for windows
  packages/remix-dev/__tests__/replace-remix-imports-test.ts
Labels: CLA Signed

#3005 Revert "feat: clean directories before initial builds"
  packages/remix-dev/cli/commands.ts
Labels: CLA Signed

#2961 chore(remix-dev): resolve `extends` in tsconfig when applying defaults
  integration/cf-compiler-test.ts
  integration/compiler-test.ts
  integration/esm-only-warning-test.ts
  integration/helpers/create-fixture.ts
  integration/path-mapping-test.ts
  integration/server-code-in-browser-message-test.ts
  integration/tsconfig-test.ts
  packages/remix-dev/compiler/utils/tsconfig/write-config-defaults.ts
Labels: CLA Signed

#2988 ci(deployment-tests): update deleting of old arc app
  scripts/deployment-test/arc.mjs
Labels: CLA Signed

#2014 docs: remove misleading information about cache purge on file change
  docs/other-api/serve.md
Labels: CLA Signed, documentation

#2275 docs: refine README for create-remix/express
  contributors.yml
  templates/express/README.md
Labels: CLA Signed, needs-response, documentation, template:express

#3031 docs(jokes): fix prisma schema misspelling
  contributors.yml
  docs/tutorials/jokes.md
Labels: CLA Signed, documentation
