Repository remix-run/remix, pull requests merged in 2023-04, with the labels that each got.

#5972 docs(pages/v2): fix typo in `serverBuildTarget` section
  docs/pages/v2.md
Labels: CLA Signed, docs

#5973 docs(pages/v2): fix typo in `serverBuildTarget` section
  contributors.yml
  docs/pages/v2.md
Labels: CLA Signed, docs

#5960 feat(dev): stabilize PostCSS and Tailwind options
  .changeset/postcss-option.md
  .changeset/tailwind-option.md
  docs/file-conventions/remix-config.md
  docs/guides/styling.md
  docs/pages/api-development-strategy.md
  integration/css-modules-test.ts
  integration/css-side-effect-imports-test.ts
  integration/hmr-test.ts
  integration/postcss-test.ts
  integration/tailwind-test.ts
  integration/vanilla-extract-test.ts
  packages/remix-dev/__tests__/readConfig-test.ts
  packages/remix-dev/compiler/utils/postcss.ts
  packages/remix-dev/config.ts
  packages/remix-react/entry.ts
  packages/remix-server-runtime/entry.ts
Labels: CLA Signed, package:dev

#5989 docs(meta-v2): fix links
  docs/route/meta-v2.md
Labels: CLA Signed, docs

#5991 docs(pages/v2): fix typo in `useFetcher` section
  contributors.yml
  docs/pages/v2.md
Labels: CLA Signed, docs

#5988 test(dev): fix PostCSS tests in Node 14
  integration/postcss-test.ts
Labels: CLA Signed

#6019 docs: update blog tutorial for v2 routes
  docs/tutorials/blog.md
Labels: CLA Signed

#5959 docs(tutorials/blog): use enabled `v2_routeConvention` flag
  docs/tutorials/blog.md
Labels: CLA Signed, docs

#6005 Fix `V2_MetaFunction` type import in templates
  contributors.yml
  templates/arc/app/routes/_index.tsx
  templates/cloudflare-pages/app/routes/_index.tsx
  templates/cloudflare-workers/app/routes/_index.tsx
  templates/deno/app/routes/_index.tsx
  templates/express/app/routes/_index.tsx
  templates/fly/app/routes/_index.tsx
  templates/netlify/app/routes/_index.tsx
  templates/remix/app/routes/_index.tsx
  templates/vercel/app/routes/_index.tsx
Labels: CLA Signed

#5695 feat!(remix-eslint-config): remove magic imports ESLint warnings
  .changeset/remove-magic-import-eslint-warnings.md
  packages/remix-eslint-config/rules/core.js
  packages/remix-eslint-config/rules/packageExports.js
Labels: CLA Signed, package:eslint-config

#5751 chore(remix-dev/compiler): remove `deprecatedRemixPackagePlugin`
  .changeset/remove-magic-exports-esbuild-plugin.md
  packages/remix-dev/compiler/assets/js.ts
  packages/remix-dev/compiler/plugins/deprecatedRemixPackage.ts
  packages/remix-dev/compiler/server/index.ts
Labels: CLA Signed, package:dev

#6025 docs(playground): clarify README
  contributors.yml
  scripts/playground/template/README.md
Labels: CLA Signed, docs

#5881 feat: add TS 5 support
  docs/guides/typescript.md
  package.json
  packages/remix-dev/__tests__/fixtures/cloudflare/package.json
  packages/remix-dev/__tests__/fixtures/indie-stack/package.json
  packages/remix-dev/__tests__/fixtures/node/package.json
  packages/remix-dev/__tests__/fixtures/replace-remix-magic-imports/package.json
  packages/remix-eslint-config/package.json
  packages/remix-testing/package.json
  scripts/playground/template/package.json
  templates/arc/package.json
  templates/cloudflare-pages/package.json
  templates/cloudflare-workers/package.json
  templates/express/package.json
  templates/fly/package.json
  templates/netlify/package.json
  templates/remix/package.json
  templates/vercel/package.json
  yarn.lock
Labels: CLA Signed, docs, package:dev, package:eslint-config, template:express, template:architect, template:vercel, template:cloudflare-pages, template:cloudflare-workers, template:fly, template:netlify, template:remix, package:testing

#6038 chore: bump deps to resolve some security issues
  package.json
  packages/remix-dev/package.json
  scripts/deployment-test/arc.mjs
  scripts/deployment-test/package.json
  yarn.lock
Labels: CLA Signed

#5516 fix(server-runtime): fix SerializeFrom type inference
  .changeset/serialize-from-data-key.md
  packages/remix-react/__tests__/hook-types-test.tsx
  packages/remix-server-runtime/__tests__/serialize-test.ts
  packages/remix-server-runtime/__tests__/utils.ts
  packages/remix-server-runtime/responses.ts
Labels: CLA Signed

#6039 chore(deps): bump minimatch to latest
  packages/remix-dev/config/flat-routes.ts
  packages/remix-dev/config/routesConvention.ts
  packages/remix-dev/package.json
  yarn.lock
Labels: CLA Signed

#6041 fix(remix-cloudflare-pages): fix `GetLoadContextFunction` type
  packages/remix-cloudflare-pages/worker.ts
Labels: CLA Signed, adapter:cloudflare-pages, feat:typescript

#6043 chore(remix-dev): fix `v2_meta` warning
  packages/remix-dev/config.ts
Labels: CLA Signed, package:dev

#6051 fix: move `@types/*` to devDependencies
  packages/remix-architect/package.json
  packages/remix-server-runtime/package.json
Labels: CLA Signed

#6050 docs(tutorials/jokes): use enabled future flags
  docs/tutorials/jokes.md
Labels: CLA Signed, docs

#6046 feat(dev): enable all CSS bundling features
  .changeset/css-bundling.md
  docs/guides/styling.md
  docs/pages/api-development-strategy.md
  integration/css-modules-test.ts
  integration/css-side-effect-imports-test.ts
  integration/deterministic-build-output-test.ts
  integration/hmr-test.ts
  integration/postcss-test.ts
  integration/tailwind-test.ts
  integration/vanilla-extract-test.ts
  packages/remix-dev/__tests__/readConfig-test.ts
  packages/remix-dev/compiler/assets/css.ts
  packages/remix-dev/compiler/assets/js.ts
  packages/remix-dev/compiler/plugins/vanillaExtract.ts
  packages/remix-dev/compiler/plugins/vanillaExtract/index.ts
  packages/remix-dev/compiler/plugins/vanillaExtract/sideEffects.ts
  packages/remix-dev/compiler/plugins/vanillaExtract/uncached.ts
  packages/remix-dev/compiler/server/index.ts
  packages/remix-dev/config.ts
  packages/remix-react/entry.ts
  packages/remix-server-runtime/entry.ts
  packages/remix-testing/create-remix-stub.tsx
Labels: CLA Signed, package:dev

#6058 chore: update CSS bundling changesets
  .changeset/postcss-enabled-by-default.md
  .changeset/remove-unstable-css-modules.md
  .changeset/remove-unstable-css-side-effect-imports.md
  .changeset/remove-unstable-postcss.md
  .changeset/remove-unstable-tailwind.md
  .changeset/remove-unstable-vanilla-extract.md
  .changeset/tailwind-enabled-by-default.md
Labels: CLA Signed

#6064 docs: add docs for `isRouteErrorResponse`
  docs/utils/is-route-error-response.md
Labels: CLA Signed, docs

#6065 feat(remix-testing): cast types to use Remix type definitions + allow passing context
  .changeset/testing-helper-context-and-types.md
  packages/remix-testing/__tests__/stub-test.tsx
  packages/remix-testing/create-remix-stub.tsx
Labels: CLA Signed

#5696 feat!(remix-eslint-config): remove `@remix-run/eslint-config/jest` ESLint config
  .changeset/heavy-crabs-kick.md
  packages/remix-eslint-config/jest.js
Labels: CLA Signed, package:eslint-config

#5697 feat(remix-eslint-config): add deprecation warning to `@remix-run/eslint-config/jest` ESLint config
  .changeset/wicked-hairs-tell.md
  packages/remix-eslint-config/jest.js
Labels: CLA Signed, package:eslint-config

#5822 templates: use TS `server` file
  integration/helpers/cf-template/remix.config.js
  integration/helpers/cf-template/server.ts
  packages/remix-dev/__tests__/fixtures/cloudflare/remix.config.js
  packages/remix-dev/__tests__/fixtures/cloudflare/server.ts
  templates/arc/remix.config.js
  templates/arc/server.ts
  templates/cloudflare-pages/remix.config.js
  templates/cloudflare-pages/server.ts
  templates/cloudflare-workers/remix.config.js
  templates/cloudflare-workers/server.ts
  templates/express/package.json
  templates/express/server.ts
  templates/netlify/package.json
  templates/netlify/remix.config.js
  templates/netlify/server.js
  templates/netlify/server.ts
  templates/vercel/remix.config.js
  templates/vercel/server.ts
Labels: CLA Signed, template:architect, template:vercel, template:cloudflare-pages, template:cloudflare-workers, template:netlify

#5274 refactor(remix-dev): replace `@esbuild-plugins/node-modules-polyfill` with `esbuild-plugin-polyfill-node`
  packages/remix-dev/compiler/assets/css.ts
  packages/remix-dev/compiler/assets/js.ts
  packages/remix-dev/compiler/server/index.ts
  packages/remix-dev/package.json
  yarn.lock
Labels: CLA Signed, dependencies, javascript

#6057 docs: update references to CSS bundling
  docs/guides/migrating-react-router-app.md
  docs/guides/styling.md
Labels: CLA Signed, docs

#6045 chore(deps): bump `minimatch` to latest
  packages/remix-dev/config/flat-routes.ts
  packages/remix-dev/config/routesConvention.ts
  packages/remix-dev/package.json
  yarn.lock
Labels: CLA Signed, package:dev

#5705 feat!(remix-react,remix-server-runtime): remove deprecated properties from `HtmlLinkDescriptor`, `LinkDescriptor` & `PrefetchPageDescriptor` types
  .changeset/large-goats-double.md
  integration/action-test.ts
  integration/defer-test.ts
  packages/remix-react/components.tsx
  packages/remix-react/links.ts
  packages/remix-server-runtime/links.ts
Labels: CLA Signed, feat:typescript, package:server-runtime, renderer:react

#6071 docs(guides/typescript): add punctuation
  contributors.yml
  docs/guides/typescript.md
Labels: CLA Signed, docs

#6085 refactor(dev): clean up
  packages/remix-dev/cli.ts
  packages/remix-dev/cli/commands.ts
  packages/remix-dev/cli/error.ts
  packages/remix-dev/compiler/options.ts
  packages/remix-dev/compiler/server/index.ts
  packages/remix-dev/devServer/liveReload.ts
  packages/remix-dev/devServer_unstable/index.ts
  packages/remix-dev/index.ts
  packages/remix-dev/logging.ts
Labels: CLA Signed

#6082 chore: update `no-response` workflow
  .github/workflows/no-response.yml
Labels: CLA Signed

#6044 fix(deps): update `node-fetch`
  packages/remix-vercel/package.json
  yarn.lock
Labels: CLA Signed

#5732 feat!(remix-cloudflare,remix-cloudflare-pages,remix-cloudflare-workers): drop `@cloudflare/workers-types` v2 & v3 support
  .changeset/seven-queens-try.md
  packages/remix-cloudflare-pages/package.json
  packages/remix-cloudflare-workers/package.json
  packages/remix-cloudflare/package.json
  templates/cloudflare-pages/package.json
  templates/cloudflare-workers/package.json
  yarn.lock
Labels: CLA Signed, adapter:cloudflare-pages, adapter:cloudflare-workers, template:cloudflare-pages, template:cloudflare-workers, runtime:cloudflare

#5733 feat!(remix-netlify): drop `@netlify/functions` v0.x support
  .changeset/brown-gifts-chew.md
  packages/remix-netlify/package.json
Labels: CLA Signed, adapter:netlify

#5976 docs(pages/v2): remove default values from `serverBuildTarget` section
  docs/pages/v2.md
Labels: CLA Signed, docs

#6069 chore(templates): update dependencies to latest minor
  templates/arc/package.json
  templates/cloudflare-pages/package.json
  templates/cloudflare-workers/package.json
  templates/deno/package.json
  templates/express/package.json
  templates/fly/package.json
  templates/netlify/package.json
  templates/remix/package.json
  templates/vercel/package.json
Labels: CLA Signed, template:express, template:architect, template:vercel, template:cloudflare-pages, template:cloudflare-workers, template:fly, template:netlify, template:remix, template:deno

#6070 docs(tutorials/jokes): fix code highlighting
  docs/tutorials/jokes.md
Labels: CLA Signed, docs

#6098 fix: resolve route module imports back to virtual
  .changeset/mdx-automatic-jsx-runtime.md
  .changeset/unstable-dev-resolve-route-module-imports.md
  integration/shared-route-imports-test.ts
  packages/remix-dev/compiler/assets/js.ts
  packages/remix-dev/compiler/assets/plugins/routes_unstable.ts
  packages/remix-dev/compiler/plugins/mdx.ts
Labels: CLA Signed

#5947 docs: use TS files where possible
  decisions/0004-streaming-apis.md
  decisions/0005-remixing-react-router.md
  decisions/0007-remix-on-react-router-6-4-0.md
  docs/file-conventions/remix-config.md
  docs/file-conventions/route-files-v2.md
  docs/guides/constraints.md
  docs/guides/data-writes.md
  docs/guides/disabling-javascript.md
  docs/guides/envvars.md
  docs/guides/mdx.md
  docs/guides/migrating-react-router-app.md
  docs/guides/routing.md
  docs/guides/styling.md
  docs/hooks/use-fetcher.md
  docs/hooks/use-fetchers.md
  docs/hooks/use-matches.md
  docs/hooks/use-revalidator.md
  docs/hooks/use-transition.md
  docs/other-api/fetch.md
  docs/pages/faq.md
  docs/pages/gotchas.md
  docs/pages/technical-explanation.md
  docs/route/error-boundary-v2.md
  docs/route/handle.md
  docs/route/links.md
  docs/route/loader.md
  docs/route/should-revalidate.md
  docs/utils/cookies.md
  docs/utils/sessions.md
  integration/helpers/playwright-fixture.ts
  packages/remix-dev/__tests__/fixtures/deno/README.md
  packages/remix-eslint-config/README.md
  packages/remix-eslint-config/package.json
  packages/remix-react/CHANGELOG.md
  packages/remix-server-runtime/CHANGELOG.md
  templates/deno/README.md
  yarn.lock
Labels: CLA Signed, docs

#6089 chore: update `LICENSE`
  LICENSE.md
Labels: CLA Signed

#6122 fix(templates): import metafunction from remix runtime pkg
  templates/arc/app/routes/_index.tsx
  templates/cloudflare-pages/app/routes/_index.tsx
  templates/cloudflare-workers/app/routes/_index.tsx
  templates/deno/app/routes/_index.tsx
  templates/express/app/routes/_index.tsx
  templates/fly/app/routes/_index.tsx
  templates/netlify/app/routes/_index.tsx
  templates/remix/app/routes/_index.tsx
  templates/vercel/app/routes/_index.tsx
Labels: CLA Signed

#6123 fix(templates): import metafunction from remix runtime pkg
  templates/arc/app/routes/_index.tsx
  templates/cloudflare-pages/app/routes/_index.tsx
  templates/cloudflare-workers/app/routes/_index.tsx
  templates/deno/app/routes/_index.tsx
  templates/express/app/routes/_index.tsx
  templates/fly/app/routes/_index.tsx
  templates/netlify/app/routes/_index.tsx
  templates/remix/app/routes/_index.tsx
  templates/vercel/app/routes/_index.tsx
Labels: CLA Signed

#6124 test(mdx): create referenced css file
  integration/mdx-test.ts
Labels: CLA Signed

#6110 templates: add `css-bundle` boilerplate
  templates/arc/app/root.tsx
  templates/arc/package.json
  templates/cloudflare-pages/app/root.tsx
  templates/cloudflare-pages/package.json
  templates/cloudflare-workers/app/root.tsx
  templates/cloudflare-workers/package.json
  templates/deno/app/root.tsx
  templates/deno/package.json
  templates/express/app/root.tsx
  templates/express/package.json
  templates/fly/app/root.tsx
  templates/fly/package.json
  templates/netlify/app/root.tsx
  templates/netlify/package.json
  templates/remix/app/root.tsx
  templates/remix/package.json
  templates/vercel/app/root.tsx
  templates/vercel/package.json
Labels: CLA Signed, template:express, template:architect, template:vercel, template:cloudflare-pages, template:cloudflare-workers, template:fly, template:netlify, template:remix, template:deno

#6125 Fix false-positive resource route identification if a route only expo…
  .changeset/resource-route-boundary.md
  integration/resource-routes-test.ts
  packages/remix-react/components.tsx
Labels: CLA Signed

#6132 feat: add `@remix-run/node/install` side-effect to allow `--require`
  .changeset/install-globals.md
  packages/remix-node/install.d.ts
  packages/remix-node/install.js
  packages/remix-node/package.json
  packages/remix-node/rollup.config.js
  packages/remix-serve/env.ts
  packages/remix-serve/package.json
Labels: CLA Signed

#6138 docs(guides/streaming): remove text about AWS Lambda not supporting streaming
  contributors.yml
  docs/guides/streaming.md
Labels: CLA Signed, docs

#6136 templates: explicit installGlobals call in server entries
  templates/arc/server.ts
  templates/express/server.ts
  templates/netlify/server.ts
  templates/vercel/server.ts
Labels: CLA Signed, template:express, template:architect, template:vercel, template:netlify

#6133 feat(dev): unstable dev server improvements
  .changeset/dev-server.md
  integration/hmr-test.ts
  package.json
  packages/remix-dev/channel.ts
  packages/remix-dev/cli/commands.ts
  packages/remix-dev/cli/run.ts
  packages/remix-dev/compiler/compiler.ts
  packages/remix-dev/config.ts
  packages/remix-dev/devServer_unstable/env.ts
  packages/remix-dev/devServer_unstable/index.ts
  packages/remix-dev/devServer_unstable/ping.ts
  packages/remix-dev/devServer_unstable/socket.ts
  packages/remix-dev/index.ts
  packages/remix-dev/result.ts
  packages/remix-server-runtime/server.ts
  yarn.lock
Labels: CLA Signed

#6130 Fix splat route index matching
  .changeset/splat-index-matching.md
  integration/revalidate-test.ts
  integration/splat-routes-test.ts
  packages/remix-dev/__tests__/readConfig-test.ts
  packages/remix-dev/config.ts
Labels: CLA Signed

#6155 fix(dev): handle rebuilds that start before previous one finished
  integration/hmr-test.ts
  packages/remix-dev/devServer_unstable/index.ts
Labels: CLA Signed

#6154 feat(remix-dev): add warning for v2 "cjs"->"esm" defaults
  .changeset/cjs-esm-warning.md
  docs/pages/v2.md
  integration/hmr-test.ts
  packages/remix-dev/__tests__/create-test.ts
  packages/remix-dev/config.ts
Labels: CLA Signed, package:dev

#6157 fix(dev): get dependencies bin path for any package manager
  packages/remix-dev/cli/commands.ts
  packages/remix-dev/cli/create.ts
  packages/remix-dev/cli/detectPackageManager.ts
  packages/remix-dev/cli/getPreferredPackageManager.ts
  packages/remix-dev/cli/run.ts
  packages/remix-dev/codemod/replace-remix-magic-imports/index.ts
  packages/remix-dev/compiler/js/compiler.ts
  packages/remix-dev/compiler/server/plugins/bareImports.ts
  packages/remix-dev/config.ts
  packages/remix-dev/devServer_unstable/index.ts
Labels: CLA Signed

#6158 fix(dev): define `process.env.REMIX_DEV_HTTP_PORT` in server build
  packages/remix-dev/cli/commands.ts
  packages/remix-dev/compiler/options.ts
  packages/remix-dev/compiler/server/compiler.ts
  packages/remix-dev/compiler/server/plugins/entry.ts
  packages/remix-dev/devServer_unstable/index.ts
  packages/remix-react/__tests__/components-test.tsx
  packages/remix-react/browser.tsx
  packages/remix-react/components.tsx
  packages/remix-react/entry.ts
  packages/remix-server-runtime/build.ts
  packages/remix-server-runtime/serverHandoff.ts
Labels: CLA Signed

#6159 fix(dev): export `devReady` from runtime packages
  .changeset/dev-server.md
  integration/hmr-test.ts
  packages/remix-cloudflare/index.ts
  packages/remix-deno/index.ts
  packages/remix-dev/index.ts
  packages/remix-node/index.ts
  packages/remix-server-runtime/dev.ts
  packages/remix-server-runtime/index.ts
Labels: CLA Signed

#6135 feat: revalidate loaders only when a change to one is detected
  .changeset/hdr-revalidate-only-when-needed.md
  integration/hmr-test.ts
  packages/remix-react/browser.tsx
  packages/remix-react/components.tsx
  packages/remix-react/routes.tsx
Labels: CLA Signed

#6120 chore(remix-node): bump `@remix-run/web-fetch` to latest
  .github/workflows/test.yml
  integration/error-data-request-test.ts
  packages/remix-architect/__tests__/server-test.ts
  packages/remix-express/__tests__/server-test.ts
  packages/remix-netlify/__tests__/server-test.ts
  packages/remix-node/package.json
  packages/remix-vercel/__tests__/server-test.ts
  yarn.lock
Labels: CLA Signed, runtime:node

#6166 ci: disable tsc annotations for files changed
  .github/workflows/lint.yml
  .github/workflows/reusable-test.yml
Labels: CLA Signed

#6173 fix(dev): statically serve built assets from dev server
  .changeset/dev-server.md
  packages/remix-dev/__tests__/cli-test.ts
  packages/remix-dev/cli/commands.ts
  packages/remix-dev/cli/run.ts
  packages/remix-dev/compiler/options.ts
  packages/remix-dev/compiler/server/compiler.ts
  packages/remix-dev/config.ts
  packages/remix-dev/devServer_unstable/index.ts
  packages/remix-server-runtime/dev.ts
Labels: CLA Signed

#6175 fix(dev): reliably detect path to bin for deps
  packages/remix-dev/devServer_unstable/index.ts
Labels: CLA Signed

#6107 fix: short circuit links and meta for routes that are not rendered due to errors
  .changeset/link-meta-short-circuit.md
  integration/link-test.ts
  packages/remix-react/components.tsx
Labels: CLA Signed

#6174 feat: express template outputs ESM for build
  .changeset/express-template-esm.md
  templates/express/.eslintrc.cjs
  templates/express/package.json
  templates/express/remix.config.js
  templates/express/server.js
Labels: CLA Signed

#6177 feat(dev): dev command defaults to remix-serve
  .changeset/dev-server.md
  integration/hmr-test.ts
  packages/remix-dev/cli/commands.ts
  packages/remix-dev/devServer_unstable/index.ts
Labels: CLA Signed

#6179 chore(remix-node): add missing files to published package
  .changeset/two-pumpkins-roll.md
  packages/remix-node/package.json
Labels: CLA Signed

#6170 feat: support async `getLoadContext` in all adapters
  .changeset/async-load-context.md
  packages/remix-architect/server.ts
  packages/remix-cloudflare-pages/worker.ts
  packages/remix-cloudflare-workers/worker.ts
  packages/remix-express/server.ts
  packages/remix-netlify/server.ts
  packages/remix-vercel/server.ts
Labels: CLA Signed, adapter:architect, adapter:vercel, adapter:express, adapter:netlify, adapter:cloudflare-pages, adapter:cloudflare-workers

#6103 docs(pages/v2): typo heirarchy -> hierarchy
  contributors.yml
  docs/pages/v2.md
Labels: CLA Signed

#5545 docs(file-conventions/routes-files): Fix headers link
  contributors.yml
  docs/file-conventions/routes-files.md
Labels: CLA Signed

#5836 feat(remix-server-runtime): pass `AppLoadContext` to `handleRequest`
  .changeset/twelve-cheetahs-drive.md
  contributors.yml
  packages/remix-server-runtime/__tests__/server-test.ts
  packages/remix-server-runtime/__tests__/utils.ts
  packages/remix-server-runtime/build.ts
  packages/remix-server-runtime/server.ts
Labels: CLA Signed, package:server-runtime

#6181 fix(remix-dev): use correct require context in serverBareModulesPlugin
  .changeset/empty-taxis-call.md
  packages/remix-dev/compiler/server/plugins/bareImports.ts
Labels: CLA Signed

#6188 feat(serve): call `devReady` for dev server compatibility
  .changeset/dev-server.md
  packages/remix-serve/cli.ts
Labels: CLA Signed

#6180 template: enable unstable_dev by default in the remix template
  .changeset/pink-walls-hide.md
  templates/remix/remix.config.js
Labels: CLA Signed

#6121 fix(remix-react): adopt `react-router`'s removal of `useSyncExternalStore`
  .changeset/remove-use-sync-external-store.md
  package.json
  packages/remix-react/browser.tsx
  packages/remix-react/package.json
  packages/remix-react/routes.tsx
  packages/remix-server-runtime/package.json
  packages/remix-testing/package.json
  scripts/bump-router-versions.sh
  yarn.lock
Labels: CLA Signed, renderer:react

#6189 fix(dev): tracking of prev build even when rebuilds are interrupted
  packages/remix-dev/devServer_unstable/index.ts
Labels: CLA Signed

#6194 chore: rename devReady to broadcastDevReady
  .changeset/dev-server.md
  .changeset/modern-ways-eat.md
  integration/hmr-test.ts
  packages/remix-cloudflare/index.ts
  packages/remix-deno/index.ts
  packages/remix-dev/devServer_unstable/index.ts
  packages/remix-node/index.ts
  packages/remix-serve/cli.ts
  packages/remix-server-runtime/dev.ts
  packages/remix-server-runtime/index.ts
  templates/express/server.ts
Labels: CLA Signed

#6199 revert template changes from merge
  templates/express/.gitignore
  templates/express/package.json
  templates/express/server.js
Labels: CLA Signed

#6201 fix(react,dev): dev chunking and refresh race condition
  .changeset/dry-buses-care.md
  packages/remix-dev/compiler/js/compiler.ts
  packages/remix-dev/config/defaults/entry.dev.ts
  packages/remix-react/browser.tsx
Labels: CLA Signed

#6202 fix(dev): show first compilation error when build fails
  .changeset/thin-knives-try.md
  packages/remix-dev/compiler/compiler.ts
Labels: CLA Signed

#6156 chore: stop modifying user tsconfig
  .changeset/tsconfig-no-modify.md
  integration/tsconfig-test.ts
  packages/remix-dev/config.ts
  packages/remix-dev/config/write-tsconfig-defaults.ts
Labels: CLA Signed, package:dev

#6145 templates(express): fix `build`, `dev` & `start` scripts
  templates/express/server.js
Labels: CLA Signed, template:express

#6207 chore: quiet warnings in remix template
  templates/remix/remix.config.js
Labels: CLA Signed

#6208 fix: use renamed devReady method
  templates/express/server.js
Labels: CLA Signed

#6213 feat(remix-cloudflare): support `@cloudflare/workers-types` v4
  .changeset/chilly-hotels-sleep.md
  packages/remix-cloudflare/package.json
  templates/cloudflare-workers/.eslintrc.cjs
  templates/cloudflare-workers/build.d.ts
  templates/cloudflare-workers/package.json
  templates/cloudflare-workers/remix.config.js
  templates/cloudflare-workers/remix.env.d.ts
  templates/cloudflare-workers/server.ts
  templates/cloudflare-workers/wrangler.toml
Labels: CLA Signed, template:cloudflare-workers, runtime:cloudflare

#6217 Revert "feat(remix-cloudflare): support `@cloudflare/workers-types` v4"
  .changeset/chilly-hotels-sleep.md
  packages/remix-cloudflare/package.json
  templates/cloudflare-workers/.eslintrc.js
  templates/cloudflare-workers/build.d.ts
  templates/cloudflare-workers/package.json
  templates/cloudflare-workers/remix.config.js
  templates/cloudflare-workers/remix.env.d.ts
  templates/cloudflare-workers/server.ts
  templates/cloudflare-workers/wrangler.toml
Labels: CLA Signed

#6218 chore: revert templates using unstable_dev
  .changeset/express-template-esm.md
  templates/express/.eslintrc.js
  templates/express/package.json
  templates/express/remix.config.js
  templates/express/server.js
  templates/remix/remix.config.js
Labels: CLA Signed

#6219 chore(changeset): update dev server changeset
  .changeset/dev-server.md
Labels: CLA Signed

#6221 chore: fix cf template imports
  templates/cloudflare-pages/app/root.tsx
  templates/cloudflare-workers/app/root.tsx
Labels: CLA Signed

#6222 Revert "Fix splat route index matching
  .changeset/splat-index-matching-revert.md
  .changeset/splat-index-matching.md
  docs/tutorials/jokes.md
  integration/revalidate-test.ts
  integration/root-route-test.ts
  integration/splat-routes-test.ts
  packages/remix-dev/CHANGELOG.md
  packages/remix-dev/__tests__/readConfig-test.ts
  packages/remix-dev/config.ts
  packages/remix-server-runtime/CHANGELOG.md
Labels: CLA Signed

#6225 chore: write mjs server output files
  .changeset/clever-hairs-live.md
  integration/compiler-mjs-output-test.ts
  packages/remix-dev/compiler/server/write.ts
Labels: CLA Signed

#6228 fix: look for @remix-run/serve in devDependencies
  .changeset/afraid-mice-remain.md
  packages/remix-dev/cli/commands.ts
  packages/remix-dev/dependencies.ts
Labels: CLA Signed

#6233 bump router to stable
  .changeset/stable-router-versions.md
  packages/remix-react/package.json
  packages/remix-server-runtime/package.json
  packages/remix-testing/package.json
  yarn.lock
Labels: CLA Signed

#6243 docs(streaming): Fix useAsyncValue example
  docs/guides/streaming.md
Labels: CLA Signed, docs

#6239 chore: fix docs links
  docs/index.md
  packages/remix-css-bundle/README.md
  packages/remix-server-runtime/responses.ts
  templates/arc/app/entry.client.tsx
  templates/arc/app/entry.server.tsx
  templates/cloudflare-pages/app/entry.client.tsx
  templates/cloudflare-pages/app/entry.server.tsx
  templates/cloudflare-workers/app/entry.client.tsx
  templates/cloudflare-workers/app/entry.server.tsx
  templates/deno/app/entry.client.tsx
  templates/deno/app/entry.server.tsx
  templates/express/app/entry.client.tsx
  templates/express/app/entry.server.tsx
  templates/fly/app/entry.client.tsx
  templates/fly/app/entry.server.tsx
  templates/netlify/app/entry.client.tsx
  templates/netlify/app/entry.server.tsx
  templates/remix/app/entry.client.tsx
  templates/remix/app/entry.server.tsx
  templates/vercel/app/entry.client.tsx
  templates/vercel/app/entry.server.tsx
Labels: CLA Signed, docs, template:express, template:architect, template:vercel, template:cloudflare-pages, template:cloudflare-workers, template:fly, template:netlify, template:remix, template:deno

#6241 tests(remix-vercel): remove `@vercel/node-bridge` usage
  packages/remix-vercel/__tests__/server-test.ts
  packages/remix-vercel/package.json
  yarn.lock
Labels: CLA Signed, adapter:vercel

#6254 Revert "chore: update `no-response` workflow"
  .github/workflows/no-response.yml
Labels: CLA Signed
