Repository remix-run/remix, pull requests merged in 2023-12, with the labels that each got.

#8190 test(vite): refactor Vite CSS tests
  integration/helpers/vite.ts
  integration/vite-css-build-test.ts
  integration/vite-css-dev-express-test.ts
  integration/vite-css-dev-test.ts
  integration/vite-css-test.ts
  integration/vite-hmr-hdr-test.ts
Labels: CLA Signed, vite

#8171 feat(vite): strict route exports
  .changeset/grumpy-cats-roll.md
  docs/future/vite.md
  integration/vite-route-exports-test.ts
  packages/remix-dev/vite/plugin.ts
Labels: CLA Signed, package:dev, vite

#8193 docs(vite): align squiggly
  docs/future/vite.md
Labels: CLA Signed

#8194 docs(vite): add example to beginning of strict exports section
  docs/future/vite.md
Labels: CLA Signed

#8199 test(vite): dynamic .server imports are excluded from client
  integration/vite-dot-server-test.ts
Labels: CLA Signed

#8202 docs(sessions): remove not returned currentUser
  contributors.yml
  docs/utils/sessions.md
Labels: CLA Signed, docs

#8174 fix (remix-serve): Fix source map loading
  .changeset/sour-stingrays-roll.md
  packages/remix-serve/cli.ts
  templates/express/server.js
Labels: CLA Signed, package:serve, template:express

#8189 Support HMR/HDR for Client Data
  packages/remix-dev/devServer_unstable/hdr.ts
  packages/remix-dev/vite/plugin.ts
  packages/remix-dev/vite/static/refresh-utils.cjs
Labels: CLA Signed, package:dev, feat:dx

#8183 Client Data Documentation Updates
  .changeset/client-data.md
  .changeset/data-function-args.md
  docs/route/client-action.md
  docs/route/client-loader.md
  docs/route/hydrate-fallback.md
  docs/route/loader.md
Labels: CLA Signed, docs

#8173 Client Data Support
  .changeset/client-data.md
  .changeset/data-function-args.md
  docs/file-conventions/entry.server.md
  docs/route/client-action.md
  docs/route/client-loader.md
  docs/route/hydrate-fallback.md
  docs/route/loader.md
  integration/client-data-test.ts
  packages/remix-dev/compiler/js/plugins/routes.ts
  packages/remix-dev/compiler/manifest.ts
  packages/remix-dev/devServer_unstable/hdr.ts
  packages/remix-dev/manifest.ts
  packages/remix-dev/package.json
  packages/remix-dev/vite/plugin.ts
  packages/remix-dev/vite/static/refresh-utils.cjs
  packages/remix-react/browser.tsx
  packages/remix-react/data.ts
  packages/remix-react/errorBoundaries.tsx
  packages/remix-react/fallback.tsx
  packages/remix-react/index.tsx
  packages/remix-react/package.json
  packages/remix-react/routeModules.ts
  packages/remix-react/routes.tsx
  packages/remix-react/server.tsx
  packages/remix-server-runtime/build.ts
  packages/remix-server-runtime/data.ts
  packages/remix-server-runtime/package.json
  packages/remix-server-runtime/routeModules.ts
  packages/remix-testing/__tests__/stub-test.tsx
  packages/remix-testing/create-remix-stub.tsx
  packages/remix-testing/package.json
  scripts/bump-router-versions.sh
  yarn.lock
Labels: CLA Signed, feat:routing

#8216 Add future.v3_relativeSplatPath flag
  .changeset/relative-splat-path.md
  docs/components/form.md
  docs/components/link.md
  docs/hooks/use-href.md
  docs/hooks/use-navigate.md
  docs/hooks/use-resolved-path.md
  docs/hooks/use-submit.md
  integration/form-test.ts
  packages/remix-dev/__tests__/readConfig-test.ts
  packages/remix-dev/config.ts
  packages/remix-dev/package.json
  packages/remix-dev/vite/plugin.ts
  packages/remix-react/browser.tsx
  packages/remix-react/entry.ts
  packages/remix-react/package.json
  packages/remix-react/server.tsx
  packages/remix-server-runtime/entry.ts
  packages/remix-server-runtime/package.json
  packages/remix-server-runtime/server.ts
  packages/remix-testing/create-remix-stub.tsx
  packages/remix-testing/package.json
  yarn.lock
Labels: CLA Signed

#8211 fix(remix-dev/vite): add Vite commands to dev CLI
  .changeset/poor-eels-bow.md
  docs/future/vite.md
  integration/helpers/create-fixture.ts
  integration/helpers/vite-template/package.json
  integration/helpers/vite.ts
  integration/vite-dev-custom-entry-test.ts
  integration/vite-dev-test.ts
  integration/vite-dot-client-test.ts
  integration/vite-dot-server-test.ts
  integration/vite-route-exports-test.ts
  package.json
  packages/remix-dev/cli/commands.ts
  packages/remix-dev/cli/run.ts
  packages/remix-dev/vite/build.ts
  packages/remix-dev/vite/dev.ts
  packages/remix-dev/vite/plugin.ts
  templates/unstable-vite-express/package.json
  templates/unstable-vite/package.json
  yarn.lock
Labels: CLA Signed, package:dev, vite

#8220 fix(vite): make server .client exports undefined
  .changeset/rude-keys-heal.md
  packages/remix-dev/vite/plugin.ts
Labels: CLA Signed, package:dev, vite

#8221 refactor(vite): handle all future flags
  packages/remix-dev/vite/plugin.ts
Labels: CLA Signed, package:dev, vite

#8222 fix(remix-dev/vite): warn on source maps in build
  .changeset/sour-snakes-melt.md
  packages/remix-dev/vite/plugin.ts
Labels: CLA Signed, package:dev, vite

#8225 Bump web fetch dep
  .changeset/fast-cars-poke.md
  packages/remix-node/package.json
  yarn.lock
Labels: CLA Signed

#8227 Bump router
  .changeset/kind-radios-know.md
  packages/remix-dev/package.json
  packages/remix-react/package.json
  packages/remix-server-runtime/package.json
  packages/remix-testing/package.json
  yarn.lock
Labels: CLA Signed

#8231 Bump fetch
  .changeset/dull-numbers-fry.md
  packages/remix-node/package.json
  yarn.lock
Labels: CLA Signed

#8236 Minor client data implementation cleanups
  .changeset/pink-pumpkins-clean.md
  integration/client-data-test.ts
  packages/remix-react/browser.tsx
  packages/remix-react/routes.tsx
  packages/remix-react/server.tsx
Labels: CLA Signed

#8238 Add error type to server runtime meta args
  .changeset/big-cooks-confess.md
  contributors.yml
  packages/remix-server-runtime/routeModules.ts
Labels: CLA Signed, feat:typescript, package:server-runtime

#8229 Add Client Data guide to docs
  docs/guides/client-data.md
  docs/route/client-action.md
  docs/route/client-loader.md
  docs/route/hydrate-fallback.md
Labels: CLA Signed, docs

#8244 docs(vite): add link to publint for troubleshooting esm/cjs
  docs/future/vite.md
Labels: CLA Signed

#8245 Cherry-pick dependabot updates
  yarn.lock
Labels: CLA Signed, dependencies

#7778 docs(utils/sessions): clarify `session.id`
  docs/utils/sessions.md
Labels: CLA Signed, docs

#8248 Add missing fields to EntryRoute
  .changeset/short-mayflies-stare.md
  packages/remix-server-runtime/routes.ts
Labels: CLA Signed

#8253 Minor client data edge case fixes
  .changeset/mean-falcons-love.md
  integration/client-data-test.ts
  packages/remix-react/routes.tsx
Labels: CLA Signed

#8260 docs(vite): Update TypeScript integration guide
  docs/future/vite.md
Labels: CLA Signed, docs, vite

#8261 docs(vite): Clarify TypeScript guide steps
  docs/future/vite.md
Labels: CLA Signed, docs, vite

#8264 fix(vite): remove virtual server build ID export
  .changeset/breezy-walls-scream.md
  docs/future/vite.md
  integration/helpers/vite.ts
  packages/remix-dev/index.ts
  packages/remix-dev/vite/index.ts
  packages/remix-dev/vite/plugin.ts
  packages/remix-dev/vite/server-entry-id.ts
  packages/remix-dev/vite/vmod.ts
  templates/unstable-vite-express/server.mjs
Labels: CLA Signed, package:dev, vite

#8265 refactor(vite): rename Vite dev server variable
  docs/future/vite.md
  integration/helpers/vite.ts
  templates/unstable-vite-express/server.mjs
Labels: CLA Signed, docs, vite

#8266 fix(vite): Remove Vite production use warnings
  docs/future/vite.md
  packages/remix-dev/vite/plugin.ts
Labels: CLA Signed, package:dev, vite

#8267 feat(vite): error messages when .server files are referenced by client
  .changeset/breezy-grapes-roll.md
  integration/package.json
  integration/vite-dot-server-test.ts
  packages/remix-dev/vite/plugin.ts
  yarn.lock
Labels: CLA Signed

#8272 docs(discussion/server-vs-client) Add missing `formData` to `action` example
  contributors.yml
  docs/discussion/server-vs-client.md
Labels: CLA Signed, docs

#8275 Remove @remix-run/eslint-config references from unit test fixtures
  packages/remix-dev/__tests__/fixtures/cloudflare/.eslintrc.cjs
  packages/remix-dev/__tests__/fixtures/cloudflare/package.json
  packages/remix-dev/__tests__/fixtures/node/.eslintrc.js
  packages/remix-dev/__tests__/fixtures/node/package.json
Labels: CLA Signed

#8269 Enhance client data type inference
  .changeset/clean-boats-deliver.md
  packages/remix-server-runtime/jsonify.ts
  packages/remix-server-runtime/routeModules.ts
  packages/remix-server-runtime/serialize.ts
Labels: CLA Signed, feat:typescript

#8277 Lock into stable router versions
  .changeset/metal-dragons-wink.md
  packages/remix-dev/package.json
  packages/remix-react/package.json
  packages/remix-server-runtime/package.json
  packages/remix-testing/package.json
  yarn.lock
Labels: CLA Signed

#8284 chore(templates): Update Vite template readmes
  templates/unstable-vite-express/README.md
  templates/unstable-vite/README.md
Labels: CLA Signed, vite

#8287 docs(changelog): fix client-action link in changelog
  CHANGELOG.md
  contributors.yml
Labels: CLA Signed, docs

#8286 add codeblock tag
  contributors.yml
  docs/start/tutorial.md
Labels: CLA Signed, docs

#8299 docs(vite): Add note about CSS import order
  docs/future/vite.md
Labels: CLA Signed

#8297 Add helpful pointer for how to read uploaded files
  contributors.yml
  docs/utils/parse-multipart-form-data.md
Labels: CLA Signed

#8308 Add encType application/json to useSubmit docs
  docs/hooks/use-submit.md
Labels: CLA Signed

#8317 fix(templates/vite): remove unnecessary eslint ignore
  templates/unstable-vite-express/vite.config.ts
  templates/unstable-vite/vite.config.ts
Labels: CLA Signed

#8318 fix(templates/vite): no polyfills by default
  templates/unstable-vite/vite.config.ts
Labels: CLA Signed

#8323 docs: fix link in `remix-config.md`
  contributors.yml
  docs/file-conventions/remix-config.md
Labels: CLA Signed

#8314 Update v2.md to specify installing v1 route convention as dev dep
  docs/start/v2.md
Labels: CLA Signed

#8312 docs(vite): fix incorrect build output path
  docs/future/vite.md
Labels: CLA Signed

#8307 docs(vite) use server.ts as file name, not server.tsx
  docs/future/vite.md
Labels: CLA Signed

#8321 fix (remix-serve): convert file url to path when loading source maps
  .changeset/angry-poets-accept.md
  contributors.yml
  packages/remix-serve/cli.ts
  templates/express/server.js
Labels: CLA Signed, package:serve, template:express

#8327 docs(vite): migrating full stack components
  docs/future/vite.md
Labels: CLA Signed

#8339 fix(remix-dev/vite): preload Vite ESM build in CLI
  packages/remix-dev/vite/build.ts
  packages/remix-dev/vite/dev.ts
Labels: CLA Signed, package:dev, vite

#8320 fix(vite): disable `server.watch` for child compiler during build
  packages/remix-dev/vite/plugin.ts
Labels: CLA Signed, package:dev, vite

#8342 chore(vite): add changeset for disabling build watch
  .changeset/seven-bees-thank.md
Labels: CLA Signed

#8346 Bump router
  .changeset/sharp-ants-march.md
  packages/remix-dev/package.json
  packages/remix-react/package.json
  packages/remix-server-runtime/package.json
  packages/remix-testing/package.json
  yarn.lock
Labels: CLA Signed

#8348 Bump router
  .changeset/lazy-rivers-boil.md
  packages/remix-dev/package.json
  packages/remix-react/package.json
  packages/remix-server-runtime/package.json
  packages/remix-testing/package.json
  yarn.lock
Labels: CLA Signed

#8353 fix(vite): fix errors for non-existent `index.html` importer
  .changeset/curly-coats-reflect.md
  packages/remix-dev/vite/plugin.ts
Labels: CLA Signed

#8332 feat(remix-dev/vite): Add unstable_serverBundles
  .changeset/five-peaches-attend.md
  .changeset/flat-toys-hope.md
  docs/future/server-bundles.md
  docs/future/vite.md
  integration/helpers/vite.ts
  integration/vite-server-bundles-test.ts
  packages/remix-dev/cli/commands.ts
  packages/remix-dev/index.ts
  packages/remix-dev/vite/build.ts
  packages/remix-dev/vite/index.ts
  packages/remix-dev/vite/plugin.ts
Labels: CLA Signed, package:dev, vite

#8351 Re-export response helpers through react package
  .changeset/twelve-cars-work.md
  packages/remix-react/index.tsx
Labels: CLA Signed

#8355 fix(remix-dev/vite): rename bundles manifest key
  integration/vite-server-bundles-test.ts
  packages/remix-dev/vite/build.ts
Labels: CLA Signed, package:dev, vite
