Repository remix-run/remix, pull requests merged in 2023-01, with the labels that each got.

#4984 docs(tutorials/jokes): fix code highlighting
  contributors.yml
  docs/tutorials/jokes.md
Labels: CLA Signed, docs

#4989 docs(tutorials/jokes): Fix link to the scripts component
  contributors.yml
  docs/tutorials/jokes.md
Labels: CLA Signed

#4966 ci(nightly): revert to comparing sha instead of checking for changes against dev
  .github/workflows/nightly.yml
Labels: CLA Signed

#4898 refactor(remix-architect): use `@architect/functions`' built-in types
  .changeset/modern-pumas-hide.md
  packages/remix-architect/package.json
  packages/remix-architect/sessions/arcTableSessionStorage.ts
  yarn.lock
Labels: CLA Signed, adapter:architect

#4852 feat: CSS Modules support
  .changeset/little-avocados-fetch.md
  docs/guides/migrating-react-router-app.md
  docs/guides/styling.md
  integration/css-modules-test.ts
  integration/deterministic-build-output-test.ts
  package.json
  packages/remix-css-bundle/README.md
  packages/remix-css-bundle/browser.ts
  packages/remix-css-bundle/package.json
  packages/remix-css-bundle/rollup.config.js
  packages/remix-css-bundle/server.ts
  packages/remix-css-bundle/tsconfig.json
  packages/remix-dev/__tests__/readConfig-test.ts
  packages/remix-dev/assets-manifest.d.ts
  packages/remix-dev/compiler/assets.ts
  packages/remix-dev/compiler/compileBrowser.ts
  packages/remix-dev/compiler/compilerServer.ts
  packages/remix-dev/compiler/plugins/cssBundleEntryModulePlugin.ts
  packages/remix-dev/compiler/plugins/cssModulesPlugin.ts
  packages/remix-dev/compiler/plugins/serverBareModulesPlugin.ts
  packages/remix-dev/config.ts
  packages/remix-dev/index.ts
  packages/remix-dev/modules.ts
  packages/remix-dev/package.json
  packages/remix-react/entry.ts
  packages/remix-server-runtime/entry.ts
  packages/remix-testing/create-remix-stub.tsx
  scripts/publish.js
  scripts/utils.js
  tsconfig.json
  yarn.lock
Labels: CLA Signed, package:dev, package:css-bundle

#4913 fix: fix Deno lint errors
  packages/remix-deno/server.ts
Labels: CLA Signed

#4998 templates: don't use `window` in `entry.client.tsx`
  integration/helpers/node-template/app/entry.client.tsx
  scripts/playground/template/app/entry.client.tsx
  templates/arc/app/entry.client.tsx
  templates/cloudflare-pages/app/entry.client.tsx
  templates/cloudflare-workers/app/entry.client.tsx
  templates/deno/app/entry.client.tsx
  templates/express/app/entry.client.tsx
  templates/fly/app/entry.client.tsx
  templates/netlify/app/entry.client.tsx
  templates/remix/app/entry.client.tsx
  templates/vercel/app/entry.client.tsx
Labels: CLA Signed, template:express, template:architect, template:vercel, template:cloudflare-pages, template:cloudflare-workers, template:fly, template:netlify, template:remix, template:deno

#4995 fix(remix-react): fix `content-type` on proxied action request
  .changeset/cool-crews-kneel.md
  packages/remix-react/data.ts
Labels: CLA Signed, renderer:react

#4999 chore(templates): use typeof check for `requestIdleCallback`
  integration/helpers/node-template/app/entry.client.tsx
  scripts/playground/template/app/entry.client.tsx
  templates/arc/app/entry.client.tsx
  templates/cloudflare-pages/app/entry.client.tsx
  templates/cloudflare-workers/app/entry.client.tsx
  templates/deno/app/entry.client.tsx
  templates/express/app/entry.client.tsx
  templates/fly/app/entry.client.tsx
  templates/netlify/app/entry.client.tsx
  templates/remix/app/entry.client.tsx
  templates/vercel/app/entry.client.tsx
Labels: CLA Signed, template:express, template:architect, template:vercel, template:cloudflare-pages, template:cloudflare-workers, template:fly, template:netlify, template:remix, template:deno

#5001 Add integration test for 404 loader behavior
  integration/catch-boundary-test.ts
Labels: CLA Signed

#5005 Bump RR to 6.6.2-pre.0
  .changeset/few-seas-hunt.md
  packages/remix-react/package.json
  packages/remix-testing/package.json
  yarn.lock
Labels: CLA Signed

#4880 feat(remix-dev): flat routes
  .changeset/eight-forks-collect.md
  .prettierignore
  packages/remix-dev/__tests__/defineRoutes-test.ts
  packages/remix-dev/__tests__/flat-routes-test.ts
  packages/remix-dev/__tests__/readConfig-test.ts
  packages/remix-dev/__tests__/routesConvention-test.ts
  packages/remix-dev/config.ts
  packages/remix-dev/config/flat-routes.ts
  packages/remix-dev/config/routes.ts
  packages/remix-dev/config/routesConvention.ts
Labels: CLA Signed, package:dev

#5013 chore(remix-dev): update flat-routes invalid character error message to include link to RR proposal
  .changeset/curvy-mangos-heal.md
  packages/remix-dev/config/flat-routes.ts
Labels: CLA Signed

#5014 chore(remix-dev): don't allow `*` to be anywhere in segment
  .changeset/little-lobsters-decide.md
  packages/remix-dev/__tests__/flat-routes-test.ts
  packages/remix-dev/config/flat-routes.ts
Labels: CLA Signed

#5012 Add outer RemixErrorBoundary to catch root boundary-thrown errors
  .changeset/eighty-hounds-mix.md
  integration/error-boundary-test.ts
  package.json
  packages/remix-react/browser.tsx
  packages/remix-react/package.json
  packages/remix-react/server.tsx
  packages/remix-server-runtime/server.ts
  yarn.lock
Labels: CLA Signed

#4865 feat(remix-dev): suport `handle` in frontmatter
  .changeset/smart-doors-sing.md
  docs/guides/mdx.md
  integration/mdx-test.ts
  packages/remix-dev/compiler/plugins/mdx.ts
Labels: CLA Signed, package:dev

#5035 Lock into react-router 6.6.2 stable release
  .changeset/dry-coins-relax.md
  packages/remix-react/package.json
  packages/remix-testing/package.json
  yarn.lock
Labels: CLA Signed

#5039 chore: Update version for release
  .changeset/big-geese-cry.md
  .changeset/cool-crews-kneel.md
  .changeset/dry-coins-relax.md
  .changeset/eighty-hounds-mix.md
  .changeset/few-seas-hunt.md
  .changeset/gentle-yaks-lick.md
  .changeset/honest-phones-visit.md
  .changeset/late-bottles-shop.md
  .changeset/lucky-chairs-remember.md
  .changeset/many-zebras-arrive.md
  .changeset/metal-birds-tease.md
  .changeset/mighty-rules-drum.md
  .changeset/pre.json
  .changeset/quick-cats-fix.md
  .changeset/rotten-bulldogs-reply.md
  .changeset/rude-colts-fold.md
  .changeset/shaggy-garlics-confess.md
  .changeset/silver-ducks-protect.md
  .changeset/thirty-eels-taste.md
  packages/create-remix/CHANGELOG.md
  packages/create-remix/package.json
  packages/remix-architect/CHANGELOG.md
  packages/remix-architect/package.json
  packages/remix-cloudflare-pages/CHANGELOG.md
  packages/remix-cloudflare-pages/package.json
  packages/remix-cloudflare-workers/CHANGELOG.md
  packages/remix-cloudflare-workers/package.json
  packages/remix-cloudflare/CHANGELOG.md
  packages/remix-cloudflare/package.json
  packages/remix-deno/CHANGELOG.md
  packages/remix-deno/package.json
  packages/remix-dev/CHANGELOG.md
  packages/remix-dev/package.json
  packages/remix-eslint-config/CHANGELOG.md
  packages/remix-eslint-config/package.json
  packages/remix-express/CHANGELOG.md
  packages/remix-express/package.json
  packages/remix-netlify/CHANGELOG.md
  packages/remix-netlify/package.json
  packages/remix-node/CHANGELOG.md
  packages/remix-node/package.json
  packages/remix-react/CHANGELOG.md
  packages/remix-react/package.json
  packages/remix-serve/CHANGELOG.md
  packages/remix-serve/package.json
  packages/remix-server-runtime/CHANGELOG.md
  packages/remix-server-runtime/package.json
  packages/remix-testing/CHANGELOG.md
  packages/remix-testing/package.json
  packages/remix-vercel/CHANGELOG.md
  packages/remix-vercel/package.json
  packages/remix/package.json
Labels: CLA Signed

#5047 Update babel config to transpile down to node 14
  .changeset/purple-ads-itch.md
  babel.config.js
Labels: CLA Signed

#5034 fix: update flat-route module check for file colocation
  .changeset/funny-numbers-type.md
  packages/remix-dev/__tests__/flat-routes-test.ts
  packages/remix-dev/config/flat-routes.ts
Labels: CLA Signed

#5042 fix: write assets from CSS bundle build
  integration/css-modules-test.ts
  integration/css-side-effect-imports-test.ts
  packages/remix-dev/compiler/compileBrowser.ts
Labels: bug, CLA Signed, package:dev

#5040 feat: add Vanilla Extract support
  .changeset/giant-kings-repair.md
  .changeset/hungry-owls-greet.md
  .changeset/little-avocados-fetch.md
  docs/guides/styling.md
  integration/css-modules-test.ts
  integration/css-side-effect-imports-test.ts
  integration/deterministic-build-output-test.ts
  integration/vanilla-extract-test.ts
  package.json
  packages/remix-dev/__tests__/readConfig-test.ts
  packages/remix-dev/compiler/compileBrowser.ts
  packages/remix-dev/compiler/compilerServer.ts
  packages/remix-dev/compiler/plugins/vanillaExtractPlugin.ts
  packages/remix-dev/config.ts
  packages/remix-dev/package.json
  packages/remix-react/entry.ts
  packages/remix-server-runtime/entry.ts
  packages/remix-testing/create-remix-stub.tsx
  yarn.lock
Labels: CLA Signed, package:dev

#5062 docs(utils/cookies): Fix missing imports
  docs/utils/cookies.md
Labels: CLA Signed

#5053 chore: Update version for release (pre)
  .changeset/pre.json
  packages/create-remix/CHANGELOG.md
  packages/create-remix/package.json
  packages/remix-architect/CHANGELOG.md
  packages/remix-architect/package.json
  packages/remix-cloudflare-pages/CHANGELOG.md
  packages/remix-cloudflare-pages/package.json
  packages/remix-cloudflare-workers/CHANGELOG.md
  packages/remix-cloudflare-workers/package.json
  packages/remix-cloudflare/CHANGELOG.md
  packages/remix-cloudflare/package.json
  packages/remix-deno/CHANGELOG.md
  packages/remix-deno/package.json
  packages/remix-dev/CHANGELOG.md
  packages/remix-dev/package.json
  packages/remix-eslint-config/CHANGELOG.md
  packages/remix-eslint-config/package.json
  packages/remix-express/CHANGELOG.md
  packages/remix-express/package.json
  packages/remix-netlify/CHANGELOG.md
  packages/remix-netlify/package.json
  packages/remix-node/CHANGELOG.md
  packages/remix-node/package.json
  packages/remix-react/CHANGELOG.md
  packages/remix-react/package.json
  packages/remix-serve/CHANGELOG.md
  packages/remix-serve/package.json
  packages/remix-server-runtime/CHANGELOG.md
  packages/remix-server-runtime/package.json
  packages/remix-testing/CHANGELOG.md
  packages/remix-testing/package.json
  packages/remix-vercel/CHANGELOG.md
  packages/remix-vercel/package.json
  packages/remix/package.json
Labels: CLA Signed

#5030 chore(remix-dev): add file extensions to compiler/loaders
  .changeset/bright-moons-attend.md
  contributors.yml
  packages/remix-dev/compiler/loaders.ts
  packages/remix-dev/modules.ts
Labels: CLA Signed

#5066 chore: Update version for release (pre)
  .changeset/pre.json
  packages/create-remix/CHANGELOG.md
  packages/create-remix/package.json
  packages/remix-architect/CHANGELOG.md
  packages/remix-architect/package.json
  packages/remix-cloudflare-pages/CHANGELOG.md
  packages/remix-cloudflare-pages/package.json
  packages/remix-cloudflare-workers/CHANGELOG.md
  packages/remix-cloudflare-workers/package.json
  packages/remix-cloudflare/CHANGELOG.md
  packages/remix-cloudflare/package.json
  packages/remix-deno/CHANGELOG.md
  packages/remix-deno/package.json
  packages/remix-dev/CHANGELOG.md
  packages/remix-dev/package.json
  packages/remix-eslint-config/CHANGELOG.md
  packages/remix-eslint-config/package.json
  packages/remix-express/CHANGELOG.md
  packages/remix-express/package.json
  packages/remix-netlify/CHANGELOG.md
  packages/remix-netlify/package.json
  packages/remix-node/CHANGELOG.md
  packages/remix-node/package.json
  packages/remix-react/CHANGELOG.md
  packages/remix-react/package.json
  packages/remix-serve/CHANGELOG.md
  packages/remix-serve/package.json
  packages/remix-server-runtime/CHANGELOG.md
  packages/remix-server-runtime/package.json
  packages/remix-testing/CHANGELOG.md
  packages/remix-testing/package.json
  packages/remix-vercel/CHANGELOG.md
  packages/remix-vercel/package.json
  packages/remix/package.json
Labels: CLA Signed

#5068 ci: update previous release detection
  scripts/release/comment.ts
  scripts/release/constants.ts
  scripts/release/github.ts
  scripts/release/utils.ts
Labels: CLA Signed

#5057 docs(guides/styling): fix highlighted lines for CSS bundle setup
  docs/guides/styling.md
Labels: CLA Signed, docs

#5094 chore: Update version for release
  .changeset/eighty-donkeys-run.md
  .changeset/pre.json
  .changeset/purple-ads-itch.md
  packages/create-remix/CHANGELOG.md
  packages/create-remix/package.json
  packages/remix-architect/CHANGELOG.md
  packages/remix-architect/package.json
  packages/remix-cloudflare-pages/CHANGELOG.md
  packages/remix-cloudflare-pages/package.json
  packages/remix-cloudflare-workers/CHANGELOG.md
  packages/remix-cloudflare-workers/package.json
  packages/remix-cloudflare/CHANGELOG.md
  packages/remix-cloudflare/package.json
  packages/remix-deno/CHANGELOG.md
  packages/remix-deno/package.json
  packages/remix-dev/CHANGELOG.md
  packages/remix-dev/package.json
  packages/remix-eslint-config/CHANGELOG.md
  packages/remix-eslint-config/package.json
  packages/remix-express/CHANGELOG.md
  packages/remix-express/package.json
  packages/remix-netlify/CHANGELOG.md
  packages/remix-netlify/package.json
  packages/remix-node/CHANGELOG.md
  packages/remix-node/package.json
  packages/remix-react/CHANGELOG.md
  packages/remix-react/package.json
  packages/remix-serve/CHANGELOG.md
  packages/remix-serve/package.json
  packages/remix-server-runtime/CHANGELOG.md
  packages/remix-server-runtime/package.json
  packages/remix-testing/CHANGELOG.md
  packages/remix-testing/package.json
  packages/remix-vercel/CHANGELOG.md
  packages/remix-vercel/package.json
  packages/remix/package.json
Labels: CLA Signed

#4918 Add future.v2_errorBoundary flag
  .changeset/odd-numbers-film.md
  integration/error-boundary-v2-test.ts
  integration/helpers/create-fixture.ts
  integration/helpers/node-template/remix.config.js
  packages/remix-dev/__tests__/readConfig-test.ts
  packages/remix-dev/config.ts
  packages/remix-react/browser.tsx
  packages/remix-react/components.tsx
  packages/remix-react/entry.ts
  packages/remix-react/errorBoundaries.tsx
  packages/remix-react/index.tsx
  packages/remix-react/routeModules.ts
  packages/remix-react/routes.tsx
  packages/remix-react/server.tsx
  packages/remix-server-runtime/__tests__/data-test.ts
  packages/remix-server-runtime/__tests__/handler-test.ts
  packages/remix-server-runtime/__tests__/server-test.ts
  packages/remix-server-runtime/__tests__/utils.ts
  packages/remix-server-runtime/entry.ts
  packages/remix-server-runtime/routes.ts
  packages/remix-server-runtime/server.ts
  packages/remix-testing/create-remix-stub.tsx
Labels: CLA Signed, package:dev, package:server-runtime, renderer:react, package:testing

#4920 defer - for real this time
  .changeset/old-cameras-lay.md
  integration/defer-loader-test.ts
  integration/defer-test.ts
  integration/helpers/node-template/app/entry.server.tsx
  packages/remix-cloudflare/index.ts
  packages/remix-deno/index.ts
  packages/remix-node/index.ts
  packages/remix-react/__tests__/hook-types-test.tsx
  packages/remix-react/browser.tsx
  packages/remix-react/components.tsx
  packages/remix-react/data.ts
  packages/remix-react/entry.ts
  packages/remix-react/index.tsx
  packages/remix-react/markup.ts
  packages/remix-react/package.json
  packages/remix-react/routes.tsx
  packages/remix-react/server.tsx
  packages/remix-server-runtime/data.ts
  packages/remix-server-runtime/index.ts
  packages/remix-server-runtime/package.json
  packages/remix-server-runtime/reexport.ts
  packages/remix-server-runtime/responses.ts
  packages/remix-server-runtime/serialize.ts
  packages/remix-server-runtime/server.ts
  packages/remix-server-runtime/serverHandoff.ts
  packages/remix-testing/package.json
  yarn.lock
Labels: CLA Signed, feat:routing, package:server-runtime, renderer:react, feat:deferred

#5097 chore: Update version for release (pre)
  .changeset/pre.json
  packages/create-remix/CHANGELOG.md
  packages/create-remix/package.json
  packages/remix-architect/CHANGELOG.md
  packages/remix-architect/package.json
  packages/remix-cloudflare-pages/CHANGELOG.md
  packages/remix-cloudflare-pages/package.json
  packages/remix-cloudflare-workers/CHANGELOG.md
  packages/remix-cloudflare-workers/package.json
  packages/remix-cloudflare/CHANGELOG.md
  packages/remix-cloudflare/package.json
  packages/remix-css-bundle/CHANGELOG.md
  packages/remix-css-bundle/package.json
  packages/remix-deno/CHANGELOG.md
  packages/remix-deno/package.json
  packages/remix-dev/CHANGELOG.md
  packages/remix-dev/package.json
  packages/remix-eslint-config/CHANGELOG.md
  packages/remix-eslint-config/package.json
  packages/remix-express/CHANGELOG.md
  packages/remix-express/package.json
  packages/remix-netlify/CHANGELOG.md
  packages/remix-netlify/package.json
  packages/remix-node/CHANGELOG.md
  packages/remix-node/package.json
  packages/remix-react/CHANGELOG.md
  packages/remix-react/package.json
  packages/remix-serve/CHANGELOG.md
  packages/remix-serve/package.json
  packages/remix-server-runtime/CHANGELOG.md
  packages/remix-server-runtime/package.json
  packages/remix-testing/CHANGELOG.md
  packages/remix-testing/package.json
  packages/remix-vercel/CHANGELOG.md
  packages/remix-vercel/package.json
  packages/remix/package.json
Labels: CLA Signed

#5118 Ensure useFetcher is stable across re-renders in back-compat layer
  .changeset/lovely-seals-sin.md
  packages/remix-react/CHANGELOG.md
  packages/remix-react/components.tsx
  packages/remix-server-runtime/CHANGELOG.md
  yarn.lock
Labels: CLA Signed

#5120 Bump react router versions for 1.11 prerelease
  .changeset/famous-brooms-hunt.md
  integration/error-data-request-test.ts
  packages/remix-react/package.json
  packages/remix-server-runtime/package.json
  packages/remix-testing/package.json
  yarn.lock
Labels: CLA Signed

#5119 chore: Update version for release (pre)
  .changeset/lovely-seals-sin.md
  .changeset/pre.json
  packages/create-remix/CHANGELOG.md
  packages/create-remix/package.json
  packages/remix-architect/CHANGELOG.md
  packages/remix-architect/package.json
  packages/remix-cloudflare-pages/CHANGELOG.md
  packages/remix-cloudflare-pages/package.json
  packages/remix-cloudflare-workers/CHANGELOG.md
  packages/remix-cloudflare-workers/package.json
  packages/remix-cloudflare/CHANGELOG.md
  packages/remix-cloudflare/package.json
  packages/remix-css-bundle/CHANGELOG.md
  packages/remix-css-bundle/package.json
  packages/remix-deno/CHANGELOG.md
  packages/remix-deno/package.json
  packages/remix-dev/CHANGELOG.md
  packages/remix-dev/package.json
  packages/remix-eslint-config/CHANGELOG.md
  packages/remix-eslint-config/package.json
  packages/remix-express/CHANGELOG.md
  packages/remix-express/package.json
  packages/remix-netlify/CHANGELOG.md
  packages/remix-netlify/package.json
  packages/remix-node/CHANGELOG.md
  packages/remix-node/package.json
  packages/remix-react/CHANGELOG.md
  packages/remix-react/package.json
  packages/remix-serve/CHANGELOG.md
  packages/remix-serve/package.json
  packages/remix-server-runtime/CHANGELOG.md
  packages/remix-server-runtime/package.json
  packages/remix-testing/CHANGELOG.md
  packages/remix-testing/package.json
  packages/remix-vercel/CHANGELOG.md
  packages/remix-vercel/package.json
  packages/remix/package.json
Labels: CLA Signed

#5126 chore(docs,templates): update `typecheck` script
  docs/guides/typescript.md
  packages/remix-dev/__tests__/fixtures/replace-remix-magic-imports/package.json
  packages/remix-dev/__tests__/migrations/fixtures/indie-stack/package.json
  templates/arc/package.json
  templates/cloudflare-pages/package.json
  templates/cloudflare-workers/package.json
  templates/express/package.json
  templates/fly/package.json
  templates/netlify/package.json
  templates/remix/package.json
  templates/vercel/package.json
Labels: CLA Signed, docs, template:express, template:architect, template:vercel, template:cloudflare-pages, template:cloudflare-workers, template:fly, template:netlify, template:remix

#4835 docs: fix `useActionData`/`useLoaderData` usage
  docs/file-conventions/routes-files.md
  docs/guides/file-uploads.md
  docs/guides/routing.md
  docs/hooks/use-action-data.md
  docs/hooks/use-fetcher.md
  docs/hooks/use-loader-data.md
  docs/hooks/use-submit.md
  docs/route/action.md
  docs/route/loader.md
  docs/route/meta.md
  docs/route/should-reload.md
  docs/utils/cookies.md
  docs/utils/json.md
  docs/utils/parse-multipart-form-data.md
  docs/utils/redirect.md
  docs/utils/sessions.md
  docs/utils/unstable-create-file-upload-handler.md
  docs/utils/unstable-create-memory-upload-handler.md
Labels: CLA Signed, docs

#5129 fix(tests): fix `typecheck` script in fixtures
  packages/remix-dev/__tests__/fixtures/replace-remix-magic-imports/package.json
  packages/remix-dev/__tests__/migrations/fixtures/indie-stack/package.json
Labels: CLA Signed

#5128 fix(remix-testing): use `router.routes` so routes have ids
  .changeset/mighty-beans-judge.md
  jest.config.js
  packages/remix-testing/__tests__/stub-test.tsx
  packages/remix-testing/create-remix-stub.tsx
  packages/remix-testing/jest.config.js
  packages/remix-testing/jest.setup.js
Labels: CLA Signed

#5130 ci(comment): update package check
  scripts/release/github.ts
Labels: CLA Signed

#5134 docs: added meta@v2 docs
  docs/route/meta.md
Labels: CLA Signed, docs

#5135 chore: Update version for release
  .changeset/bright-moons-attend.md
  .changeset/eight-forks-collect.md
  .changeset/five-kings-work.md
  .changeset/giant-kings-repair.md
  .changeset/hungry-owls-greet.md
  .changeset/little-avocados-fetch.md
  .changeset/lovely-seals-sin.md
  .changeset/modern-pumas-hide.md
  .changeset/odd-numbers-film.md
  .changeset/old-cameras-lay.md
  .changeset/pre.json
  .changeset/smart-doors-sing.md
  packages/create-remix/CHANGELOG.md
  packages/create-remix/package.json
  packages/remix-architect/CHANGELOG.md
  packages/remix-architect/package.json
  packages/remix-cloudflare-pages/CHANGELOG.md
  packages/remix-cloudflare-pages/package.json
  packages/remix-cloudflare-workers/CHANGELOG.md
  packages/remix-cloudflare-workers/package.json
  packages/remix-cloudflare/CHANGELOG.md
  packages/remix-cloudflare/package.json
  packages/remix-css-bundle/CHANGELOG.md
  packages/remix-css-bundle/package.json
  packages/remix-deno/CHANGELOG.md
  packages/remix-deno/package.json
  packages/remix-dev/CHANGELOG.md
  packages/remix-dev/package.json
  packages/remix-eslint-config/CHANGELOG.md
  packages/remix-eslint-config/package.json
  packages/remix-express/CHANGELOG.md
  packages/remix-express/package.json
  packages/remix-netlify/CHANGELOG.md
  packages/remix-netlify/package.json
  packages/remix-node/CHANGELOG.md
  packages/remix-node/package.json
  packages/remix-react/CHANGELOG.md
  packages/remix-react/package.json
  packages/remix-serve/CHANGELOG.md
  packages/remix-serve/package.json
  packages/remix-server-runtime/CHANGELOG.md
  packages/remix-server-runtime/package.json
  packages/remix-testing/CHANGELOG.md
  packages/remix-testing/package.json
  packages/remix-vercel/CHANGELOG.md
  packages/remix-vercel/package.json
  packages/remix/package.json
Labels: CLA Signed

#5121 docs: initial defer docs
  docs/components/await.md
  docs/guides/streaming.md
  docs/utils/defer.md
Labels: CLA Signed

#5136 chore: update to ReactNode instead of Element
  packages/remix-react/components.tsx
Labels: CLA Signed

#5133 The new dev server
  .changeset/mean-clocks-bow.md
  packages/remix-dev/__tests__/readConfig-test.ts
  packages/remix-dev/cli/commands.ts
  packages/remix-dev/cli/run.ts
  packages/remix-dev/compiler/compilerServer.ts
  packages/remix-dev/compiler/options.ts
  packages/remix-dev/compiler/plugins/serverEntryModulePlugin.ts
  packages/remix-dev/compiler/remixCompiler.ts
  packages/remix-dev/compiler/watch.ts
  packages/remix-dev/config.ts
  packages/remix-dev/devServer2.ts
  packages/remix-dev/liveReload.ts
  packages/remix-dev/server-build.ts
  packages/remix-react/__tests__/components-test.tsx
  packages/remix-react/components.tsx
  packages/remix-react/entry.ts
  packages/remix-server-runtime/__tests__/server-test.ts
  packages/remix-server-runtime/__tests__/utils.ts
  packages/remix-server-runtime/build.ts
  packages/remix-server-runtime/entry.ts
  packages/remix-server-runtime/server.ts
  packages/remix-server-runtime/serverHandoff.ts
Labels: CLA Signed

#5138 docs(route/meta): fix typo
  docs/route/meta.md
Labels: CLA Signed, docs

#5145 docs(Await): Fix `useLoaderData` link
  contributors.yml
  docs/components/await.md
Labels: CLA Signed

#5148 chore: fix lint errors
  packages/remix-react/CHANGELOG.md
  packages/remix-server-runtime/CHANGELOG.md
Labels: CLA Signed

#5137 fix(dev): keep dev server process alive after initial build
  .changeset/mean-clocks-bow.md
  packages/remix-dev/cli/commands.ts
  packages/remix-dev/config.ts
  packages/remix-dev/devServer2.ts
Labels: CLA Signed

#5149 chore(eslint): ignore `no-extraneous-deps` in markdown files
  .eslintrc.js
  packages/create-remix/.eslintrc.js
  packages/remix-react/CHANGELOG.md
  packages/remix-server-runtime/.eslintrc.js
  packages/remix-server-runtime/CHANGELOG.md
Labels: CLA Signed

#5141 ci: update playwright reporter in ci
  integration/playwright.config.ts
Labels: CLA Signed

#5146 docs(utils/defer): Fix highlighting, and use defer instead of json
  docs/utils/defer.md
Labels: docs

#5125 feat: pass a custom config reader to `watch`
  contributors.yml
  packages/remix-dev/compiler/watch.ts
Labels: CLA Signed

#5160 fix(remix-dev/flat-routes): use `index` without leading underscore for colocation
  .changeset/fresh-needles-join.md
  packages/remix-dev/__tests__/flat-routes-test.ts
  packages/remix-dev/config/flat-routes.ts
Labels: CLA Signed

#5163 Support JS conversion for app code without `jscodeshift`
  decisions/0008-only-support-js-conversion-for-app-code.md
  packages/remix-dev/__tests__/cli-test.ts
  packages/remix-dev/__tests__/codemod-test.ts
  packages/remix-dev/__tests__/create-test.ts
  packages/remix-dev/__tests__/fixtures/indie-stack/app/entry.client.tsx
  packages/remix-dev/__tests__/fixtures/indie-stack/app/entry.server.tsx
  packages/remix-dev/__tests__/fixtures/indie-stack/app/root.tsx
  packages/remix-dev/__tests__/fixtures/indie-stack/app/routes/index.tsx
  packages/remix-dev/__tests__/fixtures/indie-stack/cypress/e2e/smoke.cy.ts
  packages/remix-dev/__tests__/fixtures/indie-stack/cypress/support/commands.ts
  packages/remix-dev/__tests__/fixtures/indie-stack/cypress/support/create-user.ts
  packages/remix-dev/__tests__/fixtures/indie-stack/cypress/support/delete-user.ts
  packages/remix-dev/__tests__/fixtures/indie-stack/cypress/support/e2e.ts
  packages/remix-dev/__tests__/fixtures/indie-stack/mocks/index.js
  packages/remix-dev/__tests__/fixtures/indie-stack/package.json
  packages/remix-dev/__tests__/fixtures/indie-stack/prisma/seed.ts
  packages/remix-dev/__tests__/fixtures/indie-stack/public/favicon.ico
  packages/remix-dev/__tests__/fixtures/indie-stack/remix.config.js
  packages/remix-dev/__tests__/fixtures/indie-stack/remix.env.d.ts
  packages/remix-dev/__tests__/fixtures/indie-stack/test/setup-test-env.ts
  packages/remix-dev/__tests__/fixtures/indie-stack/tsconfig.json
  packages/remix-dev/__tests__/fixtures/indie-stack/vitest.config.ts
  packages/remix-dev/__tests__/migrations/convert-to-javascript-test.ts
  packages/remix-dev/__tests__/useJavascript-test.ts
  packages/remix-dev/cli/create.ts
  packages/remix-dev/cli/migrate/flags.ts
  packages/remix-dev/cli/migrate/jscodeshift.ts
  packages/remix-dev/cli/migrate/migrations/convert-to-javascript/cleanupPackageJson.ts
  packages/remix-dev/cli/migrate/migrations/convert-to-javascript/convertTSConfigs.ts
  packages/remix-dev/cli/migrate/migrations/convert-to-javascript/convertTSFilesToJS/convertTSFileToJS.ts
  packages/remix-dev/cli/migrate/migrations/convert-to-javascript/convertTSFilesToJS/index.ts
  packages/remix-dev/cli/migrate/migrations/convert-to-javascript/index.ts
  packages/remix-dev/cli/migrate/migrations/convert-to-javascript/transform/checkNoDifferentImportTypesCombined.ts
  packages/remix-dev/cli/migrate/migrations/convert-to-javascript/transform/createExportExpressionStatementFromExportDefaultDeclaration.ts
  packages/remix-dev/cli/migrate/migrations/convert-to-javascript/transform/createImportExpressionStatement.ts
  packages/remix-dev/cli/migrate/migrations/convert-to-javascript/transform/createVariableDeclarationIdentifier.ts
  packages/remix-dev/cli/migrate/migrations/convert-to-javascript/transform/createVariableDeclarationObjectPattern.ts
  packages/remix-dev/cli/migrate/migrations/convert-to-javascript/transform/index.ts
  packages/remix-dev/cli/migrate/migrations/transforms.ts
  packages/remix-dev/cli/migrate/types.ts
  packages/remix-dev/cli/useJavascript.ts
  packages/remix-dev/package.json
  packages/remix-dev/rollup.config.js
  yarn.lock
Labels: CLA Signed

#5167 chore: Update version for release
  .changeset/fresh-needles-join.md
  packages/create-remix/CHANGELOG.md
  packages/create-remix/package.json
  packages/remix-architect/CHANGELOG.md
  packages/remix-architect/package.json
  packages/remix-cloudflare-pages/CHANGELOG.md
  packages/remix-cloudflare-pages/package.json
  packages/remix-cloudflare-workers/CHANGELOG.md
  packages/remix-cloudflare-workers/package.json
  packages/remix-cloudflare/CHANGELOG.md
  packages/remix-cloudflare/package.json
  packages/remix-css-bundle/CHANGELOG.md
  packages/remix-css-bundle/package.json
  packages/remix-deno/CHANGELOG.md
  packages/remix-deno/package.json
  packages/remix-dev/CHANGELOG.md
  packages/remix-dev/package.json
  packages/remix-eslint-config/CHANGELOG.md
  packages/remix-eslint-config/package.json
  packages/remix-express/CHANGELOG.md
  packages/remix-express/package.json
  packages/remix-netlify/CHANGELOG.md
  packages/remix-netlify/package.json
  packages/remix-node/CHANGELOG.md
  packages/remix-node/package.json
  packages/remix-react/CHANGELOG.md
  packages/remix-react/package.json
  packages/remix-serve/CHANGELOG.md
  packages/remix-serve/package.json
  packages/remix-server-runtime/CHANGELOG.md
  packages/remix-server-runtime/package.json
  packages/remix-testing/CHANGELOG.md
  packages/remix-testing/package.json
  packages/remix-vercel/CHANGELOG.md
  packages/remix-vercel/package.json
  packages/remix/package.json
Labels: CLA Signed

#4884 refactor(remix-cloudflare-workers): bring `RequestHandler` in line with other adapters
  .changeset/afraid-hounds-join.md
  packages/remix-cloudflare-workers/worker.ts
Labels: CLA Signed, adapter:cloudflare-workers

#4924 docs: add pages for React Router components/hooks
  docs/components/form.md
  docs/components/outlet.md
  docs/hooks/use-async-error.md
  docs/hooks/use-async-value.md
  docs/hooks/use-before-unload.md
  docs/hooks/use-fetcher.md
  docs/hooks/use-form-action.md
  docs/hooks/use-href.md
  docs/hooks/use-location.md
  docs/hooks/use-navigate.md
  docs/hooks/use-navigation-type.md
  docs/hooks/use-navigation.md
  docs/hooks/use-outlet-context.md
  docs/hooks/use-outlet.md
  docs/hooks/use-params.md
  docs/hooks/use-resolved-path.md
  docs/hooks/use-revalidator.md
  docs/hooks/use-route-error.md
  docs/hooks/use-route-loader-data.md
  docs/hooks/use-search-params.md
  docs/hooks/use-submit.md
Labels: CLA Signed, docs

#4408 feat(remix-node): add `getFilePath`& `remove` methods to `NodeOnDiskFile`
  .changeset/flat-cobras-beam.md
  contributors.yml
  packages/remix-node/__tests__/fileUploadHandler-test.ts
  packages/remix-node/upload/fileUploadHandler.ts
Labels: CLA Signed, runtime:node, NEW API

#5176 docs(tutorials/blog): fix code highlighting
  contributors.yml
  docs/tutorials/blog.md
Labels: CLA Signed, docs

#5194 docs(file-conventions): Fix entry.server link
  contributors.yml
  docs/file-conventions/entry.client.md
Labels: CLA Signed

#5181 docs(file-conventions/route-files-v2): add missing file in tree structure
  contributors.yml
  docs/file-conventions/route-files-v2.md
Labels: CLA Signed, docs

#4925 chore: fix `version` script
  scripts/utils.js
Labels: CLA Signed

#5215 docs(file-conventions/route-files-v2): fix line highlight
  docs/file-conventions/route-files-v2.md
Labels: CLA Signed

#5220 refactor(dev): simplifications
  packages/remix-dev/compiler/utils/fs.ts
  packages/remix-dev/config.ts
Labels: CLA Signed

#5077 chore(bug-report): Make sure the reporter have aligned remix dependencies
  .github/ISSUE_TEMPLATE/bug_report.yml
Labels: CLA Signed

#4801 refactor(remix-server-runtime): remove `react` & `react-dom` from `peerDependencies`
  .changeset/short-bobcats-switch.md
  packages/remix-server-runtime/package.json
  packages/remix-server-runtime/routeModules.ts
Labels: CLA Signed, package:server-runtime

#5178 fix(remix-react): export `CatchBoundaryComponent` type
  packages/remix-react/index.tsx
Labels: CLA Signed, feat:typescript, renderer:react

#2542 feat(remix-cloudflare): rename `createCloudflareKVSessionStorage` to `createWorkersKVSessionStorage`
  .changeset/breezy-dancers-lie.md
  docs/api/remix.md
  docs/utils/sessions.md
  integration/cf-compiler-test.ts
  packages/remix-cloudflare/index.ts
  packages/remix-cloudflare/sessions/workersKVStorage.ts
  packages/remix-dev/__tests__/transform-replaceRemixMagicImports-test.ts
  packages/remix-dev/codemod/replace-remix-magic-imports/utils/export.ts
  packages/remix-eslint-config/rules/packageExports.js
  rollup.utils.js
Labels: CLA Signed, runtime:cloudflare

#5223 fix(dev): dev server maintains clean build directories
  .changeset/tender-turtles-wash.md
  packages/remix-dev/cli/commands.ts
  packages/remix-dev/devServer/liveReload.ts
  packages/remix-dev/devServer/serve.ts
  packages/remix-dev/devServer2.ts
Labels: CLA Signed, package:dev

#5204 fix(remix-node): export `JsonFunction` as type instead of as value
  .changeset/old-rice-drive.md
  packages/remix-node/index.ts
Labels: CLA Signed, feat:typescript, runtime:node

#5206 fix(remix-cloudflare,remix-deno): export `JsonFunction` type
  .changeset/silver-rockets-remember.md
  packages/remix-cloudflare/index.ts
  packages/remix-deno/index.ts
Labels: CLA Signed, feat:typescript, runtime:cloudflare, runtime:deno

#5219 chore(remix-dev): update `@vanilla-extract/integration`
  packages/remix-dev/package.json
  yarn.lock
Labels: CLA Signed, package:dev

#2602 feat(remix-dev): improve types for imported MD & MDX files
  contributors.yml
  packages/remix-dev/modules.ts
Labels: CLA Signed, feat:typescript, package:dev

#5177 docs: add information about throwing `redirect`s
  docs/route/loader.md
  docs/utils/redirect.md
Labels: CLA Signed, docs

#3777 chore(remix-node): update jsdoc for `FileUploadHandlerOptions`' `filter`
  packages/remix-node/upload/fileUploadHandler.ts
Labels: CLA Signed, runtime:node, feat:file-upload

#5242 Bump react router versions
  .changeset/silent-cups-double.md
  integration/form-test.ts
  packages/remix-react/package.json
  packages/remix-server-runtime/package.json
  packages/remix-testing/package.json
  yarn.lock
Labels: CLA Signed

#5245 fix: bug report yaml parsing Yes as Boolean
  .github/ISSUE_TEMPLATE/bug_report.yml
  contributors.yml
Labels: CLA Signed

#5229 feat: add built-in PostCSS and Tailwind support
  .changeset/gorgeous-meals-rescue.md
  .changeset/lemon-humans-yell.md
  docs/guides/styling.md
  integration/css-modules-test.ts
  integration/css-side-effect-imports-test.ts
  integration/deterministic-build-output-test.ts
  integration/postcss-test.ts
  integration/tailwind-test.ts
  integration/vanilla-extract-test.ts
  package.json
  packages/remix-dev/__tests__/readConfig-test.ts
  packages/remix-dev/compiler/compileBrowser.ts
  packages/remix-dev/compiler/compilerServer.ts
  packages/remix-dev/compiler/plugins/cssFilePlugin.ts
  packages/remix-dev/compiler/plugins/cssModulesPlugin.ts
  packages/remix-dev/compiler/plugins/cssSideEffectImportsPlugin.ts
  packages/remix-dev/compiler/plugins/vanillaExtractPlugin.ts
  packages/remix-dev/compiler/utils/postcss.ts
  packages/remix-dev/config.ts
  packages/remix-dev/package.json
  packages/remix-react/entry.ts
  packages/remix-server-runtime/entry.ts
  packages/remix-testing/create-remix-stub.tsx
  yarn.lock
Labels: CLA Signed, package:dev, package:server-runtime, renderer:react, package:testing

#5246 fix: mark Vanilla Extract files as side effects
  .changeset/healthy-beers-nail.md
  integration/vanilla-extract-test.ts
  packages/remix-dev/compiler/plugins/cssSideEffectImportsPlugin.ts
  packages/remix-dev/compiler/plugins/vanillaExtractPlugin.ts
Labels: bug, CLA Signed, package:dev

#5155 docs(guides/streaming): update `serverAbortDelay` to `abortDelay`
  docs/guides/streaming.md
Labels: CLA Signed, docs

#5252 docs(guides/styling): fix Tailwind CSS installation instructions
  contributors.yml
  docs/guides/styling.md
Labels: CLA Signed, docs

#5251 fix(remix-dev): Server build should not be removed in `remix watch` and `remix dev`
  contributors.yml
  packages/remix-dev/devServer/liveReload.ts
  packages/remix-dev/devServer2.ts
Labels: CLA Signed, package:dev

#5243 chore: Update version for release (pre)
  .changeset/pre.json
  packages/create-remix/CHANGELOG.md
  packages/create-remix/package.json
  packages/remix-architect/CHANGELOG.md
  packages/remix-architect/package.json
  packages/remix-cloudflare-pages/CHANGELOG.md
  packages/remix-cloudflare-pages/package.json
  packages/remix-cloudflare-workers/CHANGELOG.md
  packages/remix-cloudflare-workers/package.json
  packages/remix-cloudflare/CHANGELOG.md
  packages/remix-cloudflare/package.json
  packages/remix-css-bundle/CHANGELOG.md
  packages/remix-css-bundle/package.json
  packages/remix-deno/CHANGELOG.md
  packages/remix-deno/package.json
  packages/remix-dev/CHANGELOG.md
  packages/remix-dev/package.json
  packages/remix-eslint-config/CHANGELOG.md
  packages/remix-eslint-config/package.json
  packages/remix-express/CHANGELOG.md
  packages/remix-express/package.json
  packages/remix-netlify/CHANGELOG.md
  packages/remix-netlify/package.json
  packages/remix-node/CHANGELOG.md
  packages/remix-node/package.json
  packages/remix-react/CHANGELOG.md
  packages/remix-react/package.json
  packages/remix-serve/CHANGELOG.md
  packages/remix-serve/package.json
  packages/remix-server-runtime/CHANGELOG.md
  packages/remix-server-runtime/package.json
  packages/remix-testing/CHANGELOG.md
  packages/remix-testing/package.json
  packages/remix-vercel/CHANGELOG.md
  packages/remix-vercel/package.json
  packages/remix/package.json
Labels: CLA Signed

#5092 feat(remix-react): allow `<Link>`'s "to" prop to accept absolute urls
  .changeset/odd-plants-doubt.md
  packages/remix-react/components.tsx
Labels: CLA Signed

#5256 chore: Update version for release (pre)
  .changeset/pre.json
  packages/create-remix/CHANGELOG.md
  packages/create-remix/package.json
  packages/remix-architect/CHANGELOG.md
  packages/remix-architect/package.json
  packages/remix-cloudflare-pages/CHANGELOG.md
  packages/remix-cloudflare-pages/package.json
  packages/remix-cloudflare-workers/CHANGELOG.md
  packages/remix-cloudflare-workers/package.json
  packages/remix-cloudflare/CHANGELOG.md
  packages/remix-cloudflare/package.json
  packages/remix-css-bundle/CHANGELOG.md
  packages/remix-css-bundle/package.json
  packages/remix-deno/CHANGELOG.md
  packages/remix-deno/package.json
  packages/remix-dev/CHANGELOG.md
  packages/remix-dev/package.json
  packages/remix-eslint-config/CHANGELOG.md
  packages/remix-eslint-config/package.json
  packages/remix-express/CHANGELOG.md
  packages/remix-express/package.json
  packages/remix-netlify/CHANGELOG.md
  packages/remix-netlify/package.json
  packages/remix-node/CHANGELOG.md
  packages/remix-node/package.json
  packages/remix-react/CHANGELOG.md
  packages/remix-react/package.json
  packages/remix-serve/CHANGELOG.md
  packages/remix-serve/package.json
  packages/remix-server-runtime/CHANGELOG.md
  packages/remix-server-runtime/package.json
  packages/remix-testing/CHANGELOG.md
  packages/remix-testing/package.json
  packages/remix-vercel/CHANGELOG.md
  packages/remix-vercel/package.json
  packages/remix/package.json
Labels: CLA Signed

#5260 chore: Update version for release (pre)
  .changeset/pre.json
  packages/create-remix/CHANGELOG.md
  packages/create-remix/package.json
  packages/remix-architect/CHANGELOG.md
  packages/remix-architect/package.json
  packages/remix-cloudflare-pages/CHANGELOG.md
  packages/remix-cloudflare-pages/package.json
  packages/remix-cloudflare-workers/CHANGELOG.md
  packages/remix-cloudflare-workers/package.json
  packages/remix-cloudflare/CHANGELOG.md
  packages/remix-cloudflare/package.json
  packages/remix-css-bundle/CHANGELOG.md
  packages/remix-css-bundle/package.json
  packages/remix-deno/CHANGELOG.md
  packages/remix-deno/package.json
  packages/remix-dev/CHANGELOG.md
  packages/remix-dev/package.json
  packages/remix-eslint-config/CHANGELOG.md
  packages/remix-eslint-config/package.json
  packages/remix-express/CHANGELOG.md
  packages/remix-express/package.json
  packages/remix-netlify/CHANGELOG.md
  packages/remix-netlify/package.json
  packages/remix-node/CHANGELOG.md
  packages/remix-node/package.json
  packages/remix-react/CHANGELOG.md
  packages/remix-react/package.json
  packages/remix-serve/CHANGELOG.md
  packages/remix-serve/package.json
  packages/remix-server-runtime/CHANGELOG.md
  packages/remix-server-runtime/package.json
  packages/remix-testing/CHANGELOG.md
  packages/remix-testing/package.json
  packages/remix-vercel/CHANGELOG.md
  packages/remix-vercel/package.json
  packages/remix/package.json
Labels: CLA Signed

#5262 docs(file-conventions/route-files-v2): fix typo
  contributors.yml
  docs/file-conventions/route-files-v2.md
Labels: CLA Signed, docs

#5264 docs(route/meta): cleanup
  docs/route/meta.md
Labels: CLA Signed, docs

#5266 fix(remix-dev): fast glob will return posix style paths even on windows
  .changeset/hip-cats-warn.md
  packages/remix-dev/config/flat-routes.ts
Labels: CLA Signed, package:dev

#5283 fix(dev): keep dev server process alive
  packages/remix-dev/cli/commands.ts
  packages/remix-dev/devServer/serve.ts
Labels: CLA Signed

#5284 ci(nightly): update sorting
  .github/workflows/nightly.yml
Labels: CLA Signed

#5249 docs: cleanup docs
  docs/components/await.md
  docs/components/form.md
  docs/components/links.md
  docs/components/live-reload.md
  docs/components/meta.md
  docs/components/nav-link.md
  docs/components/outlet.md
  docs/components/prefetch-page-links.md
  docs/components/scripts.md
  docs/file-conventions/entry.client.md
  docs/file-conventions/entry.server.md
  docs/file-conventions/root.md
  docs/guides/bff.md
  docs/guides/streaming.md
  docs/guides/typescript.md
  docs/hooks/use-action-data.md
  docs/hooks/use-before-unload.md
  docs/hooks/use-fetchers.md
  docs/hooks/use-form-action.md
  docs/hooks/use-loader-data.md
  docs/hooks/use-matches.md
  docs/hooks/use-navigation.md
  docs/hooks/use-revalidator.md
  docs/hooks/use-route-loader-data.md
  docs/hooks/use-submit.md
  docs/other-api/asset-imports.md
  docs/other-api/node.md
  docs/other-api/serve.md
  docs/utils/defer.md
  docs/utils/json.md
  docs/utils/redirect.md
  docs/utils/unstable-create-file-upload-handler.md
  docs/utils/unstable-create-memory-upload-handler.md
Labels: CLA Signed, docs

#5254 docs(other-api/adapter): add community adapters
  docs/other-api/adapter.md
  docs/pages/community.md
Labels: CLA Signed, docs

#4808 docs(guide/data-writes): add missing json imports
  contributors.yml
  docs/guides/data-writes.md
Labels: CLA Signed, docs

#5293 docs(guide/data-writes.md): fix linting
  docs/guides/data-writes.md
Labels: CLA Signed

#5292 docs(tutorials/jokes): remove `ActionData` references
  docs/tutorials/jokes.md
Labels: CLA Signed, docs

#5294 docs: cleanup highlighted lines and imports
  docs/guides/api-routes.md
  docs/guides/constraints.md
  docs/guides/data-writes.md
  docs/guides/disabling-javascript.md
  docs/guides/envvars.md
  docs/hooks/use-matches.md
  docs/other-api/adapter.md
  docs/pages/technical-explanation.md
Labels: CLA Signed, docs

#5299 docs(route/should-revalidate): Fix shouldRevalidate typing
  contributors.yml
  docs/route/should-revalidate.md
Labels: CLA Signed, docs

#5305 fix: support decorators with CSS side-effects
  .changeset/honest-crabs-sort.md
  packages/remix-dev/__tests__/cssSideEffectsPlugin-test.ts
  packages/remix-dev/compiler/plugins/cssSideEffectImportsPlugin.ts
Labels: CLA Signed, package:dev

#5308 docs(pages/*): punctuation
  contributors.yml
  docs/pages/community.md
  docs/pages/contributing.md
  docs/pages/faq.md
  docs/pages/gotchas.md
  docs/pages/philosophy.md
  docs/pages/stacks.md
  docs/pages/technical-explanation.md
Labels: CLA Signed

#5306 docs(tutorials/jokes): Remove unused json import
  contributors.yml
  docs/tutorials/jokes.md
Labels: CLA Signed

#5076 docs(route/headers): add missing types on `headers()`
  contributors.yml
  docs/route/headers.md
Labels: CLA Signed, docs

#5307 docs: add CSS bundle tree-shaking issue warnings
  docs/guides/styling.md
  docs/pages/gotchas.md
Labels: CLA Signed, docs

#5316 docs(file-conventions/route-files-v2): Fix typo
  contributors.yml
  docs/file-conventions/route-files-v2.md
Labels: CLA Signed, docs

#5317 chore: Update version for release (pre)
  .changeset/pre.json
  packages/create-remix/CHANGELOG.md
  packages/create-remix/package.json
  packages/remix-architect/CHANGELOG.md
  packages/remix-architect/package.json
  packages/remix-cloudflare-pages/CHANGELOG.md
  packages/remix-cloudflare-pages/package.json
  packages/remix-cloudflare-workers/CHANGELOG.md
  packages/remix-cloudflare-workers/package.json
  packages/remix-cloudflare/CHANGELOG.md
  packages/remix-cloudflare/package.json
  packages/remix-css-bundle/CHANGELOG.md
  packages/remix-css-bundle/package.json
  packages/remix-deno/CHANGELOG.md
  packages/remix-deno/package.json
  packages/remix-dev/CHANGELOG.md
  packages/remix-dev/package.json
  packages/remix-eslint-config/CHANGELOG.md
  packages/remix-eslint-config/package.json
  packages/remix-express/CHANGELOG.md
  packages/remix-express/package.json
  packages/remix-netlify/CHANGELOG.md
  packages/remix-netlify/package.json
  packages/remix-node/CHANGELOG.md
  packages/remix-node/package.json
  packages/remix-react/CHANGELOG.md
  packages/remix-react/package.json
  packages/remix-serve/CHANGELOG.md
  packages/remix-serve/package.json
  packages/remix-server-runtime/CHANGELOG.md
  packages/remix-server-runtime/package.json
  packages/remix-testing/CHANGELOG.md
  packages/remix-testing/package.json
  packages/remix-vercel/CHANGELOG.md
  packages/remix-vercel/package.json
  packages/remix/package.json
Labels: CLA Signed

#5318 chore: Update version for release
  .changeset/afraid-hounds-join.md
  .changeset/breezy-dancers-lie.md
  .changeset/hip-cats-warn.md
  .changeset/mean-clocks-bow.md
  .changeset/mighty-beans-judge.md
  .changeset/odd-plants-doubt.md
  .changeset/pink-ducks-impress.md
  .changeset/pre.json
  .changeset/short-bobcats-switch.md
  .changeset/silent-cups-double.md
  .changeset/tender-turtles-wash.md
  .changeset/wild-foxes-wait.md
  .changeset/yellow-ligers-clean.md
  packages/create-remix/CHANGELOG.md
  packages/create-remix/package.json
  packages/remix-architect/CHANGELOG.md
  packages/remix-architect/package.json
  packages/remix-cloudflare-pages/CHANGELOG.md
  packages/remix-cloudflare-pages/package.json
  packages/remix-cloudflare-workers/CHANGELOG.md
  packages/remix-cloudflare-workers/package.json
  packages/remix-cloudflare/CHANGELOG.md
  packages/remix-cloudflare/package.json
  packages/remix-css-bundle/CHANGELOG.md
  packages/remix-css-bundle/package.json
  packages/remix-deno/CHANGELOG.md
  packages/remix-deno/package.json
  packages/remix-dev/CHANGELOG.md
  packages/remix-dev/package.json
  packages/remix-eslint-config/CHANGELOG.md
  packages/remix-eslint-config/package.json
  packages/remix-express/CHANGELOG.md
  packages/remix-express/package.json
  packages/remix-netlify/CHANGELOG.md
  packages/remix-netlify/package.json
  packages/remix-node/CHANGELOG.md
  packages/remix-node/package.json
  packages/remix-react/CHANGELOG.md
  packages/remix-react/package.json
  packages/remix-serve/CHANGELOG.md
  packages/remix-serve/package.json
  packages/remix-server-runtime/CHANGELOG.md
  packages/remix-server-runtime/package.json
  packages/remix-testing/CHANGELOG.md
  packages/remix-testing/package.json
  packages/remix-vercel/CHANGELOG.md
  packages/remix-vercel/package.json
  packages/remix/package.json
Labels: CLA Signed

#5320 docs: fix broken links, typos, and punctuation
  docs/components/form.md
  docs/components/link.md
  docs/file-conventions/entry.server.md
  docs/guides/constraints.md
  docs/hooks/use-action-data.md
  docs/hooks/use-fetcher.md
  docs/other-api/adapter.md
  docs/other-api/dev.md
  docs/other-api/serve.md
  docs/route/action.md
  docs/route/loader.md
  docs/route/meta.md
  docs/route/should-revalidate.md
  docs/utils/cookies.md
  docs/utils/sessions.md
Labels: CLA Signed
