Repository remix-run/remix, pull requests merged in 2023-10, with the labels that each got.

#7536 Fix comment on default for serverModuleFormat
  docs/start/v2.md
Labels: CLA Signed, docs

#7574 fix: sourcemap takes into account special chars in output file
  .changeset/fix-cf-sourcemaps.md
  packages/remix-dev/compiler/server/write.ts
Labels: CLA Signed

#7580 docs(start/tutorial): fix incorrect spelling of the word trailing
  contributors.yml
  docs/start/tutorial.md
Labels: CLA Signed, docs

#7576 Fix FOUC on subsequent client-side navigations to route.lazy routes
  .changeset/route-lazy-fouc.md
  packages/remix-react/routes.tsx
Labels: CLA Signed, feat:routing

#7594 Avoid mutating meta object when tagName is specified
  .changeset/dont-mutate-meta.md
  package.json
  packages/remix-react/__tests__/integration/meta-test.tsx
  packages/remix-react/components.tsx
  yarn.lock
Labels: CLA Signed

#7622 Add missing folder slash to v2.md
  contributors.yml
  docs/start/v2.md
Labels: CLA Signed

#7619 chore: flush headers for event-stream responses
  .changeset/express-flush-stream-headers.md
  packages/remix-express/server.ts
Labels: CLA Signed

#7605 Reimplement Jsonify type utility
  .changeset/stale-apples-reply.md
  packages/remix-react/__tests__/hook-types-test.tsx
  packages/remix-server-runtime/jsonify.ts
  packages/remix-server-runtime/package.json
  packages/remix-server-runtime/serialize.ts
  packages/remix-server-runtime/typecheck.ts
Labels: CLA Signed

#7648 Add startViewTransition support
  .changeset/start-view-transition.md
  docs/components/form.md
  docs/components/link.md
  docs/components/nav-link.md
  docs/hooks/use-view-transition-state.md
  packages/remix-react/index.tsx
  packages/remix-react/package.json
  packages/remix-server-runtime/package.json
  packages/remix-testing/package.json
  yarn.lock
Labels: CLA Signed, renderer:react

#7649 Fix: using a local *.tgz stack
  .changeset/big-tigers-burn.md
  docs/guides/templates.md
  packages/create-remix/__tests__/create-remix-test.ts
  packages/create-remix/__tests__/fixtures/arc.tgz
  packages/create-remix/copy-template.ts
Labels: CLA Signed, package:create-remix

#7590 feat: add unstable Vite support
  .changeset/perfect-rockets-approve.md
  docs/future/index.md
  docs/future/vite.md
  docs/styling/bundling.md
  integration/helpers/create-fixture.ts
  integration/vite-build-test.ts
  integration/vite-dev-test.ts
  package.json
  packages/remix-dev/config.ts
  packages/remix-dev/index.ts
  packages/remix-dev/package.json
  packages/remix-dev/rollup.config.js
  packages/remix-dev/vite/babel.ts
  packages/remix-dev/vite/index.ts
  packages/remix-dev/vite/legacy-css-imports.ts
  packages/remix-dev/vite/node/adapter.ts
  packages/remix-dev/vite/plugin.ts
  packages/remix-dev/vite/remove-exports-test.ts
  packages/remix-dev/vite/remove-exports.ts
  packages/remix-dev/vite/replace-import-specifier.ts
  packages/remix-dev/vite/static/refresh-utils.cjs
  packages/remix-dev/vite/styles.ts
  packages/remix-dev/vite/vmod.ts
  packages/remix-react/browser.tsx
  packages/remix-react/components.tsx
  packages/remix-react/entry.ts
  packages/remix-react/links.ts
  packages/remix-react/routes.tsx
  packages/remix-react/server.tsx
  packages/remix-server-runtime/entry.ts
  packages/remix-server-runtime/routes.ts
  packages/remix-server-runtime/server.ts
  packages/remix-server-runtime/serverHandoff.ts
  yarn.lock
Labels: CLA Signed, package:dev

#7668 docs(vite): update MDX route support
  docs/future/vite.md
Labels: CLA Signed, docs

#7669 fix(vite): clear critical CSS on HMR
  packages/remix-dev/vite/plugin.ts
  packages/remix-dev/vite/static/refresh-utils.cjs
  packages/remix-react/browser.tsx
Labels: CLA Signed, package:dev

#7676 docs(vite): fix link to react keys
  docs/future/vite.md
Labels: CLA Signed

#7677 Lock into stable react router version
  .changeset/nine-knives-compare.md
  packages/remix-react/package.json
  packages/remix-server-runtime/package.json
  packages/remix-testing/package.json
  yarn.lock
Labels: CLA Signed

#7670 fix(create-remix): default Remix version to CLI version
  .changeset/create-remix-default-remix-version.md
  packages/create-remix/index.ts
  packages/create-remix/remix-version.ts
Labels: CLA Signed, package:create-remix

#7681 place route updates in manifest.routes, not manifest itself
  packages/remix-dev/vite/static/refresh-utils.cjs
Labels: CLA Signed

#7685 test(vite): add CSS tests
  integration/helpers/killtree.ts
  integration/hmr-test.ts
  integration/vite-css-build-test.ts
  integration/vite-css-dev-test.ts
  integration/vite-css-legacy-build-test.ts
  integration/vite-dev-test.ts
Labels: CLA Signed

#7692 Update templates.md
  contributors.yml
  docs/guides/templates.md
Labels: CLA Signed

#7702 Update error-boundary.md
  contributors.yml
  docs/route/error-boundary.md
Labels: CLA Signed

#7620 Express template wasn't restarting when server.js changes
  templates/express/package.json
Labels: CLA Signed, template:express

#7707 Correcting Form Validation Error Handling
  contributors.yml
  docs/guides/form-validation.md
Labels: CLA Signed, docs

#7717 Pedro/vite scripts ordering
  docs/future/vite.md
Labels: CLA Signed

#7711 Update remix file conventions demo to v2 link
  contributors.yml
  docs/file-conventions/remix-config.md
Labels: CLA Signed

#7705 Update form-vs-fetcher.md
  contributors.yml
  docs/discussion/form-vs-fetcher.md
Labels: CLA Signed, docs

#7724 use .ts for vite config
  docs/future/vite.md
  integration/vite-build-test.ts
  integration/vite-css-build-test.ts
  integration/vite-css-dev-test.ts
  integration/vite-css-legacy-build-test.ts
  integration/vite-dev-test.ts
Labels: CLA Signed

#7725 Unstable Vite: dedupe and optimize react deps
  integration/vite-css-dev-test.ts
  integration/vite-dev-test.ts
  packages/remix-dev/vite/plugin.ts
Labels: CLA Signed

#7738 docs(future/vite): use TS where possible
  docs/future/vite.md
Labels: CLA Signed, docs

#7323 fix(remix-express): respect expressjs hostname property when behind reverse proxies
  .changeset/fix-express-proxy.md
  packages/remix-express/server.ts
Labels: CLA Signed, adapter:express

#7747 docs(discussion/state-management): fix typo
  contributors.yml
  docs/discussion/state-management.md
Labels: CLA Signed, docs

#7682 Unstable Vite: support for custom servers
  docs/future/vite.md
  integration/helpers/dev.ts
  integration/vite-dev-express-test.ts
  packages/remix-dev/index.ts
  packages/remix-dev/vite/index.ts
  packages/remix-dev/vite/plugin.ts
  packages/remix-express/server.ts
  packages/remix-server-runtime/server.ts
Labels: CLA Signed, package:dev

#7758 test(vite): use .ts for vite config
  integration/vite-dev-express-test.ts
Labels: CLA Signed

#7759 vite: allow request body for post, put, delete, patch
  packages/remix-dev/vite/node/adapter.ts
Labels: CLA Signed

#7763 do not use built-in, minimal SSR in middleware mode
  integration/vite-dev-express-test.ts
  packages/remix-dev/vite/plugin.ts
Labels: CLA Signed

#7745 Fix console warning for routes that do not export a default component
  .changeset/empty-default-export.md
  packages/remix-react/__tests__/components-test.tsx
  packages/remix-react/routes.tsx
Labels: CLA Signed, renderer:react

#7704 Add fetcherKey APIs and update fetcher persistence architecture
  .changeset/fetcher-persist.md
  docs/components/form.md
  docs/file-conventions/remix-config.md
  docs/hooks/use-fetcher.md
  docs/hooks/use-fetchers.md
  docs/hooks/use-submit.md
  integration/fetcher-layout-test.ts
  packages/remix-dev/__tests__/readConfig-test.ts
  packages/remix-dev/config.ts
  packages/remix-dev/package.json
  packages/remix-dev/vite/plugin.ts
  packages/remix-react/browser.tsx
  packages/remix-react/components.tsx
  packages/remix-react/entry.ts
  packages/remix-react/package.json
  packages/remix-server-runtime/entry.ts
  packages/remix-server-runtime/package.json
  packages/remix-testing/create-remix-stub.tsx
  packages/remix-testing/package.json
  scripts/bump-router-versions.sh
  yarn.lock
Labels: CLA Signed, renderer:react

#7783 docs(hooks/use-fetcher): update link
  contributors.yml
  docs/hooks/use-fetcher.md
Labels: CLA Signed, docs

#7789 docs(hmr): dedicated discussion doc for hmr
  docs/discussion/hot-module-replacement.md
  docs/future/vite.md
  docs/other-api/dev.md
Labels: CLA Signed

#7791 fix links to HMR discussion
  docs/future/vite.md
  docs/other-api/dev.md
Labels: CLA Signed

#7792 fix HMR discussion links... again
  docs/future/vite.md
  docs/other-api/dev.md
Labels: CLA Signed

#7793 rewrite getting started and adapt existing migration guide
  docs/future/vite.md
  templates/unstable-vite-express/package.json
  templates/unstable-vite/package.json
Labels: CLA Signed

#7794 fix link to unstable vite template
  docs/future/vite.md
Labels: CLA Signed

#7797 docs(vite): step-by-step migration guide
  docs/future/vite.md
Labels: CLA Signed

#7798 docs(vite): fix rendering of typescript for custom server instructions
  docs/future/vite.md
Labels: CLA Signed

#7799 docs(vite): polish migrating guide
  docs/future/vite.md
Labels: CLA Signed

#7777 docs(hooks/use-navigation): fix typo
  contributors.yml
  docs/hooks/use-navigation.md
Labels: CLA Signed, docs

#7805 docs(vite): move legacy css instructions into the migration guide
  docs/future/vite.md
Labels: CLA Signed

#7811 docs(vite): move feature docs to migration guide
  docs/future/vite.md
Labels: CLA Signed, docs, vite

#7812 fix(react): fix Vite dev CSS hydration errors
  .changeset/kind-pandas-think.md
  packages/remix-react/components.tsx
Labels: CLA Signed, renderer:react, vite

#7814 fix(server-runtime): mark critical CSS arg private
  packages/remix-dev/vite/node/adapter.ts
  packages/remix-server-runtime/server.ts
Labels: CLA Signed, package:server-runtime, vite

#7658 chore(remix-react): update `Link`'s `prefetch` comment
  contributors.yml
  packages/remix-react/components.tsx
Labels: CLA Signed, renderer:react

#7801 chore: fix docs links
  README.md
  packages/create-remix/index.ts
  packages/remix-dev/config.ts
  templates/remix-javascript/app/entry.client.jsx
  templates/remix-javascript/app/entry.server.jsx
Labels: CLA Signed, package:create-remix, package:dev, template:remix-javascript

#7802 docs(guides/templates): fix links
  docs/guides/templates.md
Labels: CLA Signed, docs

#7803 docs(discussion/runtimes): fix comments
  docs/discussion/runtimes.md
Labels: CLA Signed, docs

#7800 docs: update `ActionArgs`/`LoaderArgs` references
  docs/discussion/concurrency.md
  docs/discussion/data-flow.md
  docs/discussion/form-vs-fetcher.md
  docs/discussion/pending-ui.md
  docs/discussion/server-vs-client.md
  docs/discussion/state-management.md
  docs/file-conventions/routes.md
  docs/guides/form-validation.md
  docs/guides/streaming.md
Labels: CLA Signed, docs

#7804 docs(guides/not-found): fix links
  docs/guides/not-found.md
Labels: CLA Signed, docs

#7822 docs(vite): de-emphasize CSS `?url` imports
  docs/future/vite.md
Labels: CLA Signed, docs, vite

#7826 docs(vite): put typescript and livereload steps before server scripts
  docs/future/vite.md
Labels: CLA Signed

#7825 Bump to latest router prerelease
  .changeset/spotty-timers-swim.md
  packages/remix-dev/package.json
  packages/remix-react/package.json
  packages/remix-server-runtime/package.json
  packages/remix-testing/package.json
  yarn.lock
Labels: CLA Signed

#7828 fix(vite): remove server exports from resource routes
  .changeset/curvy-wasps-occur.md
  integration/vite-build-test.ts
  packages/remix-dev/vite/plugin.ts
Labels: CLA Signed

#7829 fix(vite): fix behind-by-one-render bug for `meta` HMR
  .changeset/fifty-garlics-heal.md
  integration/vite-dev-express-test.ts
  packages/remix-dev/vite/static/refresh-utils.cjs
Labels: CLA Signed

#7832 docs(vite): remove redundant server scripts heading
  docs/future/vite.md
Labels: CLA Signed

#7834 chore(templates/vite): set TS module to ESNext
  templates/unstable-vite-express/tsconfig.json
  templates/unstable-vite/tsconfig.json
Labels: CLA Signed, vite

#7844 docs: fix @nightly to @latest for vite inits
  docs/future/vite.md
  templates/unstable-vite-express/README.md
  templates/unstable-vite/README.md
Labels: CLA Signed
