Repository remix-run/remix, pull requests merged in 2023-06, with the labels that each got.

#6512 fix(remix-node): fix `NodeRequest`'s `clone` function
  .changeset/req-clone-instanceof.md
  contributors.yml
  packages/remix-node/__tests__/fetch-test.ts
  packages/remix-node/fetch.ts
Labels: CLA Signed, runtime:node

#6287 feat: retry revalidation caused by HDR
  .changeset/hdr-revalidation-retry.md
  packages/remix-react/browser.tsx
  packages/remix-react/data.ts
Labels: CLA Signed

#6495 Fix server error logging and add onUnhandledError support
  .changeset/log-server-errors.md
  .changeset/on-unhandled-error.md
  docs/file-conventions/entry.server.md
  integration/error-sanitization-test.ts
  integration/headers-test.ts
  packages/remix-cloudflare/index.ts
  packages/remix-deno/index.ts
  packages/remix-dev/codemod/replace-remix-magic-imports/utils/export.ts
  packages/remix-dev/config/defaults/cloudflare/entry.server.react-stream.tsx
  packages/remix-dev/config/defaults/deno/entry.server.react-stream.tsx
  packages/remix-dev/config/defaults/node/entry.server.react-stream.tsx
  packages/remix-eslint-config/rules/packageExports.js
  packages/remix-node/index.ts
  packages/remix-react/errorBoundaries.tsx
  packages/remix-server-runtime/__tests__/server-test.ts
  packages/remix-server-runtime/build.ts
  packages/remix-server-runtime/index.ts
  packages/remix-server-runtime/reexport.ts
  packages/remix-server-runtime/server.ts
  rollup.utils.js
  templates/arc/app/entry.server.tsx
  templates/cloudflare-pages/app/entry.server.tsx
  templates/cloudflare-workers/app/entry.server.tsx
  templates/deno/app/entry.server.tsx
  templates/express/app/entry.server.tsx
  templates/fly/app/entry.server.tsx
  templates/netlify/app/entry.server.tsx
  templates/remix/app/entry.server.tsx
  templates/vercel/app/entry.server.tsx
Labels: CLA Signed, package:server-runtime

#6505 fix: add caching to PostCSS for regular stylesheets
  .changeset/postcss-cache-regular-stylesheets.md
  integration/hmr-test.ts
  package.json
  packages/remix-dev/cli/commands.ts
  packages/remix-dev/compiler/context.ts
  packages/remix-dev/compiler/fileWatchCache.ts
  packages/remix-dev/compiler/plugins/cssImports.ts
  packages/remix-dev/compiler/watch.ts
  packages/remix-dev/devServer/liveReload.ts
  packages/remix-dev/devServer_unstable/index.ts
  packages/remix-dev/package.json
  yarn.lock
Labels: CLA Signed, package:dev

#6506 fix(dev): fix CSS import warnings in unstable_dev
  .changeset/css-import-warnings-unstable-dev.md
  packages/remix-dev/compiler/js/compiler.ts
Labels: CLA Signed

#6518 chore: fix copy-build-to-dist script on Windows
  scripts/copy-build-to-dist.mjs
Labels: CLA Signed

#6517 Bump to router prerelease
  integration/fetcher-state-test.ts
  integration/hmr-log-test.ts
  integration/hmr-test.ts
  packages/remix-react/package.json
  packages/remix-server-runtime/package.json
  packages/remix-testing/package.json
  yarn.lock
Labels: CLA Signed

#6524 rename onUnhandledError - > handleError
  .changeset/handle-error.md
  docs/file-conventions/entry.server.md
  integration/error-sanitization-test.ts
  packages/remix-cloudflare/index.ts
  packages/remix-deno/index.ts
  packages/remix-dev/codemod/replace-remix-magic-imports/utils/export.ts
  packages/remix-eslint-config/rules/packageExports.js
  packages/remix-node/index.ts
  packages/remix-server-runtime/build.ts
  packages/remix-server-runtime/index.ts
  packages/remix-server-runtime/reexport.ts
  packages/remix-server-runtime/server.ts
  rollup.utils.js
Labels: CLA Signed

#6548 Bump to react-router stable 6.12.0 version
  .changeset/proud-dragons-add.md
  packages/remix-react/package.json
  packages/remix-server-runtime/package.json
  packages/remix-testing/package.json
  yarn.lock
Labels: CLA Signed

#6535 fix(dev): lazily generate CSS bundle
  .changeset/lazy-css-bundle.md
  packages/remix-css-bundle/browser.ts
  packages/remix-css-bundle/index.ts
  packages/remix-css-bundle/package.json
  packages/remix-css-bundle/rollup.config.js
  packages/remix-css-bundle/server.ts
  packages/remix-dev/compiler/compiler.ts
  packages/remix-dev/compiler/css/compiler.ts
  packages/remix-dev/compiler/js/compiler.ts
  packages/remix-dev/compiler/js/plugins/cssBundleUpdate.ts
  packages/remix-dev/compiler/lazyValue.ts
  packages/remix-dev/compiler/manifest.ts
  packages/remix-dev/compiler/plugins/cssBundlePlugin.ts
  packages/remix-dev/compiler/server/compiler.ts
  packages/remix-dev/compiler/server/plugins/manifest.ts
  packages/remix-dev/manifest.ts
Labels: CLA Signed, package:dev, package:css-bundle

#6562 refactor(remix-dev): replace esbuild-plugin-polyfill-node with esbuild-plugins-node-modules-polyfill
  .changeset/polyfill-replacement.md
  contributors.yml
  packages/remix-dev/compiler/css/compiler.ts
  packages/remix-dev/compiler/js/compiler.ts
  packages/remix-dev/compiler/server/compiler.ts
  packages/remix-dev/package.json
  yarn.lock
Labels: CLA Signed

#6551 chore: use long version numbers
  docs/guides/typescript.md
  integration/compiler-mjs-output-test.ts
  integration/helpers/cf-template/package.json
  integration/helpers/deno-template/package.json
  integration/helpers/node-template/package.json
  integration/hmr-log-test.ts
  integration/hmr-test.ts
  integration/server-entry-test.ts
  scripts/playground/template/package.json
  templates/arc/package.json
  templates/cloudflare-pages/package.json
  templates/cloudflare-workers/package.json
  templates/deno/package.json
  templates/express/package.json
  templates/fly/package.json
  templates/netlify/package.json
  templates/remix/package.json
  templates/vercel/package.json
Labels: CLA Signed, docs, template:express, template:architect, template:vercel, template:cloudflare-pages, template:cloudflare-workers, template:fly, template:netlify, template:remix, template:deno

#6572 Bump to react router 6.12.1
  .changeset/large-taxis-tie.md
  packages/remix-react/package.json
  packages/remix-testing/package.json
  yarn.lock
Labels: CLA Signed

#6585 docs(route/error-boundary-v2): fix broken link
  docs/route/error-boundary-v2.md
Labels: CLA Signed, docs

#6582 fix(dev): only apply pretty types for objects
  packages/remix-server-runtime/serialize.ts
Labels: CLA Signed

#6484 fix(remix-dev/cli): remove `AWS Lamba` copy
  .changeset/chilly-shoes-scream.md
  contributors.yml
  packages/remix-dev/cli/run.ts
Labels: CLA Signed, package:dev

#5964 feat(remix-vercel): show deprecation warning on usage
  packages/remix-vercel/index.ts
  templates/vercel/README.md
Labels: CLA Signed, adapter:vercel

#6602 test: fix integration tests
  integration/bug-report-test.ts
  integration/catch-boundary-data-test.ts
  integration/catch-boundary-test.ts
  integration/defer-test.ts
  integration/error-boundary-test.ts
  integration/fetcher-state-test.ts
  integration/form-test.ts
  integration/hmr-log-test.ts
  integration/hmr-test.ts
  integration/navigation-state-v2-test.ts
  integration/transition-state-test.ts
Labels: CLA Signed

#6554 fix(dev): cache PostCSS for side-effect imports
  .changeset/postcss-cache-side-effect-imports.md
  integration/deterministic-build-output-test.ts
  integration/hmr-test.ts
  packages/remix-dev/compiler/plugins/cssImports.ts
  packages/remix-dev/compiler/plugins/cssSideEffectImports.ts
  packages/remix-dev/compiler/plugins/vanillaExtract.ts
  packages/remix-dev/compiler/utils/postcss.ts
Labels: CLA Signed, package:dev

#6596 feat(dev): prettier logging for `remix build` and `remix dev`
  .changeset/orange-beds-explode.md
  integration/compiler-test.ts
  integration/esm-only-warning-test.ts
  integration/flat-routes-test.ts
  packages/remix-dev/__tests__/create-test.ts
  packages/remix-dev/__tests__/readConfig-test.ts
  packages/remix-dev/cli/commands.ts
  packages/remix-dev/compiler/context.ts
  packages/remix-dev/compiler/js/compiler.ts
  packages/remix-dev/compiler/options.ts
  packages/remix-dev/compiler/plugins/deprecatedRemixPackage.ts
  packages/remix-dev/compiler/server/plugins/bareImports.ts
  packages/remix-dev/compiler/watch.ts
  packages/remix-dev/config.ts
  packages/remix-dev/devServer/liveReload.ts
  packages/remix-dev/devServer_unstable/env.ts
  packages/remix-dev/devServer_unstable/index.ts
  packages/remix-dev/devServer_unstable/socket.ts
  packages/remix-dev/package.json
  packages/remix-dev/tux/format.ts
  packages/remix-dev/tux/index.ts
  packages/remix-dev/tux/logger.ts
Labels: CLA Signed

#6552 chore: use long version numbers
  package.json
  packages/create-remix/package.json
  packages/remix-architect/package.json
  packages/remix-cloudflare-pages/package.json
  packages/remix-cloudflare-workers/package.json
  packages/remix-cloudflare/package.json
  packages/remix-css-bundle/package.json
  packages/remix-deno/package.json
  packages/remix-dev/__tests__/fixtures/cloudflare/package.json
  packages/remix-dev/__tests__/fixtures/deno/package.json
  packages/remix-dev/__tests__/fixtures/indie-stack/package.json
  packages/remix-dev/__tests__/fixtures/node/package.json
  packages/remix-dev/__tests__/fixtures/replace-remix-magic-imports/package.json
  packages/remix-dev/__tests__/fixtures/stack/package.json
  packages/remix-dev/package.json
  packages/remix-express/package.json
  packages/remix-netlify/package.json
  packages/remix-node/package.json
  packages/remix-react/package.json
  packages/remix-serve/package.json
  packages/remix-server-runtime/package.json
  packages/remix-testing/package.json
  packages/remix-vercel/package.json
  packages/remix/package.json
Labels: CLA Signed, adapter:architect, adapter:vercel, adapter:netlify, adapter:cloudflare-pages, adapter:cloudflare-workers, package:serve, package:create-remix, package:dev, package:remix, package:server-runtime, runtime:node, runtime:cloudflare, renderer:react, adapter:netlify-edge, runtime:deno, package:testing, package:css-bundle

#6607 refactor(dev): group rebuild logs with surrounding whitespace
  .changeset/thin-rings-sparkle.md
  packages/remix-dev/devServer_unstable/index.ts
Labels: CLA Signed

#6409 fix: reload page when routeModules doesn't contain module for current route
  .changeset/dual-forward-bug.md
  integration/browser-entry-test.ts
  packages/remix-react/browser.tsx
  packages/remix-server-runtime/server.ts
  packages/remix-server-runtime/serverHandoff.ts
Labels: CLA Signed

#6609 Update to react router 6.13.0
  .changeset/ninety-swans-pay.md
  integration/bug-report-test.ts
  integration/catch-boundary-data-test.ts
  integration/catch-boundary-test.ts
  integration/defer-test.ts
  integration/error-boundary-test.ts
  integration/fetcher-state-test.ts
  integration/form-test.ts
  integration/hmr-log-test.ts
  integration/hmr-test.ts
  integration/navigation-state-v2-test.ts
  integration/transition-state-test.ts
  packages/remix-react/browser.tsx
  packages/remix-react/package.json
  packages/remix-testing/package.json
  yarn.lock
Labels: CLA Signed

#6604 fix(dev): cache PostCSS for CSS Modules
  .changeset/postcss-cache-css-modules.md
  integration/hmr-test.ts
  packages/remix-dev/compiler/fileWatchCache.ts
  packages/remix-dev/compiler/plugins/cssModuleImports.ts
  packages/remix-dev/compiler/utils/postcss.ts
Labels: CLA Signed, package:dev

#6608 Move `@types/aws-lambda` from devDependencies to dependencies
  packages/remix-architect/package.json
Labels: CLA Signed

#6474 Fix add labels workflow for merged PRs
  .github/workflows/merged-pr.yml
Labels: CLA Signed

#6614 feat(remix-eslint-config): extend from typescript-eslint/recommended
  .changeset/typescript-eslint-recommended.md
  packages/remix-dev/__tests__/cli-test.ts
  packages/remix-dev/compiler/server/plugins/bareImports.ts
  packages/remix-dev/server-build.ts
  packages/remix-eslint-config/index.js
  packages/remix-eslint-config/internal.js
  packages/remix-eslint-config/rules/core.js
  packages/remix-eslint-config/rules/import.js
  packages/remix-eslint-config/rules/typescript.js
  packages/remix-netlify/__tests__/server-test.ts
  packages/remix-node/__tests__/fetch-test.ts
  packages/remix-react/__tests__/deferred-scripts-test.tsx
  packages/remix-server-runtime/__tests__/serialize-test.ts
  packages/remix-server-runtime/responses.ts
Labels: CLA Signed, package:eslint-config

#6618 fix(dev): do not crash when app server process is already dead on windows
  packages/remix-dev/devServer_unstable/index.ts
Labels: CLA Signed

#6623 docs(guides/routing): fix typo
  contributors.yml
  docs/guides/routing.md
Labels: CLA Signed, docs

#6619 docs(tutorials/jokes): update hydrate link
  contributors.yml
  docs/tutorials/jokes.md
Labels: CLA Signed, docs

#6615 feat(dev): stabilize v2 dev server
  .changeset/clever-ways-love.md
  docs/other-api/adapter.md
  docs/other-api/dev-v2.md
  docs/other-api/dev.md
  docs/pages/api-development-strategy.md
  docs/pages/v2.md
  integration/hmr-log-test.ts
  integration/hmr-test.ts
  integration/shared-route-imports-test.ts
  packages/remix-dev/__tests__/cli-test.ts
  packages/remix-dev/__tests__/readConfig-test.ts
  packages/remix-dev/cli/commands.ts
  packages/remix-dev/cli/run.ts
  packages/remix-dev/compiler/js/compiler.ts
  packages/remix-dev/config.ts
  packages/remix-react/entry.ts
  packages/remix-serve/cli.ts
  packages/remix-server-runtime/__tests__/utils.ts
  packages/remix-server-runtime/entry.ts
  packages/remix-testing/create-remix-stub.tsx
Labels: CLA Signed

#6629 cache getRouteModuleExports calls
  .changeset/rude-meals-move.md
  packages/remix-dev/compiler/compiler.ts
  packages/remix-dev/compiler/js/plugins/routes.ts
  packages/remix-dev/compiler/manifest.ts
  packages/remix-dev/devServer_unstable/hdr.ts
Labels: CLA Signed

#6639 fix(dev): skip unused Node polyfills in CSS build
  .changeset/css-bundle-skip-node-polyfills.md
  packages/remix-dev/compiler/css/compiler.ts
Labels: CLA Signed, package:dev

#6622 fix(dev): cache CSS side-effects transform for HMR
  .changeset/css-side-effect-imports-hmr-cache.md
  packages/remix-dev/compiler/plugins/cssSideEffectImports.ts
  packages/remix-dev/package.json
  yarn.lock
Labels: CLA Signed

#6433 feat: add `prefetch="viewport"` support to `<Link>`
  .changeset/prefetch-viewport.md
  docs/components/link.md
  docs/components/nav-link.md
  integration/prefetch-test.ts
  packages/remix-react/components.tsx
Labels: CLA Signed, renderer:react

#6643 docs(v2_dev): edits
  docs/other-api/dev-v2.md
  docs/pages/v2.md
Labels: CLA Signed

#6649 Fix bug with pathless layout routes beneath nested path segments
  .changeset/five-zoos-fix.md
  packages/remix-dev/__tests__/flat-routes-test.ts
  packages/remix-dev/config/flat-routes.ts
Labels: CLA Signed

#6652 fix(dev): update polyfills plugin to use cache
  .changeset/update-polyfills-plugin.md
  packages/remix-dev/package.json
  yarn.lock
Labels: CLA Signed, package:dev

#6653 perf(dev): @remix-run/{cloudflare,deno,node} as empty modules for browser
  packages/remix-dev/compiler/js/compiler.ts
Labels: CLA Signed

#6651 docs(file-conventions/entry.server): fix typos
  contributors.yml
  docs/file-conventions/entry.server.md
Labels: CLA Signed, docs

#6654 perf(dev): skip Remix/React packages in CSS build
  .changeset/css-bundle-skip-packages.md
  packages/remix-dev/compiler/css/compiler.ts
  packages/remix-dev/compiler/plugins/emptyModules.ts
Labels: CLA Signed, package:dev

#6638 perf(dev): cache regular stylesheet compilation
  .changeset/cache-regular-stylesheets.md
  packages/remix-dev/compiler/plugins/cssImports.ts
Labels: CLA Signed, package:dev

#6655 perf(dev): ignore server runtimes indirectly imported by deps
  packages/remix-dev/compiler/js/compiler.ts
Labels: CLA Signed

#6663 fix(dev): wait until all app server descendants have been killed
  .changeset/blue-dots-glow.md
  packages/remix-dev/devServer_unstable/index.ts
  packages/remix-dev/devServer_unstable/proc.ts
  packages/remix-dev/package.json
  yarn.lock
Labels: CLA Signed

#6662 Bump router
  .changeset/chatty-birds-sing.md
  integration/helpers/playwright-fixture.ts
  package.json
  packages/remix-react/package.json
  packages/remix-testing/package.json
  yarn.lock
Labels: CLA Signed

#6677 Update to RR 6.14.0 stable
  .changeset/sweet-apes-sip.md
  packages/remix-react/package.json
  packages/remix-server-runtime/package.json
  packages/remix-testing/package.json
  yarn.lock
Labels: CLA Signed

#6650 chore(templates): integrate v2_dev
  templates/arc/.eslintrc.cjs
  templates/arc/.gitignore
  templates/arc/README.md
  templates/arc/app.arc
  templates/arc/app/root.tsx
  templates/arc/package.json
  templates/arc/plugin-remix.js
  templates/arc/remix.config.js
  templates/arc/server/config.arc
  templates/cloudflare-pages/.eslintrc.cjs
  templates/cloudflare-pages/.gitignore
  templates/cloudflare-pages/package.json
  templates/cloudflare-pages/public/_headers
  templates/cloudflare-pages/public/_routes.json
  templates/cloudflare-pages/remix.config.js
  templates/cloudflare-pages/server.ts
  templates/cloudflare-pages/wrangler.toml
  templates/cloudflare-workers/.eslintrc.cjs
  templates/cloudflare-workers/.gitignore
  templates/cloudflare-workers/package.json
  templates/cloudflare-workers/remix.config.js
  templates/cloudflare-workers/remix.env.d.ts
  templates/cloudflare-workers/server.ts
  templates/cloudflare-workers/wrangler.toml
  templates/express/.eslintrc.cjs
  templates/express/package.json
  templates/express/remix.config.js
  templates/express/server.js
  templates/fly/remix.config.js
  templates/netlify/netlify.toml
  templates/netlify/package.json
  templates/netlify/remix.config.js
  templates/remix/remix.config.js
  templates/vercel/remix.config.js
Labels: CLA Signed

#6698 test(dev): fix CLI test
  packages/remix-dev/__tests__/cli-test.ts
Labels: CLA Signed

#6717 docs(dev-v2): complete tls instructions
  docs/other-api/dev-v2.md
Labels: CLA Signed

#6719 fix(dev): do not clear screen when dev server starts
  .changeset/tasty-bats-turn.md
  packages/remix-dev/cli/commands.ts
Labels: CLA Signed

#6696 fix(dev): polyfill Node process and Buffer globals
  .changeset/pretty-moose-flow.md
  packages/remix-dev/compiler/js/compiler.ts
  packages/remix-dev/compiler/plugins/nodePolyfillsPlugin.ts
  packages/remix-dev/compiler/server/compiler.ts
  packages/remix-dev/package.json
  yarn.lock
Labels: CLA Signed, package:dev

#6725 fix(dev): ignore missing react-dom/client for react 17
  .changeset/famous-games-film.md
  packages/remix-dev/config/defaults/entry.dev.ts
Labels: CLA Signed

#6727 Bump router to 6.14.1-pre.0
  .changeset/stale-houses-grin.md
  packages/remix-react/package.json
  packages/remix-testing/package.json
  scripts/bump-router-versions.sh
  yarn.lock
Labels: CLA Signed

#6720 fix(dev): revert global Node polyfills
  .changeset/pretty-moose-flow.md
  packages/remix-dev/compiler/js/compiler.ts
  packages/remix-dev/compiler/plugins/nodePolyfillsPlugin.ts
  packages/remix-dev/compiler/server/compiler.ts
Labels: CLA Signed, package:dev

#6675 Support proper hydration of Error subclasses
  .changeset/hydrate-error-type.md
  integration/error-sanitization-test.ts
  packages/remix-react/errors.ts
  packages/remix-server-runtime/errors.ts
Labels: CLA Signed

#6736 fix: avoid circular references and infinitely recursive types
  .changeset/popular-beers-bake.md
  packages/remix-server-runtime/serialize.ts
Labels: CLA Signed

#6737 Bump router
  .changeset/angry-flowers-matter.md
  packages/remix-react/package.json
  packages/remix-server-runtime/package.json
  packages/remix-testing/package.json
  yarn.lock
Labels: CLA Signed

#6740 Bump to stable router version
  .changeset/three-crabs-jam.md
  packages/remix-react/package.json
  packages/remix-server-runtime/package.json
  packages/remix-testing/package.json
  yarn.lock
Labels: CLA Signed
