Repository remix-run/remix, pull requests merged in 2023-02, with the labels that each got.

#5337 docs: more punctuation
  docs/guides/bff.md
  docs/guides/browser-support.md
  docs/guides/data-loading.md
  docs/guides/data-writes.md
  docs/guides/errors.md
  docs/guides/migrating-react-router-app.md
  docs/guides/optimistic-ui.md
  docs/guides/performance.md
  docs/guides/resource-routes.md
  docs/guides/routing.md
  docs/guides/streaming.md
  docs/guides/styling.md
  docs/guides/typescript.md
  docs/route/meta.md
Labels: CLA Signed

#5336 Fix adapter request creation when double slashes exist
  .changeset/nine-apricots-breathe.md
  packages/remix-architect/__tests__/server-test.ts
  packages/remix-architect/server.ts
  packages/remix-express/__tests__/server-test.ts
  packages/remix-express/server.ts
  packages/remix-netlify/__tests__/server-test.ts
  packages/remix-netlify/server.ts
  packages/remix-vercel/__tests__/server-test.ts
  packages/remix-vercel/server.ts
Labels: CLA Signed, adapter:architect, adapter:vercel, adapter:express, adapter:netlify

#5339 fix(react): live reload works without scripts
  .changeset/olive-jokes-invent.md
  packages/remix-react/__tests__/components-test.tsx
  packages/remix-react/components.tsx
Labels: CLA Signed

#5342 ci(comment) use current branch when gathering PRs for stable release
  .github/workflows/nightly.yml
  .github/workflows/release-comments.yml
  .github/workflows/release.yml
  scripts/release/comment.ts
  scripts/release/constants.ts
  scripts/release/find-release-from-changeset.js
  scripts/release/github.ts
Labels: CLA Signed

#5311 docs: use `useNavigation` instead of `useTransition`
  docs/guides/optimistic-ui.md
  docs/tutorials/blog.md
  docs/tutorials/jokes.md
Labels: CLA Signed, docs

#4748 perf(remix-server-runtime): Performance improvements for large apps
  .changeset/many-pans-attack.md
  packages/remix-react/routes.tsx
  packages/remix-server-runtime/routes.ts
Labels: CLA Signed

#5351 ci: uppercase ENV, changesets output is camelCase
  .github/workflows/release.yml
  scripts/release/find-release-from-changeset.js
Labels: CLA Signed

#4841 feat(remix-dev): deprecate `serverBuildTarget`
  docs/file-conventions/remix-config.md
  packages/remix-dev/__tests__/readConfig-test.ts
  packages/remix-dev/compiler/compilerServer.ts
  packages/remix-dev/compiler/plugins/serverBareModulesPlugin.ts
  packages/remix-dev/config.ts
Labels: CLA Signed, package:dev

#4842 templates: deprecate `serverBuildTarget` usage
  integration/helpers/cf-template/remix.config.js
  integration/helpers/deno-template/remix.config.js
  templates/arc/remix.config.js
  templates/cloudflare-pages/remix.config.js
  templates/cloudflare-workers/remix.config.js
  templates/deno/remix.config.js
  templates/netlify/remix.config.js
  templates/vercel/remix.config.js
Labels: CLA Signed, template:architect, template:vercel, template:cloudflare-pages, template:cloudflare-workers, template:netlify, template:deno

#5354 add serverBuildTarget deprecation changeset
  .changeset/eleven-plums-film.md
Labels: CLA Signed

#5367 docs(file-conventions/route-files-v2): Fix incorrect routes path
  contributors.yml
  docs/file-conventions/route-files-v2.md
Labels: CLA Signed

#5372 docs(route/meta): fix grammar
  contributors.yml
  docs/route/meta.md
Labels: CLA Signed

#5228 fix(remix-dev): flat route fixes and enhancements
  .changeset/tame-swans-burn.md
  packages/remix-dev/__tests__/flat-routes-test.ts
  packages/remix-dev/config/flat-routes.ts
Labels: CLA Signed, package:dev

#5377 ci(release): fix find_package_version output
  .github/workflows/release.yml
Labels: CLA Signed

#5376 docs(utils/defer): fix code highlighting
  contributors.yml
  docs/utils/defer.md
Labels: CLA Signed, docs

#5358 fix(remix-dev): update tailwind config detection to also look for cjs
  .changeset/fresh-toes-shout.md
  packages/remix-dev/compiler/utils/postcss.ts
  packages/remix-dev/config.ts
Labels: CLA Signed, package:dev

#5387 chore: Update version for release (pre)
  .changeset/pre.json
  packages/create-remix/CHANGELOG.md
  packages/create-remix/package.json
  packages/remix-architect/CHANGELOG.md
  packages/remix-architect/package.json
  packages/remix-cloudflare-pages/CHANGELOG.md
  packages/remix-cloudflare-pages/package.json
  packages/remix-cloudflare-workers/CHANGELOG.md
  packages/remix-cloudflare-workers/package.json
  packages/remix-cloudflare/CHANGELOG.md
  packages/remix-cloudflare/package.json
  packages/remix-css-bundle/CHANGELOG.md
  packages/remix-css-bundle/package.json
  packages/remix-deno/CHANGELOG.md
  packages/remix-deno/package.json
  packages/remix-dev/CHANGELOG.md
  packages/remix-dev/package.json
  packages/remix-eslint-config/CHANGELOG.md
  packages/remix-eslint-config/package.json
  packages/remix-express/CHANGELOG.md
  packages/remix-express/package.json
  packages/remix-netlify/CHANGELOG.md
  packages/remix-netlify/package.json
  packages/remix-node/CHANGELOG.md
  packages/remix-node/package.json
  packages/remix-react/CHANGELOG.md
  packages/remix-react/package.json
  packages/remix-serve/CHANGELOG.md
  packages/remix-serve/package.json
  packages/remix-server-runtime/CHANGELOG.md
  packages/remix-server-runtime/package.json
  packages/remix-testing/CHANGELOG.md
  packages/remix-testing/package.json
  packages/remix-vercel/CHANGELOG.md
  packages/remix-vercel/package.json
  packages/remix/package.json
Labels: CLA Signed

#5286 Added better detection for absolute urls in link component
  contributors.yml
  packages/remix-react/components.tsx
Labels: CLA Signed

#5389 Bump react router versions
  .changeset/forty-bees-collect.md
  packages/remix-react/package.json
  packages/remix-server-runtime/package.json
  packages/remix-testing/package.json
  yarn.lock
Labels: CLA Signed, package:server-runtime, renderer:react, package:testing

#5390 Added better detection for absolute urls in link component
  .changeset/smart-insects-melt.md
  contributors.yml
  packages/remix-react/components.tsx
Labels: CLA Signed, renderer:react

#5393 chore: Update version for release (pre)
  .changeset/pre.json
  packages/create-remix/CHANGELOG.md
  packages/create-remix/package.json
  packages/remix-architect/CHANGELOG.md
  packages/remix-architect/package.json
  packages/remix-cloudflare-pages/CHANGELOG.md
  packages/remix-cloudflare-pages/package.json
  packages/remix-cloudflare-workers/CHANGELOG.md
  packages/remix-cloudflare-workers/package.json
  packages/remix-cloudflare/CHANGELOG.md
  packages/remix-cloudflare/package.json
  packages/remix-css-bundle/CHANGELOG.md
  packages/remix-css-bundle/package.json
  packages/remix-deno/CHANGELOG.md
  packages/remix-deno/package.json
  packages/remix-dev/CHANGELOG.md
  packages/remix-dev/package.json
  packages/remix-eslint-config/CHANGELOG.md
  packages/remix-eslint-config/package.json
  packages/remix-express/CHANGELOG.md
  packages/remix-express/package.json
  packages/remix-netlify/CHANGELOG.md
  packages/remix-netlify/package.json
  packages/remix-node/CHANGELOG.md
  packages/remix-node/package.json
  packages/remix-react/CHANGELOG.md
  packages/remix-react/package.json
  packages/remix-serve/CHANGELOG.md
  packages/remix-serve/package.json
  packages/remix-server-runtime/CHANGELOG.md
  packages/remix-server-runtime/package.json
  packages/remix-testing/CHANGELOG.md
  packages/remix-testing/package.json
  packages/remix-vercel/CHANGELOG.md
  packages/remix-vercel/package.json
  packages/remix/package.json
Labels: CLA Signed

#4094 feat(remix-dev): allow importing `.psd` files
  contributors.yml
  packages/remix-dev/compiler/loaders.ts
  packages/remix-dev/modules.ts
Labels: CLA Signed, package:dev

#3920 feat(remix-dev): allow importing `.csv` files
  .changeset/wise-masks-sniff.md
  contributors.yml
  packages/remix-dev/compiler/loaders.ts
  packages/remix-dev/modules.ts
Labels: CLA Signed, package:dev

#1830 feat(remix-server-runtime): allow generic types for `SessionData`
  docs/utils/sessions.md
  packages/remix-architect/sessions/arcTableSessionStorage.ts
  packages/remix-cloudflare/sessions/workersKVStorage.ts
  packages/remix-deno/sessions/fileStorage.ts
  packages/remix-node/sessions/fileStorage.ts
  packages/remix-server-runtime/index.ts
  packages/remix-server-runtime/reexport.ts
  packages/remix-server-runtime/sessions.ts
  packages/remix-server-runtime/sessions/cookieStorage.ts
  packages/remix-server-runtime/sessions/memoryStorage.ts
Labels: CLA Signed, adapter:architect, adapter:cloudflare-pages, adapter:cloudflare-workers, docs, feat:typescript, package:server-runtime, runtime:node, runtime:deno

#5388 Sync up release docs with react router
  DEVELOPMENT.md
Labels: CLA Signed

#3171 bug(remix-react): add failing test for scroll-restoration
  contributors.yml
  integration/bug-report-test.ts
Labels: bug, CLA Signed, feat:scroll

#5412 fix(dev): ignore failed clean up attempts
  .changeset/empty-ligers-sell.md
  packages/remix-dev/devServer/liveReload.ts
  packages/remix-dev/devServer2.ts
Labels: CLA Signed

#5413 chore: Update version for release (pre)
  .changeset/pre.json
  packages/create-remix/CHANGELOG.md
  packages/create-remix/package.json
  packages/remix-architect/CHANGELOG.md
  packages/remix-architect/package.json
  packages/remix-cloudflare-pages/CHANGELOG.md
  packages/remix-cloudflare-pages/package.json
  packages/remix-cloudflare-workers/CHANGELOG.md
  packages/remix-cloudflare-workers/package.json
  packages/remix-cloudflare/CHANGELOG.md
  packages/remix-cloudflare/package.json
  packages/remix-css-bundle/CHANGELOG.md
  packages/remix-css-bundle/package.json
  packages/remix-deno/CHANGELOG.md
  packages/remix-deno/package.json
  packages/remix-dev/CHANGELOG.md
  packages/remix-dev/package.json
  packages/remix-eslint-config/CHANGELOG.md
  packages/remix-eslint-config/package.json
  packages/remix-express/CHANGELOG.md
  packages/remix-express/package.json
  packages/remix-netlify/CHANGELOG.md
  packages/remix-netlify/package.json
  packages/remix-node/CHANGELOG.md
  packages/remix-node/package.json
  packages/remix-react/CHANGELOG.md
  packages/remix-react/package.json
  packages/remix-serve/CHANGELOG.md
  packages/remix-serve/package.json
  packages/remix-server-runtime/CHANGELOG.md
  packages/remix-server-runtime/package.json
  packages/remix-testing/CHANGELOG.md
  packages/remix-testing/package.json
  packages/remix-vercel/CHANGELOG.md
  packages/remix-vercel/package.json
  packages/remix/package.json
Labels: CLA Signed

#5435 docs: fix typos
  DEVELOPMENT.md
  contributors.yml
  docs/file-conventions/route-files-v2.md
Labels: CLA Signed, docs

#5402 docs(other-api/adapter): add `@mcansh/remix-fastify` & `@mcansh/remix-rap-http` to community adapters list
  docs/other-api/adapter.md
Labels: CLA Signed, docs

#4016 chore(templates): change`&&` into `npm-run-all`
  contributors.yml
  templates/arc/package.json
  templates/cloudflare-pages/package.json
  templates/cloudflare-workers/package.json
  templates/deno/package.json
  templates/express/package.json
Labels: CLA Signed, template:express, template:architect, template:cloudflare-pages, template:cloudflare-workers, template:deno

#5441 Fix: log errors during initial build in development
  .changeset/tidy-doors-judge.md
  packages/remix-dev/compiler/watch.ts
Labels: CLA Signed

#5456 chore: Update version for release
  .changeset/eleven-plums-film.md
  .changeset/forty-bees-collect.md
  .changeset/gorgeous-meals-rescue.md
  .changeset/healthy-beers-nail.md
  .changeset/honest-crabs-sort.md
  .changeset/lemon-humans-yell.md
  .changeset/many-pans-attack.md
  .changeset/nine-apricots-breathe.md
  .changeset/pre.json
  .changeset/smart-insects-melt.md
  .changeset/tame-swans-burn.md
  packages/create-remix/CHANGELOG.md
  packages/create-remix/package.json
  packages/remix-architect/CHANGELOG.md
  packages/remix-architect/package.json
  packages/remix-cloudflare-pages/CHANGELOG.md
  packages/remix-cloudflare-pages/package.json
  packages/remix-cloudflare-workers/CHANGELOG.md
  packages/remix-cloudflare-workers/package.json
  packages/remix-cloudflare/CHANGELOG.md
  packages/remix-cloudflare/package.json
  packages/remix-css-bundle/CHANGELOG.md
  packages/remix-css-bundle/package.json
  packages/remix-deno/CHANGELOG.md
  packages/remix-deno/package.json
  packages/remix-dev/CHANGELOG.md
  packages/remix-dev/package.json
  packages/remix-eslint-config/CHANGELOG.md
  packages/remix-eslint-config/package.json
  packages/remix-express/CHANGELOG.md
  packages/remix-express/package.json
  packages/remix-netlify/CHANGELOG.md
  packages/remix-netlify/package.json
  packages/remix-node/CHANGELOG.md
  packages/remix-node/package.json
  packages/remix-react/CHANGELOG.md
  packages/remix-react/package.json
  packages/remix-serve/CHANGELOG.md
  packages/remix-serve/package.json
  packages/remix-server-runtime/CHANGELOG.md
  packages/remix-server-runtime/package.json
  packages/remix-testing/CHANGELOG.md
  packages/remix-testing/package.json
  packages/remix-vercel/CHANGELOG.md
  packages/remix-vercel/package.json
  packages/remix/package.json
Labels: CLA Signed

#5406 docs(guides/constraints, tutorials/blog): update grammar to change se…
  contributors.yml
  docs/guides/constraints.md
  docs/hooks/use-fetchers.md
  docs/tutorials/blog.md
Labels: CLA Signed, docs

#5398 chore: sync `FutureConfig` interface
  .changeset/twelve-seahorses-arrive.md
  packages/remix-react/entry.ts
  packages/remix-server-runtime/entry.ts
  packages/remix-server-runtime/server.ts
  packages/remix-testing/create-remix-stub.tsx
Labels: CLA Signed

#5476 Ensure types for fetchers always include form* submission fields
  .changeset/tidy-singers-battle.md
  packages/remix-react/components.tsx
  packages/remix-react/transition.ts
Labels: CLA Signed

#5477 ci: disable jest and eslint github annotations
  .github/workflows/lint.yml
  jest.config.js
Labels: CLA Signed

#5482 fix(remix-dev/compiler): fix typo in `serverBareModulesPlugin` message
  contributors.yml
  packages/remix-dev/compiler/plugins/serverBareModulesPlugin.ts
Labels: CLA Signed, package:dev

#5486 ci: bump styfle/cancel-workflow-action to latest
  .github/workflows/reusable-test.yml
Labels: CLA Signed

#5487 test(reveal): prevent jest from leaking logs
  packages/remix-dev/__tests__/reveal-test.ts
Labels: CLA Signed

#5491 chore(remix-dev): remove duplicate console.log
  packages/remix-dev/config.ts
Labels: CLA Signed

#5484 chore(remix-server-runtime): fix ESLint warnings
  packages/remix-server-runtime/routes.ts
Labels: CLA Signed, package:server-runtime

#5534 fix: remove duplicate manifest imports introduced by defer work
  .changeset/new-bulldogs-allow.md
  integration/link-test.ts
  packages/remix-react/components.tsx
Labels: CLA Signed

#5259 feat(dev): HMR + Hot Data Revalidation
  .changeset/hmr.md
  integration/hmr-test.ts
  jest/transform.js
  package.json
  packages/remix-dev/codemod/replace-remix-magic-imports/transform.ts
  packages/remix-dev/compiler/assets.ts
  packages/remix-dev/compiler/compileBrowser.ts
  packages/remix-dev/compiler/compilerServer.ts
  packages/remix-dev/compiler/index.ts
  packages/remix-dev/compiler/onCompileFailure.ts
  packages/remix-dev/compiler/plugins/browserRouteModulesPlugin.ts
  packages/remix-dev/compiler/plugins/hmrPlugin.ts
  packages/remix-dev/compiler/remixCompiler.ts
  packages/remix-dev/compiler/watch.ts
  packages/remix-dev/devServer2.ts
  packages/remix-dev/hmr.ts
  packages/remix-dev/liveReload.ts
  packages/remix-dev/package.json
  packages/remix-dev/transform/create.ts
  packages/remix-dev/transform/index.ts
  packages/remix-dev/transform/plugin.ts
  packages/remix-dev/transform/plugins/recast.ts
  packages/remix-react/browser.tsx
  packages/remix-react/components.tsx
  packages/remix-react/entry.ts
  packages/remix-react/package.json
  packages/remix-react/rollup.config.js
  packages/remix-react/routes.tsx
  packages/remix-server-runtime/entry.ts
  packages/remix-server-runtime/package.json
  packages/remix-server-runtime/server.ts
  packages/remix-testing/package.json
  yarn.lock
Labels: CLA Signed, package:dev, package:server-runtime, renderer:react, package:testing

#5552 chore: Update version for release (pre)
  .changeset/pre.json
  packages/create-remix/CHANGELOG.md
  packages/create-remix/package.json
  packages/remix-architect/CHANGELOG.md
  packages/remix-architect/package.json
  packages/remix-cloudflare-pages/CHANGELOG.md
  packages/remix-cloudflare-pages/package.json
  packages/remix-cloudflare-workers/CHANGELOG.md
  packages/remix-cloudflare-workers/package.json
  packages/remix-cloudflare/CHANGELOG.md
  packages/remix-cloudflare/package.json
  packages/remix-css-bundle/CHANGELOG.md
  packages/remix-css-bundle/package.json
  packages/remix-deno/CHANGELOG.md
  packages/remix-deno/package.json
  packages/remix-dev/CHANGELOG.md
  packages/remix-dev/package.json
  packages/remix-eslint-config/CHANGELOG.md
  packages/remix-eslint-config/package.json
  packages/remix-express/CHANGELOG.md
  packages/remix-express/package.json
  packages/remix-netlify/CHANGELOG.md
  packages/remix-netlify/package.json
  packages/remix-node/CHANGELOG.md
  packages/remix-node/package.json
  packages/remix-react/CHANGELOG.md
  packages/remix-react/package.json
  packages/remix-serve/CHANGELOG.md
  packages/remix-serve/package.json
  packages/remix-server-runtime/CHANGELOG.md
  packages/remix-server-runtime/package.json
  packages/remix-testing/CHANGELOG.md
  packages/remix-testing/package.json
  packages/remix-vercel/CHANGELOG.md
  packages/remix-vercel/package.json
  packages/remix/package.json
Labels: CLA Signed

#5553 chore: Update version for release (pre)
  .changeset/pre.json
  packages/create-remix/CHANGELOG.md
  packages/create-remix/package.json
  packages/remix-architect/CHANGELOG.md
  packages/remix-architect/package.json
  packages/remix-cloudflare-pages/CHANGELOG.md
  packages/remix-cloudflare-pages/package.json
  packages/remix-cloudflare-workers/CHANGELOG.md
  packages/remix-cloudflare-workers/package.json
  packages/remix-cloudflare/CHANGELOG.md
  packages/remix-cloudflare/package.json
  packages/remix-css-bundle/CHANGELOG.md
  packages/remix-css-bundle/package.json
  packages/remix-deno/CHANGELOG.md
  packages/remix-deno/package.json
  packages/remix-dev/CHANGELOG.md
  packages/remix-dev/package.json
  packages/remix-eslint-config/CHANGELOG.md
  packages/remix-eslint-config/package.json
  packages/remix-express/CHANGELOG.md
  packages/remix-express/package.json
  packages/remix-netlify/CHANGELOG.md
  packages/remix-netlify/package.json
  packages/remix-node/CHANGELOG.md
  packages/remix-node/package.json
  packages/remix-react/CHANGELOG.md
  packages/remix-react/package.json
  packages/remix-serve/CHANGELOG.md
  packages/remix-serve/package.json
  packages/remix-server-runtime/CHANGELOG.md
  packages/remix-server-runtime/package.json
  packages/remix-testing/CHANGELOG.md
  packages/remix-testing/package.json
  packages/remix-vercel/CHANGELOG.md
  packages/remix-vercel/package.json
  packages/remix/package.json
Labels: CLA Signed

#5370 docs: add reference to Fastly's runtime
  contributors.yml
  docs/other-api/adapter.md
  docs/pages/stacks.md
Labels: CLA Signed, docs

#5585 docs(utils/sessions): fixs typo in sessions filename
  contributors.yml
  docs/utils/sessions.md
Labels: CLA Signed

#5587 fix(*): fix error message
  packages/remix-react/data.ts
Labels: CLA Signed

#5560 chore(remix-dev): remove broken param collision check
  .changeset/afraid-tigers-occur.md
  packages/remix-dev/__tests__/flat-routes-test.ts
  packages/remix-dev/config/flat-routes.ts
Labels: CLA Signed

#5590 Move scroll test to it's own file
  .changeset/red-kids-look.md
  integration/bug-report-test.ts
  integration/scroll-test.ts
Labels: CLA Signed

#5594 Bump router versions
  .changeset/eighty-toes-rhyme.md
  .changeset/red-kids-look.md
  packages/remix-react/package.json
  packages/remix-server-runtime/package.json
  packages/remix-testing/package.json
  yarn.lock
Labels: CLA Signed

#5596 chore: Update version for release (pre)
  .changeset/pre.json
  packages/create-remix/CHANGELOG.md
  packages/create-remix/package.json
  packages/remix-architect/CHANGELOG.md
  packages/remix-architect/package.json
  packages/remix-cloudflare-pages/CHANGELOG.md
  packages/remix-cloudflare-pages/package.json
  packages/remix-cloudflare-workers/CHANGELOG.md
  packages/remix-cloudflare-workers/package.json
  packages/remix-cloudflare/CHANGELOG.md
  packages/remix-cloudflare/package.json
  packages/remix-css-bundle/CHANGELOG.md
  packages/remix-css-bundle/package.json
  packages/remix-deno/CHANGELOG.md
  packages/remix-deno/package.json
  packages/remix-dev/CHANGELOG.md
  packages/remix-dev/package.json
  packages/remix-eslint-config/CHANGELOG.md
  packages/remix-eslint-config/package.json
  packages/remix-express/CHANGELOG.md
  packages/remix-express/package.json
  packages/remix-netlify/CHANGELOG.md
  packages/remix-netlify/package.json
  packages/remix-node/CHANGELOG.md
  packages/remix-node/package.json
  packages/remix-react/CHANGELOG.md
  packages/remix-react/package.json
  packages/remix-serve/CHANGELOG.md
  packages/remix-serve/package.json
  packages/remix-server-runtime/CHANGELOG.md
  packages/remix-server-runtime/package.json
  packages/remix-testing/CHANGELOG.md
  packages/remix-testing/package.json
  packages/remix-vercel/CHANGELOG.md
  packages/remix-vercel/package.json
  packages/remix/package.json
Labels: CLA Signed
