Repository remix-run/remix, pull requests merged in 2024-04, with the labels that each got.

#9176 Remove Future subheading on docs site and update CLI links
  .changeset/update-docs.md
  docs/discussion/server-vs-client.md
  docs/file-conventions/-client.md
  docs/file-conventions/-server.md
  docs/file-conventions/remix-config.md
  docs/file-conventions/vite-config.md
  docs/future/index.md
  docs/guides/contributing.md
  docs/guides/gotchas.md
  docs/guides/local-tls.md
  docs/guides/manual-mode.md
  docs/guides/mdx.md
  docs/guides/migrating-react-router-app.md
  docs/guides/performance.md
  docs/guides/presets.md
  docs/guides/server-bundles.md
  docs/guides/spa-mode.md
  docs/guides/templates.md
  docs/guides/vite.md
  docs/other-api/dev.md
  docs/start/future-flags.md
  docs/start/v2.md
  docs/styling/bundling.md
  docs/styling/css-imports.md
  docs/styling/css-modules.md
  docs/styling/css.md
  docs/styling/postcss.md
  docs/styling/tailwind.md
  docs/styling/vanilla-extract.md
  docs/tutorials/jokes.md
  integration/vite-dot-server-test.ts
  integration/vite-spa-mode-test.ts
  packages/remix-dev/vite/plugin.ts
  templates/cloudflare/README.md
  templates/express/README.md
  templates/remix-javascript/README.md
  templates/remix/README.md
  templates/spa/README.md
  templates/spa/app/routes/_index.tsx
  templates/vite/README.md
Labels: CLA Signed

#9163 Update use-params.md
  contributors.yml
  docs/hooks/use-params.md
Labels: CLA Signed

#9194 Fix Vite critical CSS resolution for route files with absolute paths
  .changeset/hot-suits-jam.md
  packages/remix-dev/vite/styles.ts
Labels: CLA Signed

#9198 chore(remix-node): put native fetch behind config option
  .changeset/good-buses-divide.md
  integration/error-data-request-test.ts
  integration/helpers/create-fixture.ts
  integration/helpers/vite.ts
  integration/hmr-test.ts
  integration/vite-basename-test.ts
  package.json
  packages/remix-architect/__tests__/setup.ts
  packages/remix-express/__tests__/setup.ts
  packages/remix-node/__tests__/setup.ts
  packages/remix-node/globals.ts
  packages/remix-node/package.json
  packages/remix-node/rollup.config.js
  packages/remix-react/__tests__/setup.ts
  packages/remix-serve/cli.ts
  packages/remix-server-runtime/__tests__/setup.ts
  packages/remix-testing/jest.config.js
  packages/remix-testing/jest.setup.js
  pnpm-lock.yaml
  templates/classic-remix-compiler/arc/server.ts
Labels: CLA Signed

#9205 Update vite-configuration link to vite-config where linked to in docs
  contributors.yml
  docs/discussion/server-vs-client.md
  docs/file-conventions/remix-config.md
Labels: CLA Signed

#9232 Fix Playwright hanging in Node 20.5.2+
  .github/workflows/test-full.yml
  .github/workflows/test-pr-ubuntu.yml
  .github/workflows/test-pr-windows-macos.yml
  integration/playwright.config.ts
Labels: CLA Signed

#9228 Fix wrong file path in headers.md
  contributors.yml
  docs/route/headers.md
Labels: CLA Signed, docs

#9197 template(cloudflare): Update remix cloudflare template to latest package versions
  contributors.yml
  templates/cloudflare/package.json
Labels: CLA Signed, template:vite-cloudflare

#9241 Ignore Babel config for `react-refresh` transform
  .changeset/tame-otters-clap.md
  packages/remix-dev/vite/plugin.ts
Labels: CLA Signed, package:dev, vite

#9235 Update errors.md for typo of "then"
  contributors.yml
  docs/guides/errors.md
Labels: CLA Signed, docs

#9254 Fix typings for response in LoaderFunctonArgs/ActionFunctionArgs
  .changeset/nice-beds-sneeze.md
  packages/remix-server-runtime/routeModules.ts
  packages/remix-server-runtime/routes.ts
  packages/remix-server-runtime/single-fetch.ts
Labels: CLA Signed

#9263 Update route docs
  docs/discussion/routes.md
Labels: CLA Signed, docs

#9272 opt-in type inference for single-fetch
  .changeset/young-eagles-grab.md
  docs/guides/single-fetch.md
  packages/remix-react/future/single-fetch.d.ts
  packages/remix-react/index.tsx
  packages/remix-react/rollup.config.js
Labels: CLA Signed, feat:typescript

#9282 Include future folder in published package
  .changeset/smooth-ways-march.md
  packages/remix-react/package.json
Labels: CLA Signed

#9289 Bump router to stable
  .changeset/shiny-ravens-cross.md
  integration/package.json
  packages/remix-dev/package.json
  packages/remix-react/package.json
  packages/remix-server-runtime/package.json
  packages/remix-testing/package.json
  pnpm-lock.yaml
Labels: CLA Signed

#9292 Updates to single fetch docs
  docs/guides/single-fetch.md
Labels: CLA Signed

#9299 Ignore future d.ts files from TS build
  .changeset/sweet-falcons-relax.md
  packages/remix-react/tsconfig.json
Labels: CLA Signed

#9301 Only add Remix packages to `ssr.external` in Remix repo
  .changeset/thirty-donuts-clean.md
  packages/remix-dev/vite/plugin.ts
Labels: CLA Signed, package:dev, vite

#9287 Remove `@remix-run/node` from Vite's `optimizeDeps.include`
  .changeset/nasty-pandas-accept.md
  packages/remix-dev/vite/plugin.ts
Labels: CLA Signed, package:dev, vite

#9294 docs(single-fetch): typo & missing parens around function
  docs/guides/single-fetch.md
Labels: CLA Signed

#9305 Fix `dest already exists` error during Vite build
  .changeset/five-planets-grin.md
  packages/remix-dev/vite/plugin.ts
Labels: CLA Signed, package:dev, vite

#9329 docs: update tailwind import with additional query string based on ta…
  contributors.yml
  docs/styling/tailwind.md
Labels: CLA Signed

#9237 Fix test command in contributing guide
  contributors.yml
  docs/guides/contributing.md
Labels: CLA Signed, docs

#9322 Add undefined to useActionData type override
  .changeset/happy-ladybugs-smoke.md
  packages/remix-react/future/single-fetch.d.ts
Labels: CLA Signed, feat:typescript

#9335 Add section on undici polyfill to Single Fetch docs
  docs/guides/single-fetch.md
Labels: docs
