Repository remix-run/remix, pull requests merged in 2024-08, with the labels that each got.

#9815 Bump RR stable
  .changeset/few-pets-try.md
  integration/package.json
  packages/remix-dev/package.json
  packages/remix-react/package.json
  packages/remix-server-runtime/package.json
  packages/remix-testing/package.json
  pnpm-lock.yaml
Labels: CLA Signed

#9830 docs(data-loading): fix SearchCheckbox snippet
  contributors.yml
  docs/guides/data-loading.md
Labels: CLA Signed, docs

#9848 Fix single fetch redirects whena basename is present
  .changeset/rich-teachers-warn.md
  integration/single-fetch-test.ts
  packages/remix-server-runtime/server.ts
  packages/remix-server-runtime/single-fetch.ts
Labels: CLA Signed

#9856 fix: update turbo-stream to v2.3.0
  .changeset/sweet-roses-shake.md
  packages/remix-react/package.json
  packages/remix-server-runtime/package.json
  pnpm-lock.yaml
Labels: CLA Signed

#9860 Handle fog of war edge cases with server-known higher-scoring routes
  .changeset/shy-ducks-repeat.md
  integration/fog-of-war-test.ts
  integration/package.json
  packages/remix-dev/package.json
  packages/remix-react/browser.tsx
  packages/remix-react/fog-of-war.ts
  packages/remix-react/package.json
  packages/remix-server-runtime/package.json
  packages/remix-server-runtime/server.ts
  packages/remix-testing/package.json
  pnpm-lock.yaml
Labels: CLA Signed

#9861 Bump RR dependency
  integration/package.json
  packages/remix-dev/package.json
  packages/remix-react/package.json
  packages/remix-server-runtime/package.json
  packages/remix-testing/package.json
  pnpm-lock.yaml
Labels: CLA Signed

#9866 Bump router
  .changeset/forty-lions-sing.md
  integration/package.json
  packages/remix-dev/package.json
  packages/remix-react/package.json
  packages/remix-server-runtime/package.json
  packages/remix-testing/package.json
  pnpm-lock.yaml
Labels: CLA Signed

#9889 Change content type on single fetch requests
  .changeset/popular-meals-hide.md
  integration/single-fetch-test.ts
  packages/remix-react/single-fetch.tsx
  packages/remix-server-runtime/server.ts
Labels: package:server-runtime, feat:single-fetch

#9888 Sort lazy route discovery manifest request params
  .changeset/dirty-adults-sparkle.md
  integration/fog-of-war-test.ts
  packages/remix-react/fog-of-war.ts
Labels: CLA Signed, renderer:react

#9890 Remove hydration URL check
  .changeset/khaki-ads-buy.md
  packages/remix-react/browser.tsx
  packages/remix-server-runtime/server.ts
  packages/remix-server-runtime/serverHandoff.ts
Labels: CLA Signed, package:server-runtime, renderer:react, hydration

#9901 Fix `dest already exists` build errors
  .changeset/tiny-crabs-deliver.md
  packages/remix-dev/vite/plugin.ts
Labels: CLA Signed, package:dev, vite

#9899 Clarify wording in default console warning
  .changeset/two-chicken-provide.md
  packages/remix-react/fallback.tsx
Labels: CLA Signed, renderer:react

#9914 Add failing test for syncronous blocker.proceed calls
  integration/blocking-test.ts
  integration/helpers/create-fixture.ts
  integration/helpers/deno-template/remix.config.js
  integration/package.json
  packages/remix-dev/package.json
  packages/remix-react/package.json
  packages/remix-server-runtime/package.json
  packages/remix-testing/package.json
  pnpm-lock.yaml
Labels: CLA Signed

#9917 handle cycles between manual chunks
  .changeset/friendly-walls-brake.md
  contributors.yml
  packages/remix-dev/vite/plugin.ts
Labels: CLA Signed

#9893 Single-fetch typesafety
  .changeset/moody-cups-give.md
  docs/guides/single-fetch.md
  integration/single-fetch-test.ts
  packages/remix-cloudflare/index.ts
  packages/remix-deno/index.ts
  packages/remix-node/index.ts
  packages/remix-react/future/single-fetch.d.ts
  packages/remix-react/index.tsx
  packages/remix-react/package.json
  packages/remix-react/rollup.config.js
  packages/remix-react/single-fetch.tsx
  packages/remix-server-runtime/future.ts
  packages/remix-server-runtime/index.ts
  packages/remix-server-runtime/package.json
  packages/remix-server-runtime/serialize.ts
  packages/remix-server-runtime/single-fetch.ts
  pnpm-lock.yaml
Labels: CLA Signed, feat:typescript, package:server-runtime, feat:single-fetch

#9919 [docs] Fix Typo in createSessionStorage
  contributors.yml
  docs/utils/sessions.md
Labels: CLA Signed

#9921 Optimize dependencies found through route module graphs
  .changeset/hot-dogs-applaud.md
  package.json
  packages/remix-dev/vite/plugin.ts
  pnpm-lock.yaml
Labels: CLA Signed

#9922 Automatically optimize dependencies of the client entry
  packages/remix-dev/vite/plugin.ts
Labels: CLA Signed

#9924 lenient return type for `unstable_data`
  packages/remix-server-runtime/single-fetch.ts
Labels: CLA Signed

#9925 fix single-fetch types: correctly check for arbitrary functions
  packages/remix-server-runtime/serialize.ts
Labels: CLA Signed

#9926 Single-fetch docs: `declare module` must be `include`d by `tsconfig`
  docs/guides/single-fetch.md
Labels: CLA Signed

#9927 future flag for automatic optimize deps
  .changeset/hot-dogs-applaud.md
  docs/guides/dependency-optimization.md
  docs/guides/single-fetch.md
  docs/start/future-flags.md
  packages/remix-dev/__tests__/readConfig-test.ts
  packages/remix-dev/config.ts
  packages/remix-dev/vite/plugin.ts
Labels: CLA Signed
